### ISSUE TITLE
New UI requires typing in the currency (no autocomplete) for new entries?

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#1013]
I updated from 1.8 to 1.11 today (been a while since I changed anything on my live system) and realised that the quick-entry UI has changed. In particular there's no box for currency, so we need to type it in to the 'Amount' box.

The problem is, if I DON'T type a currency in, it just shows a non-helpful error "Saving failed: Internal error". Hard to believe this is common, so maybe there's something unique about both my installs (I run two instances).

**Comment by yagebu** [comment]
This is to support the full range of Beancount's import syntax.

The handling of this input field has improved since 1.11 and shouldn't error anymore.

**Comment by ngoonee** [comment]
Thanks, will await the next stable release then (and tell my wife to remember the currency). A concept of 'default' currency would really help here since unlike some others I'm 95% of the time only using one currency.

**Comment by ngoonee** [comment]
Now it no longer errors out, but obviously if I don't type a currency no currency is input. Is it possible to specify a default currency?
