### ISSUE TITLE
Transactions with forecasting feature not shown on fava

### ISSUE THREAD

**Issue by mckelvin** [beancount/fava#1021]
The forecasting feature is implemented via the [`beancount.plugins.forecast`](https://bitbucket.org/blais/beancount/src/default/beancount/plugins/forecast.py) plugin. When the plugin is enabled, transactions like

```
  2014-03-08 # "Electricity bill [MONTHLY]"
    Expenses:Electricity 			50.10 USD
    Assets:Checking			       -50.10 USD
```

are not shown in fava however it works correctly with bean-web.

**Comment by yagebu** [comment]
What do you mean by "not shown" - in the Journal or are they also not reflected in the balances? By default, the journal only diplays cleared and pending transactions, have you tried showing all transactions by toggling the `x`?

**Comment by mckelvin** [comment]
> have you tried showing all transactions by toggling the x?

It works now after clicking the `x` in the `Journal` page.

```
option "operating_currency" "USD"

plugin "beancount.plugins.forecast"

2001-01-01 open Expenses:Electricity USD
2001-01-01 open Assets:Checking USD

2014-03-08 # "Electricity bill [MONTHLY]"
  Expenses:Electricity 			50.10 USD
  Assets:Checking			       -50.10 USD

```

Thanks for the help!
