### ISSUE TITLE
Unrealized accounts at market value are double calculated in Balance Sheet

### ISSUE THREAD

**Issue by mckelvin** [beancount/fava#1022]
# Steps to reproduce

1. Use https://fava.pythonanywhere.com/example-with-budgets/editor/ as an example
2. Enable the unrealized plugin by adding the following line in the beancount file: `plugin "beancount.plugins.unrealized" "Unrealized"`
3. Run the file using fava and visit http://localhost:5000/example-with-budgets/balance_sheet/?conversion=at_value
3. Now the total assets is `125389.82`, total liabilities is `-3821.70`, total net worth = 125389.82 +  -3821.70 = `121568.12`, which is NOT correct. Compared to when the plugin was disabled, the net worth should be 117867.57 + -3821.70 = `114045.87`, which is correct net worth.

# Solution

The issue happens because unrealized accounts are double calculated. The net worth shown on the graph is correct as it has consider the special case of unrealized account.

The issue can be resolved by applying the following patch

```diff
diff --git a/fava/core/tree.py b/fava/core/tree.py
index 983a0ecb..f4023b6c 100644
--- a/fava/core/tree.py
+++ b/fava/core/tree.py
@@ -88,6 +88,10 @@ class Tree(dict):
         node.balance.add_inventory(balance)
         node.balance_children.add_inventory(balance)
         node.has_txns = True
+
+        if name.endswith("Unrealized"):
+            return
+
         for parent_node in self.ancestors(name):
             parent_node.balance_children.add_inventory(balance)
```

I can't find an elegant to read the unrealized subaccount string (`"Unrealized"` in this case).
This also a edge case as the [subaccount is optional](https://bitbucket.org/blais/beancount/src/default/beancount/plugins/unrealized.py). In this case, my fix is not working anymore. :(

**Comment by yagebu** [comment]
Since Fava provides functionality to compute and display the unrealized gains, you shouldn't use it in combination with that plugin. Or don't use the market value conversion but the book value conversion instead to avoid having the unrealized gains factoring in twice.
