### ISSUE TITLE
[Request] Add a 'fava-option' for Setting the Default Conversion Dropdown

### ISSUE THREAD

**Issue by OptikSage** [beancount/fava#1028]
I almost always change the conversion to "Converted to USD". It would be great if we could set this the same way we can set "fava-option" "journal-show". Thx.

**Comment by yagebu** [comment]
This can also be solved by a bookmark.

But we also have a `interval` option - so why not. Can you provide a PR?

**Comment by OptikSage** [comment]
Sure. I just submitted a PR (https://github.com/beancount/fava/pull/1047).
