### ISSUE TITLE
fava very slow to start

### ISSUE THREAD

**Issue by johannesjh** [beancount/fava#1031]
Fava takes a very long time to start. Could you please help me debug this issue. 

More specifically: I am experiencing long delays from when I start fava to when it answers the first HTTP requests. This takes about one minute, with a python process constantly using 99% CPU.

I wrote this script to reproduce and debug the behavior.

```shell
#!/usr/bin/env bash

# preparations
pushd `dirname $0` > /dev/null

# diagnostic info
python3 --version
bean-example --version
fava --version

# run the test
rm example.beancount
bean-example -o example.beancount
fava example.beancount &
echo "waiting for the tcp port to open..."
date
while ! nc -z localhost 5000; do
  echo -n "."
  sleep 0.1 # wait before checking again
done
date
echo "done, the tcp port is now open"
echo
echo "trying to access the web interface..."
date
time curl http://localhost:5000
date
echo "done, got a reponse from the web interface"

# cleanup
rm example.beancount
popd > /dev/null
```

and I get the following output

```
Python 3.7.6
Beancount 2.2.3
fava, version 1.12
INFO    : Generating Salary Employment Income
INFO    : Generating Expenses from Banking Accounts
INFO    : Generating Regular Expenses via Credit Card
INFO    : Generating Credit Card Expenses for Trips
INFO    : Generating Credit Card Payment Entries
INFO    : Generating Tax Filings and Payments
INFO    : Generating Opening of Banking Accounts
INFO    : Generating Transfers to Investment Account

INFO    : Generating Prices
INFO    : Generating Employer Match Contribution
INFO    : Generating Retirement Investments
INFO    : Generating Taxes Investments
INFO    : Generating Expense Accounts
INFO    : Generating Equity Accounts
INFO    : Generating Balance Checks
INFO    : Outputting and Formatting Entries
INFO    : Contextualizing to Realistic Names
INFO    : Writing contents
INFO    : Validating Results
waiting for the tcp port to open...
Sat Jan 11 11:35:14 CET 2020
......Running Fava on http://localhost:5000
Connection to localhost port 5000 [tcp/commplex-main] succeeded!
Sat Jan 11 11:35:15 CET 2020
done, the tcp port is now open

trying to access the web interface...
Sat Jan 11 11:35:15 CET 2020
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/example-beancount-file/income_statement/">/
example-beancount-file/income_statement/</a>.  If not click the link.
real    1m7.208s
user    0m0.008s
sys     0m0.009s
Sat Jan 11 11:36:22 CET 2020
done, got a reponse from the web interface
```

while the first response took over 1 minute, the next responses are quick as usual.

**Comment by yagebu** [comment]
Thanks for providing the script. I can't reproduce this issue though. Do you have a really huge Beancount file in `$BEANCOUNT_FILE` by any chance?

**Comment by johannesjh** [comment]
Thank you for trying to reproduce the issue. 

Large beancount files also were my first thought. The environment variable `$BEANCOUNT_FILE` is not set on my system, so that won't be the issue. Also, when I write changes to files that are watched by fava, the UI is quick to reflect these changes. Furthermore, I get the same problematic behavior with a newly generated beancount example file. These observations lead me to think that large beancount files probably do not cause the problem.

I suspected that a broken python virtualenv could cause the problem. But I got the same behavior when running fava without virtualenv, i.e., from my system-wide installation of python 3.7.6

Python 3.7.6 is rather new (release date dec 2019). Are you also using such a fresh version of python?

My gut feeling is that beancount and fava are not directly causing the delay, but maybe the webserver / wsgi framework / other libraries that may be loaded?

Any suggestions how I could inspect fava's startup behavior? Some ideas: 

* I could try setting a finer log level to better understand what fava is doing. Do you maybe have a hint / existing documentation / a code snippet how to configure fava's logging?
* I could try running fava in debug mode using an IDE like pycharm. Note: I found that fava's cli provides a debug option, but I could not find a way to attach pycharm to a running fava process. How is fava's `debug` commandline option meant to be used?

Thank you so much! br, Johannes

**Comment by yagebu** [comment]
> Are you also using such a fresh version of python?

Yes - 3.8.1. actually.

> Do you maybe have a hint / existing documentation / a code snippet how to configure fava's logging?

There's only the command line hints really. They're mainly useful when debugging requests though, so they won't help much with debugging the startup.

> How is fava's debug commandline option meant to be used?

It uses werkzeug's debug server and does some more logging (and shows full tracebacks in the browser on errors). So that could indicate whether the server is causing the problem.

So I guess in this case for debugging you'd need to add some more `print()`s or `log`s to pinpoint where this delay is introduced

**Comment by yagebu** [comment]
Could it be that  `~/.bean-shell-history` is huge?

**Comment by johannesjh** [comment]
Thank you so much, yes, this was the problem. My `~/.bean-shell-history` file had about 650MB.

```shell
~ ❯❯❯ ls -lh ~/.bean-shell-history
-rw-------@ 1 johannes  staff   684M Jan 13 11:29 /Users/johannes/.bean-shell-history
~ ❯❯❯ wc -l ~/.bean-shell-history
 111537000 /Users/johannes/.bean-shell-history
~ ❯❯❯ rm ~/.bean-shell-history
~ ❯❯❯ # fava starts quickly again! :-)
```

Interestingly, most lines in `~/.bean-shell-history` are a simple `clear` command. More precisely, the word "clear" occurs over 111 million times in my file. 

One logical proposal would be that fava (or beancount) should limit the size of this file. I found that according to the last comment in #497, such functionality should already be present in fava since at least July 2017. Not sure why it did not work in my case.

**Comment by yagebu** [comment]
Fava is not using readline anymore at all, so this was removed. Beancount should probably limit the history length, but I'll re-add it in any case.
