### ISSUE TITLE
Show commodity amount

### ISSUE THREAD

**Issue by ikwtif** [beancount/fava#1033]
How do you show a commodity amount in the balance sheet?
For example with this transaction
```
2020-01-01 * "gold"
  Assets:myaccount:Cash                     			 -5000 EUR
  Assets:myaccount:Gold                               1 GLD {5000}
```

This shows just the EUR amount in the balance sheet. Is it possible to show GLD amount as well? I have GLD added to fava options (operating_currency) and it shows the added column for it, but no cells are populated for the account. 

The account is also defined with GLD. 

`2020-01-01 open Assets:myaccount:Gold       GLD`

I assume I'm forgetting something but haven't been able to find what's the issue

**Comment by yagebu** [comment]
By the default, the 'book value' is shown. Select a conversion of "Units" to show the actual commodities in the accounts.
