### ISSUE TITLE
Rendering of significant digits

### ISSUE THREAD

**Issue by scanta2** [beancount/fava#1036]
I have recently reorganized my large file of transactions, and split it by year, with an additional file for prices.
Previously, USD and EUR would render with two decimal digits, and commodities with a number of decimal digits depending on how they are transacted (i.e. Vanguard shows up to 3 digits, but for my car and my home I'd only see integer values).

Since splitting into multiple files, the rendering has changed, and I have tried all the tolerance options with no effect. For a while EUR would render as integer, and now every commodity renders with two decimal digits.

Is there something I am missing?

**Comment by scanta2** [comment]
It looks like the variable dcontext is getting set per commodity when the transactions are in the included files.

**Comment by Zburatorul** [comment]
I have a similar issue when using multiple files.

**Comment by yagebu** [comment]
Including files has several limitations with regards to options and the display context in Beancount...
