### ISSUE TITLE
Support for Bianuual intervals

### ISSUE THREAD

**Issue by sulemankm** [beancount/fava#1038]
Hi, I've recently started using fave+beancount.  I need to plan a payment twice a year but it seems there is no support for bianual interval in fava.  I want to write something like this.

2020-01-15 custom "budget" Expenses:University-Fees  "bianually" 800 USD

We could use the word "half yearly" or "bianually" for this interval.

BTW, wouldn't it be useful to provide a way to specify a random interval such as "every 4 months", "every 10 days" etc?

**Comment by sulemankm** [comment]
OK, I've started to implement this on my own at [https://github.com/sulemankm/fava](https://github.com/sulemankm/fava).

But I'm not sure if I'm doing it correctly.   It build correctly, reports no errors.  However, I'm not sure if it is functioning correctly.  Also not added any tests yet.  Can someone have look at my code and point out any corrections required?

Will raise a PR when it's done.

**Comment by yagebu** [comment]
Since the budgets are broken down to daily budgets in any case, specifying the biannual budget would not be any different than giving double that as a yearly budget. So IMHO there's not much need for adding an additional format (in particular the very ambiguous "biannual").
