### ISSUE TITLE
Beancount Plugin Question

### ISSUE THREAD

**Issue by ikwtif** [beancount/fava#1039]
Are all of these supported?
I'm trying to use "beancount.plugins.book_conversions" plugin from here [plugin](https://aumayr.github.io/beancount-docs-static/api_reference/beancount.plugins.html#module-beancount.plugins.book_conversions)
but I always get the - Invalid token: '“book_conversions”' - error when loading up fava. 
I tried the one from the example, but this doesn't work. I noticed there is a fava-plugins repo but those seem to be different from the beancount ones, so I'm wondering how I properly load this plugin with fava.

**Comment by yagebu** [comment]
It seems that you're writing some invalid syntax. How did you reference the plugin in your Beancount file?

**Comment by ikwtif** [comment]
I just do the same as in the example. It's in my journal.beancount file after some options, before the include statements for the beancount files where my transactions are 

```
option "title" "Personal Booking"
option "operating_currency" "EUR"
option "account_rounding" "Expenses:Rounding"
plugin “beancount.plugins.book_conversions” “Assets:Account, Income:Account”

include "accounts.beancount"
include "transactions.beancount"
```

I just tried this as well 
`plugin “book_conversions” “Assets:Account, Income:Account”`
and several other with small changes.
I always get these two errors
```
Invalid token: '“beancount.plugins.book_conversions”'
ValueError: Invalid account name: “Assets:Account



--

**Comment by yagebu** [comment]
You're using the wrong kind of quotation mark ;) The unicode LEFT DOUBLE QUOTATION MARK instead of plain double quotes...

**Comment by ikwtif** [comment]
oh I didn't even notice that. I guess I just copied the example and never actually changed it since I assumed it should just work. Thanks!
