### ISSUE TITLE
Only highlight custom sidebar link if it's an exact url match.

### ISSUE THREAD

**Issue by seltzered** [beancount/fava#1045]
I've noticed for a while that when using custom sidebar links that if you have multiple links to fava itself of say, Income Statement, you end up with all custom sidebar links that link to income statement get linked. It looks messy when you have a bunch of custom sidebar links:

![Screen Shot 2020-02-01 at 9 20 06 PM](https://user-images.githubusercontent.com/297435/73603544-ab247600-4538-11ea-857f-41e5380adbf0.png)

I'm thinking that still having 'Income Statement' highlighted is fine, but custom links should only be highlighted if you're on the same url/filter. 
 
Just started looking at the code, looks like a change to `_aside.html` will need to be changed, highlighting is done via setting of class to 'selected'. Will try to work on this soon.

**Comment by yagebu** [comment]
This actually happens in the frontend in https://github.com/beancount/fava/blob/master/fava/static/javascript/sidebar.ts. Only on the initial page load the values are set in `_aside.html`, on subsequent loads, we asynchronously load and update the main content and set the classes in the sidebar.

**Comment by seltzered** [comment]
Thanks!
