### ISSUE TITLE
Allow to set/guess default page/date range etc.

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#1049]
When first opening fava, the default is to land on the 'Income Statement' page, with no datetime restrictions.

In practice, I just save a bookmark to balance_sheet/?time=2019 which I then have to remember to update to 2020 etc.

The reason I do this is because I mainly care about balances on a day-to-day basis when checking in. Also because with historical transactions for 10 years, clicking in to active accounts just freezes my slower devices (the server isn't too hot either) if I don't have a time restriction.

Would it be possible to add fava-options for at least time range (and perhaps default page, though I can see where this gets very clunky). So basically controlling the redirect you get when you visit fava_url/

I envision something like
```
2020-01-01 custom "fava-option" "default_page" "balance_sheet"
2020-01-01 custom "fava-option" "default_time" "year-1 - year"
```
And what then happens is when I visit fava_url/ I get redirected to fava_url/my_account_name/balance_sheet/?time=year-1+-+year

**Comment by grostim** [comment]
I second that feature request.
I have already entered all the future reimburement for my real estate loan until 2030... 
I would prefer to have the default page restricted to the current year. Even better if we can set it throgh fava options.

**Comment by yagebu** [comment]
I think a bookmark solves this case quite well for most cases (in particular, just like you suggest using the `year` filter in the 'default_time', you can use that in your bookmark).

If you insist that a bookmark is really not enough, I'd not be terribly opposed to *one* option to control the redirect if someone provides a PR for this.

**Comment by aclindsa** [comment]
@yagebu 

> I think a bookmark solves this case quite well for most cases (in particular, just like you suggest using the `year` filter in the 'default_time', you can use that in your bookmark).

I won't debate that a bookmark is one way you could solve this issue, but I'm curious why you're hesitant to add a default date range option when there are seemingly-similar 'conversion' (i.e. 'At Market Value' vs. 'At Cost', etc.) and 'interval' (monthly, weekly, yearly...) options. FWIW, one reason I would prefer an option over a bookmark is the convenience of not having to remember to use such a bookmark or sync it across different devices when it changes.
 
> If you insist that a bookmark is really not enough, I'd not be terribly opposed to _one_ option to control the redirect if someone provides a PR for this.

What would the single option you're envisioning look like - are you thinking it would just be a path fragment to tack onto the end of the URL redirect, or something else? If a URL fragment, would that approach be able to accommodate a floating date range like @ngoonee mentioned (i.e. such that the range was always one year back in time from *today*)?

**Comment by yagebu** [comment]
> but I'm curious why you're hesitant to add a default date range option 

The fewer options the better.

> What would the single option you're envisioning look like - are you thinking it would just be a path fragment to tack onto the end of the URL redirect

Yep, a path fragment, so for the example in the issue, this would be `balance_sheet/?time=year-1-year`

**Comment by aclindsa** [comment]
> > but I'm curious why you're hesitant to add a default date range option
> 
> The fewer options the better.

Absolutely understand. I think my question was more "why did the existing options get priority over this one?".

> > What would the single option you're envisioning look like - are you thinking it would just be a path fragment to tack onto the end of the URL redirect
> 
> Yep, a path fragment, so for the example in the issue, this would be `balance_sheet/?time=year-1-year`

Oh, cool! I had no idea you could do math *or* use placeholder values here. I guess I thought @ngoonee 's original example option value of "year-1 - year" was theoretical. Is this feature documented somewhere and I missed it (what else have I missed?!)?

Now that I understand that the `time=` portion of the path fragment would be more powerful, I agree your proposed single option seems reasonable.

**Comment by aclindsa** [comment]
@yagebu I've taken a first pass at coding this change up: https://github.com/beancount/fava/pull/1201

Let me know what you think. My hunch is that there's a better way to do the redirection than what I have there, but I haven't found my way around flask well enough to find it yet...

**Comment by yagebu** [comment]
This is now possible with the `default-page` option thanks to @aclindsa :)
