### ISSUE TITLE
Can't import Werkzeug

### ISSUE THREAD

**Issue by ycavatars** [beancount/fava#1052]
I use `pip3 install fava` but will get a module not found error. I found fava can't import Werkzeug 1.0.0. I fixed the problem manually by specifying the version number `pip3 install "Werkzeug<1.0"`. 
I think we should specify the major version number in [setup.cfg](https://github.com/beancount/fava/blob/master/setup.cfg#L49), like `Werkzeug>=0.15.0, <1.0.0`.

**Comment by yagebu** [comment]
This is already fixed in master.

**Comment by maxwell-k** [comment]
Amazing thank you. Is there a release schedule? Do you have any idea when a release including the fix is likely? 

Thank again for your help, fava is a great tool.

**Comment by yagebu** [comment]
> Is there a release schedule?

Not really - this warrants a new release though ;)

**Comment by maxwell-k** [comment]
:+1: thank you!

https://github.com/beancount/fava/releases/tag/v1.14
