### ISSUE TITLE
Allow documents stored in non-leaf account ?

### ISSUE THREAD

**Issue by grostim** [beancount/fava#1053]
Hi.

It would make sense to me to have documents attached to non-leaf account.

Typically, I have my trading accounts structured with one sub-account per stock:
```
Assets:US:ETrade:IBM
Assets:US:ETrade:MSFT
Assets:US:ETrade:FOO
...
```

The documents, i'd like to attached (typically monthly statement) are not related to a specific stock. It's a general report for the trading account.
Therefore, it would make sense to classify the document in Assets:US:ETrade . Fava prevent me to store the document there because it is a non-leaf account.
If i manually copy the file in the relevant directory, fava don't find it. (or don't take it in consideration).

Is this a limitation of Fava or beancount ?
Is there a workaround ?

**Comment by yagebu** [comment]
This has little to do with Fava and is supported. The account needs to exist though, so you'll need to open it

**Comment by grostim** [comment]
Sorry, but if it is supported, it is not working for me though.
Documents stored in a non-leaf account are not displayed by fava.

What should i do ?

**Comment by yagebu** [comment]
> What should i do ?

As I said above, the account needs to be opened. So e.g.:

    2000-01-01 open Assets:US:Etrade
