### ISSUE TITLE
Feature Request: Graph/plot for query results

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#1055]
When using a sum(cost(position)) type query, it would be nice to have it graphed out in a similar way to the current graphs for Income Statement and Balance Sheet. This would not make sense for all queries, so perhaps only when the query contains a sum/group by (or just make it a separate link similar to the 'download as csv' link).

**Comment by yagebu** [comment]
Too late - this is already implemented ;) https://github.com/beancount/fava/commit/8a273fa4b92ab6df875209ad8ea83c30984ce0f4

**Comment by ngoonee** [comment]
@yagebu you are awesome!

**Comment by yagebu** [comment]
@ngoonee Thanks :)
