### ISSUE TITLE
problem with date when you add a new transaction

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#1059]
when i add a new transaction, i have the date that follow the "american way" mm/dd/yyyy. very disturbing, for us europeanw where we use either yyyy-mm-dd or dd/mm/yyyy.

even if you put the language to french , the format don't change.
could it be possible to either follow the localization ? 
or at least to decide which will be the format used in the calendar of the widget that appear ??

**Comment by yagebu** [comment]
We're using a standard `<input type="date">`. So the widget is shown by your browser. That should follow the localisation config of your OS or needs its own localisation config.

**Comment by tarioch** [comment]
It's an issue of pretty much all the browsers unfortunately, see https://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format

**Comment by xuhcc** [comment]
It doesn't mean it can not be fixed. A custom datepicker can be used instead of browser's default.

**Comment by yagebu** [comment]
> It doesn't mean it can not be fixed. 

I don't consider this something we need to "fix". If you set the desired language in your browser, the correct date format will be used.

**Comment by xuhcc** [comment]
The preferred language of the browser's UI could be different from preferred date format.

**Comment by yagebu** [comment]
> The preferred language of the browser's UI could be different from preferred date format.

Yes, sorry, I meant locale of course. For example @pfrancois, setting your browser to a French locale would work or if you want to keep an English browser interface, set it to British English (which has the date format DD/MM/YYYY)

**Comment by xuhcc** [comment]
Thanks, I didn't know that en-gb locale has DD/MM/YYYY format. Selecting it solved the problem for me.

Although I think that it would be nice to configure it with the `locale` fava-option.
