### ISSUE TITLE
Treemap shows bogus tooltips for accounts with zero transactions

### ISSUE THREAD

**Issue by wylfen** [beancount/fava#1061]
As the treemap chart is built containing every single account possible (such as the base "Expenses" account, for example), fava will render a tooltip if you hover over the correct area.

If the account does not have any transactions, it will render the tooltip containing "NaN" because `balance` is `undefined` here: https://github.com/beancount/fava/blob/51883c4189cdaf9eed66b9045771bc7fda543a41/fava/static/javascript/charts/hierarchy.ts#L382

`balance` is set a couple of lines above, where `d.data.balance` will not have any entries for the specified currency:

https://github.com/beancount/fava/blob/51883c4189cdaf9eed66b9045771bc7fda543a41/fava/static/javascript/charts/hierarchy.ts#L379

This bug is present for me in 1.13 and current master.

To quickly see this in action, open [an example file](https://fava.pythonanywhere.com/example-with-budgets/trial_balance/) and point your cursor to the bottom right edge of the chart. You should be seeing a tooltip for the "Expenses" account saying "NaN USD (NaN%)".

**Comment by yagebu** [comment]
Since you already started debugging this, can you provide a PR with a fix? :)

**Comment by wylfen** [comment]
I would have liked to get a PR along the report, though I have very little experience with JavaScript and the codebase & preferred deferring to people who are more familiar.

Then the question remains of how to fix it. A solution that I looked into was removing empty accounts from being rendered at all (since they're going to be invisible anyway), but I had a hard time finding the place where all accounts are passed to the chart subroutines.

Another solution would be to simply not render a tooltip. I don't think that is as clean, but perfectly viable too. I'd be happy putting something together with a few pointers where to look & which solution to apply here.

**Comment by yagebu** [comment]
> I would have liked to get a PR along the report, though I have very little experience with JavaScript and the codebase & preferred deferring to people who are more familiar.

:+1: - I'll have a look later :)

**Comment by yagebu** [comment]
> A solution that I looked into was removing empty accounts from being rendered at all (since they're going to be invisible anyway), but I had a hard time finding the place where all accounts are passed to the chart subroutines.

I think this is not doable without quite some effort, because the data for all currencies is currently stored in one "tree" object. So we can't easily filter out empty accounts since they could be different in different currencies.

Now the correct amount (0) is shown in the tooltip.

**Comment by wylfen** [comment]
Ah, that makes sense. Thanks for the quick response and fix!
