### ISSUE TITLE
Monthly Balances: Without budgets, the columns are very wide

### ISSUE THREAD

**Issue by BrettDikeman** [beancount/fava#1063]
Greetings,

I'm a new user to fava and noticed that columns are about twice as wide as necessary. I can understand some separation for readability, but the amount of space seems to make readability more difficult, and takes up a huge amount of screen real estate; lookin at two years of quarterly data requires a really wide browser window.

Example:

![Screen Shot 2020-02-20 at 1 21 29 PM](https://user-images.githubusercontent.com/4131229/74966182-996e1a00-53e4-11ea-89a6-87883fe2c0c2.png)

I searched through prior bugs/discussion and only saw mention of cases where (with multiple currencies, and on mobile?) the columns were not wide enough.

A quick glance through the documentation doesn't turn up anything promising; ditto for some googling around.

Thoughts?

**Comment by yagebu** [comment]
The columns are rather wide in your case due to the following: If you set budgets, the difference from the budgets will also be shown in these tables, see, e.g., https://fava.pythonanywhere.com/example-with-budgets/account/Expenses:Food/balances/?time=2016.

**Comment by BrettDikeman** [comment]
I'm not sure if you're implying that I have a budget set (I do not), or
that the columns are this wide in case the user sets a budget.

If it the latter: why aren't the columns widened only when necessary,
similar to how they're not widened to accommodate a second currency unless
necessary? I don't see why the budget feature would enable an additional
fixed or proportional width anyway, given the second number could be any
number of digits? Say you have a six-figure expense line and are under or
over budget by $50...or you have a two-figure budget for an expense, but
for some legitimate reason, end up spending four figures?

**Comment by yagebu** [comment]
Sorry if I wasn't clear, I meant the latter (the "in your case" was referring to the fact that they are unnecessarily wide in your case ;))

> If it the latter: why aren't the columns widened only when necessary,
similar to how they're not widened to accommodate a second currency unless
necessary?

Feel free to improve the HTML and CSS of this report :)

> Say you have a six-figure expense line and are under or
over budget by $50...or you have a two-figure budget for an expense, but
for some legitimate reason, end up spending four figures?

Well that's the same as with the normal width of these table cells. We can't have them be the perfect size for everyone (and still have a consistently formatted table). These table layouts can only be an attempt at making it look nice for most people.

**Comment by yagebu** [comment]
Closing this issue. The cell widths will be reduced slightly in #1664. Further improvements are still welcome as always.
