### ISSUE TITLE
Improve help page on filtering entries: Clarify how filters match

### ISSUE THREAD

**Issue by wylfen** [beancount/fava#1073]
Whilst working on https://github.com/beancount/fava/pull/1072, I came across a few issues in how filters are explained on the help page.

I've added the paragraphs in question below for reference:

> Filter by payee `payee:".*restaurant.*"`, or narration `narration:'Dinner with Joe'`, or any other entry attribute. The argument needs to be quoted (with `'` or `"`) if it contains spaces and can either be simply a string or a regular expression that matches the attribute. The regular expression matching is case insensitive.

> Search payee and narration by supplying a simple string, which again is matched as a regular expression. For Note directives, the comment will be searched.

#### 1. Drop the terminology of "simple" strings
In two places there is a reference to a "simple string" (or, "simply a string"). There is no indication of what a "simple" string is; no definition is given in the text. A user familiar with regular expressions might assume that a "simple" string is translated to a filter matching literally, but that is not the case.

On the other hand, a user unfamiliar with regular expressions will be confused once they enter a string containing special characters, as it might not match the term literally as they would expect.

#### 2. Inconsistent usage of the "simple" strings terminology
Compare:
> [..] can either be simply a string or a regular expression [..]

> [..] a simple string, which again is matched as a regular expression.

The first sentence implies that there are two types of strings, but the second one contradicts this. In reality (like the second sentence suggests), all quoted strings are matched as regular expressions.

#### 3. Clarify that matches are anchored to the beginning of a string
The help text does not clearly state that matches are only applied to the very beginning of a string. If familiar with regular expressions, this might be clear from a couple of examples (such as `payee:".*restaurant.*"`), but it could lead to confusion otherwise.

#### 4. Perhaps add a link to the documentation on the regex engine used
For people familiar with regular expressions (and others who are curious), it might be helpful adding a link to the Python [Regular Expression Syntax](https://docs.python.org/3/library/re.html?highlight=match#regular-expression-syntax).

----

I'd be quite happy to open a pull request for this, but would appreciate comments & feedback on the points mentioned above first.

**Comment by yagebu** [comment]
> I'd be quite happy to open a pull request for this, but would appreciate comments & feedback on the points mentioned above first.

:+1: for improving these help texts! 1 and 4 sound good :)

Regarding 2:

There's actually one edge case where we look for an exact match: If the given string is not a valid regex. That behaviour is probably not ideal though, as one single character that makes an invalid regex changes the filter quite drastically without any feedback for the user why that happened.

Regarding 3:

It would be good to document it - but maybe we should change the behaviour? Looking for a match anywhere in the string would allow one to not have to use too many `.*` and if one wants to have an anchored match, one can still use `^`.

**Comment by wylfen** [comment]
> There's actually one edge case where we look for an exact match: If the given string is not a valid regex. That behaviour is probably not ideal though, as one single character that makes an invalid regex changes the filter quite drastically without any feedback for the user why that happened.

I am not sure how to improve this. To me, the most sensible (and least invasive) choice right now is to keep, but document this behaviour.

If instead we choose to raise an error in the python code, there is no way the user ever sees this error message: I don't have a complete grasp of the codebase, but from what I have seen all that will be displayed is the generic `Loading <URL> failed` message.

How hard would it be to include error messages originating from the python side in the error popups?

> It would be good to document it - but maybe we should change the behaviour? Looking for a match anywhere in the string would allow one to not have to use too many `.*` and if one wants to have an anchored match, one can still use `^`.

I would be happy with this change.

As far as I can see this amounts to a one-line change (`search` instead of `match`) here... https://github.com/beancount/fava/blob/c388a704b82470d022c7a700df2144c76f52e4f4/fava/core/filters.py#L125

... and also making sure the tests work appropriately.

If this is something the project approves of, I'd be happy to contribute a PR here as well. In that case, I'd include the change in matching behaviour in the same PR as the help page changes (but as separate commits, of course).

**Comment by yagebu** [comment]
> I am not sure how to improve this. To me, the most sensible (and least invasive) choice right now is to keep, but document this behaviour.

Sounds good.

> How hard would it be to include error messages originating from the python side in the error popups?

Shouldn't be too hard, it's rendered in the returned HTML. I'll see if I can implement this - it would also be useful for other possible errors (like entering an invalid time filter).

> I would be happy with this change.
> As far as I can see this amounts to a one-line change (search instead of match) here... 

Yes, that looks correct.

A PR with this change and the help changes would be very welcome, thank you :)
