### ISSUE TITLE
Unable to Import External Data

### ISSUE THREAD

**Issue by akshay1994** [beancount/fava#1077]
After updating my fava installation, I am unable to import external statements (https://github.com/beancount/fava/blob/master/fava/help/import.md).

I get the following screen instead of the option to import a file as before:

<img width="920" alt="Screenshot 2020-03-18 at 9 02 11 PM" src="https://user-images.githubusercontent.com/3862942/76977782-cb2ebe00-695b-11ea-8944-6b97b867c536.png">

It asks me to set a documents folder, and even if I configure one in settings, it just copies the file over there, instead of reading and importing the entries in there.

**Comment by yagebu** [comment]
It looks like this if no importer accepts the file.

Does `bean-extract` work with your configuration? Can you give some more details of your importer and importer configuration?
