### ISSUE TITLE
Investment tools for Fava: Help me develop!

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1082]
Cross posting from [here](https://groups.google.com/forum/#!topic/beancount/PHsawHxRSI8).

One area that is missing in fava today is investment tools.

I've found Beancount to be very well designed to capture and represent almost anything necessary for handling investments in the realm of personal finance (thanks, Martin!), and Fava to be a terrific front end (thanks, Fava authors)!

I'd like to develop a set of investment reports and tooling. I've started an empty repo at:
https://github.com/redstreet/fava-investor

I'd love contributions! In the form of design input,well thought out feature requests, tests, and of course, code.

Here are my [initial thoughts](https://github.com/redstreet/fava-investor/blob/master/design.md).

# Desired feature list

The goal is to develop a comprehensive set of reports and tools related to investments
for fava. This document contains list of potential features that we would like to
consider for implementation.

### Asset allocation: By asset class:
- Port [this](https://github.com/redstreet/beancount_asset_allocation) over to fava
- Pie chart, hierarchical
  - Reference chart
  - top level alone chart (to simplify complex portfolios)?

- Tax adjusted

### Asset allocation: By account:
- like the current one

### Asset allocation: Tax Treatment:
- taxable, tax-deferred, etc.
- configure using parent account or metadata

### IRR (internal rate of return):
- across specified portfolio
- drillable down to account-level and holding-leve
- advanced: show tax drag (difficult to quantify)

### Net worth:
- across time (redundant?)
- show split of contributions, income (dividends, gains, etc.), and appreciation
  - filterable (by account?)
  - across arbitrary time periods
  - related to IRR above

### Savings rate:
- absolute number across time
- as %age of gross, net

### Summary stats:
- number of unique funds owned
- number of brokerage accounts

### Cash drag analysis:
- cash as percentage of portfolio, and where it is

### Tax loss harvester:
- suck this in

### Rebalancing:
- consider plugging into a rebalancing tool ([example1](https://github.com/AlexisDeschamps/portfolio-rebalancer))

**Comment by bryall** [comment]
I was about to code something similar for my needs. I would love to contribute

**Comment by HappyEinara** [comment]
Hi, I've written a script to do IRR which I was planning to open source once it was ready, with the intention of building this out into a suite of performance tools along the lines you're considering.

With my script: assuming the price database is filled in for any opening or closing balances, it does the whole history of the file, or optional start or end dates. It does this by collapsing the history into a series of dated cashflows in or out of the operating currency, with 'synthetic' cashflows representing opening or closing balances at the specified dates or at the start or end of the file's history.

What was hard was breaking this down by holding (either by currency or account). The problem I got stuck on was designing robust logic for this. If transactions that 'touch' a given account-set or commodity have only the operating currency plus one other currency, it might be quite straightforward. But imagine I buy Bitcoin with AUD, then buy LTC with BTC. I'd need to convert the second tx into correctly priced synthetic 'sale' and 'purchase' transactions denominated in my operating currency (AUD) before converting those into cashflows. Didn't get that far.

**Comment by HappyEinara** [comment]
Can I add one more feature to the IRR bullet points: annualising returns is very important and (X)IRR is essential. But so is benchmarking. Given a beancount commodity and price history that represents a benchmark (e.g. the history of an index), I'd like to be able to see my under-/outperformance. This could be done by calculating the XIRR of the chosen commodity/account/portfolio/file and also the benchmark commodity over the same period. Ideally I'd like to be able to set a file-level default benchmark, but also override this via metadata on an account or commodity, as there may be more appropriate benchmarks for specific investments than my usual one.

**Comment by HappyEinara** [comment]
It would also be good if this could be built in modular fashion so we can use it as a library for beancount scripting, a cli and as a fava plugin (should fava-investor be beancount-investor, with a fava plugin?)

**Comment by baartosz** [comment]
I can help. Would be great if you could describe how to set up env, install deps and run fava with the plugin so I (and others) can jump in easily.

**Comment by redstreet** [comment]
@baartosz good idea, will do shortly.

**Comment by redstreet** [comment]
Done:
https://github.com/beancount/fava/blob/master/CONTRIBUTING.md

Does this help? There's currently only a hello world example which is mostly copied from the example in fava. I'll put in my tax loss harvestor once I figure out https://github.com/redstreet/fava-investor/issues/10, and also port over https://github.com/redstreet/beancount_asset_allocation

**Comment by redstreet** [comment]
Fixed CONTRIBUTING.md link above.

**Comment by redstreet** [comment]
Added two modules: a simple asset allocation (by account), and a tax loss harvester.

**Comment by baartosz** [comment]
Thanks for the doc. I am having some issues there still - Fava runs with `example.bc` but throws `Importing module "plugins.fava.investor" failed.`. Is there some more setup needed?

Sorry if question is silly, i am not really sure how plugins are loaded in fava.

**Comment by redstreet** [comment]
@HappyEinara, 👍 on your notes about IRR/XIRR. Proposal welcome. You can open an issue in fava-investor, or submit a PR for modules/performance/design.md if you want to start coding.

**Comment by redstreet** [comment]
Appreciate the pinning, @yagebu!

**Comment by redstreet** [comment]
Would love help from anyone interested in:
### Web related
- Pretty-fying the tabbed interface
- Rendering the asset allocation by class as a tree-table

### Building and publishing
- PyPI
- Adding tests, linter
- Building releases
- Writing blog posts

### Developing modules
- see modules above, or suggest your own


### Beta testers

**Comment by redstreet** [comment]
Wanted! Beta testers. Test [Fava Investor](https://github.com/redstreet/fava_investor) with your personal finances, and let me know of anything that doesn't make sense. Minimal test files to reproduce the issues appreciated.
