### ISSUE TITLE
Can a fava extension have tabs like the Holdings page?

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1083]
See: https://github.com/redstreet/fava-investor/issues/10

App routine (@app.route) is needed to make the Holdings page work. Can this be done in a Fava extension? If so, would someone be kind enough to post an example? If not, what is need to make this possible?

Thank you.

**Comment by yagebu** [comment]
Instead of there being separate full URL paths for these tabs, you could also add something to the query string (the `?key=value`) part of the URL and render your report depending on the query string. You can access the query in the template with request.args (you can grep Fava for some examples)

**Comment by redstreet** [comment]
Thank you, that helps!
