### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by bryall** [beancount/fava#1084]
With most browsers adding the ability to have a light and dark mode. How hard would it be to add this to fava? is it just a CSS change? 

Would be nice to have  this feature

**Comment by yagebu** [comment]
I don't plan on adding this, a PR would be welcome though, is this is an easily maintainable addition.

For the most part, this can be done in CSS (in style.css, we set variables for most of the colors used in CSS in Fava), the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), could be used to overwrite those conditionally.

**Comment by TRSx80** [comment]
I have been using the Firefox add-on "Dark Background and Light Text" not only for Fava, but pretty much everything for some years now.  I have tried some others, but keep coming back to it.

**Comment by yagebu** [comment]
If anyone wants to step up and provide a PR, that would be welcome, I'll close this issue in the meantime, since I don't plan to implement it.

**Comment by arkn98** [comment]
I'm willing to work on this. I've created a draft PR #1238 so that related discussion can begin.

**Comment by TRSx80** [comment]
In similar vein as my previous comment, except now I have become a convert to Dark Reader for most sites (in fact I keep them both installed, but most of time now DBLT is turned off)!
