### ISSUE TITLE
How to change the language of fava

### ISSUE THREAD

**Issue by SupernovaTitanium** [beancount/fava#1086]
How could I change the language from Simplified Chinese to Traditional Chinese/English?
I noticed you had a language column in options, but it said "none". How could I set it?

Thank you.
![favalanguage](https://user-images.githubusercontent.com/12254451/78804038-441cb500-79f2-11ea-95ae-bb97eab4fccf.png)

**Comment by yagebu** [comment]
Fava's options and how to set them are documented on the help pages (Help -> Options). https://fava.pythonanywhere.com/example-beancount-file/help/options/
