### ISSUE TITLE
Fava extension: ability to use multiple html files

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1087]
`fava.core.extensions.ExtensionModule.template_and_extension()` reads a single html file. Can this be extended to support all html files in the extension's template directory? This will help larger extensions like https://github.com/redstreet/fava_investor

@seltzered: thoughts?

**Comment by yagebu** [comment]
This should already be possible - simply put multiple Fava extension classes in the same module.

**Comment by redstreet** [comment]
My use case is for having a single extension class with built-in tabs. See [screenshot](https://github.com/redstreet/fava_investor/blob/master/screenshot.png).

Even if I split that into multiple extension classes, the problem is, I can't share any template code between them. Eg: see the [tree ](https://github.com/redstreet/fava_investor/blob/master/screenshot.png) macro.

**Comment by yagebu** [comment]
Ah, I see, you want to use include directives in your templates. Yes, that would need some code changes on Fava's side. I think you'll need to change the Jinja2 template loader temporarily for that request.

**Comment by redstreet** [comment]
Yes :). It's not a pressing issue. I'll leave this ticket open to see if @seltzered or someone else wants to work on it while I work on the fava_investor backend.

**Comment by yagebu** [comment]
Actually, after looking into this a bit more, I'll close this as a wont-fix, as this is non-trivial to do and not worth the effort.

If you need to reuse a macro, it's not hard to do that in the extension: just load the template, compile it and pass the macro to the template where you want to use it.

**Comment by redstreet** [comment]
Sounds good!
