### ISSUE TITLE
Fava extension: Make portfolio_demo example support time filtering

### ISSUE THREAD

**Issue by seltzered** [beancount/fava#1093]
As discussed in https://github.com/beancount/fava/pull/1092, the fava extension example (portfolio_demo) should support time filtering as most other views in fava support it.

**Comment by yagebu** [comment]
It seems to just use `root_tree`, which is filtered, so what needs to be done here?

**Comment by yagebu** [comment]
I'll close this, if I missed something here, please reopen :)
