### ISSUE TITLE
why it just quits?

### ISSUE THREAD

**Issue by dotkt** [beancount/fava#1109]
why it just quits?
this is my bean file:

1970-01-01 open Income:Windfall
1970-01-01 open Assets:Cash
1970-01-01 open Liabilities:Da-Ming
1970-01-01 open Expenses:Clothing

2016-01-01 * "捡到钱了"
  Income:Windfall                            -100.00 CNY
  Assets:Cash                                +100.00 CNY

2016-01-01 * "向大明借钱"
  Liabilities:Da-Ming                        -200.00 CNY
  Assets:Cash                                +200.00 CNY

2016-01-01 * "XX 百货商店" "买衣服"
  Assets:Cash                                -300.00 CNY
  Expenses:Clothing                          +300.00 CNY

2016-01-02 * "XX 百货商店" "退衣服"
  Expenses:Clothing                          -250.00 CNY
  Assets:Cash                                +250.00 CNY

**Comment by yagebu** [comment]
> why it just quits?

Without some more detail that's impossible to answer. That file works for me.

**Comment by Xdminsy** [comment]
My `fava.exe` also quits without any output.
Even `fava --help` gives nothing and quits.
My system is Windows 10 Version 1903, and my Python environment is Anaconda.
Is there another way to start fava like `python -m fava`?
It seems my `fava.exe` is totally unusable.

**Comment by yagebu** [comment]
> Is there another way to start fava like python -m fava?

`python -m fava.cli` should work.

**Comment by kangdalei** [comment]
I have the same operating results.  fava.exe quits without any output. My system is Windows 7.  fava  Version: 1.15  python 3.6

`python3 -m fava.cli` doesn't work, and also quit without any output.

@dotkt , did you solve this problem?
