### ISSUE TITLE
Viewing expenses in treemap in the spender's currency on trial balance

### ISSUE THREAD

**Issue by Azenet** [beancount/fava#1110]
Hi,

In the treemap, is there a way to view a converted sum in the currency used in the asset instead of the currency of the receiving expense?

<details>
<summary>Example ledger</summary>

    option "operating_currency" "EUR"
    option "operating_currency" "USD"
    
    2020-01-01 open Expenses:E1
    2020-01-01 open Assets:A1
    
    2020-01-01 * "EUR->EUR operation"
    	Expenses:E1	10.00 EUR
    	Assets:A1
    
    2020-01-01 * "USD->EUR operation"
    	Expenses:E1	10.00 USD @@ 5.00 EUR
    	Assets:A1

</details>

In the above ledger, balance of Assets:A1 is -15.00 EUR, however when the treemap is selected I can only see 10.00 EUR to Expenses:E1, or 10.00 USD to Expenses:E1 depending on the selected currency. I thought #242 would allow me to select "Converted to EUR" in the other dropdown to see a converted sum in the treemap, however to no avail as it changes nothing in the resulting treemap.

I'm not sure whether this is a bug or the way it is supposed to work, if it is would you consider adding this as a feature? My use case is visualizing at a glance expenses converted in my main currency.

Thank you!

**Comment by yagebu** [comment]
Adding a price with the `@` syntax doesn't add an entry to the price database. Without any prices in the price map, no conversion will happen, so you need to specify a price entry for the EUR-USD price explicitly:

    2020-01-01 price EUR 2.00 USD

**Comment by Azenet** [comment]
Right, I must have skipped this in the documentation. That led me to find about the `beancount.plugins.implicit_prices` plugin, which works as well. Thank you!
