### ISSUE TITLE
Translation to Catalan

### ISSUE THREAD

**Issue by MarcRiera** [beancount/fava#1115]
Hello,

I am a freelancer who has begun to use Fava for personal and professional accounting and it perfectly suits my needs. Thanks for the amazing piece of software! I would like to translate it to Catalan but I see that new languages cannot be added directly from POEditor.com (at least not as a translation contributor).

Thanks!

**Comment by yagebu** [comment]
I've added Catalan on poeditor.com.

Let me know when you're done with a first pass then I'll add it to the languages to be fetched into Fava.

**Comment by MarcRiera** [comment]
Thank you. I have been able to join the Catalan team but I am still unable to access the editor. When selecting "Catalan" for Fava in my list of projects, "pending" is displayed. Maybe contributors need to be approved once they join a project? (Sorry, first time user of POEditor)

**Comment by yagebu** [comment]
Done
