### ISSUE TITLE
unrealized gain not shown from the date

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#1120]
in fava, when we are in the balance sheet , if we decide to see the market value , we see in green or red  the unrealised gain or loss. 
we can also ask to only for a period of time.
we see the unrealised gain or loss for all the time not for the requested period of time. 

it could be very good, if we can see the gain during the time requested.

**Comment by Zburatorul** [comment]
Have you tried the "Time" filter in the top right corner of the page? Accessible with shortcut "ft".

**Comment by ThomasdenH** [comment]
The unrealized profit/loss is always just the difference between the bought value and the current market value, independent of the selected time. Am I missing something?
