### ISSUE TITLE
Queries don't load when behind traefik (direct access works) - TypeError: NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#1126]
I'm using the fava docker (have been for a while), and I recently switched from the nginx reverse proxy to traefik. Am much happier with traefik for various reasons but I just noticed I'm getting the error "TypeError: NetworkError when attempting to fetch resource", only in the queries screen. Other screens in fava seem to work fine. When I switch to chromium instead of firefox, I get the error "TypeError: Failed to Fetch".

I'm using yegle's Fava dockerfile and traefik v2.2 with the traefik-forward-auth middleware (to provide OAuth).

I'm posting here first to try and find out what's different about that page so I can either narrow my google searches down or report the issue to traefik. In particular, the scattered google responses seem to indicate something to do with headers (can't really comment, not really a web person). The web console shows some error about 'Mixed Content' requesting an insecure resource, but I'm not sure why this wouldn't have been an issue with nginx (identical fava docker).

**Comment by yagebu** [comment]
The API calls on the query page use the same helper functions as the other places, so I don't have an explanation why that page would behave differently.

**Comment by ngoonee** [comment]
Could you provide an example of another page which uses those helper functions? Because I think there's a difference in behaviour, in that the query page does a 'sub-call' somehow which doesn't change the rest of the page (something to do with Ajax?) while the other pages are simply links (loads the page at a new URL).

Been trying to figure out how to use the console, and the content which is being blocked is "http://my.fava.url.duckdns.org/accounts/api/changed/" if that helps. Another error is for the URL "http://my.fava.url.duckdns.org/accounts/api/query_result/?query_string=run+%22queryname%22"

**Comment by yagebu** [comment]
Yes, those are ajax calls that fail. I assume those errors are due to some proxy misconfiguration (Maybe an incorrect redirect?). We request the `baseURL` value plus the api path.

**Comment by yagebu** [comment]
Looks like this https://github.com/beancount/fava/issues/665#issuecomment-545112429

**Comment by ngoonee** [comment]
Interestingly enough this started working (same docker-compose files) when I moved to a different machine (older machine has reliability issues currently). Pretty sure the issue isn't with fava then.
