### ISSUE TITLE
Consider alternative pathways to viewing account journals.

### ISSUE THREAD

**Issue by seltzered** [beancount/fava#1127]
I've been noticing my uses for fava have been more around viewing just a specific account. Normally one gets to an account journal page not through any direct link in the sidebar or when searching an account (that's for filtering, but by going into a different area (e.g. income statement, navigating the tree tab to look for the account you want, then selecting the account). 

I think a faster user path could be done through either:

1. Having a sidebar page to the account journal, paired a text-filter within either the page itself or in the breadcrumb menu (see mockup) to enable changing the account being viewed. 
(tradeoffs: I'm not sure what a user clicking on 'view account' in the sidebar would see by default.)<img width="405" alt="Screen Shot 2020-07-24 at 1 22 45 PM" src="https://user-images.githubusercontent.com/297435/88432301-c74ef480-cdb0-11ea-9238-a31d1e87480d.png">

2. Adding a 'view' button within the account filter entry to not filter, but enter the associated account journal
(tradeoffs: from a functional perspective, it may seem a bit confusing to throw in viewing from an area oriented around generic filtering, but may be easier to implement since it's already there.) <img width="625" alt="Screen Shot 2020-07-24 at 1 15 18 PM" src="https://user-images.githubusercontent.com/297435/88431718-c1a4df00-cdaf-11ea-9718-67d08c42bee6.png">

Anyone else have a similar sentiment or have ideas to jumping into account journals easier?

**Comment by Zburatorul** [comment]
I have a similar usage pattern and I find myself having to first "gi" or "gb", then "fa", enter keyword, use mouse to click on account. This kinda works, but it doesn't actually filter by account name.

I like both of your suggestions provided they navigable entirely from the keyboard (I don't want to have to click "view" with the mouse).

**Comment by yagebu** [comment]
Yep, this has also been bugging me. I think I'd prefer a sidebar link with a filterable dropdown. The `g a` keyboard shortcut is still available :)
