### ISSUE TITLE
set bean file title to "Account books" will cause auto-reload failed.

### ISSUE THREAD

**Issue by wctang** [beancount/fava#1129]
### Subject of the issue
set bean file title to "Account books" will cause auto-reload failed.

### Your environment
Python 3.8.3
beancount-2.3.1-dev
fava (git commint '330d023")
chrome v84

### Steps to reproduce
set the bean file title as
`option "title" "Account books"`

### Expected behaviour
every thing good.

### Actual behaviour
the auto-reload function failed, and lot's of console log in browser
`GET http://localhost:5000/account-books/api/changed/ 404 (NOT FOUND)`

### Workaround
change bean file title.

**Comment by yagebu** [comment]
I couldn't reproduce this from the given steps. I assume you changed the title without restarting Fava - then this is caused by Fava currently not checking whether the slugs change.
