### ISSUE TITLE
Missing "other currency" column in Balance Sheet

### ISSUE THREAD

**Issue by scanta2** [beancount/fava#1131]
I just reinstalled Ubuntu on my laptop, and reinstalled fava, too. I used to have three columns in the Balance Sheet page: USD, EUR, and Other for commodities without prices or conversions, such as VACA, POINTS, etc.

That column is not showing up anymore.
Did anything change, or is there a new option to bring it back?
Thanks

**Comment by yagebu** [comment]
Beancount silently dropped the "commodities" option which was used for this: https://github.com/beancount/beancount/pull/472

**Comment by xwartz** [comment]
how to add the `other currency` column back?

**Comment by yagebu** [comment]
You'll either have to downgrade Beancount or wait for the next release of Fava.
