### ISSUE TITLE
Fava load on server

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#1139]
I first started using fava on pythonanywhere's free tier, they're an awesome service but it was always slightly laggy (which is fair enough as I wasn't paying for it). Eventually I moved to self-hosting on an old laptop I had lying around, which worked just fine.

Recently the laptop has shown signs of failing, so I started thinking about moving things off it. I have a raspberry pi 3b from an old project, so I thought I'd try that. It was horrendously slow (website itself takes minutes to load), which was very surprising to me.

There's this old report - https://github.com/beancount/fava/issues/582 which touches on a similar issue with an older model of the pi. Things aren't as bad on the raspberry pi 3b because it's multi-core, but it still does max out one core.

The relative speed is surprising to me though because even in active use on my old laptop, CPU use was minimal in my monitoring. This is backed up by my pi not really struggling to run other CLI stuff while fava is running. Am wondering whether there's some ARM-related bottlenecks (as it doesn't seem like my CPU should be anywhere close to being maxed given its relative lack of use on my laptop) or inefficiencies, perhaps with flask?

**Comment by yagebu** [comment]
> Am wondering whether there's some ARM-related bottlenecks (as it doesn't seem like my CPU should be anywhere close to being maxed given its relative lack of use on my laptop) or inefficiencies, perhaps with flask?

I doubt that it's with Flask, that doesn't really take up much compute time.

It could be that the PI is just too slow or there's some ARM-related bottlenecks somewhere else (the OS, libc, Python, Beancount). The only Fava or Beancount related factor that I could think would be somehow lack of a fast cdecimal on your system.

**Comment by ngoonee** [comment]
The possibility of it just being too slow is quite possible, but the load times I'm seeing are crazy.

Would I/O speed be a factor? I've got almost 5MB total among my various beancount files.

**Comment by yagebu** [comment]
> Would I/O speed be a factor? I've got almost 5MB total among my various beancount files.

I doubt it - at that size, it should all be loaded into RAM by the kernel.

You'll have to do some profiling if you want to get to the bottom of this I guess.

**Comment by ngoonee** [comment]
Urgh I was afraid of that. I only have experience profiling C++ with valgrind, haven't had a need with python code (beyond simple 'print(time.time())' stuff. Does fava have any built-in tooling for it, or should I just start picking at the code?

**Comment by yagebu** [comment]
Fava has a flag in the CLI to profile the requests.

**Comment by ngoonee** [comment]
@yagebu I've gotten around to trying this out, here's the output. Seems like it's to do with pydecimal being slow as *** (perhaps other things, but that's what stands out):-

PATH: '/bethsimchatadonai-accounts/income_statement/'
         12459731 function calls (12457694 primitive calls) in 113.116 seconds

   Ordered by: internal time, call count
   List reduced from 444 to 30 due to restriction <30>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   206155   10.456    0.000   28.702    0.000 /usr/lib/python3.8/_pydecimal.py:1661(_fix)
   354485    9.011    0.000   10.598    0.000 /usr/lib/python3.8/_pydecimal.py:522(__new__)
   127251    8.717    0.000   41.531    0.000 /usr/lib/python3.8/_pydecimal.py:1157(__add__)
   530711    6.631    0.000    6.854    0.000 /usr/lib/python3.8/_pydecimal.py:5620(__init__)
   277862    6.331    0.000    7.155    0.000 /usr/lib/python3.8/_pydecimal.py:4024(_raise_error)
    78904    6.079    0.000   27.887    0.000 /usr/lib/python3.8/_pydecimal.py:1324(__truediv__)
     9352    5.925    0.001   73.664    0.008 /home/ngoonee/fava/lib/python3.8/site-packages/fava/core/budgets.py:142(calculate_budget)
   124301    5.259    0.000    5.743    0.000 /usr/lib/python3.8/_pydecimal.py:5640(_normalize)
   292824    4.653    0.000    4.653    0.000 /home/ngoonee/fava/lib/python3.8/site-packages/fava/util/date.py:337(days_in_daterange)
  1173478    3.980    0.000    3.980    0.000 /usr/lib/python3.8/_pydecimal.py:810(__bool__)
   137924    3.643    0.000    8.384    0.000 /usr/lib/python3.8/_pydecimal.py:6032(_convert_for_comparison)
    78904    3.406    0.000    4.680    0.000 /home/ngoonee/fava/lib/python3.8/site-packages/fava/util/date.py:354(number_of_days_in_period)
   321547    3.171    0.000    3.661    0.000 /usr/lib/python3.8/_pydecimal.py:3830(_dec_from_triple)
    46459    2.592    0.000   32.771    0.001 /home/ngoonee/fava/lib/python3.8/site-packages/beancount/core/inventory.py:361(add_amount)
      504    2.279    0.005  112.862    0.224 /home/ngoonee/fava/lib/python3.8/site-packages/fava/core/charts.py:107(interval_totals)
   283472    2.265    0.000    2.265    0.000 /home/ngoonee/fava/lib/python3.8/site-packages/fava/core/budgets.py:126(_matching_budgets)
  2175341    2.002    0.000    3.180    0.000 {built-in method builtins.isinstance}
   148526    1.821    0.000    4.000    0.000 /usr/lib/python3.8/_pydecimal.py:1790(_round_half_even)
   297321    1.615    0.000    1.838    0.000 /usr/lib/python3.8/_pydecimal.py:444(getcontext)
   206155    1.607    0.000    4.386    0.000 /usr/lib/python3.8/_pydecimal.py:6013(_convert_other)
   206155    1.396    0.000    1.396    0.000 /usr/lib/python3.8/_pydecimal.py:4067(Etiny)
    91020    1.378    0.000   12.203    0.000 /usr/lib/python3.8/_pydecimal.py:916(__ge__)
    79405    1.298    0.000    1.298    0.000 /home/ngoonee/fava/lib/python3.8/site-packages/fava/util/date.py:71(get_next_interval)
   137924    1.281    0.000    2.266    0.000 /usr/lib/python3.8/_pydecimal.py:817(_cmp)
   145394    1.245    0.000    1.499    0.000 /usr/lib/python3.8/_pydecimal.py:1774(_round_half_up)
   206155    1.231    0.000    1.231    0.000 /usr/lib/python3.8/_pydecimal.py:4071(Etop)
   770035    1.207    0.000    1.207    0.000 {built-in method __new__ of type object at 0xffffa47440e0}
   226538    0.984    0.000    0.984    0.000 {method 'match' of 're.Pattern' objects}
   100372    0.872    0.000    1.178    0.000 /usr/lib/python3.8/abc.py:96(__instancecheck__)
    46904    0.842    0.000    2.404    0.000 /usr/lib/python3.8/_pydecimal.py:881(__eq__)

**Comment by yagebu** [comment]
Well that definitely looks like your missing `cdecimal`

**Comment by ngoonee** [comment]
The thing is, I'm pretty sure cdecimal is supposed to be built in with python 3.3 and above (I'm on 3.8). Indeed I have /usr/lib/python3.8/lib-dynload/_decimal.cpython-38-aarch64-linux-gnu.so on my Pi.

But when I run a simple benchmark using Decimal it seems to run a hundred times slower than float. This ratio is consistent between my desktop and my pi, difference being my desktop is much faster anyway. Anyway it seems clear the issue is on the system python rather than fava or beancount. Thanks much

**Comment by yagebu** [comment]
> The thing is, I'm pretty sure cdecimal is supposed to be built in with python 3.3 and above (I'm on 3.8). Indeed I have /usr/lib/python3.8/lib-dynload/_decimal.cpython-38-aarch64-linux-gnu.so on my Pi.

It's supposed to be built-in, but some distributions only put an optional dependency on the underlying C library, for example on Arch Linux, mpdecimal is only an optional dependency (https://www.archlinux.org/packages/extra/x86_64/python/). So you might have the .so on the Python side of things, but that won't help if mpdecimal is not installed.

**Comment by ngoonee** [comment]
That's it exactly! I was just testing the benchmark on another machine and got much faster results, so I actually came across mention of mpdecimal on another search trying to figure this out. Now the benchmark is almost equivalent to float. Let me start fava up again...
