### ISSUE TITLE
Segmentation fault on any command

### ISSUE THREAD

**Issue by philip-iv** [beancount/fava#1140]
On latest Windows 10 with `fava==1.15`, `beancount==2.3.0`, `python==3.6.6` running the `fava` command always results in a segfault. This includes running `fava --help`, `fava ledger.beancount`, or plain `fava`. No output is displayed, only the segmentation fault message.

**Comment by yagebu** [comment]
Fava doesn't use any compiled extension modules, so it can't really cause any segmentation faults. The bug must lie somewhere else - does the segmentation fault message give any hints? Does beancount work?

**Comment by philip-iv** [comment]
Beancount works, I can run reports or bean-web without an issue. The message only says "Segmentation fault".

**Comment by yagebu** [comment]
Since this segmentation fault can't come from a bug in Fava, I'll close this bug. I'd suggest trying to see if upgrading all dependencies helps.
