### ISSUE TITLE
Faster transaction inserting: Don't automatically populate amounts left out in the template transaction

### ISSUE THREAD

**Issue by pmarciniak** [beancount/fava#1146]
When populating the transaction entry dialog based on a past (template) transaction (using the payee search feature), fava adds an auto-calculated amount for the Amount field that was left empty in the original transaction. I feel like this feature hurts more than it helps. More often than not, I end up clearing that field back (which takes additional time for every entered transaction).

Consider this example: every week I add the same kind of transaction:

1955-11-05 * "Migros" "Weekly shopping"
  Expenses:Groceries
  Expenses:Supplies  15 CHF
  Liabilities:Credit-card  -100 CHF

The groceries line is made of dozens of entries on the receipt, so having to sum them up would be a deal breaker.
The following week, when I enter "Migros" for payee, I get this:
  Expenses:Groceries 85 CHF
  Expenses:Supplies  15 CHF
  Liabilities:Credit-card  -100 CHF

Ideally, I'd like the Groceries line to remain empty, so that I can just quickly update the Supplies and Credit-card values and click save.

**Comment by yagebu** [comment]
After the booking happened in Beancount, all "empty" postings will have been filled. So Fava does nothing to add them and there's no quick way to get the Transaction back as it is in your Beancount file. I'm not opposed to your suggestion but it just doesn't seem worth the effort, so I'll close this as a wont-fix. If you want to implement this, feel free :)
