### ISSUE TITLE
Transaction inserting: Support adding per-posting metadata

### ISSUE THREAD

**Issue by pmarciniak** [beancount/fava#1147]
When entering transactions directly from a text editor, I often add comments to postings, e.g.:

1955-11-05 * "" "Grocery shopping"
  [...]
  Expenses:Groceries:Alcohol  20.00 USD
    memo: "Beer for the BBQ"
  [...]

This is currently not supported in fava's transaction adding dialog.

**Comment by yagebu** [comment]
I don't really intend for the transaction form to support every intricacy of Beancount's syntax. At some point, I don't think there's much to be gained and writing the transaction directly in the editor would be similarly convenient.

**Comment by mcbloch** [comment]
Is this something you would accept a pr for or are you certain you don't want this?

Don't want someone wasting their time tackling an issue that will not be approved

**Comment by pmarciniak** [comment]
OK, just for posterity, here's why I think entering transactions directly in the editor is far less convenient. This applies especially when one manually enters transactions from receipts, so dozens of transactions during a single session, and every second/click/keystroke/fava UI refresh counts:
1. One cannot rely on "insert-entry" fava-option and has to manually pick one out of potentially dozens of files to enter the transaction into.
2. No auto-completion of the Payee name
3. No pre-populated transaction template after choosing an already used Payee
4. No auto-formatting: indentations need to be added and removed manually, values not automatically aligned to the right.
5. No way to have simple arithmetic done and skip the main currency symbol. I.e. when entering with the dialog, I can write simply "2.20+3.30" and have "5.50 CHF" end up in my beancount file.

**Comment by yagebu** [comment]
> here's why I think entering transactions directly in the editor is far less convenient.

I hear you - there's definitely aspects where the transaction form excels :) I mostly use a two-step process, because I find certain edits to be faster in a proper editor like vim, so I can also do edits there that the transaction form doesn't allow.

I personally have no real use for it but I wouldn't be completely opposed to it either. But I think an implementation should make some smart use of something like keyboard shortcuts so that we don't have to add a ton of buttons.

**Comment by yagebu** [comment]
This was added in #1722
