### ISSUE TITLE
Transaction inserting: support adding a new posting directly under the current one

### ISSUE THREAD

**Issue by pmarciniak** [beancount/fava#1150]
Being able to add a new posting only at the very bottom is problematic in case one uses the feature to auto-populate transaction template together with fava's "insert-entry" option.
"insert-entry" option treats the last posting of the transaction as the anchor, so it has to remain last. Therefore, when an additional posting needs to be added to the template transaction, one has to delete the anchor posting, add whatever new postings are needed, and then finally re-add the anchor posting.

**Comment by yagebu** [comment]
Are you aware that the transaction form supports dragging and dropping to reorder postings?

**Comment by pmarciniak** [comment]
Oh, I didn't know! Thank you. I think that's a good enough workaround - feel free to close this FR.
