### ISSUE TITLE
Fava cannot edit files in Editor under https proxy

### ISSUE THREAD

**Issue by CharlesLiu7** [beancount/fava#1153]
My fava version is `1.15`, I used Apache http server to map fava 5000 port service to a https service, but I found I cannot edit any ledger file in Editor sidebar of webpage. The error is 
![](https://wx1.sinaimg.cn/mw690/e3aaf28fly1gimnxid82hj20bi03t0t0.jpg)

I tried to use `fava -d main.beancount` and found a behavior: in the Editor sidebar of Fava webpage, when I try to edit some ledger file, e.g. `/home/user/beancount/2020/09.bean`, Fava will first requests a 308 resource and then redirects to the real resource:
```bash
# http://localhost:5000, it works well
127.0.0.1 - - [11/Sep/2020 13:37:59] "GET /user/editor?file_path=%2Fhome%2Fuser%2Fbeancount%2F2020%2F09.bean&partial=true HTTP/1.1" 308 -
127.0.0.1 - - [11/Sep/2020 13:37:59] "GET /user/editor/?file_path=%2Fhome%2Fuser%2Fbeancount%2F2020%2F09.bean&partial=true HTTP/1.1" 200 -
```
```bash
# https://mydomain.com, I cannot edit any ledger
127.0.0.1 - - [11/Sep/2020 13:37:59] "GET /user/editor?file_path=%2Fhome%2Fuser%2Fbeancount%2F2020%2F09.bean&partial=true HTTP/1.1" 308 -
```
Is this behavior necessary? **OR** am I missing some configuration during the proxy process?

**HERE** is my apache config:
```
<VirtualHost *:80>
	ServerName mydomain.com
	<Location />
        RequestHeader unset Accept-Encoding
        ProxyPass        http://localhost:5000/
        ProxyPassReverse http://localhost:5000/
        ProxyPreserveHost on
        Order allow,deny
        Allow from all
	</Location>
    RewriteEngine On
    # This will enable the Rewrite capabilities
    RewriteCond %{HTTPS} !=on
    # This checks to make sure the connection is not already HTTPS
    RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</VirtualHost>
<VirtualHost *:443>
	ServerName mydomain.com
	<Location />
        RequestHeader unset Accept-Encoding
        ProxyPass        http://localhost:5000/
        ProxyPassReverse http://localhost:5000/
        ProxyPreserveHost on
        Order allow,deny
        Allow from all
	</Location>
    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /etc/letsencrypt/live/mydomain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.com/privkey.pem
</VirtualHost>
```

**Comment by yagebu** [comment]
> Is this behavior necessary? OR am I missing some configuration during the proxy process?

Not all these redirects would be strictly necessary, however Fava expects redirects to work - so your proxy configuration seems to be insufficient. I can't really you help you with that though since I'm no expert in configuring Apache.

**Comment by CharlesLiu7** [comment]
Okay, thanks for your response.

**Comment by yagebu** [comment]
There's a couple of other deployment-related issues on the tracker, maybe you can find a working snippet somewhere. Other than that, we're using the Flask framework, so if you run Fava as a WSGI application and not from the CLI, https://flask.palletsprojects.com/en/1.1.x/deploying/ might help.
