### ISSUE TITLE
Import transactions window too easy to close

### ISSUE THREAD

**Issue by justyns** [beancount/fava#1154]
Hello!

I recently upgraded Fava and decided to import a backlog of transactions (from .csv files), and noticed a frustrating issue with the new import UI/UX.  Instead of a single page listing all transactions, there's now a modal/popup type of window that comes up with "next" buttons to show one transaction at a time.

This is fine, but my problem is that it is _way too easy_ to accidentally close this window and lose all of the progress you've made so far.   After I noticed this issue, I started breaking my .csv file into smaller chunks so that I wouldn't lose as much.

A couple examples:

* Click "next" ~50 times, forget to click in the textbox, press "n" (first letter of an account I'm looking for).  The "new transaction" window pops up and I lose all of the data I entered for the previous 50 transactions.
* Click "next" ~50 times to enter data for transactions, go to another browser window to look up something, click on the original browser window to go back to fava.  The import dialog closes because I clicked outside of it and I lose all of the data I entered for the previous transactions.

I use a custom importer which is kind of slow, so having to start over from scratch each time is pretty painful.

Can we either a) make it harder to close that import dialog or b) save the state of an in-progress import and allow the user to complete it from where they left off later?

**Comment by yagebu** [comment]
Accidentally closing the dialog hasn't happened to me yet, but I can see that this might happen

I think saving the state would be good. Also, I guess that `n` (and most over keyboard shortcuts) should be ignored when this dialog is open. So basically a) and b) :)

**Comment by yagebu** [comment]
Keeping the extracted entries cached is implemented in #1167. There aren't any changes to the keyboard binding yet, I'd consider that a lower priority.
