### ISSUE TITLE
No response with add transaction and Editor page

### ISSUE THREAD

**Issue by fang-niuwa** [beancount/fava#1155]
beancount version: 2.3.2
fava version: 1.15
system: MacOS

I ran `fava filename.beancount` on my terminal and I can access the `localhost:5000`. But when I hit the add transaction button as usual, nothing is prompt for adding the transaction. and if I go to the editor panel, it is a blank page. 

<img width="358" alt="Screen Shot 2020-09-14 at 1 20 38 PM" src="https://user-images.githubusercontent.com/5194080/93123017-fef26280-f6b6-11ea-8cd9-3a1c8235b185.png">

The path on the address bar changed correctly, but nothing was showed up.

I've done

1. reinstall beancount and fava
2. upgrade the python to 3.8.5 from 3.8.1 and reinstall the beancount and fava
3. run `bean-check` on the file, it is a valid beancount file.

Any idea for why this is happenning?

**Comment by yagebu** [comment]
Which browser are you using and how are you installing Fava? What does the browser console show?

**Comment by yagebu** [comment]
Closing this due to missing feedback
