### ISSUE TITLE
Graphs should allow for line graph without points

### ISSUE THREAD

**Issue by floatingheads** [beancount/fava#1160]
Graphs can get really congested with the points when time intervals of weekly or daily are used. Is it possible to have an option to make the graph only a line without the points plotted separately?

**Comment by yagebu** [comment]
Area charts as an alternative to line charts were recently implemented - since these don't show the points, I'd be hesitant to addd such an option for the line charts. I guess we could reduce the size of the points a bit in any case.

**Comment by floatingheads** [comment]
Thanks yagebu. How do you access the area charts option? I hadn't seen that.
