### ISSUE TITLE
Can't convert to single currency

### ISSUE THREAD

**Issue by duarteocarmo** [beancount/fava#1162]
Hey there! First of all thanks for an amazing project. 

I live in two countries and have assets both in `DKK` and `EUR` 

Given the following file: 

```
; File name
option "title" "Duarte Finances"

; Currencies declaration
option "operating_currency" "EUR"
option "operating_currency" "DKK"

; Assets
2020-09-15 open Assets:Banking:CG:Savings    EUR
2020-09-15 open Assets:Banking:DB:Savings       DKK

; Equity
2020-09-15 open Equity:Opening-Balances

; Balances
2020-10-05 * "Initialize accounts"
    Assets:Banking:CG:Savings                       50.83 EUR
    Assets:Banking:DB:Savings                        200.98 DKK
    Equity:Opening-Balances

2020-10-06 balance Assets:Banking:CG:Savings        50.83 EUR
2020-10-06 balance Assets:Banking:DB:Savings         200.98 DKK                                                                                                         
```

Fava, creates a dashboard as such: 

![image](https://user-images.githubusercontent.com/26342344/95369665-041e8800-08d8-11eb-82d0-49873155b5aa.png)

However, when I click "Converted to EUR", none of the values change...

Moreover, it's quite misleading to have EUR and DKK amounts plotted on the same scale, as they have very different unit value..

Further investigating, I'm also not able to convert in BSQL:

![image](https://user-images.githubusercontent.com/26342344/95369719-139dd100-08d8-11eb-89ce-4eadbd8ad60c.png)

I would expect for some "conversion" to take place..

Is this a bug? Something I'm missing? Perhaps a beancount question? 

Thanks a lot for your help!

**Comment by yagebu** [comment]
Without any conversion rates specified, it's impossible for Fava to do the conversion. You'll need to add some price directives to your ledger (https://beancount.github.io/docs/beancount_language_syntax.html#prices)

**Comment by duarteocarmo** [comment]
Ah got it! Thanks for the help. Any tip on how you would handle those price directives throughout time?

**Comment by yagebu** [comment]
> Any tip on how you would handle those price directives throughout time?

I personally use the `beancount.plugins.implicit_prices` plugin, which basically adds a price for all transaction where a conversion happens. For foreign currencies, that's good enough for me.

There's also the `bean-price` utility, which allows fetching prices from online sources.

**Comment by duarteocarmo** [comment]
Great, won't bother you anymore, as I'm sure your busy, thanks for all the help and fantastic project 😄

**Comment by yagebu** [comment]
> Great, won't bother you anymore, as I'm sure your busy, thanks for all the help and fantastic project smile

No worries :D - you're welcome!
