### ISSUE TITLE
Income Statement Shows Conversion at Present Rate

### ISSUE THREAD

**Issue by diomekes** [beancount/fava#1168]
In the Income Statement view, if there's earned interest in a different currency, the balance shown for that interest is calculated at the present conversion rate, instead of the historical rate when the interest was earned.

I have entries with earned interest in a different currency without a price in the entry itself, but with a separate price entry for that date.  Should it not show the price from the date it was earned instead of changing it to the present conversion rate?

**Comment by yagebu** [comment]
This behaviour is expected, for currency conversions with `@`, Beancount discards the conversion rate. If you want to track the exchange rate, you'll have to add a cost, which you can then view in Fava with the "At Cost" conversion option.

**Comment by diomekes** [comment]
I see.  So it seems that, even if I use an implicit @ in the transaction, Beancount won't remember that (even though it shows up correctly when I look at the balance history, either in Fava or a query).

This is for tax purposes.  If I earn interest in a currency other than USD, I need to report it in USD and the correct amount would be the conversion rate at the time I actually earn the interest.  In this case, adding a cost doesn't really make sense, I don't think.

**Comment by yagebu** [comment]
Quite right. When you add a transaction with a conversion, you either tell Beancount to attach the exchange rate to the amount (`{}`) or to forget the exchange rate for this amount (`@`). Since you want the former behaviour, you should use cost.
