### ISSUE TITLE
Cannot click buttons in Safari

### ISSUE THREAD

**Issue by Triple-Z** [beancount/fava#1169]
1. Cannot click the ".." button in the cost column.
    <img width="962" alt="image" src="https://user-images.githubusercontent.com/16285716/96959865-8db69280-1533-11eb-966f-99ac20350242.png">

2. Cannot click the "open" button in journal page.
    <img width="487" alt="image" src="https://user-images.githubusercontent.com/16285716/96959871-94dda080-1533-11eb-9e6c-850099c84540.png">

There is no error in Safari console, and the `app.js` has loaded with no error.

There is no issue when I using Chrome.

Additional info:
- OS: macOS 10.15.7 (19H2)
- Safari: 14.0 (15610.1.28.1.9, 15610)
- Fava: 1.16

**Comment by yagebu** [comment]
Sadly, Safari doesn't yet support "Customized built-in elements" yet (https://caniuse.com/custom-elementsv1). These are used in some places like the journal to initialise elements.

**Comment by Triple-Z** [comment]
@yagebu Thanks for verifying it.

**Comment by yagebu** [comment]
I replaced some of the custom elements with the ones supported by Safari. The remaining two are sortable tables and the account trees, where the Javascript part is non-essential.

**Comment by Triple-Z** [comment]
Thx! This fix can work!
