### ISSUE TITLE
Cannot filter the query view

### ISSUE THREAD

**Issue by bamse16** [beancount/fava#1170]
In the https://fava.pythonanywhere.com/example-beancount-file/query/, run the following query:

```
SELECT date, account, narration, sum(number) as total, currency
FROM year = 2016 
GROUP BY date, account, narration, currency 
ORDER BY date, currency, account
```

Then using the boxes from the top bar, try to filter by tag or account (click in the box, then select tag/account).

In the previous versions, it was possible to do that. Not sure if this change is a bug or the previous behaviour was a bug.

As a workaround, you can edit the above query to include tags like this:

```
SELECT date, account, narration, sum(number) as total, currency
FROM year = 2016
WHERE 'trip-chicago-2016' in tags
GROUP BY date, account, narration, currency 
ORDER BY date, currency, account
```

**Comment by yagebu** [comment]
This was an unintended change of behaviour. The query page was rewritten and now fetches just the query result. However, it doesn't pass the current filters along with that request, so all entries are queried. I'd call it a bug.

**Comment by yagebu** [comment]
Fixed in https://github.com/beancount/fava/commit/ea524e143b411aacda88100d94d0ba70ad9a1e0f
