### ISSUE TITLE
Cost vs Market Value Graph

### ISSUE THREAD

**Issue by floatingheads** [beancount/fava#1174]
Is there any way to put cost and market value on the same graph? Would be a sexy way to see capital gains in graph format.

**Comment by redstreet** [comment]
What information or insight would you like to derive from such a graph?

A simple graph of the cost vs market value could be misleading to most users given it only shows unrealized capital gains. Usually, what people want is the performance of their portfolio, which includes the effect of realized capital gains, and dividends or other generated income. Calculating these tends to be non-trivial.

**Comment by redstreet** [comment]
This is probably subsumed by [this one](https://github.com/beancount/fava/issues/1071) and can be closed.
