### ISSUE TITLE
Show the current version of Fava in the help pages.

### ISSUE THREAD

**Issue by grostim** [beancount/fava#1181]
I think the title is self-explanatory.
A link to the changelog would be nice too. 
As well as the version number of beancount.

**Comment by yagebu** [comment]
I think this could be part of the index page of the included help pages. A PR would be welcome.

**Comment by aclindsa** [comment]
@yagebu @grostim I took a first pass at this in https://github.com/beancount/fava/pull/1250. After my change, the help index page looks like this with my local install of fava:

![2021-04-09-222613_1172x569_scrot](https://user-images.githubusercontent.com/362852/114255653-a2bc9c00-9982-11eb-9e2f-817cda7c8f87.png)

**Comment by grostim** [comment]
It looks simple and straightforward. I like it.
I will give it a try over this week end.

Le sam. 10 avr. 2021 à 04:28, Aaron Lindsay ***@***.***> a
écrit :
