### ISSUE TITLE
WebKit JavaScript Error "The superclass is not a constructor" on fava's editor page

### ISSUE THREAD

**Issue by johannesjh** [beancount/fava#1189]
I created a python + GTK application to be able to conveniently run fava as a desktop application, see attached screenshot. This works fine except for the editor page, where the following error is thrown "The superclass is not a constructor".

```
  /**
   * Read-only editors in the help pages.
   */
  class BeancountTextarea extends HTMLTextAreaElement {  // <-- The superclass is not a constructor
      constructor() {
          super();
          codemirror.fromTextArea(this, {
              mode: "beancount",
              readOnly: true,
          });
      }
  }
```

Any ideas how to fix or shim this error? (I tried loading custom-elements shims, which apparently should allow to extend HTMLElement Subclasses, but it did not help the issue).

thank you!

PS:  
Screenshot of the application... I find that fava's GUI works perfectly fine in GTK's embedded webkit browser, except for this error on the editor page.

![Screenshot from 2020-12-08 13-21-33](https://user-images.githubusercontent.com/581188/101483959-304a9980-3959-11eb-95db-22b59642a443.png)

**Comment by yagebu** [comment]
It's interesting that this breaks the Editor report and not others, since that code isn't used on the editor page but only on the help page. The error itself is due to webkit not yet properly supporting custom elements (https://caniuse.com/custom-elementsv1)

**Comment by johannesjh** [comment]
Thank you! - I'll try to debug this a little more. There has to be a different reason why the editor page is not working. (The superclass error appears on other pages as well, and does not prevent them from functioning in a normal way)

**Comment by johannesjh** [comment]
The [ungap/custom-elements]( https://github.com/ungap/custom-elements) polyfill solves the problem. I now have a working editor page, and my overall impression is that everything is working fine inside the webkit GTK-widget. 

I used a quick and dirty fix in order to test the polyfill, i.e., I added the following line to `_layout.html` just before `app.js` is loaded:

```
<script src="//unpkg.com/@ungap/custom-elements"></script>
```

Obviously, the script should be loaded in a different way. Before we get into this, my question is:

Would it be acceptable to you to add this polyfill (or a similar one) to fava?

**Comment by johannesjh** [comment]
Note: The smaller `es` variant of the same polyfill also works. This has 3.25KB if transmitted using gzip compression, 5KB without compression.

```
<script src="//unpkg.com/@ungap/custom-elements/es.js"></script>
```

**Comment by yagebu** [comment]
> Would it be acceptable to you to add this polyfill (or a similar one) to fava?

Reluctantly, but yes. However loading it from an external URL is not acceptable. If we include it, we include it in the build. Can you provide a PR?

**Comment by johannesjh** [comment]
Thank you, I gave it a shot, see pull request https://github.com/beancount/fava/pull/1192

**Comment by yagebu** [comment]
This is now polyfilled :) e72ea4235185fba028de8fa78f41ad3224933aa1

**Comment by johannesjh** [comment]
Thank you for adding the polyfill. The GTK desktop app is now functional, see https://github.com/beancount/fava/issues/1209 I'd love to hear your feedback, thank you!
