### ISSUE TITLE
When `pedantic` plugin is enabled, all transactions and accounts disappear

### ISSUE THREAD

**Issue by orfest** [beancount/fava#1193]
Hello,

I have 5 beancount files resulting in a total of 30k lines. fava runs on a raspberry pi 3.
Enabling `plugin "beancount.plugins.pedantic"` results in fava showing no accounts and no transactions.
How can I debug this issue?

Enabling `-d` option only shows the HTTP get requests and nothing about parsing errors or any other errors.
`bean-check` returns success for my beancount files with and without the plugin. Adding a bad transaction at the end of the file gets correctly noticed by `bean-check` with and without the plugin.

I worry that Raspberry pi takes a long while to process requests. Can it be that requests simply timeout and return nothing?

**Comment by yagebu** [comment]
Which versions of Fava and Beancount do you have installed? Does `bean-report` work correctly for that file?

> I worry that Raspberry pi takes a long while to process requests. Can it be that requests simply timeout and return nothing?

That seems unlikely if it works without the plugin.

**Comment by orfest** [comment]
`bean-report` works.

`beancount` debian package version: 2.2.0-3
`fava, version 1.9`

**Comment by yagebu** [comment]
That's quite an old version of Fava (and Beancount), can you also reproduce this with the latest releases?

**Comment by ngoonee** [comment]
My own testing on the Pi 3 is that fava is usable but a bit slow. It was horrendously slow initially until I realised my distro doesn't automatically install mpdecimal (without a fast cdecimal beancount just... dies)

Unfortunately my fava instance there isn't currently up, and I don't use the specific plugin described in any case. I'm using the latest release, will see if I'm able to get back to the pi 3 and test.

**Comment by yagebu** [comment]
> 1.9 seems to be the latest version.
Anyhow, built fava from head, and it works.

Glad to see that it works now :) If your distribution is stuck with such an old version, doing a user installation with `pip` might be the easiest way to get the current release.
