### ISSUE TITLE
Save chart type (area/line, sunburst/treemap) to localStorage

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1195]
Low priority request: the area chart from #1125 looks great. So much that I'd love for an option to make this the default. Would that be hard to do? Perhaps a good beginner task?

Also: one could think about whether to provide an option to prefer the Sunburst over the Treemap.

**Comment by yagebu** [comment]
This is not something that I'd really want to add an option for. I think we could just save the current choice to localStorage or so.

**Comment by redstreet** [comment]
Is it the option explosion you are concerned about? If so, I agree :).

If it helps to define this option well, I'd consider something like "prefer-area-over-line-chart" when both are available.

That said,I totally understand if you would still rather not expose this as an option.

How would the save to local storage work? Thanks!

**Comment by yagebu** [comment]
> Is it the option explosion you are concerned about? If so, I agree :).

Yep, that's my concern here.

> How would the save to local storage work? Thanks!

I was refering to the localStorage browser API (https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), which would allow us to save this in the browser without the user having to explicitly set an option.

**Comment by redstreet** [comment]
> I was refering to the localStorage browser API (https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), which would allow us to save this in the browser without the user having to explicitly set an option. 

Thanks, I wasn't aware of this API.l 🙂. Way better than harassing the user with an additional config option 👍.
