### ISSUE TITLE
Allow to disable default importer hooks

### ISSUE THREAD

**Issue by tarioch** [beancount/fava#1197]
It would be nice if it would be possible to disable the default importer hooks.

Unfortunately beancount uses the standard duplicate detector if you don't specify any hooks. This unfortunately marks entries as duplicates although they aren't.

I'm using the apply_hooks from smart importer, so I would not want any hooks from beancount to run.

**Comment by yagebu** [comment]
I think we could read the list of hooks that should be used from a variable, say, `HOOKS` in the import script and having the list containing just the duplicate detector as a default. A PR would be welcome :)

**Comment by yagebu** [comment]
This was implemented in #1208
