### ISSUE TITLE
Missing spacing for pad entries

### ISSUE THREAD

**Issue by nblock** [beancount/fava#1198]
When viewing the journal and enabling `pad` entries, the second `account-link` misses some spacing.

![screenshot](https://user-images.githubusercontent.com/131119/103445001-448b6900-4c6f-11eb-9697-4eecb1ecfed6.png)

* Fava 382d89eb437fd7d1d962f96d66e5686e74d73ab1
* tested with `tests/data/example.beancount`: http://localhost:5000/short-example/journal/?show=transaction&show=cleared&show=pending&show=balance&show=note&show=document&show=discovered&show=pad&show=query&show=custom&show=budget

**Comment by yagebu** [comment]
A PR with a fix would be welcome.

**Comment by wylfen** [comment]
Seemed like an easy fix, so I took a look at this. There's two main ways fava deals with padding right now, either with CSS through `margin`, or in the template itself using `&nbsp;`. Custom entries, for example, do not have this problem as the template inserts non-breaking spaces:
https://github.com/beancount/fava/blob/f4166a89229d7eab41999803de3c30e30470db57/src/fava/templates/_journal_table.html#L128-L134

The CSS for journal tables defines `margin-right` for any account link:
https://github.com/beancount/fava/blob/f4166a89229d7eab41999803de3c30e30470db57/frontend/css/journal-table.css#L175-L177

I can see three possible solutions here.
1) We leave the template as is and use something like the following:
    ```css
    .journal li.pad .description .account-link:last-child {
      margin-left: 0.5em;
    }
    ```
2) We leave the stylesheet as is and insert a non-breaking space:
    ```jinja
    {% elif type == 'pad' %}
        {{ account_link(entry.account) }} from&nbsp;{{ account_link(entry.source_account) }}
    ```
3) We remove `margin-right` for `.account-link` and insert two non-breaking spaces.
    ```jinja
    {% elif type == 'pad' %}
        {{ account_link(entry.account) }}&nbsp;from&nbsp;{{ account_link(entry.source_account) }}
    ```

As far as I can see, the margin for `.account-link` is not needed anywhere except in pad entries (where there's no non-breaking space). Indeed technically with custom entries there is *too much* padding right now. I couldn't really trace the history of the stylesheet well, so maybe I'm missing something. Let me know which solution is preferred and I'll send a PR along.

**Comment by yagebu** [comment]
Thanks @wylfen for investigating this. I just went ahead and applied your suggested fix (3), which also allowed me to remove the `account-link` class altogether, since it wasn't used anywhere else :)
