### ISSUE TITLE
Interface doubts and suggestions

### ISSUE THREAD

**Issue by AlphaJack** [beancount/fava#1203]
The only places where I can see cents are the editor section and the detailed view of a specific transaction.  Can I use an option to show decimals with a arbitrary number of digits (2 in my case) even in other sections?

If I add a transaction using the built-in feature, the date picker shows the date as "01/02/2021" (US format) instead of "01/02/2021" (my country format) or even better "2021-01-02" (ISO format). Can this be changed with an option or is it hardcoded?

Is it possible to add a scroll bar to sections like editor and journal?

Is already there or is it possible to implement a feature to autocollapse in the Editor certain sections delimited by the same or greater number of asterisks? For instance:

```
* 2020 (collapses until 2021)
** 2020-Q1 (collapses until 2020-Q2)
    [...]
** 2020-Q2 (collapses until 2020-Q3)
    [...]
** 2020-Q3 (collapses until 2020-Q4)
    [...]
** 2020-Q4 (collapses until 2021)
    [...]
* 2021 (doesn't collapse since it's the last "*" section)
** 2021-Q1 (collapses until 2021-Q2)
    [...]
** 2021-Q2 (doesn't collapse since it's the last "**" section)
    [...]
```

**Comment by yagebu** [comment]
For this kind of usage questions, posting in the Gitter chat will probably get you quicker answers.

> Can I use an option to show decimals with a arbitrary number of digits (2 in my case) even in other sections?

Beancount infers the precision of the currencies from your input and there's no option to set it explicitly yet (https://github.com/beancount/beancount/issues/171). So the easiest way to always get 2 digits shown is to write most of your amounts with 2 digits.

> If I add a transaction using the built-in feature, the date picker shows the date as "01/02/2021" (US format) instead of "01/02/2021" (my country format) or even better "2021-01-02" (ISO format). Can this be changed with an option or is it hardcoded?

 This dialog is provided by your browser, so you need to set the localisation there or at the operating system level.

> Is it possible to add a scroll bar to sections like editor and journal?

All pages are scrollable if their content overflows the window size.

> Is already there or is it possible to implement a feature to autocollapse in the Editor certain sections delimited by the same or greater number of asterisks? For instance:

This is already implemented.

**Comment by AlphaJack** [comment]
> So the easiest way to always get 2 digits shown is to write most of your amounts with 2 digits.

Thanks, I'll try it

> All pages are scrollable if their content overflows the window size.

Giving another look at the online demo I see that there is a scrollbar even on the editor, but in my local instances the scrollbar doesn't appear.

![fava-online](https://user-images.githubusercontent.com/19962243/106298221-8a762580-624b-11eb-916d-2c8da51aadcc.png)
![fava-offline](https://user-images.githubusercontent.com/19962243/106298222-8ba75280-624b-11eb-967b-ba823e1295a8.png)

My Fava version is 1.18

> This is already implemented.

How? I don't mean "click here to collapse", but rather a global option to have all the sections (apart from the last one) automatically collapsed, so I can easily open specific parts of the document

**Comment by yagebu** [comment]
> How? I don't mean "click here to collapse", but rather a global option to have all the sections (apart from the last one) automatically collapsed, so I can easily open specific parts of the document

I misunderstood your question then. With CodeMirror 5, the performance of folding is not good enough to allow this IMHO. With the next release which I'm currently migrating too, I might make having all parts collapsed the default.

**Comment by yagebu** [comment]
Regarding the missing scrollbar - have you tried some different browsers and reinstalling? If all that doesn't help, please open a new issue
