### ISSUE TITLE
Help with extracting some UI elements for fava_investor

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1211]
Hello,
I'm wanting just the "At cost/market value..." drop down menu for a certain page for the fava_investor plugin. I don't want the chart or the monthly/yearly menu to be displayed. Would this be possible?

I'm talking about:
![image](https://user-images.githubusercontent.com/691755/104088776-17fec080-521e-11eb-93a6-b1028c1f3362.png)

The template [code is here](https://github.com/redstreet/fava_investor/blob/master/fava_investor/templates/Investor.html).

Thank you!

**Comment by yagebu** [comment]
This is all implement as Svelte components. Those are used from the templates via `<svelte-component .../>` custom elements. So you'd need to add the component you want to have as one of the possible types in `frontend/src/svelte-custom-elements.ts`.

**Comment by redstreet** [comment]
Perfect, thanks for the help! Apologies I hadn't responded when I saw your response earlier.
