### ISSUE TITLE
Creating a file that was missing is not considered "changed"

### ISSUE THREAD

**Issue by ksesong** [beancount/fava#1219]
Supposing we have a very simple ledger file that has an include to another file.
```
include "A.beancount"
```
Since this file is missing, there is expectedly an error.
```
File glob "A.beancount" does not match any files
```

We should expect a reload to be suggested when we create this missing file `A.beancount`, but there is none, and we have to manually re-run `fava`.

Similarly, `fava` crashes when we delete an existing include file, with the following error type`FileNotFoundError: [Errno 2] No such file or directory:`

**Comment by yagebu** [comment]
The first issue I'd consider out of scope. We get a list of included files from Beancount, not the globs. So to detect any missing files we'd have to parse the file ourselves for includes and then run a file watcher for a glob.

But we shouldn't error when an included file disappears and that I've just fixed.
