### ISSUE TITLE
Import page shows files that can't be imported

### ISSUE THREAD

**Issue by mattr555** [beancount/fava#1224]
I'm someone who tends to hoard a lot of files in my `~/Downloads` folder, which is where I download my monthly statements, and is the import directory for `bean-file`/`fava`. I'd prefer to only see files that have an associated importer on fava's import page (though I understand the value in having other files show up in the list if you're using a different directory to collect documents before they're filed).

I'm happy to contribute a PR that adds an option to enable this. Would this be a sensible default to enable, or should we show all files by default? Don't want to break anyone's workflow. Thanks!

edit: as an alternative, we could explore adding a toggle to do this filtering on the frontend. The only quibble I would have with that is that we get a performance win by not sending down files that the user doesn't care about.

**Comment by yagebu** [comment]
This is not really something that I'd want to add an option for but doing this filtering in the frontend sounds like a worthwhile solution. Maybe we could display the list in two parts to allow those that don't have an importer to be more easily ignored and just toggled in the frontend.

> The only quibble I would have with that is that we get a performance win by not sending down files that the user doesn't care about.

The size of the data loaded on that page is really quite negligible.

**Comment by mattr555** [comment]
> Maybe we could display the list in two parts to allow those that don't have an importer to be more easily ignored and just toggled in the frontend.

I like this idea! Hope to have a PR out implementing it this weekend.

> The size of the data loaded on that page is really quite negligible.

Fair enough. I was noticing loading times of a couple seconds before I purged some of my old downloads, but nothing extreme.

**Comment by yagebu** [comment]
> I like this idea! Hope to have a PR out implementing it this weekend.

Cool :)

> I was noticing loading times of a couple seconds before I purged some of my old downloads, but nothing extreme.

All files in the import directory are checked by the `identify` part of Beancount's ingest mechanism, depending on your importers that might load and read all files (e.g., to check for the existence of some identifier in a CSV file). That might take some time if you have a lot of files in that directory of course and can't really be avoided, transmitting the result will only be a fraction of those seconds
