### ISSUE TITLE
Layout problems with transaction popup on Safari, Chrome

### ISSUE THREAD

**Issue by mat5n** [beancount/fava#1225]
The modal window that appears when you click a date in the Journal view has some layout issues on both Safari and Chrome (but not on Firefox).  See pictures below.

Version info:

- macOS 11.1
- fava 1.18
- Safari 14.0.2
- Chrome 88.0.4324.96
- Firefox 84.0.2

Safari:

<img width="828" alt="Safari" src="https://user-images.githubusercontent.com/43117384/105842862-880f9380-5fdf-11eb-8910-8d3368c86b5f.png">

Chrome:

<img width="824" alt="Chrome" src="https://user-images.githubusercontent.com/43117384/105843002-b9885f00-5fdf-11eb-9736-61dc46b7dcf3.png">

**Comment by yagebu** [comment]
These issues should be fixed by #1220
