### ISSUE TITLE
Editor scrollbar doesn't appear

### ISSUE THREAD

**Issue by AlphaJack** [beancount/fava#1227]
I have noticed that my local Fava instance doesn't make the CodeMirror scrollbar appear. I see it in the "inspect element" browser panel (same properties and values), but it only appears in the demo instance at pythonanywhere.

I have reproduced the issue with both Firefox and Chrome accross multiple versions of Fava

Browser scrollbars in other pages appear normally

Demo instance
![fava-online2](https://user-images.githubusercontent.com/19962243/106359433-b1476100-630a-11eb-942e-bc2b19389ca8.png)
Local instance
![fava-offline2](https://user-images.githubusercontent.com/19962243/106359435-b2788e00-630a-11eb-8fb9-89e987ec8b7b.png)

Demo instance
![fava-online](https://user-images.githubusercontent.com/19962243/106359436-b3112480-630a-11eb-96fb-c86d0da0b97e.png)
Local instance
![fava-offline](https://user-images.githubusercontent.com/19962243/106359438-b4425180-630a-11eb-8d8f-9ffe50c39586.png)

**Comment by yagebu** [comment]
The whole editor got completely reworked (#1223) and I believe this is fixed now. Could you check this?

**Comment by AlphaJack** [comment]
Thank you, I can see it now.
I have also noticed that when opening the editor in the new version the cursor is placed at the beginning of the file, no more at the end. Is that desired?

**Comment by yagebu** [comment]
> I have also noticed that when opening the editor in the new version the cursor is placed at the beginning of the file, no more at the end. Is that desired?

Yes, it now jumps to an `insert-entry` option, so if you want to have it jump to the end of the file, just put such an option there.

**Comment by AlphaJack** [comment]
From the help page I read 

> **insert-entry**
> Default: Not set.
> 
>This option can be used to specify where entries are inserted. The argument to this option should be a regular expression matching account names. This option can be given multiple times. When adding an entry, the account of the entry (for a transaction, the account of the last posting is used) is matched against all insert-entry options and the entry will be inserted before the datewise latest of the matching options. If the entry is a Transaction and no insert-entry option matches the account of the last posting the account of the second to last posting and so on will be tried. **If no insert-entry option matches or none is given, the entry will be inserted at the end of the main file.**

If I did not set that option, can the cursor be placed at the end of the file (where entries would be inserted in this case)?  
This would allow to directly append an entry when opening the editor, without the need to scroll down a bit

**Comment by yagebu** [comment]
> If I did not set that option, can the cursor be placed at the end of the file (where entries would be inserted in this case)?

I'd rather not special-case that behaviour. You can simply add an option at the end of the file.

**Comment by AlphaJack** [comment]
Ok, but I will need to periodically move down that option.
I can live with that, these are just my 2 cents.

Thanks again for the bugfix (and the whole webapp!)

**Comment by yagebu** [comment]
> Ok, but I will need to periodically move down that option.

Fair enough, having the option at the end doesn't work well together with other tools that just append at the end. I'll restore the previous behaviour, people who want the cursor at the beginning of the file can more easily use the option.

Just storing some of the editor state like the cursor position to `localStorage` might be even more convenient, I might implement that at some point.
