### ISSUE TITLE
Improve AddEntry modal on mobile

### ISSUE THREAD

**Issue by taimrli** [beancount/fava#1229]
First of all thanks for this great frontend!

Something that bothers me a bit about using it is that the AddEntry form is really cumbersome to use on mobile.

Would there be a way to be able to have it also non-modal... like a 'normal' sub route? Perhaps an additional option?

Unfortunately, I have too little expertise in Svelte, let alone Python, to make myself useful in this...

**Comment by yagebu** [comment]
On mobile, the modal should already fill most of the screen. How would making it its own page make it more easily usable?

**Comment by taimrli** [comment]
The problem is, the modal fills _more_ than the screen... which leads to scrolling back an forth:
![Screenshot_20210206-110426_Brave](https://user-images.githubusercontent.com/18010667/107137997-d55e0000-6911-11eb-8cb5-cfc4e9b10e73.jpg)

**Comment by yagebu** [comment]
I think this should be fixed by improving the CSS for the modal overlay on mobile, not by creating a separate page. Mobile browsers have some odd behaviours and mobile screen sizes are also not very consistent so that's not a trivial task. A PR improving the CSS for the modal would be welcome :)

**Comment by yagebu** [comment]
Should be fixed by #1431 :)
