### ISSUE TITLE
PyPi install contains import errors

### ISSUE THREAD

**Issue by JonBoyleCoding** [beancount/fava#1231]
When trying to launch fava from the pip install, I'm getting this error:

> ImportError: cannot import name 'DispatcherMiddleware' from 'werkzeug.wsgi'

It certainly doesn't seem to exist when I check the python file. Any thoughts?

**Comment by JonBoyleCoding** [comment]
I notice this has been fixed in master now, so it's just an issue with the pypi version. I shall update my version with master for the time being.

**Comment by yagebu** [comment]
> It certainly doesn't seem to exist when I check the python file. Any thoughts?
>I notice this has been fixed in master now, so it's just an issue with the pypi version.

Since the offending line of code has been fixed a long time ago, this can't really happen with an up-to-date install from PyPI. Maybe you have some outdated install of Fava that got loaded instead?

**Comment by JonBoyleCoding** [comment]
I honestly don't know how it happened. I installed it via pip yesterday and it happened to be there... Either way, as it's been fixed a while back, I suppose there is no longer a need for the issue!

**Comment by addisonklinke** [comment]
I am having the same issue (among others) with the pip install. What is the recommended alternative? The readme only documents the PyPI approach
