### ISSUE TITLE
problem with import

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#1236]
i have one importer that is use twice for two file.
my personal.import_config is like this:

```
CONFIG = [
    sg.ImporterSG(
        currency="EUR",
        account_root="Assets:Parents:SG-papa",
        account_id="000604513850",
    ),
    sg.ImporterSG(
        currency="EUR",
        account_root="Assets:Parents:SG-maman",
        account_id="00070424111",
    )
]
```
this works well with bean extract. i have my transactions with each accounts.
but with the import feature of fava, i get all the transactions attach with one account (the last).

**Comment by mattr555** [comment]
In fava, importers are cached using the result of calling `.name()` on each importer. You can override the `name` method to return a unique string based on the account (for example `"SG<{}>".format(self.account_id)`).

See [here](https://github.com/beancount/fava/blob/309fdbec7cf6dc75046190160d1c154ea8c91067/src/fava/core/ingest.py#L132) for the code that does that caching.
