### ISSUE TITLE
Download as CSV (query page) do not take time into consideration

### ISSUE THREAD

**Issue by Tarliton** [beancount/fava#1241]
Hello,

If we make a query in query page, for example:
```sql
SELECT account,
    units(sum(position)) as units
  GROUP BY account, account_sortkey(account), currency
  ORDER BY account_sortkey(account), currency
```

The results we get will be filtered by our bar filters:
![Screenshot from 2021-03-31 00-24-32](https://user-images.githubusercontent.com/7471617/113086176-8b79f380-91b7-11eb-8519-db2decd2e157.png)

But, if we choose to download this csv (by clicking in csv):
![Screenshot from 2021-03-31 00-26-24](https://user-images.githubusercontent.com/7471617/113086317-cb40db00-91b7-11eb-94c1-156111b060cc.png)

We will get a file with all our data, not filtered by these attributes (time in this case).

Is this intended?

Thank you

**Comment by clsacramento** [comment]
+1

I have a query that I use every month. It would be super handy if I could leave the query without date condition (i.e WHERE date > 2021-03-01), and every month use the same query and export the CSV using the time filter on the top.
It would allow to not need to change the query everytime I need to export the CSV.

Thanks,
