### ISSUE TITLE
https scheme not respected in `router.navigate`

### ISSUE THREAD

**Issue by xinluh** [beancount/fava#1243]
This is a problem if fava is hosted with SSL. 

There are a few places (account selector, for example) where `router.navigate(urlFor(...))` is used navigate to a different page, but somewhere in the navigation the url scheme `https://` is not respected, and the navigation fails in modern browser. In Chrome, here is the error message in console:

```
Mixed Content: The page at 'https://<somehost>/beancount/trial_balance/' was loaded over HTTPS, but requested an insecure resource 'http://<somehost>/beancount/account/Income:Income?partial=true'. This request has been blocked; the content must be served over HTTPS.
```

Other sidebar links works. I tried to trace where the url scheme got overwritten in the `router.navigate(urlFor(...))`  call but couldn't locate the problem...

**Comment by yagebu** [comment]
As you have found out in #1245, this is an issue with your deployment setup.
