### ISSUE TITLE
Converted to currency

### ISSUE THREAD

**Issue by ibigbug** [beancount/fava#1247]
### Problem:

For example, I have 3 operation currencies:

- USD
- AUD
- HKD 

and in the priceMap I have something like this:

```
2021-04-07 price USD                                1.3046 AUD
2021-04-07 price HKD                               0.16779 AUD
```

If I choose to convert to AUD, then all the USD and HKD currencies will be converted to the AUD, guessing it's because it has the direct price map entry in the 'priceMap'

But if I wanted to convert to USD, it will end up showing two currencies in the table as USD and HKD, guessing again, because it doesn't know how to convert HKD <-> USD.

That could be a problem because if I chose to convert to a single currency, I'd like to see all the amount in the particular currency, while it has all the priceMap provided, directly or indirectly(in which case can be inferred).

### Proposal

After digging a bit in to the fava and beancount code base, I found that the template filter is actually calling the [`convert_position`](https://github.com/beancount/beancount/blob/d269deba46fc5187d9872f1a4743cc3b648b73c2/beancount/core/convert.py#L158) from beancount, which doesn't give the options to pass in a `via` list which can be used as _interim_ currency for the conversion in [`convert_amount`](https://github.com/beancount/beancount/blob/d269deba46fc5187d9872f1a4743cc3b648b73c2/beancount/core/convert.py#L184)

As much as I wanted to create the patch myself to leverage on the `convert_amount` with a list of currencies passed in as `via`, without a good understanding of this code base, it's a bit hard for me to do. So trying to get some help/thoughts here if that's possible to solve the "problem" like this?

**Comment by tarioch** [comment]
I have the same use case but I solved it differently.
I created a plugin which creates the cross rates on the fly, so for beancount (and therefore also fava), it's as all the prices would exist.
You can find it here https://github.com/tarioch/beancounttools it's called generate_base_ccy_prices

**Comment by yagebu** [comment]
I consider this to be out of scope for Fava and a good fit for a plugin :)
