### ISSUE TITLE
Preview of `png` documents

### ISSUE THREAD

**Issue by orfest** [beancount/fava#1253]
Fava says that:

Preview for file `/home/myuser/beancount/documents/Expenses/Gifts/Presents/2021-04-15.Amazon.Gift.png` with file type `png` is not implemented

The workaround for this issue is really simple. Take all my `png`s and print them to `pdf`s.
However, I'd like to be able to render `png`s in the fava interface.

I'm happy to contribute. Please let me know your thoughts about possible implementations of this feature and I'll get it done :)

**Comment by yagebu** [comment]
A PR for this would be welcome :)

This could be added in [DocumentPreview.svelte](https://github.com/beancount/fava/blob/master/frontend/src/documents/DocumentPreview.svelte) - adding a `<img />` should work for pngs, so this shouldn't be too hard to do. I guess it would have to be checked whether the image is sized correctly.

**Comment by orfest** [comment]
Cool, will give it a try.

**Comment by orfest** [comment]
That wasn't hard: https://github.com/beancount/fava/pull/1260

**Comment by yagebu** [comment]
This was implemented in #1260 by @orfest and merged just now :)
