### ISSUE TITLE
Confusing behavior with "insert-entry"

### ISSUE THREAD

**Issue by hitit-web** [beancount/fava#1262]
I have been enjoying the switch to beancount with fava for my personal finances. I especially love the editing capabilities and want to thank you for the hard work so far.

One small sticking point regarding the "input-entry" option has me confused. It was very easy to get the entry to go to the correct file (I have each asset and liability in a separate file and my files will be separated by year). However, the date of the "custom" entry is not as I would have expected.

My goal is to have the transaction placed at the end of the file everytime. Quoting the help text for insert-entry:
> [...] the entry will be inserted before the datewise latest of the matching options.

Seeing that, I added this to the end of one of the asset accounts:
`2021-12-31 custom "fava-option" "insert-entry" "Assets:Bank"`
That is the only "insert-entry" line in the file.

The transaction wound up at the end of my main file. The source in `file.py` shows why:
```
...
            # Only consider InsertOptions before the entry date.
            if insert_option.date >= entry.date:
                continue
...
```
Obviously there is probably a good reason for that but it does mean that I have to back-date the "custom" entry to before today. This goes against my attempts to keep all the entries in date order.

Is there a reason that that date check is necessary? Would it be safe to remove so that future dates will again be considered in the for-loop?

If it must remain, could you please add a note to the help description that explicitly mentions the limitation of "datewise latest before today".

Thanks in advance!

**Comment by aronsky** [comment]
The idea behind this test is that you can use multiple `insert-entry` entries for the same account (e.g., if you separate your beancount files by year, then one for each year). And in that case, when you add a new entry, it will be inserted into the correct file based on the entry date. If you drop the check you mention, the entry will be inserted into the file with the latest `insert-entry` found. That prevents the aforementioned feature of multiple `insert-entry` entries.

I suppose this feature could be reworked to reverse the traversal of `insert-entry` entries, and to insert the new entry before the earliest `insert-entry` that's still after the entry date. However, that wouldn't be backward-compatible, so I doubt it'll be implemented like that. Maybe you can add this kind of implementation in addition to the original one, and use an option to switch the behavior.

**Comment by yagebu** [comment]
I've update the help text to make it more explicit that the datewise latest before the entry date is considered.

> Obviously there is probably a good reason for that but it does mean that I have to back-date the "custom" entry to before today. This goes against my attempts to keep all the entries in date order.

I believe the previous comment described the motivation well. If you want to still keep your entries in date order, you could write a short Beancount plugin that updates the dates of these insert-entry options.
