### ISSUE TITLE
Flask, Jinja major releases break Fava

### ISSUE THREAD

**Issue by patricklucas** [beancount/fava#1266]
~12 hours ago, version [2.0.0 of Flask](https://github.com/pallets/flask/releases/tag/2.0.0) and [3.0.0 of Jinja](https://github.com/pallets/jinja/releases/tag/3.0.0) were released, with which Fava does not appear to be compatible:

```
$ virtualenv --python python3 venv
$ ./venv/bin/pip install fava
$ ./venv/bin/fava ledger.beancount
Traceback (most recent call last):
  File "/home/foo/./venv/bin/fava", line 5, in <module>
    from fava.cli import main
  File "/home/foo/venv/lib/python3.9/site-packages/fava/cli.py", line 11, in <module>
    from fava.application import app
  File "/home/foo/venv/lib/python3.9/site-packages/fava/application.py", line 67, in <module>
    app.jinja_options["extensions"].append("jinja2.ext.do")
KeyError: 'extensions'
$ ./venv/bin/pip freeze | grep -i fava
fava==1.18
$ ./venv/bin/pip freeze | grep -i flask
Flask==2.0.0
$ ./venv/bin/pip freeze | grep -i jinja
Jinja2==3.0.0
```

I suggest just pinning both versions as strictly-less-than the new major releases until an upgrade can be coordinated. I'll open a PR shortly.

**Comment by yagebu** [comment]
Thanks for the report - the incompatibility seems to be just in that one place. I'll just fix that instead :)

**Comment by redstreet** [comment]
Thanks everyone for this!
pip3 uninstall click itsdangerous Werkzeug Flask Flask-Babel jinja2 click Jinja2                                               pip3 install -Iv Jinja2==2.11.3 Flask-Babel==1.0.0 Flask==1.1.4 Jinja2==2.11.3
