### ISSUE TITLE
Format numbers in charts tooltip using Beancount's dcontext (DisplayContext)

### ISSUE THREAD

**Issue by upsuper** [beancount/fava#1271]
In the tables, numbers correctly respect dcontext, but not in tooltips of charts. They should probably be consistent.

**Comment by yagebu** [comment]
Yes, this would be indeed nice. This would require reading and handling the display context in the frontend code. A PR implementing this would be very welcome :)

**Comment by yagebu** [comment]
Implemented in 051305b7e74bb3d31a8799b0586e37e68f58f0d3
