### ISSUE TITLE
Bulgarian translation

### ISSUE THREAD

**Issue by mlvnt** [beancount/fava#1273]
Would like to add a Bulgarian translation but it seems it's only possible to select from the already existing languages in poeditor. Can someone who has access to the poeditor project add Bulgarian to the list of defined languages if this is the way it works. On the same note is it possible to translate the build-in help pages in addition to the UI? Haven't looked too much into it and if it's not supported will open a separate feature request and work on a PR.

**Comment by yagebu** [comment]
I've added Bulgarian to the project on poeditor. Now you should be able to request to translate that language.

The help pages are currently not translateable. I'm not sure that it's very feasible to add translations for them. They contain a lot more text than all the other translateable strings put together and change more frequently. So they would add quite a bit of churn for translators.

**Comment by mlvnt** [comment]
Thanks:) Joined the project and now the status is pending. Maybe one more approval is needed.

Makes sense. Probably will do a patch for the local build.

**Comment by mlvnt** [comment]
The translation is done. Found few missing entries:

1. "**Converted to**" -> https://github.com/beancount/fava/blob/a5c85397c4bba43e7818c06caa1bc1ceaad28e10/frontend/src/stores/chart.ts#L43
2. "**Query**" ->
https://github.com/beancount/fava/blob/a5c85397c4bba43e7818c06caa1bc1ceaad28e10/frontend/src/query/QueryLinks.svelte (most probably) - this is the query link found under Holdings (`Query (Download as CSV, XLS, XLSX, or ODS )`) and Statistics `(Postings per Account (Query)`), may also be used somewhere else
3. "**Chart is empty.**" -> frontend/src/charts/HierarchyContainer.svelte (from build)

```html
  <svg {width}>
    <text x={width / 2} y={80} text-anchor="middle">Chart is empty.</text>
  </svg>
```
