### ISSUE TITLE
Fix inconsistent/missing localization

### ISSUE THREAD

**Issue by mlvnt** [beancount/fava#1278]
Since working on #1273 found a lot of missing entries and overall inconsistent i18n implementation:

## Charts

1. [ ] `Converted to` -> https://github.com/beancount/fava/blob/a5c85397c4bba43e7818c06caa1bc1ceaad28e10/frontend/src/stores/chart.ts#L43
2. [ ] `Chart is empty.` -> frontend/src/charts/HierarchyContainer.svelte (from build)

    ```html
      <svg {width}>
        <text x={width / 2} y={80} text-anchor="middle">Chart is empty.</text>
      </svg>
    ```

## Balance Sheet

1. [ ] Equity table autogenerated accounts/subaccounts:

    `Equity`, `Conversions`, `Earnings`, `Current` ->
    
    ```txt
    Equity:Conversions:Current
    Equity:Earnings:Current
    ```
   The behavior of  **Unrealized** Equity subaccount can be replicated so that the user can set the name of the accounts through options, and where not feasible translated as i18n string

2. [ ] `Net Worth` -> https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/balance_sheet.html#L3

3. [ ] Day and Month localization of `y` axis

## Journal

Mix of flags and their corresponding tooltips:

1. [ ] All entry types - `Open`, `Close`, `Transaction`, `Balance`, `Note`, `Document`, `Pad`, `Query`, `Custom`  and their tooltips (`Toggle <entry> entries`) ->

2. [ ] https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/_journal_table.html#L4
    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/_journal_table.html#L84

3. [ ] All entry short type flags - `Bal`, `Close`, `Doc`, `Note`, `Open` ->

    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/_journal_table.html#L38

4. [ ] `Toggle metadata` tooltip ->

    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/_journal_table.html#L91

5. [ ] `Toggle postings` tooltip ->

    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/_journal_table.html#L92

6. [ ] For consistency sake translate/make configurable the `sub_types` symbols -> `B`, `D`, `L`

    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/_journal_table.html#L7

    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/_journal_table.html#L10

    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/_journal_table.html#L11

## Query

1. [ ] The query link found under Holdings (`Query (Download as CSV, XLS, XLSX, or ODS )`) and Statistics `(Postings per Account (Query)`), may also be used somewhere else - `Query` ->
    https://github.com/beancount/fava/blob/a5c85397c4bba43e7818c06caa1bc1ceaad28e10/frontend/src/query/QueryLinks.svelte#L6

(most probably) 

## Holdings

1. [ ] Table query BQL column keys - `account`, `units`, `cost`, `price`, `book_value`, `market_value`, `acquisition_date` ->

    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/holdings.html#L3

## Events

1. [ ] The `Event: ` selector for the chart ->

    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/events.html#L3

## Statistics

1. [ ] Entries per Type table - `ledger.entries.type` - `Balance`, `Event`, `Open`, `Price`, `Transaction` ->

    https://github.com/beancount/fava/blob/f1dfd44e2bb5ba52832f2a09e147aab47b435433/src/fava/templates/statistics.html#L80

**Comment by yagebu** [comment]
PRs addressing these issues would be welcome, except for account names and the Beancount directive names, which shouldn't be translated IMHO.

**Comment by yagebu** [comment]
Most of these should be fixed by now
