### ISSUE TITLE
Filter by amount?

### ISSUE THREAD

**Issue by andreasgerstmayr** [beancount/fava#1297]
Is there a way to filter transactions by amount? For example, I'd like to view all transactions of the expenses account over 1000 EUR (i.e. where the "changes" column is over 1000 EUR).

I think it's tricky for the other views (e.g. for the journal view, which posting amount should be selected for filtering?), but for the account detail view it would be straight forward to filter (filter by the "changes" column).

I know I can use custom BQL for it, but then I don't have the nice editing functionality and the other UI elements/options of the accounts page.

**Comment by nzbart** [comment]
This would be great as a Fava feature.

For those of you (like I did) who have trouble figuring out how to write BQL to search by amount, the magic column you need is `Number`:

```
select * where Number = 25000
```

**Comment by xinluh** [comment]
Implemented in #1307

**Comment by LucaBernstein** [comment]
Btw, for anyone curious how to perform at least exact matches, just found out that this works in fava:

`any(units: "2.00 USD")`

You can leave out the currency, but then the regex could include unwanted results (e.g. extreme example: `any(units: "2")` would match transactions with units of `2.00 EUR` as well as `0.02 EUR` (i.e. filtering for `.*2.*`))
