### ISSUE TITLE
The value in balance sheet is different from `bean-report balsheet`

### ISSUE THREAD

**Issue by flyisland** [beancount/fava#1299]
fava, version 1.19
Google Chrome: Version 91.0.4472.114 (Official Build) (x86_64)

In terms of the below beancount file, the value of Assets:Positions from `bean-report balsheet` is 4000.00 USD, 
![Screen Shot 2021-06-22 at 09 20 10](https://user-images.githubusercontent.com/547085/122848537-4db2e400-d33c-11eb-9ccd-6ac3d396ae88.png)

but the value from fava is 2500 USD!
![Screen Shot 2021-06-22 at 09 20 40](https://user-images.githubusercontent.com/547085/122848581-68855880-d33c-11eb-8a8e-4e195bd0c7ec.png)

```
option "operating_currency" "USD"

2020-06-01 commodity IBM
2020-06-01 open Equity:Opening-Balances
2020-06-01 open Assets:Cash
2020-06-01 open Assets:Positions
2020-06-01 open Income:Investments:Dividends


2020-06-01 * "Open Balances for Assets:Cash"
    Assets:Cash                              5000.00 USD
    Equity:Opening-Balances

2020-06-01 * "Buy IBM"
    Assets:Positions                           10.00 IBM {100 USD} @@ 1000 USD
    Assets:Cash


2020-06-10 * "Buy more IBM"
    Assets:Positions                           10.00 IBM {150 USD}
    Assets:Cash


2021-06-20 price IBM 200 USD
```

**Comment by ThomasdenH** [comment]
I think the value you expected will show up if you select 'Market Value' instead of 'At Cost'.

**Comment by flyisland** [comment]
> I think the value you expected will show up if you select 'Market Value' instead of 'At Cost'.

@ThomasdenH , thanks for the reply, could you please tell me how to select "Market Value" on the Balance Sheet page?

**Comment by yagebu** [comment]
On the top right of the charts there's a couple of select dropdowns. To the left of the interval (monthly by default), there's one to change the conversion ("At Cost" by default).

**Comment by flyisland** [comment]
@yagebu thanks!
