### ISSUE TITLE
Failed to parse fava-option entry: unknown option `conversion`

### ISSUE THREAD

**Issue by AlphaJack** [beancount/fava#1306]
This [option](https://fava.pythonanywhere.com/example-beancount-file/help/options/) has been added as PR in February 2020 (see #1047), however now it is not present in the list of options. Why?

**Comment by yagebu** [comment]
This option was removed as this behaviour can now be achieved with the default-page option.

**Comment by AlphaJack** [comment]
Thank you, I see the parameter is kept when navigating other sections.
