### ISSUE TITLE
Confusing german translation for "At Cost"

### ISSUE THREAD

**Issue by nils-werner** [beancount/fava#1308]
> [At Cost](https://github.com/beancount/fava/blob/main/src/fava/translations/de/LC_MESSAGES/messages.po#L497)

is incorrectly and confusingly translated to

> Kosten anzeigen

A better translation would be

> Einkaufspreis anzeigen

Which also works better with 

> Marktwert anzeigen

I would have suggested an edit on POEditor, but my request for joining the project there is still pending.

**Comment by yagebu** [comment]
> but my request for joining the project there is still pending.

You should be able to change it on POEditor now :)

**Comment by nils-werner** [comment]
No, it still says "pending"

**Comment by yagebu** [comment]
Ah, that's some confusing UI. On the overview page you're already listed as a contributor without any indication that it's still pending. But on the list of contributors I can see that it's pending. It should work *now* :)

**Comment by nils-werner** [comment]
Yes, it's definitely confusing! I've now changed the strings in POEditor, but I didn't see a "submit" button... Did the changes end up in the database?

**Comment by yagebu** [comment]
>  I've now changed the strings in POEditor, but I didn't see a "submit" button... Did the changes end up in the database?

Yep, looks like it. They don't automatically end up in Fava though but only get fetched from manually from time to time (which I just did).
