### ISSUE TITLE
Inverse search in filter

### ISSUE THREAD

**Issue by cataclysmic** [beancount/fava#1310]
Hey everyone.

I want to inverse filter in the web interface.
Specifically I want to hide planned expenses.

Planned expenses can either be booked to specific subaccounts or could be tagged or using meta-data.

However, I want to filter "show everything but not 'planned' expenses". 
I know that the filter supports regex but several attempts have failed.

Thanks for you help in advance.

**Comment by yagebu** [comment]
You can prefix a filter with a minus `-` to invert it.
