### ISSUE TITLE
Trial Balance Aggregation Settings don't work

### ISSUE THREAD

**Issue by kaangoksal** [beancount/fava#1325]
I'm experimenting on this deployment:

https://fava.pythonanywhere.com/example-with-budgets/trial_balance/?conversion=USD

As you can see here, this is aggregated monthly right now
![image](https://user-images.githubusercontent.com/8029035/132109472-7fded379-1a11-4537-aef0-170902d9ab68.png)

Changing to yearly does not impact any of the values:
![image](https://user-images.githubusercontent.com/8029035/132109486-def9e0c3-647c-4393-b8b3-2d7702ad8707.png)

The rent is still $76800, 

I want to be able to see my monthly expenses in a treemap, this ui gives the complete picture + non-functional filtering options

**Comment by yagebu** [comment]
This report shows the latest balance of your accounts, so the interval option has no impact on this.

**Comment by kaangoksal** [comment]
Thanks!
