### ISSUE TITLE
Sort order in Journal view is not in URL and therefore not preserved through browser navigation

### ISSUE THREAD

**Issue by nzbart** [beancount/fava#1338]
When in the journal view, it's possible to sort by columns such as "Naration/Payee". However, when changing the view - such as by clicking on a specific Payee to "drill in" - this sort order is lost when coming back to the previous page using the browser back button or by clicking the `x` on the filter edit field.

I think that this would not be a problem if the sort order was stored in the URL as with the filter criteria.

**Comment by yagebu** [comment]
A PR for this would be welcome :)

**Comment by nzbart** [comment]
@yagebu I'll see if I can find time to contribute. I'm no Python expert, and it's a big job to get up to speed with an unfamiliar project's toolset and way of doing things (coding standards, tests, etc.) - even if the change itself isn't huge.
