### ISSUE TITLE
Feature: Filter/Query Presets

### ISSUE THREAD

**Issue by feluxe** [beancount/fava#1339]
I love fava and I use it a lot. I have one issue with the UX though. I need to copy/paste the same filter rules from a text document into the filter nav (top right corner) over and over. These filters allow me to view my finances each from a certain perspective and I need the same set of filters again and again.

I think it would be awesome if there was a menu which allowed me to save certain sets of filters (or even BQL queries). Then I could select the stored "Filter/Query Presets" to view my "Income Statements" from different perspectives and I wouldn't have to copy/paste any rules.

Is there any love for this?

**Comment by yagebu** [comment]
Fava already has support for adding custom links to the sidebar. This is documented in the "Custom links in the sidebar" section on the features help page.

**Comment by feluxe** [comment]
@yagebu That helps a lot, thanks! I didn't know this feature was there. :tada: 
Is this working with BQL queries as well? I couldn't get it to work with `/income_statement/?query_string=xxx`.
