### ISSUE TITLE
Balance Sheet chart used to have a slope between data points

### ISSUE THREAD

**Issue by cookie223** [beancount/fava#1341]
Now the chart seems weird that the lines between data points are like stairs.

![image](https://user-images.githubusercontent.com/5301377/137661637-2c351e90-df7a-43a9-9852-d63621e8a1b4.png)

I think the change was introduced between 1.18 and 1.20.1. I can't seem to find any mention of it in release note or issues.
Apologies if it was a feature and there is a configuration. Is there a way to change it back?

**Comment by ThomasdenH** [comment]
It was changed in #1265!

**Comment by yagebu** [comment]
I also visually preferred the old style visually initially but the new one is just much more correct (and I've now gotten used to it ;)). This not really something that I'd want to add an option for.
