### ISSUE TITLE
Security vulnerabilty

### ISSUE THREAD

**Issue by haby0** [beancount/fava#1344]
What would be the right contact to report a security vulnerabilty? thanks!

**Comment by yagebu** [comment]
An email to me would be a good way to report it, thanks :)

**Comment by haby0** [comment]
> An email to me would be a good way to report it, thanks :)

Please give me your email.

**Comment by yagebu** [comment]
See https://pypi.org/project/fava/ (I'm listed there as maintainer)

**Comment by haby0** [comment]
> See https://pypi.org/project/fava/ (I'm listed there as maintainer)

The details of the vulnerability have been sent to your email.
