### ISSUE TITLE
Trial Balance values in Sunburst chart don't match the values in the table

### ISSUE THREAD

**Issue by gerdemb** [beancount/fava#1345]
In some cases the Trial Balance values in the Sunburst chart don't match the values in the table. This appears to happen when filtering by a time period and also applying a currency conversion. 

http://localhost:5000/beancount/trial_balance/?time=2020&conversion=USD

I have accounts in various currencies and when I open the URL above, which converts all the amounts to USD, the amounts in the table at the bottom and Sunburst chart at the top are not exactly the same. The amounts are close, but different by a few percentage points which makes me suspect a difference in the way the currency exchange rates are applied.

Removing either the `conversion=USD` or `time=2020` parameters resolves the problem.

**Comment by yagebu** [comment]
Can you produce an example file that this can be reproduced with? Do you maybe have some subaccounts that don't match the sign of the root account? In these hierarchical charts it's not really possible to correctly display account hierarchies with a mix of positive and negative accounts, so it might be that some values get dropped in the summation...

**Comment by gerdemb** [comment]
Here's an example:

```
option "operating_currency" "USD"
option "operating_currency" "EUR"
plugin "beancount.plugins.auto_accounts"

2021-05-11 * ""
  Assets:S                1000 USD
  Equity:Opening-Balances

2021-05-11 * ""
  Assets:S             -122.37 USD
  Assets:W              100.00 EUR @@ USD

2021-06-18 * ""
  Assets:S             -480.92 USD @@ EUR
  Assets:W              400.00 EUR

2019-01-01 price USD     0.872 EUR
2020-01-01 price USD      0.89 EUR

2021-10-27 price EUR  1.161845 USD
2021-10-27 price USD    0.8606 EUR
```

http://localhost:5000/beancount-journal-export/trial_balance/?conversion=EUR&time=2021-06

![image](https://user-images.githubusercontent.com/218609/142843331-2f5727cc-ab4c-437e-8b62-cce3c5fcb731.png)

Sunburst Assets:S = 341.45 EUR
Table Assets:S = 353.07 EUR

**Comment by yagebu** [comment]
Thanks for the reproduction :) The filtered end date was not correctly passed to the chart, so the newest prices was used. This has a simple fix :)
