### ISSUE TITLE
Precision for holdings in included files is not correct

### ISSUE THREAD

**Issue by glasserc** [beancount/fava#1347]
Here is a minimal set of beancount files.

`holdings.beancount`

```
option "title" "Holdings Bad"
option "operating_currency" "USD"
option "infer_tolerance_from_cost" "TRUE"

2021-11-01 open Income:Salary USD
2021-11-01 open Assets:Bank USD
2021-11-01 open Assets:Investments GOOG

2021-11-02 * "Receive salary"
  Assets:Bank                                  10.01 USD
  Income:Salary

include "investments.beancount"
```

`investments.beancount`

```
2021-11-02 * "Buy some stuff"
  Assets:Bank                               -10.01 USD
  Assets:Investments        1.234 GOOG {8.11 USD}
```

Expected behavior:

When I retrieve the `holdings` report, I should see `GOOG` reported at three decimals precision (i.e. `1.234` units).

Actual behavior:

When I click on the `holdings` report, I see `GOOG` reported at two decimals precision:

![Screenshot from 2021-11-20 14-44-24](https://user-images.githubusercontent.com/17006/142739137-7e26d9a5-b5cd-471b-82b2-294d04b48d72.png)
![Screenshot from 2021-11-20 14-44-25](https://user-images.githubusercontent.com/17006/142739140-64fee1fe-c9f7-4388-99c0-da0a3cca0880.png)

Additional notes:

If I manually expand the `include` directive into the contents of the file, I see the expected precision.

`holdings-2.beancount`

```
option "title" "Holdings Good"
option "operating_currency" "USD"
option "infer_tolerance_from_cost" "TRUE"

2021-11-01 open Income:Salary USD
2021-11-01 open Assets:Bank USD
2021-11-01 open Assets:Investments GOOG

2021-11-02 * "Receive salary"
  Assets:Bank                                  10.01 USD
  Income:Salary

2021-11-02 * "Buy some stuff"
  Assets:Bank                               -10.01 USD
  Assets:Investments        1.234 GOOG {8.11 USD}
```

![Screenshot from 2021-11-20 14-45-49](https://user-images.githubusercontent.com/17006/142739145-1f843c5d-8ebe-462c-933b-cf571d4a3423.png)

The `infer_tolerance_from_cost` option does not seem to make a difference and neither does adding something like `option "inferred_tolerance_default" "GOOG:0.0001"`.

Interestingly, if you update `holdings.beancount` without restarting Fava, under some circumstances it preserves the precision. For example, if you copy the transaction from `investments.beancount` into `holdings.beancount`, it will show 3 decimals in the holdings. If you then remove that transaction from `holdings.beancount` and refresh the page without restarting Fava, it will continue to show 3 decimals.

Fava version: 1.18
Beancount version: 2.3.4

**Comment by yagebu** [comment]
Hey, this is actually due to the following issue in Beancount and won't be fixed in Fava: https://github.com/beancount/beancount/issues/131

**Comment by glasserc** [comment]
Thank you! I wasn't sure where to file this issue or how to best describe it so the pointer is appreciated. I'll close this.

In the meantime, I was able to work around the issue by using `bean-query` directly, copying the query from `fava`.

```
> bean-query ~/tmp/holdings.beancount 'SELECT account,
      units(sum(position)) as units,
      cost(sum(position)) as book_value,
      value(sum(position)) as market_value
    WHERE account_sortkey(account) ~ "^[01]" 
    GROUP BY account, currency, cost_currency, account_sortkey(account)
    ORDER BY account_sortkey(account), currency'
     account         units    book_valu market_val
------------------ ---------- --------- ----------
Assets:Bank                                       
Assets:Investments 1.234 GOOG 10.00 USD 1.234 GOOG
```

**Comment by yagebu** [comment]
While just taking another look at the Beancount issue, it actually seems to be fixed in Beancount itself (but not released yet). So if you install it from the v2 branch, that include issue should be fixed.
