### ISSUE TITLE
Use URLs with a trailing '/'

### ISSUE THREAD

**Issue by SmartHypercube** [beancount/fava#1353]
related: #1245

In editor, when I try to choose a different file to edit, it generates a request like this:
`http://localhost:5000/foo/editor?...`
The correct URL should be:
`http://localhost:5000/foo/editor/?...`

Although Flask will automatically redirect, it may be better to always use the correct URL in code. Also, there may be still other wrong URLs like this in code. I just found this one.

**Comment by yagebu** [comment]
This was already fixed quite a while ago: 3f480d54eea36698bcc4edd5e4f19b2d86457e88
