### ISSUE TITLE
Add an option to specify base url

### ISSUE THREAD

**Issue by SmartHypercube** [beancount/fava#1354]
Currently, there is no way for fava to know the correct base url, if it is behind a reverse proxy. Flask will guess the base url based on the request it received. Since fava's cli only support listening on HTTP, the best I can do is to send "Host: example.com" header, and make it think it's being accessed from "http://example.com/". This is still wrong because I use HTTPS on the reverse proxy. When redirecting, Flask will generate a response like this:
```
HTTP/1.1 308 PERMANENT REDIRECT
Content-Type: text/html; charset=utf-8
Content-Length: 287
Location: http://example.com/foo/income_statement/
Date: Wed, 05 Jan 2022 08:16:47 GMT
Server: Cheroot/8.5.2+ds1

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="http://example.com/foo/income_statement/">http://example.com/foo/income_statement/</a>.  If not click the link.
```

How to reproduce:
```
fava foo.beancount
curl -i http://localhost:5000/foo/income_statement -H 'Host: example.com'
```

Note that it uses the wrong guessed base url "http://example.com/" instead of "https://example.com/" everywhere. Because of issues like #1353 , this kind of redirections do happen, and will redirect user to the wrong url. Because of such redirections (from HTTPS to HTTP on HTTPS pages) is insecure, modern browsers forbid them.

I think there are two ways to fix this problem:
1. Add a command line option "--base-url https://example.com:1234". A web server behind a reverse proxy cannot know on which url its content is actually being served, unless being told like this.
2. Add a command line option "--use-forwarded-headers". When enabled, get the base url from [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header, which was set by the reverse proxy in order to let the proxied server know the real url. Note that the headers "X-Forwarded-Proto", "X-Forwarded-Host", and "X-Forwarded-Port" are non-standard, and "Forwarded" is the standard version for them.

I recommend option 1.

**Comment by yagebu** [comment]
I don't really think Fava needs to have an option for this as this can be handled by the reverse proxy. That makes more sense IMHO as the reverse proxy then takes care of rewriting URLs in both directions (`https://example.com/` to `http://localhost:5000/` and vice versa). There is a `--prefix` option since the absolute URLs are all over the generated HTML, whereas the URL scheme and host should only be relevant for the HTTP responses where they can "easily" be rewritten by the reverse proxy.

Which reverse proxy are you using? I just tried out nginx for Fava running with `--prefix /fava` and then a corresponding `proxy_pass` setting for that location. That worked out of the box and rewrote the redirects, for more advanced cases one might need to tweak `proxy_redirect`. For Apache it looks like one needs to set `ProxyPass` and `ProxyPassReverse`: https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html#simple

**Comment by SmartHypercube** [comment]
> the reverse proxy then takes care of rewriting URLs in both directions

> the absolute URLs are all over the generated HTML

Do you think the reverse proxy should search and replace all URLs in response body? That's both dangerous (because any matched strings will be replaced even if they should not, e.g. I wrote an URL in my beancount file and it happened to be http://localhost:5000) and not enough to solve the problem (because JS may concat strings to form an URL and the reverse proxy won't replace it, e.g. `proto='http'; host='localhost'; ajax_load(proto+'://'+host);`).

That's why AFAIK reverse proxies (I mainly use Nginx) don't perform replaces in response body by default. They only replace the `Location` header. Any absolute hyperlink embeded in the document will not get replaced. Any request with absolute URL made by JS will not get replaced.

Reverse Proxies cannot solve this problem perfectly by themselves. They can only try to fix some simple things. That's why many web server programs nowadays have a base url config.

**Comment by yagebu** [comment]
As written in my last comment, rewriting the response body is not necessary.

> They only replace the Location header. 

Yes that should be enough for Fava to work. The HTTP response you posted in your initial comment should be easy for nginx to rewrite - does that not work with the right `proxy_pass` and `proxy_redirect` setting?

**Comment by SmartHypercube** [comment]
I see. That's fine then. I didn't notice any problem using the right `proxy_redirect` setting. But I always feel uncomfortable when using `proxy_redirect` to fix a base url because "I don't notice any problem for now" is different from "there is indeed no problem and I can trust that the software is running as the developers intended". Many software will have hard-to-find bugs using this setup and I always look for a base url config. But if the developer confirms that the server only uses absolute URLs in `Location` headers, I think it's okay. Thanks!
