### ISSUE TITLE
How to clear fava query history

### ISSUE THREAD

**Issue by Ynjxsjmh** [beancount/fava#1365]
Is it possible to clear the query history in fava web gui? I tried to type `clear` and submit but nothing happens. I also tried to clear site usage, but it keeps the same. I also read *Fava's Features* in http://localhost:5000/beancount/help/features, but didn't notice is it possible.

![image](https://user-images.githubusercontent.com/40143136/149668566-121d6fbc-0c31-4702-af46-ac38f2b89ebd.png)

**Comment by mechanarchy** [comment]
For now, this can only be done via developer tools. I have found the same problem though so I'll create a pull request to add the feature shortly.

Manual steps (for Firefox, it will be similar for Chome):
1. Open the Developer Tools. Generally <kbd>F12</kbd> or right click->developer tools->inspect element
2. Go to the 'Storage' tab in Firefox (may be 'Application' tab for Chrome)
3. Expand 'Local Storage', then select the address of your Fava host (probably `http://localhost:5000`)
4. Right click on the `fava-query-history` row and pick Delete.

**Comment by Ynjxsjmh** [comment]
Thank you, this really helps.

**Comment by yagebu** [comment]
Thanks to @mechanarchy, the `clear` command does now work :)
