### ISSUE TITLE
Idea: Show Liabilities on Income Statement

### ISSUE THREAD

**Issue by lockjs** [beancount/fava#1370]
Would it be possible to display non zero-value liabilities on the Income Statement page?

I have a mortgage which I've currently modeleded as a liability. I pay an amount off each month, however this isn't represented on my Income Statement as it's not an expense (despite being my largest individual outgoing) - which creates a false impression of my monthly net profit.

Alternatively is tthere a bettter way to model these payments so that the Income Statement correctly shows/calculates the net profit?

 _I tried transfering the balance into an intermediary expence account before transfering it to the liability but this isn't then shown on the Income Statement, presumably because the final balance for the expense account is 0_

**Comment by yagebu** [comment]
Liabilities shouldn't be displayed on the income statement.

> I have a mortgage which I've currently modeleded as a liability. I pay an amount off each month, however this isn't represented on my Income Statement as it's not an expense (despite being my largest individual outgoing) - which creates a false impression of my monthly net profit.

I think this is a question of modeling these transactions (or interpreting what the resulting numbers mean). You say that not having these mortgage payments as an expense creates a false impression of your net profit - is that the case though? Say you bought a flat for 250k with a 200k mortgage (principal) and 50k in cash. So you start with a net worth of 50k cash which is still a 50k net worth after the acquisition (250k + -200k). Every mortgage payment adds a positive amount to your liabilities, say after a year you payed of 30k (25k principal, 5k fees + interest), so now your net worth stands at 75k (250k + -175k). So just on these transactions you would have a net profit of 25k (from 30k income with 5k expenses). The only expenses are interest and fees, the remainder of your income that pays off your mortgage is real net profit as it increases your net worth.

For this you'd need to split the mortgage payments into two parts - one for interest+fees (expenses) and one for principal repayment (not an expense). Then your net profit should be shown correctly.
