### ISSUE TITLE
Missing setup.py prevents from installing in --editable mode

### ISSUE THREAD

**Issue by jenicek** [beancount/fava#1381]
In the [Development docs](https://beancount.github.io/fava/development.html), there is a command `pip install --editable .` which fails due to missing `setup.py`. Previous stub `setup.py` is sufficient:

```
"""Setup script for Fava.
The configuration is in setup.cfg.
"""
from setuptools import setup

setup()
```

**Comment by yagebu** [comment]
Editable installs without the stub setup.py require a recent version of pip, see https://pip.pypa.io/en/stable/news/#v21-3

**Comment by jenicek** [comment]
You are right, with the most recent pip (22.0.2), it installs without issues. Sorry, I thought I was using the most recent version.

**Comment by yagebu** [comment]
Great :) I've added a note to the docs about the pip version requirement
