### ISSUE TITLE
Feature suggestion - add unrealized profit and loss column in Holdings

### ISSUE THREAD

**Issue by jenicek** [beancount/fava#1384]
One more minor suggestion :) It may be worth considering whether not to add a column for unrealized profit and loss (either as an absolute value or as a percentage of cost) to those Holdings tables that are aggregated (by Account, etc.).

In `src/fava/templates/holdings.html`, either one of these two would be added to the select clause

- `sum(number(value(position))) - sum(number(cost(position))) as unrealized_profit`
- `(abs(sum(number(value(position)))) - abs(sum(number(cost(position))))) / sum(number(cost(position))) * 100 as unrealized_profit_pct`

**Comment by yagebu** [comment]
Sounds good. I have a slight preference for the percentage value as it's the one I usually look at (in my brokerage online account) and it seems like the absolute value could be more easily computed in the head (or in a separate BQL query) if one needs it

**Comment by jenicek** [comment]
I agree - to me, percentages are easier to interpret than absolute values. Should I create a patch for that change?

**Comment by yagebu** [comment]
> Should I create a patch for that change?

Yes, that would be great :)

**Comment by jenicek** [comment]
No worries :) I've tested it for commodities with a negative cost and commodities with no cost (in my original query posted here, a division-by-zero error would have been raised). I've added it in all the tables except the first "holdings_all" table, as that one seems already a bit polluted, but it should be easy to update that one as well.

```
diff --git a/src/fava/templates/holdings.html b/src/fava/templates/holdings.html
index f30e935d..3434544c 100644
--- a/src/fava/templates/holdings.html
+++ b/src/fava/templates/holdings.html
@@ -14,7 +14,8 @@
 'account': 'SELECT account,
     units(sum(position)) as units,
     cost(sum(position)) as book_value,
-    value(sum(position)) as market_value
+    value(sum(position)) as market_value,
+    safediv((abs(sum(number(value(position)))) - abs(sum(number(cost(position))))), sum(number(cost(position)))) * 100 as unrealized_profit_pct
   WHERE account_sortkey(account) ~ "^[01]"
   GROUP BY account, cost_currency, account_sortkey(account), currency
   ORDER BY account_sortkey(account), currency',
@@ -22,14 +23,16 @@
     units(sum(position)) as units,
     SAFEDIV(number(only(first(cost_currency), cost(sum(position)))), number(only(first(currency), units(sum(position))))) as average_cost,
     cost(sum(position)) as book_value,
-    value(sum(position)) as market_value
+    value(sum(position)) as market_value,
+    safediv((abs(sum(number(value(position)))) - abs(sum(number(cost(position))))), sum(number(cost(position)))) * 100 as unrealized_profit_pct
   WHERE account_sortkey(account) ~ "^[01]"
   GROUP BY currency, cost_currency
   ORDER BY currency, cost_currency',
 'cost_currency': 'SELECT
     units(sum(position)) as units,
     cost(sum(position)) as book_value,
-    value(sum(position)) as market_value
+    value(sum(position)) as market_value,
+    safediv((abs(sum(number(value(position)))) - abs(sum(number(cost(position))))), sum(number(cost(position)))) * 100 as unrealized_profit_pct
   WHERE account_sortkey(account) ~ "^[01]"
   GROUP BY cost_currency
   ORDER BY cost_currency',
```

**Comment by redstreet** [comment]
Nice suggestion, and I look forward to it. Is it in code yet? If not, was there a PR submitted for it, @jenicek ? Thank you!
