### ISSUE TITLE
Market Value in balance sheet

### ISSUE THREAD

**Issue by ibigbug** [beancount/fava#1394]
Is it possible to convert the value of commodities from the postings in "Market Value" page in balance sheet?

for example, posting like below:

```
2021-10-28 * "APPLE.COM/AU              SYDNEY  " ^airpods-3
  Liabilities:CC  -279 AUD
  Assets:AAP3    1 APPLE_AIR_PODS3 @ 279.00 AUD
```

It will create an entry in `commodities` with the price on the date of tx.

But it's not declared as a `price` entry.

On the balance sheet page, no matter "At Cost" or "Market Value" is selected, the commodity is shown as it's raw.

Is it possible to convert those commodities into the "run currency" ?

**Comment by ibigbug** [comment]
figured it out - can choose "Convert to CURRENCY" from the drop down.

thanks.

**Comment by yagebu** [comment]
If you only use the `@` price syntax, Beancount thinks of `APPLE_AIR_PODS3` as a currency, which doesn't have an attached cost and hence no book or market value in AUD. You'll probably want to use the cost syntax like the following if you want to track the cost:

```
2021-10-28 * "APPLE.COM/AU              SYDNEY  " ^airpods-3
  Liabilities:CC  -279 AUD
  Assets:AAP3    1 APPLE_AIR_PODS3 {} @ 279.00 AUD
```

**Comment by ibigbug** [comment]
I see. in this case, is it best practice to track assets with `{}` ?

**Comment by yagebu** [comment]
Since Beancount can infer some missing numbers, I'd say it's pretty much up to you which to leave out and where to explicitly specify the cost in the curly brackets.
