### ISSUE TITLE
When expanding transactions in my journal, Chrome crashes/freezes

### ISSUE THREAD

**Issue by tcpekin** [beancount/fava#1403]
Hello,

I have a pretty reproducible bug which occurs when I am on my journal view. When I expand the journal view for a transaction, to see the accounts that the transaction is associated with, I get a beachball of death for Chrome. The whole fava application freezes, cursor turns into the beachball, and all my other chrome windows and tabs become unresponsive. In the Activity Manager, it shows 100% CPU utilization by Chrome. I don't know what could be causing this. My use case is pretty standard I think, 1 beancount file that is ~8000 lines long. Thanks for all the work you do!

Computer: Mac Air M1
OS: macOS 12.3
Chrome: 99.0.4844.84 (Official Build) (arm64)

**Comment by yagebu** [comment]
I can't reproduce this at all (Chromium/Linux/x64). Does this also happen on some minimal example that you could share? If this is some macOS or ARM-specific issue I won't be able to debug this unfortunately so you'd have to help with that.

**Comment by tcpekin** [comment]
I will try to make a reproducible example - it is 85% reproducible with my beancount file, but when I start taking things out, or shortening it, fava works like normal. If I can get a reproducible version of the file I will upload it. Is there a way I could enable or upload a log that is created while this crash happens?

**Comment by yagebu** [comment]
Does this still happen?

**Comment by tcpekin** [comment]
In my quick check right now, it no longer happens. If it happens again, I will reopen the issue. Thanks for checking up!
