### ISSUE TITLE
Support for multiple levels of currency conversions

### ISSUE THREAD

**Issue by leipert** [beancount/fava#1407]
I am new to beancount! Thank you for this great visualization tool!

Given a simple beancount file with three commodities: EUR, USD and some imaginary stock called `HOOL` which is tracked in `USD`.

```
option "operating_currency" "EUR"
option "operating_currency" "USD"

2022-01-01 open Equity:Opening-Balances
2022-01-01 open Assets:US:HOOL
2022-01-01 open Assets:Cash

2022-01-30 * "Some stock" ""
  Equity:Opening-Balances -100 HOOL
  Assets:US:HOOL 100 HOOL

2022-01-30 * "Some USD" ""
  Equity:Opening-Balances -100 USD
  Assets:Cash 100 USD

2022-01-28 * "Some EUR" ""
  Equity:Opening-Balances -100 EUR
  Assets:Cash 100 EUR

2022-01-30 price HOOL 100 USD
2022-01-30 price EUR 1.25 USD
2022-02-28 price HOOL 200 USD
2022-02-28 price EUR 1.12 USD
```

When Converting to USD, both HOOL and EUR are converted, but when converting to EUR, only USD is converted, but not HOOL:

| USD | EUR |
| - | - |
| <img width="735" alt="USD" src="https://user-images.githubusercontent.com/2906107/161144763-7027fcc2-ea5d-4f08-ab86-3c6fa5d15fa1.png"> | <img width="731" alt="EUR" src="https://user-images.githubusercontent.com/2906107/161144801-62c67746-5660-4dab-a7af-51b95b69120a.png"> | 

I had a quick look at the source and seems like that `beancount.core.convert.convert_position` only resolves "one level deep", there is also a `beancount.core.convert.convert_amount` which supports multiple levels of conversion, but not for positions, but just amounts.

In my mind there are multiple solutions:

1. Workaround, I could also put HOOL prices in EUR into the DOC
2. Extend the function on fava side (e.g. by permutating the pricemap, or extending the existing function, e.g. like with `get_market_value`)

**Comment by carderne** [comment]
It will work if you change it as below. i.e. specify the cost.
I can't remember the mechanics of why (presumably the conversion is based on cost and not price) but this is a more realistic entry to have in your journal anyway.

```diff
@@ -7,6 +7,6 @@
 
 2022-01-30 * "Some stock" ""
-  Equity:Opening-Balances -100 HOOL
-  Assets:US:HOOL 100 HOOL
+  Assets:Cash
+  Assets:US:HOOL 100 HOOL {100 USD}
```

**Comment by vascosantos** [comment]
Even if you add the cost in USD for a HOOL purchase, the report tables will not convert down to EUR even if there is a USD-EUR price quote in the file.

If you use, say, beanprice to automate price quote retrieval, some commodities will not be available in the desired currency.

It would be great to be able to specify HOOL-USD and USD-EUR quotes (fetchable from APIs) and have the reports converted all the way down to the desired currency.

**Comment by gzagatti** [comment]
I'm new with Beancounts so apologies in advance if this is an obvious mistake. But, I'm in a similar situation as above, dealing with trip expenses. This is a ledger that I put together only for the trip. So I've added this particular expense in my ledge:

```beancount
2023-06-30 *
  Income:Guilherme
  Expenses:Restaurant                         602550.00 IDR @@ 56.35 SGD
    desc: "lunch rice field"
```

My expectation was that at the end of the exercise, I would be able to see all expenses converted to my operating currency. The option on the top right-hand corner even says: "Converted to SGD".

![image](https://github.com/beancount/fava/assets/11043156/38e29fc7-daf6-4e2e-a90b-7b4332ffd52e)

For a one-off case like this, I know I could just use the SGD amount directly on the ledger. However, what I really want is to see all the expenses in my income statement in the operating currency of my choice. 

Is there anyway around this? Maybe via an SQL Query?

This issue also relates to #1497.

**Comment by yagebu** [comment]
With #1407, you can now select multiple currencies - the conversions will be performed in sequence

**Comment by leipert** [comment]
Thanks, I guess you meant to link #1732!
