### ISSUE TITLE
Unable to view pad entries

### ISSUE THREAD

**Issue by gerdemb** [beancount/fava#1420]
Whenever I try to view/edit a pad entry by clicking on the date of the entry, I get the following error:

`Loading entry context failed...`

`Invalid data returned in API request: Validating object failed at key 'entry': Validating union failed` 

<img width="759" alt="image" src="https://user-images.githubusercontent.com/218609/167092153-04d612c6-4335-40ac-b9ad-927b6fcda528.png">

Running Beancount version 2.3.5 and Fava 1.21

**Comment by yagebu** [comment]
I can't reproduce this with a simple pad entry. Could you provide an example file?

**Comment by gerdemb** [comment]
This test case fails with the same error for me in both Safari and Chrome.

```
option "operating_currency" "USD"

2018-01-01 open Assets:Account USD
2018-01-01 open Equity:Opening-Balances 
2019-01-01 pad Assets:Account Equity:Opening-Balances
2020-01-01 balance Assets:Account  100 USD
```

Open http://localhost:5000/beancount-journal-export/journal/?show=budget&show=custom&show=discovered&show=document&show=note&show=query&show=statement&show=pad# and click on the pad entry.

If it helps, from the Chrome debug console:

![image](https://user-images.githubusercontent.com/218609/169700779-ddc61755-f058-4df7-ad35-bbe6f44fc65f.png)

![image](https://user-images.githubusercontent.com/218609/169700803-c524f0b4-a3c2-4802-ba7e-6cd500dd5c30.png)

Fava & Beancount versions:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/218609/169700853-0f4b01cb-f780-416a-8991-d2c3b9eed1a8.png">

**Comment by yagebu** [comment]
Thanks for the example, now I can reproduce it :)
