### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [beancount/fava#1427]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@saharshtapi) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by JamieSlome** [comment]
@yagebu - I am just following up on behalf of @saharshtapi. Could you please confirm the e-mail address you would like me to send the reports to?

You will be able to view the contents of both reports without having to sign-up 👍

**Comment by yagebu** [comment]
Thanks, sending the reports to my email address (mail@jakobschnitzer.de), which is also listed on the project's PyPI page at https://pypi.org/project/fava/ would be great. I'll see about adding a comment to the README or a separate security-related doc as well.

**Comment by JamieSlome** [comment]
@yagebu - appreciate the response :)

I have opened #1432 for you ❤️
