### ISSUE TITLE
Support explicit configuration of decimal format per commodity

### ISSUE THREAD

**Issue by tcrossland** [beancount/fava#1437]
It would be useful to be able to explicitly configure the decimal format used to render values of a commodity in fava. The `dcontext` inferred during parsing may have issues in some cases:

* https://github.com/beancount/beancount/issues/716
* https://github.com/beancount/beancount/issues/713

**Comment by tcrossland** [comment]
> It is now possible in Fava to overwrite the inferred display precision using commodity metadata like the following example:
> 
> ```
> 1998-07-22 commodity AAPL
>   name: "Apple Computer Inc."
>   precision: 3
> ```

This is working fine except if precision is 0, in which case it seems to be ignored.

**Comment by kaiwei** [comment]
I'm not sure what I did wrong here but everything seems to be configured correctly yet fava is not rendering them correctly. Any hints?
![image](https://user-images.githubusercontent.com/449920/219984462-51ab0b54-9c88-497b-bf3a-b15221438660.png)
![image](https://user-images.githubusercontent.com/449920/219984490-bda5ca22-ff2d-4061-9e9b-f93467927217.png)

**Comment by yagebu** [comment]
That's odd - can you open an issue with a complete file to reproduce this? Does the help page also show that you are running Fava v1.23.1?

**Comment by kaiwei** [comment]
Solved - sorry for the trouble. The issue was completely end user related.
