### ISSUE TITLE
Auto suggestion partially gone.

### ISSUE THREAD

**Issue by newboydj169** [beancount/fava#1444]
For example I have an account called Expenses:ABCD.
In previous version, if you type AB in editor, then the Expenses:ABCD will shows up.
But now, you have to type Expen and something more.

**Comment by yagebu** [comment]
I cannot reproduce this, for me, account suggestions always show up after two typed characters. Can you provide a minimal example file where this happens?

**Comment by yagebu** [comment]
Closing this stale issue - it's not reproducible without feedback.
