### ISSUE TITLE
Thanks for a great release!

### ISSUE THREAD

**Issue by duarteocarmo** [beancount/fava#1448]
[v1.22](https://github.com/beancount/fava/releases/tag/v1.22) looks incredible, really like the stacked charts! Keep at it @yagebu  - thanks for some great work 💪🏻

**Comment by redstreet** [comment]
Came here to say exactly this! Stacked charts has been implemented well, and this was obvious within seconds of trying it. For both Income and Expenses, the visual instantly offered insights that were not obvious earlier without mentally asking and answering the right questions. Well done!

Thank you, @jeffwheeler, @PhracturedBlue, @yagebu for the design and implementation, and also @aclindsa and others for the discussions!
#716,  #1408, #1286
