### ISSUE TITLE
Dev docs should mention a minimal required Node.js version

### ISSUE THREAD

**Issue by adrienbeau** [beancount/fava#1452]
As I tried to rebuild fava from source, I encountered the following error while running `make`:

```
(...)/fava/frontend/node_modules/esbuild-svelte/dist/index.js:42
  const svelteFilter = (options == null ? void 0 : options.include) ?? SVELTE_FILTER;
                                                                     ^

SyntaxError: Unexpected token ?
```

The reason is that I was using an old Node.js version.

The unrecognized `??` operator is the somewhat recent [nullish coalescing operator (??)](https://github.com/tc39/proposal-nullish-coalescing). According to https://node.green/, the first Node.js version that supports it is **14.5.0**.

**Comment by yagebu** [comment]
I cannot give an exact minimal required version, but I'll add some vague text that a recent version should work. I guess it should actually work on *all* supported Node versions.
