### ISSUE TITLE
 Narration / Payee should be Payee / Narration

### ISSUE THREAD

**Issue by Umiiii** [beancount/fava#1455]
According to the beancount documentation,

```

2014-05-05 txn "Cafe Mogador" "Lamb tagine with wine"
  Liabilities:CreditCard:CapitalOne         -37.45 USD
  Expenses:Restaurant
...

In the first example above, the payee is “Cafe Mogador” and the narration is “Lamb tagine with wine”.
```

So the first item should be payee and the second item should be Lamb tagine with wine
For current version, 
<img width="583" alt="image" src="https://user-images.githubusercontent.com/29030474/179753003-faf61e37-0525-476a-a790-df316398ca40.png">

It was reversed.

I think we should change it back to  Payee / Narration

**Comment by yagebu** [comment]
I'm not sure that whether we should keep this column header at all. It's only correct for transactions and not for other entry types like documents or notes.
