### ISSUE TITLE
Cannot see the exact value of the highest value in the icon

### ISSUE THREAD

**Issue by kba977** [beancount/fava#1459]
https://fava.pythonanywhere.com/example-beancount-file/income_statement/

The scale on the left looks like based on the highest in the chart, however, when I check the specific expenses of a month first, I could move the mouse hovers over the blank (as in the red arrow of right), but when I want to see the highest one, there is no blank to hover over(as in the red arrow of left) in the below chart.

<img width="1873" alt="image" src="https://user-images.githubusercontent.com/2995667/181256628-786c3f93-e675-412d-9a49-0623d42c8039.png">

**Comment by yagebu** [comment]
I guess we should pad the ranges like we do for the bar charts. PRs welcome.
