### ISSUE TITLE
What is the best way to access commodity metadata

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1467]
With FavaLedger.entries being deprecated, what is the best way to access a commodity's metadata (found in its commodity declaration)? This is not guaranteed to be available in the filtered context since the commodity declaration may be outside the currently selected date interval.

I was previously accessing it this way: `getters.get_commodity_directives(ledger.entries)`.

**Comment by yagebu** [comment]
You can still get the list of all entries with `ledger.all_entries`. Or even better just `ledger.all_entries_by_type.Commodity`.

**Comment by redstreet** [comment]
Perfect, thanks @yagebu !
