### ISSUE TITLE
Question: removing conversion and time period drop down selectors

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1469]
1. How can I do this for my Fava extension (Fava Investor)?
2. How can I force my extension to only display the sunburst (and not the Treemap)?
3. And conversely, how can I include just the conversion dropdown (not the time period) in my extension's page?

The template for Fava Investor [is here](https://github.com/redstreet/fava_investor/blob/main/fava_investor/templates/Investor.html).

I see `app.js` contains the dropdowns, but I don't see where they are rendered.

Thanks a bunch!

**Comment by yagebu** [comment]
re 1. and 3. I consider the conversion and time dropdown global settings like the filters and I don't plan to let them be removable. I think their positioning within the chart component is not ideal - I'll probably move them to the sidebar at some point.
re 2. Why not both? Is it not better to leave that choice up to the user?

**Comment by redstreet** [comment]
Re 1: sounds good.

Re 2: because certain datasets are much better represented by one type of chart than another.

A compromise would be if there were a way to make the sunburst the default for a given extensions. Is there a way to do this now?

**Comment by yagebu** [comment]
> A compromise would be if there were a way to make the sunburst the default for a given extensions. Is there a way to do this now?

There is not. Right now, I cannot think of a good and easy way to enable this...
