### ISSUE TITLE
Fava PythonAnywhere instance down

### ISSUE THREAD

**Issue by aleck2** [beancount/fava#1471]
The PythonAnywhere instance of fava leads to a python anywhere "Coming Soon" page
[https://fava.pythonanywhere.com/example-beancount-file/](https://fava.pythonanywhere.com/example-beancount-file/)

In case they're not aware, I want to bring this to the attention of whoever owns it.

**Comment by yagebu** [comment]
Thanks for the report, I've reactivated it :) The free pythonanywhere sites expire every 3 months and have to be manually activated again...
