### ISSUE TITLE
Breakdown by payee in charts

### ISSUE THREAD

**Issue by CicadaCinema** [beancount/fava#1472]
Like a few other users ( https://groups.google.com/g/beancount/c/vefi9DzrU4s ) I have found it difficult to make the distinction between when a payee should be specified instead of a subaccount.

The Language Syntax document [states](https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit#heading=h.aki1rqfx1z8q) :

> Payees are sometimes useful on transactions that post amounts to Expense accounts, whereby the account accumulates a category of expenses from multiple businesses. A good example is “Expenses:Restaurant”, which will include all postings for the various restaurants one might visit.

See also - https://docs.google.com/document/d/17_u_cYxeXVsCV4GmaubK_xsTQl_H9rP87E_vnZHKNb0/edit :

> I've been thinking about adding a reporting feature to Beancount whereby it would report payees as sub-accounts (i.e., define subaccounts automatically), which might be fun and it might make sense.

So it might be natural for me to expect that I will be able to see a breakdown of all such expenses filed under Expenses:Restaurant, but I see no option in fava to view this breakdown.

Is this feature intentionally omitted?

Here is the kind of view I am looking for:

![image](https://user-images.githubusercontent.com/52425971/187272541-bd168a28-beb1-4a12-b0f6-a585f23666a4.png)

Here, 'other' represents no payee present in the transaction.

**Comment by yagebu** [comment]
This could be implemented with a Beancount plugin that automatically creates these subaccounts for you. Once you have that, Fava would automatically show these in the charts. I don't want to add this just to Fava as a reporting feature.

**Comment by Rudd-O** [comment]
Adding subaccounts with a plugin does not give you the additional axis of reporting that people want.  If I want to know what *groceries* I have bought at Coop, I need to filter down by account and payee, which would work with your suggestion, but if I want to know what I have bought at Coop *in total*, your subaccounts idea would not work because my normal visit to Coop involves multiple subaccounts already.

**Comment by yagebu** [comment]
> if I want to know what I have bought at Coop in total, your subaccounts idea would not work because my normal visit to Coop involves multiple subaccounts already.

You could still filter just by the payee Coop to get that total, no? (or if you remove the payee, you could use a regex `.*:Coop` to filter across these accounts).

**Comment by Rudd-O** [comment]
I believe this issue was closed in error, as this is not complete.

**Comment by yagebu** [comment]
This was intentionally closed. I don't see this as anything that we need to implement in Fava - I think this is best implemented as a Beancount plugin
