### ISSUE TITLE
No description of new argument of execute_query

### ISSUE THREAD

**Issue by dimakor** [beancount/fava#1473]
https://github.com/beancount/fava/blob/da9230b59d46fd4b4bfddf930ee128ae84d1bbaf/src/fava/core/query_shell.py#L116

Missed description of "entries: Entries" of execute_query. Also, all extensions that used execute_query are broken now.

**Comment by yagebu** [comment]
Thanks, I've fixed the docstrings. This was part of a necessary fix in v1.22 to avoid race conditions which would lead to the unfiltered list of entries being used in some context.
