### ISSUE TITLE
Idea: Automatically open additional posting lines if not transaction is not balanced

### ISSUE THREAD

**Issue by fdw** [beancount/fava#1477]
Sometimes, a transaction has three or more postings. In the current dialog, two posting lines appear by default, and I have to add one manually when I need one.

While this works, the button to add a new one is on the very right and on small screen (phone, for example), I have to scroll. For some additional comfort, I'd love Fava to recognize that the transaction is not balanced yet and add another posting automatically.

Is this something you find valuable, or is it too complex?

**Comment by yagebu** [comment]
This shouldn't be too hard to do (for the simple case of postings without cost and maybe all of the same currency). A PR would be welcome :)

**Comment by fdw** [comment]
Do you have a hint for me how/where this could be done? I'm still *very* new to Vue.

**Comment by fdw** [comment]
Thanks for the pointers, they're very helpful 🙂

But to make this work, I need to sum the `Posting`s using their currency. Is there already a method to do that?

**Comment by yagebu** [comment]
No there isn't any such logic in the frontend yet (so far the amounts are only treated as strings). You'll have to split the amounts, convert to a number, group by currency and then sum them.

**Comment by fdw** [comment]
That means I would have to re-implement [Beancount's balancing](https://beancount.github.io/docs/beancount_language_syntax.html#balancing-rule-the-weight-of-postings)... do you have a pointer where I can leave such a general function that extracts the amount out of a posting? Can I do it in the same `Posting.svelte`?

**Comment by yagebu** [comment]
I think `entries.ts` would be the right place for it. Feel free to refactor Amount and Posting to classes if that helps implementing that functionality.

**Comment by fdw** [comment]
Sorry, one more question: I've noticed that when I try to enter a total price (in contrast to a per-unit price) using `{{<blah>}}` double braces, it's transformed into `{ 0 # <blah>}`. It works fine, but I can't find either syntax in the Beancount documentation. Have I used it wrong the whole time?

**Comment by yagebu** [comment]
I'd be fine if this logic in the frontend didn't support cost at all (and ignored anything between the {})

**Comment by fdw** [comment]
So, I've finally opened a PR for the simple case. I hope this is okay 🙂

**Comment by sohamshanbhag** [comment]
A simpler fix for the usability problem would be to add an empty line whenever all lines in the input have text and/or amounts(irrespective of if they balance). Then, you could change the default 2 line input to one line input.

**Comment by fdw** [comment]
This solution has one drawback in my eyes: If the new line is only added when the whole transaction is unbalanced, it also gives you feedback about errors (f.e. it's only unbalanced because you mistyped one amount).

**Comment by yagebu** [comment]
Yes, more frontend validations to better catch invalid transactions are still possible

**Comment by sohamshanbhag** [comment]
Another alternative would be to validate transaction on clicking save.

**Comment by fdw** [comment]
How about disabling save and showing maybe a red border around all amounts until they're balanced? That feels more streamlined and intuitive than only checking on save.

**Comment by sohamshanbhag** [comment]
Beancount allows unbalanced postings in input transactions, so I'm not sure if this should be added. However, if this is to be added, the code is very short. I can add a PR if @yagebu wants this.
