### ISSUE TITLE
Income Statement - Allow Filtering at Posting Level

### ISSUE THREAD

**Issue by jtpereyda** [beancount/fava#1479]
I'd like to get an income report filtered by postings metadata, at the postings level. For example, given a transaction like this:

```
2022-09-02 * "" "Replacement outlets half main floor half upstairs"
  Expenses:Repairs 100 USD
    unit: "A"
  Expenses:Repairs 100 USD
    unit: "B"
  Assets:Checking -200
```

I'd like to get income statements that show totals for each "unit".

Is this possible with fava right now?

Edit: Getting similar data with bean-query could look like:
```
> bean-query issue-1479.beancount 'select date, account, position where account ~ "Expenses" and META("unit") ~ "A"'
   date        account      positio
---------- ---------------- -------
2022-09-02 Expenses:Repairs 100 USD
```

**Comment by yagebu** [comment]
No, this is not possible with Fava - it only supports filtering complete entries across all of its reports. See also #1423

**Comment by jtpereyda** [comment]
THanks @yagebu ! I suspected so -- I guess this is a feature request then with a similar gist to #1423

**Comment by yagebu** [comment]
I'll close this issue, we have the other one to track this.
