### ISSUE TITLE
Uploaded document not showing up in Documents view

### ISSUE THREAD

**Issue by yusf** [beancount/fava#1480]
I've an issue with Fava and documents. Uploads via Journal works fine and are added to the transaction with `document: "2022-10-14 receipt.pdf"`. This document can't however be accessed in the Documents view, it's simply not represented there.

When clicking on the journal line of the document, I get redirected to `http://localhost:5000/ledger/statement/?entry_hash=1234567890qwertyuiop&key=document` which simply says

> Statement not found.

I can add documents to the Documents view, but not through uploading, only manually: `2022-07-13 document [account] [path]`

Is something broken or am I missing something here?

**Comment by yusf** [comment]
>Does Beancount's generation of Document directives worked before for you?

I have never tried beancount outside of using it with Fava.

**Comment by yagebu** [comment]
Using any of the command-line reports of Beancount that list documents would be a way to try it in Beancount directly. In any case it sounds like this feature in Beancount has never worked for you...

Where do the uploaded documents end up? What is the documents option set to?

**Comment by Ramblurr** [comment]
@yagebu I think something is broken here, see https://github.com/beancount/fava/issues/1496

I see the following behavior:

Repro:
* Drag a document onto a journal entry
* Drop the document

Result:
* Receive a green success message that the document was attached
* I can verify that the `document:` metadata has been added to the beancount file
* However the document it self has not been uploaded to the documents folder. It's simply not there.

Tracing the code path reveals the following:

* the `drop` event enters the `url` block and calls the `attach_document` api endpoint
  https://github.com/beancount/fava/blob/dfd52bd3e0b711493269e957089fb9fdf3c5655f/frontend/src/document-upload.ts#L52-L72
* it then returns, line 72
* the DocumentUpload modal is never invoked, and so the `add_document` endpoint is never called.

**Comment by yagebu** [comment]
Since this seems to be the same underlying issue as #1496, which has a bit more detail, I'm closing this one.

**Comment by yusf** [comment]
I don't recognize the problem described in #1496, this is not my problem.

I probably have misunderstood something, judging from the contents of yabebu's comment https://github.com/beancount/fava/issues/1480#issuecomment-1261031625.

Is the Fava drag-and-drop only ever supposed to add `document:` metadata to existing directives?

How then does one create document directives in Fava?

Are only document directives ever supposed to show in the Documents view of Fava? If so, why not document metadata?

**Comment by yagebu** [comment]
> Is the Fava drag-and-drop only ever supposed to add document: metadata to existing directives?

It adds the metadata and uploads the file to the documents directory (which allows Beancount to create the document directives)

> How then does one create document directives in Fava?

Just as any other document directive in Beancount - have Beancount create them automatically (or add them manually to the file)

> Are only document directives ever supposed to show in the Documents view of Fava? If so, why not document metadata?

Yes. The metadata is just a string with a path, it doesn't have a date or an account - we need those attributes of the document directives.

**Comment by yusf** [comment]
Finally came to the bottom of this. For posterity I'll sum it up here.

Whatever code is responsible for searching through the documents folder is _not able to handle any characters_  outside A–Z and a–z. Me having localized account names and having those accepted by Beancount it never entered my mind that the document scanner would work any different, but it does. 

A bug should be filed over at the Beancount repo.
