### ISSUE TITLE
Bar, treemap & sunburst charts aren't rendered when converting currencies

### ISSUE THREAD

**Issue by ybnd** [beancount/fava#1485]
When defining "conversion targets" with the `conversion-currencies` option, many charts show up as empty when converting.
* For example, the charts on the income statement & trial balance pages disappear even though all of the account balances below are converted as expected
* Line & area charts for account balances seem to work as expected, but bar charts for changes are broken as well
* **This issue does not occur if you declare the commodity as `operating_currency`**

On the last point: this can be somewhat of a workaround but is not ideal.
I noticed this issue when messing around with conversions to adjust for inflation -- something like that doesn't make any sense as an operating currency.

**Comment by yagebu** [comment]
The `conversion-currencies` options should only change the list of currencies that is shown in the conversion dropdown. So I guess you describe some behaviour you encounter when using one of these conversion options?

It is expected that the charts might be missing some amounts if there is no conversion towards the selected conversion. The currency specific charts are only shown for the operating currencies plus potentially the selected conversion currency. Does this match with what you mean by "disappear"? If not, could you provide a more specific example to help me understand the issuer?

**Comment by ybnd** [comment]
> It is expected that the charts might be missing some amounts if there is no conversion towards the selected conversion.

I'm not sure I understand completely, but the issue is not that _some_ amounts are missing; the entire chart is blank

The dropdowns themselves work correctly and contain the expected list of currencies. It's shown next to all types of chart, but conversion only works for line & area charts.

For an example, I took the data from https://fava.pythonanywhere.com/example-beancount-file/ and added USD->EUR echange rate for the whole example period (taken from [here](https://www.wsj.com/market-data/quotes/fx/USDEUR/historical-prices)) and added EUR to the `conversion-currencies`

In e.g. this line chart, USD is correctly converted to EUR if I select the option
![20221218-182947](https://user-images.githubusercontent.com/31547038/208311238-d97191a4-b72d-48a9-9b64-8f8a5c1ab934.png)

However, e.g. the trial balance chart is just empty even though all of the required numbers are there in the table below
![20221218-183213](https://user-images.githubusercontent.com/31547038/208311367-188d6338-9d97-40de-9b59-0417814bb9b1.png)

Now looking at it in more detail this seems due to the fact that the conversion "moves" the USD value to the "Other" column -- line/area charts can support this because they show all currencies independently.
I guess what I expected was that the conversion currency would _replace_ the operating currency instead of becoming another "Other" currency.

**Comment by yagebu** [comment]
> However, e.g. the trial balance chart is just empty even though all of the required numbers are there in the table below

I think the reason for that is just that the chart that is shown is the USD chart (which is empty) - you should be able to select the EUR chart from the dropdown. Not showing the initial currency seems to be an issue with initialisation of the `<select>` dropdown.

**Comment by ybnd** [comment]
> you should be able to select the EUR chart from the dropdown

The dropdown was already on "Converted to EUR" (see screenshot). Is there another one I'm missing or something?

**Comment by yagebu** [comment]
Sorry, "the dropdown" wasn't very precise. I mean the one to the left of the treemap/sunburst buttons

**Comment by ybnd** [comment]
Right, that one didn't have any options at all IIRC

**Comment by yagebu** [comment]
#1652 replaces the select dropdown with a list, so that initialisation issue of the `<select>` shouldn't occur anymore. Other than that I'm not sure whether anything encountered here is a bug - feel free to reopen with an example file that allows reproducing this.
