### ISSUE TITLE
Dropping files onto journal entries to upload documents has stopped working

### ISSUE THREAD

**Issue by Ramblurr** [beancount/fava#1496]
* Fava version: 1.23
* OS: Fedora Silverblue 36
* affects Firefox/Chrome latest
* file manager: Nautilus v42.2-1

I can no longer drop files onto the journal entries to upload files.

Dragging a file onto a journal entry shows the highlight (so the drag event is working).

But dropping the file onto a journal entry does nothing.

From the dev tools I was able to narrow down the problem to this section of code:

https://github.com/beancount/fava/blob/dfd52bd3e0b711493269e957089fb9fdf3c5655f/frontend/src/document-upload.ts#L54-L61

Specifically the `.searchParams.get("filename"); ` on line 54 is returning `null`, so the `put()` branch is never entered.

Setting a breakpoint on line 54, then debugging the values at my console reveals the following:

![image](https://user-images.githubusercontent.com/14830/197491320-aab12b77-a77b-443b-8463-b5fa25839d07.png)

Why is the `filename` attribute not there? I don't know :shrug:

Any ideas?

**Comment by Ramblurr** [comment]
More investigation reveals that one can obtain the filename without going through `URL`.

The `event.dataTransfer.files[n].name` property contains the filename:

![image](https://user-images.githubusercontent.com/14830/197492935-273503a1-430e-4b38-8fa2-42649a92d25a.png)

Perhaps we could switch to using this property instead of `URL`?

**Comment by yagebu** [comment]
Thank you for debugging this :) Sadly this logic is somewhat fragile due to drag-and-drop not working the same cross-browser and cross-OS, but maybe it has standardised a bit since this part was implemented :)

**Comment by yagebu** [comment]
It was actually still working fine on my setup (Arch Linux, Sway WM, and Firefox), so it doesn't look like this has standardised too much.

Can you check if #1499 fixes it? It's now using `event.dataTransfer.types` to check which kind of data was dropped (and checks for Files first, so that the URL dropping part is never attempted for files).
