### ISSUE TITLE
click on date of a posting fails 

### ISSUE THREAD

**Issue by voxspox** [beancount/fava#1510]
click on date of a posting does not show the editor in the popup but the following message:

    Loading entry context failed...

fava server reports:
```
File "...../lib/python3.10/site-packages/simplejson/encoder.py", line 379, in iterencode
   return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not type
```

see [test1.bc.txt](https://github.com/beancount/fava/files/10147358/test1.bc.txt) for example beancount file to reproduce the error and full stacktrace

**Comment by yagebu** [comment]
Thanks for the report, I think I've identified the issue. Due to the missing currencies, Beancount adds an opaque `MISSING` Python object to the `__tolerances__` dict, which we can't serialise. We should probably just omit `__tolerances__`...
