### ISSUE TITLE
`use-external-editor` feature doesn't actually use an external editor

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1512]
This feature is supposed to result in a `beancount://` url instead of opening the built-in editor, when clicking on the file link on the top of this example:

![image](https://user-images.githubusercontent.com/691755/206845847-c30b0aaa-7716-4aee-b267-3cf03540ee0b.png)

However, even when `use-external-editor` is set to True, this does not happen. I haven't dug into why. [Here is the relevant code](https://github.com/beancount/fava/blob/c46d4498615e5dbeb9590653200ac361cb045fe7/src/fava/application.py#L201).

**Comment by yagebu** [comment]
That dialog is now frontend-rendered and I think that logic is not implemented there yet.

**Comment by redstreet** [comment]
Ah, good to know. If you could point me to the frontend code (I couldn't easily find it), and an example where frontend code looks up an option, I can try to submit a PR.

Related: filed #1514. I would personally not even miss the `use-external-editor` much, if #1514 were implemented, given how good the internal editor has gotten.

**Comment by yagebu** [comment]
I'm tending towards removing that option altogether then (after implementing #1514 ;))

**Comment by yagebu** [comment]
Nevermind, I just fixed it in #1519

**Comment by redstreet** [comment]
Awesome, thank you!
