### ISSUE TITLE
Feature request: do not reload after editing, to speed up UI

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1514]
![image](https://user-images.githubusercontent.com/691755/206933910-be13c0e0-aade-4f10-b69c-f56cf86a5a9f.png)

Currently, when `Save` is pressed above, the source is reloaded and run through Beancount again. This results in a latency (few seconds for large journals) that makes it unusable to make a whole bunch of serial edits across several transactions.

Ideas to solve for this:
a) Add a `Save No Reload` button next to the current `Save` button. User can manually reload from the journal page when they are ready after all the serial edits

b) Add a `Reload` checkbox next to the save button (default: checked)

c) Add a config option `auto-reload-on-save` (default: true) (similar to the existing `auto-reload` option, but for user interaction (uploading a document or adding or editing a transaction)

Thoughts?

**Comment by yagebu** [comment]
b) sounds good :)

**Comment by redstreet** [comment]
Sweet! Thank you!
