### ISSUE TITLE
When there is an exception during import of a custom Extension Fava fails to print the complete trace.

### ISSUE THREAD

**Issue by vahidmah** [beancount/fava#1525]
Fava version 1.23.1
While Fava is trying to find custom Extensions and import them if there is a problem (an exception) in an extension Fava fails to report the error. It swallow the details. Its not clear what is the cause of failure. 

The only way to know what is causing the extension to fail is to put a break point [here](https://github.com/beancount/fava/blob/5c9c85e72e38c5723e5561fbe7cab4ab2326f2ad/src/fava/ext/__init__.py#L82) and check the `ImportError`.

Its very helpful if Fava can report the exact error details of an extension in case it happens during import.

**Comment by yagebu** [comment]
Sounds good. A PR would be welcome.

**Comment by vahidmah** [comment]
When UI is trying to parse an error it expects an [errors](https://github.com/beancount/fava/blob/db9fd75b9cc20850d2c1829f1bd44f52b7904ffc/frontend/src/api/validators.ts#L51) object. Current implementation is setting `None`. As a result, UI fails to show the error.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/24546202/214771195-265d2165-021f-457a-9a6f-d58e9cba00fb.png">

A simple fix could be 

```python
try:
    module = importlib.import_module(name)
except ImportError as ie:
    error = FavaExtensionError(
           { "filename": "", "lineno": -1 }, f'Importing module "{name}" failed.\nError: "{ie.msg}"', None
    )
    return (
        [],
        [error],
    )
```
How should we go about it?
