### ISSUE TITLE
Idea: Config to limit x axis

### ISSUE THREAD

**Issue by fdw** [beancount/fava#1542]
Currently, the x-axis of time charts gets longer with each month. Would it be possible to limit it to some configurable amount?

**Comment by marvin-yorke** [comment]
You could probably use dynamic date queries like 
`year - day` - to show graph from the beginning of this year, or
`(quarter-3) - quarter` to show 1 year window by quarters

Set a desirable time frame, save url as a bookmark in your browser (e.g. `http://localhost/beancount/income_statement/?time=year+-+day` or as a custom sidebar query
```2023-01-01 custom "fava-sidebar-link" "Quarters" "../income_statement?time=%28quarter-3%29-quarter"```

**Comment by fdw** [comment]
Thank you :) I know that it's already possible to do it manually for a query or so, but I forgot to mention that or my goal.

I would like to improve the default state/graphs. The graphs have only a fixed space available, and if you show all the history (the current approach), then each bar gets smaller. At least for me, the oldest entries in my history aren't all that relevant anymore and so I'd like to spend the space on a more detailed view of the present, cutting of everything from (for example) 5 years or earlier.
The goal would be to make the graph on the main pages more relevant.

As you said, it's possible to build custom queries for this, or limit it using the time selector, or use bookmarks, but I can imagine that integrating this in the default graphs would be helpful for more people :)

**Comment by yagebu** [comment]
A limit for the bar charts (at most 100 intervals) was added in #1579
