### ISSUE TITLE
Importers don't work installing from main

### ISSUE THREAD

**Issue by carderne** [beancount/fava#1543]
## Description
If you install fava locally following [these instructions](https://beancount.github.io/fava/development.html) (whether or not you use `--editable` install), the importers stop working with this error (in the browser):
```
Error: Validating object failed at key 'importers': Validating object failed at key 'account': string validation failed.

get http://192.168.178.2:6123/static/app.js?mtime=1675116434:4197
    load6 http://192.168.178.2:6123/static/app.js?mtime=1675116434:44845
    frontendRender http://192.168.178.2:6123/static/app.js?mtime=1675116434:2307
    init http://192.168.178.2:6123/static/app.js?mtime=1675116434:2330
    init2 http://192.168.178.2:6123/static/app.js?mtime=1675116434:51732
    <anonymous> http://192.168.178.2:6123/static/app.js?mtime=1675116434:51744
```

## Steps to reproduce
1. Create basic beancount file with importers
```beancount
; test.beancount
option "operating_currency" "GBP"
2000-01-01 custom "fava-option" "import-config" "config.py"
2000-01-01 custom "fava-option" "import-dirs" "raw"
```

```python
# config.py
from beancount.ingest import importer
class Imp(importer.ImporterProtocol):
    def __init__(self, acc):
        self.acc = acc
    def name(self) -> str:
        return self.acc
    def identify(self, file) -> bool:
        return self.acc in file.name
CONFIG = [Imp("rawfile")]
```

Make empty raw file:
```bash
mkdir -p raw && touch raw/rawfile
```

2. Install fava from git
```bash
git clone git@github.com:beancount/fava.git
cd fava
make
pip install .
```

3. Run fava
```bash
fava ../test.beancount
```

4. Open fava in a browser and click on `Import`.

**Comment by carderne** [comment]
(Dealing with this trying to confirm that #1538 is all good.)

**Comment by carderne** [comment]
So, I realised this is caused by some new validation that hasn't yet been released to PyPI. Unfortunately, instead of printing the Python error, it just prints the console logs I pasted above.

What breaks it in the example above is that the `Imp` importer doesn't implement the `extract`, `file_account`, `file_name`, `file_date` methods.

So not a bug, just less useful for debugging.

**Comment by yagebu** [comment]
Thanks for reporting this :)
