### ISSUE TITLE
Header rendered above content on mobile devices

### ISSUE THREAD

**Issue by cheif** [beancount/fava#1559]
I've noticed that the header is rendered on top of some views on small devices (AKA. mobile), see screenshot.

I've just looked through the inspector a bit, and this seems to stem from the use of a static variable `--header-height: 50px`, even though we permit the header to grow on mobile. This then affects the `.fixed-fullsize-container` used in some views, since that uses fixed layout with a fixed offset from the top.

Just quickly messing around in the inspector removing the `position: fixed` from the `.fixed-fullsize-container` solves this, but I guess there's a reason for having it fixed?

If there's no good reason for this, I can put up a PR that removes it and cleans up the usage of `--header-height` a bit, I guess that we'd like to avoid absolute positioning/sizing as far as possible, even if reality get's in the way from time to time 😅 

<img width="576" alt="image" src="https://user-images.githubusercontent.com/678919/221978082-03fba45d-a497-49ef-8bb6-b974daf31f8b.png">

**Comment by yagebu** [comment]
> Just quickly messing around in the inspector removing the position: fixed from the .fixed-fullsize-container solves this, but I guess there's a reason for having it fixed?

I think that's mainly needed for the editors, which would look ok but then have the height of the text (and hence tens of thousands of pixels) and bad performance. If you can play around and find a way to get the editors have window height and not having the fixed position container, that could work.
