### ISSUE TITLE
Unable to open `Errors` screen on latest `main`

### ISSUE THREAD

**Issue by cheif** [beancount/fava#1560]
When trying to open the `Errors` screen I get this error: `Error: Validating object failed at key 'entry': Validating object failed at key 'type': string validation failed.`. Trying to understand what happens I think that it's a regression introduced in: https://github.com/beancount/fava/commit/d26b1e0e7a7901cae54ba2dbcf398cafc96713d2, and it seems like the problem is that the `EntryBaseAttributes` has a `type`, which isn't returned from the API.

I'm not really sure where the problem resides, but since the json-API uses `beancount` types under the hood I guess that maybe we should just remove `type` from `EntryBaseAttributes`?

**Comment by yagebu** [comment]
The `type` attribute is added by the serialise function which currently isn't used in all cases when creating the JSON data (since it is not easily possible to hook into the JSON encoding of NamedTuples with the standard JSON encoder). I'll just remove the entry property for now.
