### ISSUE TITLE
Holdings by currency detailed.

### ISSUE THREAD

**Issue by gety9** [beancount/fava#1566]
First of all thank you for amazing work on the project, fava is amazing!

I have small suggestion / feature request:

Say i have MSFT currency in several  brokerages

> accounts / units / cost / ........
> Assets:Brokerage1:MSFT 1,005 MSFT 150
> Assets:Brokerage1:MSFT 600 MSFT 210
> Assets:Brokerage1:FB ...
> Assets:Brokerage1:AMZN ...
> Assets:Brokerage1:KO ...
> ....
> Assets:Brokerage2:MSFT 800 MSFT 180
> 

Currently there is no way to sort by and see detailed breakdown per currency (to see exact units and cost, not averages)

Holdings by currency shows only average cost:
```
units / average_cost / ...
2,405 MSFT 174.95...
....

```
Could you please consider either:
-, adding sort by currency to "Holdings"
-, or detailed (not average cost) view to "Holdings by currency"
?

**Comment by yagebu** [comment]
If you want to see the detailed breakdown, just for MSFT, this could be achieved by looking at the "Holdings" and setting an account filter of `.*:MSFG". Or alternatively, you can always open the underlying query and modifying that to your liking.
