### ISSUE TITLE
Web demo not displayed

### ISSUE THREAD

**Issue by widp** [beancount/fava#1573]
The web demo in the description points to a blank site.

https://fava.pythonanywhere.com/

**Comment by redstreet** [comment]
![image](https://user-images.githubusercontent.com/691755/228139792-e5e14a3f-b28a-471f-9902-5640595422e5.png)

**Comment by yagebu** [comment]
Thanks, I reactivated it (the free pages on Pythonanywhere expire every 3 months)

**Comment by RobOlejniczak** [comment]
FYI, The free pages on Pythonanywhere must have expired again. I'm currently getting the same page redstreet posted a year ago.
