### ISSUE TITLE
Price and cost columns always partially obscured

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1575]
No matter how wide the screen is. Tried with Chrome, Edge.

![image](https://user-images.githubusercontent.com/691755/228140100-f2e2c336-2b38-4ed6-b56d-eea947048a2f.png)

Fava has been like this for as long as I remember. Are others seeing this too or am I doing something wrong?

**Comment by redstreet** [comment]
Also like this in the account view:
![image](https://user-images.githubusercontent.com/691755/228140840-82fbcdd5-0ba3-4004-8306-56a52c5d2a9d.png)

**Comment by yagebu** [comment]
Yeah, a PR with CSS fixes for this would be welcome :)

**Comment by redstreet** [comment]
Heh, I'd truly love to fix this as it's quite an annoyance, but I have close to zero CSS skills. I hope someone with skills will notice this ticket and submit a fix :-)
