### ISSUE TITLE
Editor auto-indentation behavior changed in 1.24

### ISSUE THREAD

**Issue by bnabholz** [beancount/fava#1577]
I have noticed a change in the indent behavior starting with v1.24.  In v1.23 and earlier, pressing enter after the first line of the transaction directive would indent the posting lines that follow, until pressing enter on a whitespace line, then it would return to not being indented (set up for the next transaction).  This was very ergonomic for entering multiple transactions in the editor.

Starting with v1.24, indentation is not performed for the first posting line and has to be done manually.  Additional posting lines remain indented, but pressing enter on a whitespace line does not stop indentation and the indent must be manually removed for the next transaction.

This started with commit 3703c9e when dependency [codemirror/language](https://github.com/codemirror/language) upgraded from 6.3.0 to 6.3.1.  The relevant code in CodeMirror is https://github.com/codemirror/language/commit/bd34cf40cb00f1658dba935a2bd0f546ce151bf4 in response to https://github.com/codemirror/dev/issues/1000.  Starting with 6.3.1, codemirror/language treats a `null` response from an indenting service as "I don't know how to indent this and stop trying."  Because of that, when `getIndentation` calls the default indent service implementation in CodeMirror, it gives up on the first null it gets back and does not attempt to ask the `beancountIndent` implementation.

I tried to fix this by implementing `indent()` method in `beancountStreamParser` to simply return `undefined`, but the `StreamParser` interface in CodeMirror doesn't include `undefined` as an acceptable return type so this fails linting.

I'm not sure if CodeMirror needs to do something different but I'm not familiar enough with their project yet to suggest what.  I have pinned codemirror/language to 6.3.0 in package.json for my own build of fava and have not encountered any issues.  I'm not sure if that's acceptable in the short term for Fava, so figured I'd open an issue before submitting a PR.

**Comment by yagebu** [comment]
Hi, thank you for reporting this and for already debugging the issue!

There might be a way to work around this with the stream parser, but IMHO this should maybe the final push for us to add and use a Lezer parser. I've pinned the package for now as suggested by you :)
