### ISSUE TITLE
Sunburst graph stacked together on switch

### ISSUE THREAD

**Issue by ssine** [beancount/fava#1598]
To reproduce:

Select trial balance, sunburst. Then click between Income and Expenses, the new graph is drawn on top of the old one (the old one should have disappeared).

<img width="751" alt="image" src="https://user-images.githubusercontent.com/20841764/234671293-9e70e09c-4272-4d71-9b29-965361fb319b.png">

PS: I'm using multiple currencies, not sure if its related.

**Comment by vkbytes** [comment]
I am seeing the same issue, After I reload the browser it adjusted correctly. The refresh does not clear the old graphs at times

**Comment by yagebu** [comment]
I can't reproduce this. Can you reproduce this with one of the example files in the repository? Which browser are you using? Are there any errors in the Javascript console?

**Comment by villivateur** [comment]
I've got this issue for a long time. Now I go back to v1.22.3

**Comment by yagebu** [comment]
Closing this issue as it is not reproducible and cannot be debugged without further information

**Comment by eliptus** [comment]
This seems easily reproducible with multiple operating currencies.

With the below file, you can observe this by going to `Trial Balance` and first viewing `Income` in `Sunburst` mode, then selecting `Assets`.

```
option "operating_currency" "USD"
option "operating_currency" "JPY"

2023-12-04 open Assets:Checking USD,JPY
2023-12-04 open Income:Salary USD,JPY
2023-12-04 open Expenses:Food USD,JPY

2023-12-04 * "Mixed Transaction"
  Assets:Checking   +10000 JPY
  Assets:Checking  +100.00 USD
  Income:Salary

2023-12-04 * "USD Transaction"
  Assets:Checking   -10.00 USD
  Expenses:Food
```
