### ISSUE TITLE
the top toolbar and the left-side menu disappear.

### ISSUE THREAD

**Issue by shichao402** [beancount/fava#1622]
When I run Fava, the top toolbar and the left-side menu disappear.
![image](https://github.com/beancount/fava/assets/1974733/512cab3d-2a14-4672-8bc4-13505c35501a)

windwos 11, pure reinstall python 3.9 
i install fava via "pip3 install fava"
then
`D:\>bean-example > test.bean
INFO    : Generating Salary Employment Income
INFO    : Generating Expenses from Banking Accounts
INFO    : Generating Regular Expenses via Credit Card
INFO    : Generating Credit Card Expenses for Trips
INFO    : Generating Credit Card Payment Entries
INFO    : Generating Tax Filings and Payments
INFO    : Generating Opening of Banking Accounts
INFO    : Generating Transfers to Investment Account
INFO    : Generating Prices
INFO    : Generating Employer Match Contribution
INFO    : Generating Retirement Investments
INFO    : Generating Taxes Investments
INFO    : Generating Expense Accounts
INFO    : Generating Equity Accounts
INFO    : Generating Balance Checks
INFO    : Outputting and Formatting Entries
INFO    : Contextualizing to Realistic Names
INFO    : Writing contents
INFO    : Validating Results

D:\>fava test.bean -d
Starting Fava on http://127.0.0.1:5000
 * Serving Flask app 'fava.application'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
Starting Fava on http://127.0.0.1:5000
 * Debugger is active!
 * Debugger PIN: 109-750-056
127.0.0.1 - - [03/Jun/2023 18:47:35] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [03/Jun/2023 18:47:35] "GET /example-beancount-file/income_statement/ HTTP/1.1" 200 -
127.0.0.1 - - [03/Jun/2023 18:47:36] "GET /static/app.js?mtime=1685788901 HTTP/1.1" 304 -
127.0.0.1 - - [03/Jun/2023 18:47:36] "GET /static/app.css?mtime=1685788901 HTTP/1.1" 304 -
127.0.0.1 - - [03/Jun/2023 18:47:36] "GET /static/fira-mono-latin-400-normal-JUOXJG4X.woff2 HTTP/1.1" 304 -
127.0.0.1 - - [03/Jun/2023 18:47:36] "GET /static/fira-sans-latin-400-normal-BVHR5GIK.woff2 HTTP/1.1" 304 -`

What could be the issue, and did I miss something?

**Comment by shichao402** [comment]
I tried Fava 2.3.1 and the display is normal, but there are no input fields in the top right corner. I'm not sure if it's because this version doesn't have them or for some other reason.

**Comment by yagebu** [comment]
The header and the sidebar are rendered in the frontend, so it looks like there is some error in the Javascript part that stops them from being rendered - what does the browser console show?

**Comment by shichao402** [comment]
![image](https://github.com/beancount/fava/assets/1974733/162ad730-9249-48e6-9e6b-e9dde4cab75f)
I have disabled all the extension plugins in Chrome.
and i checked the console and indeed saw errors in app.js. Do you have any thoughts on this?

**Comment by yagebu** [comment]
I believe this might be the same as #1446 (invalid system configuration causing the Javascript file to be served with the wrong mimetype), see https://github.com/beancount/fava/issues/1446#issuecomment-1229485770 for how this can be fixed.

**Comment by shichao402** [comment]
Thank you, I modified the registry, cleared the browser cache, and restarted the computer, and now the display is normal.
