### ISSUE TITLE
Self signed SSL and password for localhost?

### ISSUE THREAD

**Issue by Blocked** [beancount/fava#1645]
Since transaction data is very sensitive information, Is there a option to provide certificates, self signed or otherwise to host the data using https?  Is there a way to provide some basic authentication like password based authentication? 

Using it on a mobile device, where every app that has internet permission can access this localhost:5000, seems to be a privacy nightmare.

**Comment by yagebu** [comment]
That's something that I would probably consider as being out-of-scope for the Fava CLI (AFAICT there's no way to add those things with a few extra lines using the libraries we currently use).

However, this can be achieved by using `fava.application.create_app` to create a Fava WSGI application and then running that application with a WSGI server and/or middlewares and/or proxies that support those features.
