### ISSUE TITLE
Fava editor broken in v1.25 ("Could not resolve WASM paths.")

### ISSUE THREAD

**Issue by mechanarchy** [beancount/fava#1647]
The editor is broken for me in v1.25, using both Chrome and Firefox on Ubuntu.

from #1629 

## Broken in v1.25:
![image](https://github.com/beancount/fava/assets/1166756/acc8b9c9-392c-4d89-8685-e61136d88e39)
> Loading Editor failed with error:
> 
> Could not resolve WASM paths.
```
git clone https://github.com/beancount/fava.git . \
    && git checkout v1.25 \
    && pip install -e .[excel] \
    && make \
    && pre-commit install \
    && fava
```

## Works in v1.24 (same as above, replace `v1.25` with `v1.24`):
![image](https://github.com/beancount/fava/assets/1166756/53562cc5-024b-4d16-b671-1c8f73ec16de)

**Comment by yagebu** [comment]
Hi, thanks for the report. Can you check whether your browser versions are recent enough to support https://caniuse.com/?search=import.meta.resolve?

**Comment by mechanarchy** [comment]
Nope, they sure don't support it.

Looks like I'm still using Firefox 84 (latest is 115) and Chrome 89 (latest is 115). I'll try and update at least one of my browsers and just pin my Fava to version 1.24 in the meantime. Thanks for the guidance.

**Comment by mechanarchy** [comment]
Yep, I bumped Firefox to 115 and the issue is gone. Thanks again!
