### ISSUE TITLE
Charts don't show unless refresh the web

### ISSUE THREAD

**Issue by OdinZhang** [beancount/fava#1662]
I use beancount in WSL Ubuntu 22.04. When I open the web, it shows well. But when I click something like Balance Sheet, the charts doesn't show anymore, and shows `Rendering component failed: array validation failed`, unless I refresh the broswer. It's wired.

fava, version 1.25.1
Beancount 2.3.5
Microsoft Edge Version 116.0.1938.54 (Official build) (64-bit)
Python 3.11.4

**Comment by yagebu** [comment]
Can you provide an example file to reproduce this with?

**Comment by OdinZhang** [comment]
```
2000-01-01 open Assets:Cash CNY
2000-01-01 open Equity:OpeningBalance

2023-08-23 * ""
    Assets:Cash 123 CNY
    Equity:OpeningBalance
```

![image](https://github.com/beancount/fava/assets/25601078/71900fbb-79db-4b53-97f0-28b2a5f8e5a3)
![image](https://github.com/beancount/fava/assets/25601078/76d7edbf-ed1e-4715-9f61-2467d0abd034)

**Comment by yagebu** [comment]
I cannot reproduce this with the example file that you provided. Can you try clearing your browser caches? Also, how did you install Fava? This might be due to some outdated Javascript or Python code being used in some place.

**Comment by OdinZhang** [comment]
I found it. It's all because adguard, I turned it off and the charts shows normally. Now I need to change its profile.
