### ISSUE TITLE
Journal postings UI showing unnecessary scroll bar

### ISSUE THREAD

**Issue by addisonklinke** [beancount/fava#1667]
If I enable the postings filter in the journal tab, the amounts show up correctly. However, the UI is cluttered with horizontal and vertical scroll bars for every posting (see screenshot) even though there appears to be plenty of real estate on the screen to fit all the information

![image](https://github.com/beancount/fava/assets/39926682/ab928990-bb2f-4b1b-8774-0969eec3b636)

This is with the latest `fava==1.25.1`. I don't have much front-end experience, so please let me know what additional information would be useful for debugging

**Comment by yagebu** [comment]
This was introduced by #1636, which added an `overflow: scroll` there. I think nowadays on many setups (also for me in Firefox on Linux for example) the scroll bars are only shown when in use, but changing it to `overflow: auto` should fix it on browsers/setups like yours that where those scrollbars are always visible.
