### ISSUE TITLE
Autofill in Transaction Entry Form doesn't overwrite

### ISSUE THREAD

**Issue by yogiparish** [beancount/fava#1676]
This is something that has been around for a while, but I couldn't figure out how to get this working:

If I add a transaction in the entry form and immediately add another one in the same form, the fields are still populated with the data of the last transaction. (see other issue)

If I select a payee from the Autocomplete List it doesn't change the rest of the fields if they are already populated. The problem seems to lie somewhere in these lines:

From - frontend/transaction

  // Autofill complete transactions.
  async function autocompleteSelectPayee() {
    if (entry.narration || !entry.postings.every((p) => !p.account)) {
      return;
    }
    const data = await get("payee_transaction", { payee: entry.payee });
    data.date = entry.date;
    entry = data; **<-- THE NON-EMPTY FORM FIELDS ARE NOT REPLACED.**
  }

If I manually clear all the input fields, the behavior is as expected.

Unfortunately, I am not versed enough in Svelte to propose a fix, but I imagine it shouldn't be too complicated.

Thanks for any pointers.

**Comment by fdw** [comment]
I think this is actually desired behavior: If you've already filled in some things and then change the payee, it should not erase your previous work.
The problem is that the form is stilled filled from the last added transaction. See #1674 .

**Comment by yagebu** [comment]
Yep, I'd also consider this to be the same bug as #1674
