### ISSUE TITLE
1.26 regression: Account listings with umlaut are now empty

### ISSUE THREAD

**Issue by MJochim** [beancount/fava#1678]
A second regression I noticed in 1.26: When an account name includes a German umlaut, the account page is now empty. For example:

`http://localhost:2020/<my-filename>/account/Aufw%C3%A4nde:30-Haushalt/`

Both the table and the charts are empty. The heading (blue bar at the top) shows `Aufw%C3%A4nde:30-Haushalt` instead of `Aufwände:30-Haushalt` as the account name. Maybe the account name is just URL-encoded too early. Or it’s never URL-decoded.

Also, on the balance sheet and income statement, these accounts show up just fine with their correct numbers. Only the `/account/` page appears to be broken.

I have tested an account named "Jahresüberschuss" and two whole classes of accounts starting with "Erträge:" and "Aufwände:". When I remove the ü/ä from the account names, Fava works fine.

Version 1.25 did not have this problem. The dev tools console in Firefox shows no messages. I have just verifed the bug with Fava 1.25 and Fava 1.26 right after each other with the same Firefox, so apparently it’s not browser behavior.

**Comment by fredrik-eriksson** [comment]
I can confirm this as well; my accounts containing Swedish letters 'åäö' is now broken in the account page.

**Comment by mikaeljagelid** [comment]
Same here using åäö in account names. Tested in several different browsers in macOS, iOS and Windows with the same result. Downgraded back to 1.25 and the problem is gone.

**Comment by fredrik-eriksson** [comment]
I managed to get the account reports working by changing [this line](https://github.com/beancount/fava/blob/216d7ddf5796dd46f12515e8c2726692393e545b/frontend/src/reports/accounts/index.ts#L21). Or rather the corresponding line in the compiled .js-file. Where the account variable was actually called account2... I won't even pretend to understand how web development works :sweat_smile: 

From:
```
      a: account,
```
To:
```
      a: decodeURI(account),
```

This gets the account page working again, but the account name is still url-encoded in the heading as @MJochim described, so this is not the complete fix, but hopefully it helps someone with better understanding of this stuff to come up with a proper fix.

**Comment by MJochim** [comment]
@fredrik-eriksson Based on what you did I found out how to fix both the heading and the journal. I know how web development works, in general, but I’m not familiar with Svelte. Also, I don't know if @yagebu has any plans of bigger changes to this code, but I’ll prepare a PR and we’ll see if he likes it.

**Comment by yagebu** [comment]
Thanks for the report and for providing the fix :)
