### ISSUE TITLE
View treemap without sub-accounts

### ISSUE THREAD

**Issue by plejon** [beancount/fava#1693]
I like having many sub accounts when I run my CSV exports in my custom importer.
However, the treemap get a bit cluttered when there are many subcategories

Can i specify to group subcategories to the parent account of Expenses, Income etc?

Example.

```
Expenses:Car:insurance
Expenses:Car:Tax
Expenses:Car:Gasoline
```

into

`Expenses:Car`

**Comment by yagebu** [comment]
There's already an open option for this feature (PR welcome ;)): #1062
