### ISSUE TITLE
Fava option 'default file' has no effect (Fava 选项“default-file” 没有效果)

### ISSUE THREAD

**Issue by czcn** [beancount/fava#1698]
Fava 选项“default-file” 没有效果，新交易记录，总是写到Beancount的"filename"中
Fava option 'default file' has no effect. New transaction records are always written to the 'filename' of Beancount option.

**Comment by czcn** [comment]
It works. Used for Fava editor to open by default. Not the file where the transaction record was added.

**Comment by yagebu** [comment]
Yes, exactly, this option only sets to the default file to open for the editor.

You can use the `insert-entry` option to influence where the entries get inserted.
