### ISSUE TITLE
Can the account name be displayed in other languages?

### ISSUE THREAD

**Issue by codingchan** [beancount/fava#1701]
Now we can only set account names in English, which is not a problem, but can we translate the account names in other languages, such as Chinese, etc. and display them on the web page?

**Comment by korrat** [comment]
Could you help me understand what you're looking for? As I understand it, you want to have account names in other scripts, such as Chinese. Is that right?

For the most part, Beancount and Fava support any Unicode letter in an account name. So you can have account names like "Assets:α-Invest" (Greek letter alpha). That only leaves the root accounts: Assets, Equity, Expenses, Income, Liabilities. For these you can use the corresponding Beancount options: `name_assets`, …

Here is a minimal example of using those. Apologies if the translation is wrong/inaccurate, I just put “Assets” into DeepL.

```beancount
option "name_assets" "资产"
option "operating_currency" "USD"

2023-01-01 open 资产:Savings-Institute:Checking
```

For me, this works and I see the account in the balance sheet. Does this work for you too?

**Comment by chylli-deriv** [comment]
I tried but I got error: Error for option 'name_assets': Invalid root accont name: '资产'
