### ISSUE TITLE
Sunburst graph stacked together on switch

### ISSUE THREAD

**Issue by eliptus** [beancount/fava#1718]
This is a re-open of #1598 with repro steps. [I tried to provide these in the original bug](https://github.com/beancount/fava/issues/1598#issuecomment-1837692247), but it seems to have gone unnoticed.

---

This seems easily reproducible with multiple operating currencies.

With the below file, you can observe this by going to `Trial Balance` and first viewing `Income` in `Sunburst` mode, then selecting `Assets`.

```
option "operating_currency" "USD"
option "operating_currency" "JPY"

2023-12-04 open Assets:Checking USD,JPY
2023-12-04 open Income:Salary USD,JPY
2023-12-04 open Expenses:Food USD,JPY

2023-12-04 * "Mixed Transaction"
  Assets:Checking   +10000 JPY
  Assets:Checking  +100.00 USD
  Income:Salary

2023-12-04 * "USD Transaction"
  Assets:Checking   -10.00 USD
  Expenses:Food
```

**Comment by yagebu** [comment]
Thanks for providing an example file to reproduce this, with it, this was an easy fix.
