### ISSUE TITLE
Fiscal Year cannot end in the next year of Calendar Year

### ISSUE THREAD

**Issue by lo48576** [beancount/fava#1719]
In my country (Japan), FY2023 starts at 2023-04-01 and ends at 2024-03-31, but Fava option cannot describe this.
`custom "fava-option" "fiscal-year-end" "03-31"` defines FY2023 as `[2022-04-01, 2023-04-01)`, and this is not my intention.

**Comment by yagebu** [comment]
I think the behaviour of this option could be extended to cover your use case. Currently, as you describe, it always assumes that the fiscal year end is in the same calendar year. I think it would be logical to extend that to allow "higher" months that fall in the next year, e.g., `15-31` to define FY2023 to end on `2024-03-31`. A PR implementing that would be welcome :)

**Comment by Anks** [comment]
Huh, Indian Fiscal Years also start on 1st April and end on 31st March. I had not noticed any issues — it just seems to work for me.

I have this option:

`2000-01-01 custom "fava-option" "fiscal-year-end" "03-31"`

Transactions on 31st March or 1st April all look fine in the journal view; and graphs on income statement, balance sheet are correct as well.

**Comment by lo48576** [comment]
[India](https://en.wikipedia.org/w/index.php?title=Fiscal_year&oldid=1206650402#India):
> The financial year from 1 April 2022 to 31 March 2023 would generally be abbreviated as FY 2022-23 or( FY22-23) ( FY2022/23),(FY2022/2023),(FY22/23), but it may also be called FY 2023 or FY23 on the basis of the ending year. [[25]](https://en.wikipedia.org/w/index.php?title=Fiscal_year&oldid=1206650402#cite_note-25)

The difference is, the Indian Fiscal Years is named after the **ending year**, in contrast to the Japanese Fiscal Year being named after the **beginning year**. Indian FY23 is Japanese FY22.
So yeah `"fiscal-year-end" "15-31"` would be (relatively) intuitive to represent Japanese Fiscal Year system.
