### ISSUE TITLE
Don't find the Export or Download button

### ISSUE THREAD

**Issue by momu** [beancount/fava#1736]
As I wanted to export a subset of my journal I was happy that I found this section on the [help page](https://fava.pythonanywhere.com/example-beancount-file/help)

> Exporting a Journal view
>
> When displaying a Journal, including a filtered Journal, the entries displayed can be downloaded in Beancount format by clicking the Export button.

So no messing with `BSQL` was necessary.

But unfortunately I'm not able to find the appropriate button here:

https://fava.pythonanywhere.com/example-beancount-file/journal/?account=Expenses%3AFood%3ARestaurant

Checking the code showed that the URL for the download is 
 
https://fava.pythonanywhere.com/example-beancount-file/download-journal/?account=Expenses%3AFood%3ARestaurant

and I got my export. But the question remains: where is this button?

**Comment by floriskruisselbrink** [comment]
The export-button is actually the '+'-sign next to the menu-item 'Import'

I know, a little counter-intuitive with the only text nearby reading the opposite of import ;)

**Comment by momu** [comment]
Orrr, thanks for the clarification. At least I tried and inspected the page source and looked for download, but not export.
