### ISSUE TITLE
Suggestion: Remove price directive when deciding start date of the graph

### ISSUE THREAD

**Issue by sohamshanbhag** [beancount/fava#1754]
I first posted this 2 weeks back in #1119, but that issue is closed, and I'm not sure if github informs the owner when someone comments on a closed issue. This is a copy of the same.

---

From the git history, it seems that #1119 was the issue which prompted adding Price directives for determining time axis limits. This was done so that variation in price would be shown on the chart, even when no transactions have taken place. Moreover, in #1593, the code was changed from using beancount.core.getters.get_min_max_date to using the code of beancount.core.getters.get_min_max_date directly. In that case, can the code be changed such that price is only considered when selecting _date_last, and not _date_start? The present implementation in src/fava/core/\_\_init\_\_.py, i.e.

    for entry in self.entries:
        if isinstance(entry, (Transaction, Price)):
            self._date_first = entry.date
            break
    for entry in reversed(self.entries):
        if isinstance(entry, (Transaction, Price)):
            self._date_last = entry.date + timedelta(1)
            break

leads to a large part of the graph in the start containing no data if the price values for those are given (which happen in my file due to automatically fetching historical data). The plot with Price in filter:
![2024-01-25_01-21-48_screenshot](https://github.com/beancount/fava/assets/11429526/3f386f76-447e-4367-8189-7660929484fb)

vs the one with Price not in filter:
![2024-01-25_01-22-24_screenshot](https://github.com/beancount/fava/assets/11429526/c881916f-422c-4671-995f-b0af5e92b8f1)

(There is a very small transaction at the start of the second plot hence the plot looks empty there)

The change for the same would be

    for entry in self.entries:
        if isinstance(entry, (Transaction,)):
            self._date_first = entry.date
            break
    for entry in reversed(self.entries):
        if isinstance(entry, (Transaction, Price)):
            self._date_last = entry.date + timedelta(1)
            break

Making this change would also not affect #1119 since there would be no assets whose values would be changing before the first transaction.

_Originally posted by @sohamshanbhag in https://github.com/beancount/fava/issues/1119#issuecomment-1908485981_

**Comment by yagebu** [comment]
Sure, sounds good - can you open a PR with that change?
