### ISSUE TITLE
Pythonanywhere demo site not working

### ISSUE THREAD

**Issue by RobOlejniczak** [beancount/fava#1782]
Hi,

Same issue as in the referenced closed issue below from 1 year ago. I'm receiving the same "Coming Soon" pythonanywhere page as redstreet posted in the referenced thread.

              ![image](https://user-images.githubusercontent.com/691755/228139792-e5e14a3f-b28a-471f-9902-5640595422e5.png)

_Originally posted by @redstreet in https://github.com/beancount/fava/issues/1573#issuecomment-1486252435_

**Comment by yagebu** [comment]
Thanks for reporting, I've reactivated it
