### ISSUE TITLE
Translations - Norwegian Bokmål language

### ISSUE THREAD

**Issue by paul-lilley** [beancount/fava#1785]
Hi,
I'd be happy to contribute to a Norwegian (Bokmål) translation - could you approve me on the translation tool?

**Comment by yagebu** [comment]
I've added Nowergian Bokmal - could you try joining now?

**Comment by paul-lilley** [comment]
Thanks - unfortunately I get
"This project can't accept new contributors at this time. Please try again later."

**Comment by paul-lilley** [comment]
Hi @yagebu, any idea how I can join the project?  I still get the error message above.

**Comment by yagebu** [comment]
Can you try again? (I had switched to allow contributors to join without approval, maybe that was the issue? - now you'll need approval again but maybe it works...)

**Comment by paul-lilley** [comment]
Hi @yagebu, I still get the same "This project can't accept new contributors at this time. Please try again later."

**Comment by yagebu** [comment]
yeah, this is a mess - can you maybe send me your email address by email then I can invite you manually.

Also this makes switching away from poeditor.com (e.g. to Weblate, see #1447) more attractive
