### ISSUE TITLE
Configure number of lines in the preview popup

### ISSUE THREAD

**Issue by ileodo** [beancount/fava#1790]
Currently, if I click the date of a transaction in fava, a popup will come up showing the preview of the raw transaction text. However I believe the text got truncated, and turns out the transaction was not displayed properly. (my transaction has a lot of lines of meta data)

Is there a way to fix it or make it configurable? 

Thanks

**Comment by yagebu** [comment]
The code to obtain the lines for an entry is here: [get_entry_slice](https://github.com/beancount/fava/blob/main/src/fava/core/file.py#L327). A PR with a fix would be welcome :)

**Comment by ileodo** [comment]
I think the implementation is correct. my ledger file had some issue which caused the problem. thanks!
