### ISSUE TITLE
fava not working in winpython

### ISSUE THREAD

**Issue by holahapi** [beancount/fava#1804]
I'm new to beancount and Fava

I'm a beginner with beancount and Fava. 

When attempting to run them in WinPython (portable Python), the server only shows a blank page. 
What could be causing this issue?

**Comment by yangyun98** [comment]
You need to change the win's registry to do so,I did this successfully.
like this https://github.com/beancount/fava/issues/1446#issuecomment-1271737802

**Comment by holahapi** [comment]
Thanks for your help! I'd rather not touching the registry. I'll just wait for the problem to be fixed. Thanks again!

**Comment by yagebu** [comment]
A workaround was added for that issue in #1672, so that shouldn't be causing it.
Does the browser console show any errors or other logs? Does the Fava application log any errors? Which versions did you install?

**Comment by yagebu** [comment]
mhh, so that workaround does not seem to be working - can you try fixing your registry or seeing whether it works with a more up-to-date Python version.

What does the following Python script output?:
```py
import mimetypes

print(mimetypes.guess_type('app.js'))
print(mimetypes.types_map.get(".js", ""))
mimetypes.add_type("text/javascript", ".js")
print(mimetypes.guess_type('app.js'))
```

**Comment by holahapi** [comment]
```
import mimetypes

print(mimetypes.guess_type('app.js'))
print(mimetypes.types_map.get(".js", ""))
mimetypes.add_type("text/javascript", ".js")
print(mimetypes.guess_type('app.js'))
```

output
```
('text/plain', None)
text/plain
('text/javascript', None)
```

After further testing, I found out that WinPython 3.9 works with Beancount and Fava in VMware Workstation.

I guess the issue was caused by having another Anaconda Python installation.
