### ISSUE TITLE
Allow ISO Formatted string dates in charts svelte-component

### ISSUE THREAD

**Issue by mattmccormick** [beancount/fava#1810]
I'm trying to write a Fava extension.  The extension would display a line chart using the following code:

```html
{% set chart_data = [{'type': 'balances', 'label': 'Chart', 'data': extension.data()}] %}

<svelte-component type="charts">
    <script id="chart-data" type="application/json">{{chart_data|tojson}}</script>
</svelte-component>
```

The issue is that the `LineChartDatum` must be a native JS Date object
https://github.com/beancount/fava/blob/528f81845b2bc18a8071a45e08bd7b6bd5af6b47/frontend/src/charts/line.ts#L16

However, it is not possible to use a date string  as the component will fail with the following error:

```
Rendering component 'charts' failed due to invalid JSON data:

Parsing of data for balances chart failed:
Validating object failed at key 'date': Expected a date
```

**Comment by yagebu** [comment]
> Allow ISO Formatted string dates in charts svelte-component

That is already the case - JSON data is loaded via validators, which try to convert from e.g. a string to a Date. The error comes from the function https://github.com/beancount/fava/blob/528f81845b2bc18a8071a45e08bd7b6bd5af6b47/frontend/src/lib/validation.ts#L65 which tries exactly that.

Can you provide some example data that fails loading?

**Comment by mattmccormick** [comment]
Here's a test plugin that should reproduce the issue.

`test_plugin/templates/TestPlugin.html`

```html
{% set chart_data = [{'type': 'balances', 'label': 'Chart', 'data': extension.data()}] %}

<svelte-component type="charts">
    <script id="chart-data" type="application/json">{{chart_data|tojson}}</script>
</svelte-component>
```

`test_plugin/__init__.py`

```python
from datetime import datetime

from fava.ext import FavaExtensionBase


class TestPlugin(FavaExtensionBase):
    report_title = 'Test Plugin'

    def data(self):
        return [
            {
                'name': 'Chart',
                'values': [
                    {'name': 'Value', 'date': datetime.now().isoformat(), 'value': 2}
                ]
            }
        ]
```

In the .beancount file, add:

```
2000-01-01 custom "fava-extension" "test_plugin"
```

When clicking on the `Test Plugin` link in the left side navbar, the page should display the following error:

```
Rendering component 'charts' failed due to invalid JSON data:
Parsing of data for balances chart failed:
Validating object failed at key 'date': Expected a date
```

**Comment by yagebu** [comment]
A date is expected there, not a datetime - so calling `date()` on that datetime before serialising it should do the trick. In theory, so far anything the Javascript Date constructor accepted would have worked, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format - due to the timezone inconsistencies in parsing though, that's not really desirable, I'll tighten the validation there.
