### ISSUE TITLE
Cursor jumps on save in editor

### ISSUE THREAD

**Issue by abourget** [beancount/fava#1815]
I've been using `fava` quite a lot, and one thing has annoyed me quite a bit: each time I save, the cursor jumps to the end of the file, or near the `insert-entry` location.

Is there a reason why, when saving, the cursor couldn't be restored to where it was, and the view port would just stay where it was?

Am I the only one with this issue?

thanks! awesome project btw.

**Comment by kentj** [comment]
This has been driving me crazy lately too.  My files are not chronologically ordered, rather they are broken into multiple 'sections' by transaction type, and then ordered chronologically within that section.  When I save interim work within that section, it moves to the end of the file and I have to move back to that section.

**Comment by quewen08** [comment]
Same with me. But I fixed it by [this issue comment](https://github.com/beancount/fava/issues/1393#issuecomment-1055081416)
