### ISSUE TITLE
Wrong Chinese Translation

### ISSUE THREAD

**Issue by david4958606** [beancount/fava#1835]
The translation of 'Payee' in Chinese should be "收款人", but it has been translated to "付款人", which means 'Payer'.

<img width="381" alt="image" src="https://github.com/user-attachments/assets/03b7cb62-20e2-4d56-aa03-7c62c918d128">
<img width="312" alt="image" src="https://github.com/user-attachments/assets/2a2408d8-64a8-44e8-8919-e4b9a4b4cf3f">

**Comment by yagebu** [comment]
Fixed in #1856
