### ISSUE TITLE
"fava-sidebar-link" does not work for queries anymore

### ISSUE THREAD

**Issue by pm-bernhard** [beancount/fava#1837]
This line should be a link to a help command inserted into the query page:

2020-01-01 custom "fava-sidebar-link" "TestQuery" "../query/?query_string=help"

I use this feature for storing complex queries which was very helpful for me.
I don't remember the old fava version, but this feature was already working.

**Comment by yagebu** [comment]
Not totally related to the main purpose by the PR, but this should be fixed by #1854
