### ISSUE TITLE
Holdings not correctly displayed when using @ notation for prices

### ISSUE THREAD

**Issue by mwip** [beancount/fava#1839]
Given the following two different ways of accounting for buying stocks, only the `{}` notation is displayed correctly in the `Holdings` view:

```
2024/01/01 open Assets:Cash
2024/01/01 open Assets:Stocks

2024/01/01 * "Buying Stocks"
    Assets:Cash
    Assets:Stocks  10 STOCK @ 100.00 FIAT
    Assets:Stocks  10 STONK {100.00 FIAT}

2024/02/01 * "Buying Stocks"
    Assets:Cash
    Assets:Stocks  10 STOCK @ 200.00 FIAT
    Assets:Stocks  10 STONK {200.00 FIAT}
```

![image](https://github.com/user-attachments/assets/896d6b56-aa1a-474d-a24a-cc8d019d804a)
![image](https://github.com/user-attachments/assets/e108bbc6-9127-4876-8f99-c83b7b7107ea)
![image](https://github.com/user-attachments/assets/d2be963a-2481-43d5-991b-299f70b03044)
![image](https://github.com/user-attachments/assets/62448652-8fc6-4323-bf2e-9fcc6a36ad91)

As beancount lists the `@` notation in the [docs](https://beancount.github.io/docs/beancount_cheat_sheet.html) as supported, I thought I'd ask whether this behavior of `fava` is intentional.

version info: 
- `fava==1.28`
- `beancount==2.3.6`
- `python==3.10.6`

**Comment by yagebu** [comment]
Yes, that's intentional, that's the core difference between the two types of syntax. With `@` you state "I don't care about this exchange rate", with `{}` you state "this is held at cost at this rate" - see also https://beancount.github.io/docs/beancount_language_syntax.html#costs-and-prices
