### ISSUE TITLE
Search completion issue when searching payee: field with unescaped `*` character

### ISSUE THREAD

**Issue by alexandre-janniaux** [beancount/fava#1846]
Hi,

I've met an issue with the search completion where it suggests an unescaped string (I'm searching for "leroy"):

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/17fa81ec-b3ac-4eee-8f46-60a9e4b87b7c">

leading to the account being empty

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/53decbf9-420c-4f8c-9d10-7cc4127c1b8f">

If I escape the string correctly, I do get the correct payee subacount:

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/fdb83617-b486-4feb-86ea-e5c7408b9491">

Tested on fava-1.29.dev3+g365cd5dc

**Comment by yagebu** [comment]
Yeah, I guess we need to escape those suggestions. A PR with a fix would be welcome.

**Comment by alexandre-janniaux** [comment]
I've found where to modify the generated suggestion but didn't have time to actually test. I'll send the PR in the next weeks hopefully!

**Comment by yagebu** [comment]
Fixed in https://github.com/beancount/fava/commit/a45e7f688e433729e7a3d97bff18cf7cda1cd102
