### ISSUE TITLE
request: Option for custom CSS

### ISSUE THREAD

**Issue by mdlaat** [beancount/fava#1848]
I don´t believe there currently is an option for adding custom css to fava.

Would it be possible to make available an option like:
`1998-01-01 custom "fava-option" "customcss" "/path/to/custom.css"`

which would inject 
`<link rel="stylesheet" href="/path/to/custom.css" />`
into the html that fava produces?

**Comment by yagebu** [comment]
I'm not too keen to add an option for this. The exact CSS of Fava is an implementation detail and may change at any point, I don't want to encourage tweaking that heavily.

What's the exact use case here? Aren't there browser extensions that allow one to do this?

**Comment by mdlaat** [comment]
Thank you for your reply.
For now, I would like to hide the buttons 'at costs', 'monthly' and the arrow to hide/show the graphs, which would (I guess) easily been done with custom css.
I thought a custom css  might also be useful to others.
I rather not have tweaks at the client side, because it could lead to different interfaces at different clients.

**Comment by yagebu** [comment]
As written above, I don't want to make this sort of tweaking too easy (as it would be either quite fragile or would totally impede CSS changes). It shouldn't be too hard to do this with a Fava extension. You could provide a Javascript file that adds the custom CSS in the `init` function.

**Comment by mdlaat** [comment]
That's ok. Thank you for you pointing to fava extensions, which is all new to me. Will have to dive into that, but am struggling to find a *really* simple (like hello world) example.

**Comment by yagebu** [comment]
Closing this as I currently don't plan to implement this in Fava.

For example of extensions, see https://github.com/beancount/fava/tree/main/src/fava/ext
