### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by rafacla** [beancount/fava#1862]
Hello dears,

I'm starting in the Beancount/Fava world, and so far I'm liking a lot the experience.
As I'm putting a sort of order in the chaos that my finances got in the last year, I want to make my wife participate of this.

So, looking at Fava translation to portuguese I can realize two things:
- It's mixing brazilian portuguese with the portuguese spoke in Portugal
- It's kind broken, I can see parts of Fava where a noun is translated as a verb (those are different in portuguese), and parts that have no translation at all.

So, I want to help with translation, but checking the POEditor I can't see how to open a node for brazilian portuguese.
Most of software have the two most spoken variants of portuguese (Portugal and Brazilian), for brazilian portuguese we use pt_BR and for Portugal pt_PT.

If you guys decide to keep only one variant, I can help anyway, but I'm afraid that Fava will suffer of personality issues, using mixed variant terms like "Guardar" for "Salvar" (pt_PT and pt_BR variants to Save word) or "Arquivo" for "Ficheiro" (pt_BR and pt_PT variants to File).

Please let me know which way should I continue.

Thanks for the amazing work, by the way.

# Quick Edit
POEditor project is not accepting new editors:
![image](https://github.com/user-attachments/assets/bb5e3d7d-1b65-41da-9b00-1bc6aee2284f)

**Comment by yagebu** [comment]
Happy to add Brazilian Portuguese of course :)

I've contact POEditor support to inquire about this error (see also #1785) - it should be configured correctly from what I can access but somehow noone can join or be added.

**Comment by yagebu** [comment]
There was some limitation in place (that they can remove for open source projects or paid ones). That was removed, can you try joining on POEditor again? (I've already added Brazilian Portuguese there.)

**Comment by rafacla** [comment]
Hi yagebu!

Just joined the team in POEditor, many thanks!

This weekend I'm going to start working on this!

**Comment by rafacla** [comment]
Dears,

Just finished translating available strings.
It seems we have other parts in English that I don't know if it's possible to translate, examples:

![Screenshot_20240921_074950_Chrome](https://github.com/user-attachments/assets/6c7dfef4-6267-4dc2-8b87-af865255e187)
Month names on charts

![Screenshot_20240921_075044_Chrome](https://github.com/user-attachments/assets/bc060ef5-737d-43c8-bad1-c415fafa09fe)
Help pages

**Comment by yagebu** [comment]
> It seems we have other parts in English that I don't know if it's possible to translate, examples:

Yes, that's somewhat intentional. It's not realistic to have the help pages fully translated, on those, using some translation extension / service
