### ISSUE TITLE
Do not send user at the top of the current file if a file change is detected

### ISSUE THREAD

**Issue by AlphaJack** [beancount/fava#1889]
When I open Fava, I have some scripts that update commidity prices in the background.
These files are imported from the main file that I am manually editing.

Whenever a file is changed in the background, the UI warns me with a yellow message (OK), but  also moves my cursor from line 10k to line 1 (not OK). Luckily, my manual changes are not lost, so I can scroll down and resume them before clicking "Save".
However, I have to wait for all scripts to finish before doing my manual edits, otherwise I get moved up every few seconds.

Is there a way to disable that the user's cursor is moved to the first line of the file, whenever a change is detected?

**Comment by yagebu** [comment]
This sounds like a duplicate of #1815 - can you verify that this is really not fixed?

**Comment by AlphaJack** [comment]
Hi, I still have the issue

**Comment by yagebu** [comment]
You'll need to provide some more details on how to reproduce this. I cannot reproduce this on main or v1.29, changing the file in the background does not lead to any scrolling of the editor.

**Comment by AlphaJack** [comment]
I also cannot reproduce the issue now in 1.29, I believe I was using 1.28 still.
Thank you for trying it out
