### ISSUE TITLE
Error calling importer method: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by gary-roach** [beancount/fava#1894]
I created a custom importer to import credit card transactions from a pdf. The importer is based on [pdfreader](https://github.com/redstreet/beancount_reds_importers/blob/main/beancount_reds_importers/libreader/pdfreader.py). It works fine when calling bean-identify and bean-extract from the command line, but when I attempt to go to the import page on Fava, I get the error message Error calling importer method: exceptions must derive from BaseException.

![Screenshot_1](https://github.com/user-attachments/assets/7170f8df-e399-446c-b86a-38ea272d585e)

I'm not sure how to troubleshoot this in Fava. Is there logs somewhere I can look at? Is this something anyone has seen before when building custom importers? Does Fava have any requirements for importers outside of what would be needed to run bean-identify and bean-extract?

**Comment by gary-roach** [comment]
The issue was that the importers file_date method was throwing an exception like `raise "not implemented"`. After implementing the method this issue was resolved.

**Comment by yagebu** [comment]
> The issue was that the importers file_date method was throwing an exception like raise "not implemented".

`raise "not implemented"`  is not even valid Python and the error this causes is exactly the one you had in the screenshot above, yes.
