### ISSUE TITLE
Time is being included in document name during Fava import

### ISSUE THREAD

**Issue by gary-roach** [beancount/fava#1897]
![image](https://github.com/user-attachments/assets/aa1d4f19-0b7e-4645-a617-2bdf0f0dd51a)

This is a visual issue, but it's also an issue when trying to pull my beancount files and documents from source control on a Windows machine. The time includes colons in the name, which are not valid in Windows file names. 

I tried modifying the importers file_date method to return a date instead of a datetime, but it causes beancounts bean-file commands to fail as well as an internal server error within Fava. 

It looks like [ingest.py](https://github.com/beancount/fava/blob/8f8061fe8e65b3f9dbed51d785a29bb1844f3943/src/fava/beans/ingest.py#L70) is returning a date, not a datetime, so I'm not sure why this is happening. Maybe this was fixed, but not released yet? I'm running Fava version 1.29.

I'm open to help fixing this issue if someone familiar with the project can provide some guidance on where the date is concatenated with the file name.

**Comment by gary-roach** [comment]
I just realized that you can manually change the filename before hitting move, so this isn't a huge deal, but I'd still be willing to help fix it.

**Comment by yagebu** [comment]
> I tried modifying the importers file_date method to return a date instead of a datetime, but it causes beancounts bean-file commands to fail as well as an internal server error within Fava.

The file_date method should return a date, not a datetime - but looking at #1894, I'd assume your importer is doing something fishy as well thath would cause errors then

**Comment by gary-roach** [comment]
@yagebu Thanks for your reply. You are correct. 

I thought that `datetime_object.date` would return the date property of the datetime object, but python doesn't provide such a property, instead it requires calling the method `datetime_object.date()`. `bean-file` handles the datetime object fine, stripping out the time portion, which added to my confusion. 

Changing the output to `datetime_object_date()` does fix the issue in Fava and `bean-file` still has the expected output as well.
