### ISSUE TITLE
filter by date not available in v1.29

### ISSUE THREAD

**Issue by pwalkr** [beancount/fava#1918]
I use `filter=date:2024` instead of `time=2024` to filter out `Summarization` transactions. In v1.29 I get this error:
```
Failed to parse filter: date:2024
```
To reproduce, add to any url:
```
&filter=date%3A2024
```
Date is arguably special given the dedicated `time` filter. Other `filter` filters are working so maybe this undocumented feature was dropped in the latest query updates and there's a better way to filter out `Summarization` transactions?

**Comment by yagebu** [comment]
I guess this was broken by #1819 - `2024` is treated as a number now and can be used for numerical comparisons.

The "string search" version that you used can still be achieved with `date:"2024"`

**Comment by pwalkr** [comment]
Ah, that's it. Confirmed: `filter=date%3A"2024"` works. Thanks!
