### ISSUE TITLE
Convert expenses to single currency

### ISSUE THREAD

**Issue by goshakkk** [beancount/fava#242]
I am trying to get on the CLI accounting bandwagon and trying out beancount as it seems to be the most semantically cohesive (also has fava!)

Is there a way to have expenses converted into a single currency (USD) in the charts (account page & income statement)? As well as everything on the trial balance page

<img width="1481" alt="screen shot 2016-03-27 at 5 41 22 pm" src="https://cloud.githubusercontent.com/assets/315596/14065882/bda7b4f8-f443-11e5-9871-fd309d2323ed.png">

Setting two operating currencies results in ugly charts which are basically useless (given that in terms of my national currency, 1 USD = 20,300 BYR; and only credit card transactions are in BYR, everything else is dollars only)

<img width="981" alt="screen shot 2016-03-27 at 5 46 13 pm" src="https://cloud.githubusercontent.com/assets/315596/14065888/dfc9d66a-f443-11e5-81b6-f53a0aa5194d.png">

FWIW, there are `price` statements in the file, and conversion works manually using `convert(sum(position), 'USD')`.

Ideally, I'd love to have everything converted into dollars and plotted as such. Is there a way to achieve that currently in fava?

Thanks!

**Comment by yagebu** [comment]
This is currently not possible in fava, but it's a useful feature that we should have. There's an [issue](https://bitbucket.org/blais/beancount/issues/103/make-the-balance-sheet-and-income) on the beancount issue tracker for this as well.

This is something I've been meaning to implement for some time, but it doesn't have the highest priority for me. So no idea if I'll get round to do it anytime soon. If you know Python and want to get your hands dirty, I could give you some pointers, otherwise you'll have to wait for me or someone else to implement this.

**Comment by goshakkk** [comment]
I do know some Python and would appreciate any pointers on this feature, might get some time on the weekend to work on that

**Comment by yagebu** [comment]
- We need a function to convert an inventory to the specified currency: `convert_inventory(price_map, target_currency, inventory)`. This can probably be done similarly to `beancount.ops.holdings.convert_to_currency`, as a Position and Holding have basically the same attributes (and an Inventory is a list of Positions). `ops.prices`, `ops.holdings` and the basic beancount data types should be all that's needed. This function could go in `fava.api.helpers`.
- `fava.api.serialization.serialize_inventory` should take the currency as an optional argument and then use the above conversion.
- To link this to the frontend, the currency could be passed to the api as a "filter".
- There should be some select/dropdown form to select the conversion in the interface.

**Comment by aumayr** [comment]
Maybe this could go (UI-wise) with #179: Having a new filter for "Currency" (as with Time, Tags, etc.) and in there a checkbox to convert everything to a certain currency or just filter for it.

**Comment by yegle** [comment]
I have a very similar feature request. For an account mixed with cash/stock, I'd like to see the account balance in USD, with the stock convert to USD using the price at the end of each month.

Right now if you have such an account, the account balance graph only shows the cash balance change, not the total values of that account.

Please let me know if you feel it should be a separate feature request and I'll file another one instead.

**Comment by xentac** [comment]
@yegle There is an unrealized plugin that does an equity conversion for commodities at the current date.  That gets you close to what you want.  What you really want is my modification to that plugin (https://github.com/xentac/beancount-plugins-xentac) that does the calculation per month.  That will show you the unrealized value over time on a monthly basis.

**Comment by aumayr** [comment]
Isn't this something beancount should do (and we just display the results)?

**Comment by blais** [comment]
There's a lot in this thread.

- Converting to a single currency should be available in a function beancount.core somewhere.

- In the meantime, you can use that code from beancount.ops.holdings, but heads-up: holdings are going to go away at some point. I think I can degenerate them to be a list of Posting instances. (This has become possible with the new booking code changes.) In any case, that code would be migrated.

- Realizing gains over multiple times (e.g. at the end of each month) is a separate topic, and is a fair bit more complicated. I think that ultimately you shouldn't do this using the unrealized plugin, but rather, at the time of converting the units to market value (and not cost). Converting to a single currency is a second transformation that should happen on top of that. So in short, there are two layers: (1) "convert to cost, or, convert to market value", and (2) convert that to a single currency.

**Comment by yagebu** [comment]
This is implemented now :) Thanks to the work of @blais, there wasn't much to do.
