### ISSUE TITLE
New chart types: Calendar and Sankey

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#258]
These two charts look like we could use them:

![sankey](https://cloud.githubusercontent.com/assets/5135450/14403424/ee9b3488-fe55-11e5-8674-2a41127860dc.png)

https://bost.ocks.org/mike/sankey/

![calendar](https://cloud.githubusercontent.com/assets/5135450/14403425/f0800846-fe55-11e5-9460-3876af0ef850.png)
http://bl.ocks.org/mbostock/4063318

Do you think this is worth the trouble?

**Comment by corani** [comment]
Here are almost 2500 sample D3 charts that may give some inspiration: http://christopheviau.com/d3list/gallery.html

**Comment by aumayr** [comment]
Do any particular ones spring to your eye, @corani ?

**Comment by corani** [comment]
No particular ones (yet). I came across the page last night in a D3 tutorial video.

**Comment by vlaci** [comment]
I think a [stacked bar chart](http://bl.ocks.org/timelyportfolio/5586845) would make sense e.g. for the `Monthly Changes` graphs. That would make much easier to see the dynamics how accounts' contributions changed from month to month to the expenses

**Comment by johannesjh** [comment]
Also check the visualizations from this open source portfolio analysis tool: 
http://www.portfolio-performance.info/portfolio/

**Comment by yagebu** [comment]
I'll close this issue as there seems to be little interest in implementing calendar and sankey charts (well for sankey, there was some interest but implementing it seems hard/not worth it #642). Links to collections of a hundred charts are not specific enough to start any work in Fava . More specific chart suggestions are very welcome though (but can have and deserve their own issues).

I've openened a new issue for a stacked bar chart.

@johannesjh: The tool you linked to seems to have some nice charts - if there's one you'd really like to see in Fava, could you open a new issue with some more specific suggestions?

**Comment by yagebu** [comment]
I'm still not sure whether it works well (with many accounts, three-and-more-legged transactions) but maybe vibecode it to see whether it's worth it? ;)

**Comment by lukasalexanderweber** [comment]
+1 on "would love sankey in fava" 😊

to get a better understanding where my money flows is the main motivation I started using beancount in 2026

**Comment by cbrxyz** [comment]
The [fava-dashboards](https://github.com/andreasgerstmayr/fava-dashboards) extension can show these graphs! You can use the [example `dashboards.tsx` file](https://github.com/andreasgerstmayr/fava-dashboards/blob/main/example/dashboards.tsx) to get them.
