### ISSUE TITLE
Budgets: Add budget levels as line in bar-charts

### ISSUE THREAD

**Issue by corani** [beancount/fava#299]
To get a quicker overview of how you're doing regarding your budget, it would be useful if the budget level is shown in some of the charts. The X-ly changes bar-chart is an obvious candidate for this. For example:

![screenshot from 2016-05-26 16 23 53](https://cloud.githubusercontent.com/assets/480775/15568503/dbbfa7f8-235e-11e6-931e-ec85a80ca5b6.png)

**Comment by aumayr** [comment]
I intend to add some more charts for budgets, and this is a great idea and would be one of the first things to implement. 

@yagebu How hard is this to achieve in d3.js?

@corani Do you have more ideas for charts (and new "integrations" or new pages altogether for budgets)?

**Comment by yagebu** [comment]
> @yagebu How hard is this to achieve in d3.js?

Shouldn't be hard, once you know how you want it to know it exactly (and added the data).

**Comment by aumayr** [comment]
OK so the data would be calculated as follows: 

1) A point in the line-chart for every change of budget-per-day, as per a budget directive setting a new budget for this account.
2) A line connecting those points. 

The data for this is quite easy to get, as it's already held in the `Budgets`-class. I will write a function to get this as a dict of `currency: [(date, value), ...]`.

**Comment by aumayr** [comment]
In f746cff I added a method to `Budgets` that returns the data as described above. 

Adding the line chart does require some refactoring of the JavaScript-code, as this mixes two chart types.

@yagebu: Could you add the line chart, if you have time?

**Comment by yagebu** [comment]
> @yagebu: Could you add the line chart, if you have time?

Don't know when I'll have time for it. You can ping me here to remind me in one or two weeks, might forget otherwise.

**Comment by adamgibbins** [comment]
@yagebu Bit late, but better late than never - giving you a 3 month instead of week ping ;)
I'd really love to have this, I don't know anything of JS nor d3, would really love if you managed to find time to complete this :)

**Comment by yagebu** [comment]
Could you provide an example file with some budgets?

**Comment by adamgibbins** [comment]
@yagebu How's this? Budgets are at the bottom [example.txt](https://github.com/aumayr/fava/files/478165/example.txt)

**Comment by yagebu** [comment]
Thanks! There are some more pressing issues that I'll address first, but then I'll try to implement this.

**Comment by yagebu** [comment]
I've started implementing this. Mixing a line chart and a bar chart for the same kind of data seems to be quite a bad idea though, so I'll add bars for the budget as well.
