### ISSUE TITLE
Support large numbers with multiple currencies better

### ISSUE THREAD

**Issue by xentac** [beancount/fava#385]
Right now if you have a single operating currency and use comma separators, you won't run into text overlap issues until you have a billion of something (even then, it's minor).

With two operating currencies that number drops down to 100,000.00 of something.  With three operating currencies, it's 10,000.00 of something.

I'd like to be able to support up to 5 currencies with tens of millions of something before having problems.  How exactly to do that I'm open to suggestions.

One idea is to progressively demote things to Other currencies as the number of digits increases, so someone with two operating currencies and 1,000,000.00 of something will automatically have the table convert to a two operating currency table.

Another is to absorb some of the account name space if there's room (often when we convert to single column mode there's plenty of whitespace initially).

Or we could hide the contents and make it expandable with a hover or click if it's above the column width.

**Comment by yagebu** [comment]
The only reason to set `operating_currency` is to have it displayed in a separate column in the trees (because that's about the only thing it does). So I don't see how putting them in the "Other" column makes sense.

If you're happy with some of your 5 currencies being demoted, why do you set them as operating in the first place?

**Comment by xentac** [comment]
operating_currency doesn't just make a currency get its own column, it also stops the currency from being converted to an existing operating currency.  This is why most commodities don't show up in the Other column, even though you hold them, instead they get converted into an operating currency if possible.  In my finances, I have two operating currencies (USD and CAD) and I have unvested shares and vacation time in the Other column (HOOLI.UNVEST and VACHR).

My idea would be to keep the individual reporting of the currency, but instead put it in the Other column.  Hopefully I could wrap this into a different change that was able to expand the currency columns responsively, so if there was enough space (like just after we go from 2 column to 1), all operating currencies will have their own columns and be large enough to hold the right number of digits.

**Comment by yagebu** [comment]
> operating_currency doesn't just make a currency get its own column, it also stops the currency from being converted to an existing operating currency.

That's incorrect. Beancount doesn't do any conversions, I guess what you mean is that the account balances are displayed at cost. The only thing the operating currency does and should do is to move it to its own column but never change what gets displayed. If this happens, it's a bug, can you provide an example file to reproduce this?

**Comment by xentac** [comment]
You are right, I meant to say that it displays non-operating_currencies at cost.  Either way, my original idea does make a distinction between a non-operating_currency (converted cost) and a demoted operating_currency (original commodity in the Other column).

**Comment by yagebu** [comment]
> You are right, I meant to say that it displays non-operating_currencies at cost.

No, all currencies are displayed at cost, it really doesn't make a difference if it's an operating_currency or not.

**Comment by xentac** [comment]
Hmmm... I guess I was mistaken...

In testing it out, I did realize that operating currencies are displayed in the graphs as well, which could still be useful.
