### ISSUE TITLE
Commodities do not load due to JS error

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#395]
The Commodities page does not load due to a JavaScript error:

`app.js:11673 Uncaught (in promise) TypeError: Cannot read property 'click' of null(…)`

This line is the source in the `initCharts`-function:

``` javascript
  $('label:first-child', labels).click();
```

**Comment by yagebu** [comment]
Will fix it. I guess you don't have any prices in your beancount file?

The new `$` in JS is basically a shortcut for `document.querySelector` (or here `labels.querySelector`)  which returns `null` if the element is not found, so you'll get this error if the element is not found. I find this quite helpful actually as it makes code where we usually assume these elements exist error out and not just fail quietly like it did when using jQuery.

**Comment by aumayr** [comment]
> I guess you don't have any prices in your beancount file?

You are absolutely right - I forgot that I commented out the includes for my prices files 🙄
