### ISSUE TITLE
Query is not selected in aside

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#396]
If you click on "Query" in the sidebar the menu-item in the sidebar is not marked as selected.
- When you then execute a query it then gets selected correctly.
- When you reload a page with the URL http://localhost:5000/example/query/ the menu-item is selected correctly.

**Comment by yagebu** [comment]
Can't reproduce this. Works like all the other sidebar links for me. Can you open the developer tools to see if there's some JS error?

**Comment by aumayr** [comment]
```
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null(…)
```

in `initEditor`:

```javascript
var select = $('.stored-queries select');
    select.addEventListener('change', function () {
    //     ^^^ here
      var sourceElement = $('.stored-queries a.source-link');
      var sourceLink = select.options[select.selectedIndex].getAttribute('data-source-link');

      editor.setValue(select.value);
      sourceElement.setAttribute('href', sourceLink);
      sourceElement.classList.toggle('hidden', select.value === '');
    });
```
