### ISSUE TITLE
Partial page loads don't offer an indicator

### ISSUE THREAD

**Issue by xentac** [beancount/fava#399]
After I click on something, I'm not quite sure if it's loading.  We should find a sweet loading spinner to use when a partial is loading.

**Comment by aumayr** [comment]
IMHO the perfect location for a spinner is on the right margin of the menu item that is loading.

**Comment by xentac** [comment]
What about when you load an account from the account tree? Or load journal details? Or apply or remove a filter? All of these things turn into partial page loads.

**Comment by aumayr** [comment]
> What about when you load an account from the account tree? Or load journal details? Or apply or remove a filter? All of these things turn into partial page loads.

Even in these cases I would be for showing the spinner next to the corresponding sidebar-item - don't you think that would work (UI-wise)?

**Comment by yagebu** [comment]
I'd prefer a global indicator. There's not always a corresponding sidebar entry and the sidebar might actually be hidden. Also, if the indicator is not right next to the clicked link, I feel it should be always in the same place.

It should be something noticeable but not too obtrusive. The sort of indicator that Github uses seems to be all the rage these days. I think they're quite nice but something relying on progress state might a hard to implement with `fetch`. Two other ideas off the top of my head: 1) Replacing the logo with a spinner icon.; 2) replacing the page title with a spinner.

**Comment by aumayr** [comment]
I like the logo-replacing-idea, as it does not change the layout much (as opposed to replacing the title).

**Comment by xentac** [comment]
I imagined a query indicator or a circular indeterminate:
https://material.google.com/components/progress-activity.html
