### ISSUE TITLE
ctrl-click doesn't work on date links in journal view, account links in journal view, or aside menu

### ISSUE THREAD

**Issue by xentac** [beancount/fava#400]
Similar to https://github.com/beancount/fava/issues/379, it looks like some links were also missed.

Perhaps it'd be a good idea to find all the click event handlers and make sure they support ctrl clicking?

**Comment by yagebu** [comment]
> Similar to #379, it looks like some links were also missed.

This is actually just #379 again, the fix apparently went missing in some rebase.
