### ISSUE TITLE
Reload issues

### ISSUE THREAD

**Issue by yagebu** [beancount/fava#404]
Apparently there are some issues with the page reload after the documents upload.

Seems like the `PUT` requests to upload the file would trigger an update to the file watcher, so that the file check on the reload would, as we were only using 1s precision, think that nothing changed since the upload.

**Comment by yagebu** [comment]
@aumayr can you test if this fixes the issue with reload after uploading a document? On modern file systems, this should be completely fixed and on non-modern filesystems (I'm looking at you, HFS+), there should only be problems in some obscure edge cases (if had you had some independent change to one of the watched files <1s before the upload).

**Comment by aumayr** [comment]
When I drop a file into the folder manually it is picked up and the green reload-icon is shown in the header. (Aside: I don't like the green.)

There is a bug where `data-account-name="..."` is missing in the Account view, therefore the upload goes to "undefined". I fixed this in the `invoices2` branch.

When I drop the file on a tree-table, the change is picked up correctly (despite the non-modern filesystem I'm using 🙈).

**Comment by aumayr** [comment]
Ergo: Fixed 👍
