### ISSUE TITLE
Redesign the "reload" button when changes are picked up in the background

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#405]
(coming from #404)

When a background change occurs (eg. editing the beancount file in an external editor or dropping a file into one of the documents folders and beancount picks that up and inserts a Document directive) a little icon is shown, indicating that the data changed:

![bildschirmfoto 2016-11-01 um 10 09 53](https://cloud.githubusercontent.com/assets/5135450/19884725/6172e19c-a01b-11e6-9b32-467205520ad6.png)

I think that two things should change:

- Get rid of the green. 
- Also show a "notification", like when a file was uploaded through Fava. The notification, when clicked, could also trigger the refresh. 

There is also a bug here: Clicking the green refresh-button does remove any filters set.

**Comment by yagebu** [comment]
> Get rid of the green.

Sure, go ahead.

> Also show a "notification", like when a file was uploaded through Fava. The notification, when clicked, could also trigger the refresh.

The upload already triggers the reload so there's no need to show the icon then.

**Comment by aumayr** [comment]
> The upload already triggers the reload so there's no need to show the icon then.

But for example when the beancount file was changed with an external editor - then the notification should be shown as well.

**Comment by yagebu** [comment]
> But for example when the beancount file was changed with an external editor - then the notification should be shown as well.

I don't quite follow - this is how it works already, isn't it?

**Comment by yagebu** [comment]
Ah sorry I just misread your initial suggestion, ignore my previous comments. A notification sounds good.

**Comment by yagebu** [comment]
It would be nice if this kind of notification would disappear quite quickly automatically as it won't contain any useful information in addition to making a visual notification.
