### ISSUE TITLE
Graph width adjustable?

### ISSUE THREAD

**Issue by matthiasbeyer** [beancount/fava#406]
Hi!

it would be neat if one could adjust the width of a graph... for example if I only select `2016-11` I get (as of today) a graph over three days... which is (for me, with only 5 transactions) not really easy to keep visually track of on a 24" monitor, for example.

If one could shrink the width of a graph down to (for example) 50% of the screen width, this would be way better.

---

Also if I could drag a graph around (for example if I have an account that keeps jumping around at $100 for example) to hide everything below a certain value, that would be great.

**Comment by aumayr** [comment]
Having a max-width per bar in the bar-chart, and calculatibg a max-width for the chart from there, should be trivial. Just number of periods in the chart multiplied by a max-width per bar.

**Comment by Akuukis** [comment]
I would like to contribute this feature. I am first time around FAVA code, and looks like you are using generators instead of JS itself. So can someone point me to right direction where and how to start?

**Comment by aumayr** [comment]
@Akuukis For the Python/Server-side part of Fava have a look at http://beancount.github.io/fava/development.html . 

The JavaScript-part runs through rollup - have a look at https://github.com/beancount/fava/blob/master/fava/static/package.json to see which scripts are built in and can be run by `npm`.

In `fava/static`:
- Run `npn run build` to build the JavaScript and CSS once.
- Run `npm run watch-js` to continuously build the JavaScript when a file is modified. 
- Run `npm run watch-css` to continuously build the CSS when a file is modified. 
- Run `npm run lint` for linting.

**Comment by aumayr** [comment]
@Akuukis Do you need any further help on this?

**Comment by Akuukis** [comment]
@aumayr I am ok, but shouldn't have came forward at my busiest time, because in the end I had to postpone looking into it for a while. Thanks for directions, all set!
