### ISSUE TITLE
Editor: Keyboard shortcut for commenting out a line/selection

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#407]
Add a keyboard shortcut for commenting out the selected lines or the line the cursor is in (if there is no selection).

On a Mac this would be Shift + Cmd + 7

**Comment by yagebu** [comment]
> On a Mac this would be Shift + Cmd + 7

I guess you mean `Cmd`+`/`, that's what Atom and Sublime apparently, or what do you mean by "On a Mac"?

**Comment by aumayr** [comment]
That's what I meant 🙈

**Comment by aumayr** [comment]
Should be trivial: 

* http://codemirror.net/doc/manual.html#addon_comment
* https://github.com/codemirror/CodeMirror/commit/d4f05936c278ea12ff41eb766a1cd9935e37c965
