### ISSUE TITLE
Budgets don't show up

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#409]
@TomJohnZ via Gitter:

> in versions before 1.0, budget amounts would show up in the account tables (for instance the */account/Expenses/changes page). Now I don't see anything there after updating to 1.0. Am I missing something?

**Comment by yagebu** [comment]
You can't have a budget for the Expenses account, right? So it will only show up on the children accounts for which one has declared a budget, I guess.

**Comment by TomJohnZ** [comment]
My apologies, I should have clarified the original issue. I wasn't trying to apply a budget to the Expenses account; that's where (for instance) I was attempting to view the budget output.

To elaborate, fava 0.3.0 correctly displayed the budgets (over/under budget amounts) for my beancount file previously; I would view these balances on the */account/Expenses/changes page. However, on upgrading to 1.0.0, the same beancount file no longer shows any budget information there.

I've tried reinstalling fava and beancount to no avail; even trimming down to a MWE with just one account and two transactions doesn't show any budgets.

I suspect something on my end given how such a bug would presumably affect everyone using budgets, but reverting to v0.3.0 fixes it while upgrading breaks it. Anything I might be missing?
Thanks!

**Comment by yagebu** [comment]
My first comment was before I really looked into this. I thought that maybe the Expenses page shouldn't really show any budgets if the budgets are only for child-accounts. That doesn't make sense though as the child-accounts have their own rows...

There were two bugs in the template that did cause this - thank you for the report! They should both be fixed now and the budgets should work again as expected.

**Comment by TomJohnZ** [comment]
Great, that looks like it fixed it for me as well. Thank you very much! That was incredibly quick :)

(By the way, just wanted to thank you guys for your hard work; fava is an incredibly piece of software!)
