### ISSUE TITLE
journal-show-document options not honored when doing a full reload

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#412]
With the option

```
2016-01-01 custom "fava-option" "journal-show-document" "discovered"
```

if you do a full reload of the Journal, `#statement` will be shown, but shouldn't. Toggling the filter manually does what it should.

**Comment by aumayr** [comment]
@yagebu This is IMHO a blocker for 1.1

**Comment by yagebu** [comment]
Did you implement this in the template?

**Comment by aumayr** [comment]
Yes, and it should work like all the other filters, except it doesn't :-/

**Comment by yagebu** [comment]
> Yes, and it should work like all the other filters, except it doesn't :-/

It seems you did not - the `hidden` class was never set for "statement" and "discovered".

**Comment by aumayr** [comment]
Oh - sorry for the confusion :-/

**Comment by aumayr** [comment]
And thanks for fixing it!
