### ISSUE TITLE
Journal: Show checkmark for transactions that have a statement attached to them

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#413]
Currently one has to display metadata, and go through each line in the Journal to check this. 

I want to display a small grey checkmark on the right side of a transaction to indicate that at least one statement is attached to this line. 

This makes it easier to spot transactions that are missing a statement.

**Comment by yagebu** [comment]
To make this more universal, we could show - next to the posting bubbles - the initial characters of the metadata keys.
