### ISSUE TITLE
rollup does not watch .scss-files

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#427]
Running `npm run dev` in `fava/static` does not watch/react to changes in `.scss`-files. 

@yagebu Do you know how to fix that?

**Comment by yagebu** [comment]
Yes that's an annoying bug in rollup. It seems to be hard to do the copying of fonts with plain sass and rollup allows us to use `postcss-copy` which does it for us. I guess for development running plain `node-sass` without copying the fonts would be fine...

**Comment by aumayr** [comment]
How do you run plain `node-sass`?

**Comment by yagebu** [comment]
I've added `npm run watch-sass` (and renamed `dev` to `watch-js`). If `node_modules` are present, the fonts should probably work too. I've not really tested it though.

**Comment by aumayr** [comment]
Perfect, thanks!
