### ISSUE TITLE
Transaction entry: tags and metadata

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#434]
It would be nice to have input fields to add tags and metadata to a transaction in the input form. 

These fields should ideally be hidden by default, as they would clutter up the UI. 

There also should be a field for uploading documents as statements directly in the form.

**Comment by ngoonee** [comment]
An alternative to input fields is to have reserved symbols on the narration input field (not sure how many people actually use a hashtag in narration for example).

For metadata I guess separate fields would be required. One for the transaction and one for each posting in it. One easy way to represent this would be to have a '...' or similar symbol right at the end of each line (similar to the '+' currently). Then the '+' could be moved to be centered on a new line, which is symbolically clearer (hey, this adds a new posting).

**Comment by yagebu** [comment]
Ref #485.
