### ISSUE TITLE
UI for beancount.ingest

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#436]
I propose the implementation of an UI to expose the features of `beancount.ingest` (http://furius.ca/beancount/doc/ingest):

- Upload a file (a bank statement, XML, CSV, PDF, etc.)
- Let `beancount.ingest`/`bean-extract` (or any other algorithm/program/part/#433 of Fava) try to parse the transactions in this file
- Present a UI with two columns, and per row/transaction in the input file: To the left there is the parsed line(s), and to the right the Transaction-UI with the data that `bean-extract` et al. "understood".

This way parsing a bank-statement would be a straightforward task:

1. Upload the file to this Fava page
2. Check each row and change if needed (you can tab quickly through the input fields and make adjustments, etc.
3. Save them (Fava writes them to your beancount file)

(Previous discussion: https://github.com/beancount/fava/issues/421#issuecomment-263837979)

**Comment by aumayr** [comment]
As a result of step 3 (Saving the new transactions), the original text the transaction was parsed from and the resulting transaction, as adjusted by the user, should be stored somewhere separate, so future imports would 

1) Not display the same (source) transaction to be imported again. This way, the user does not have to be careful to only upload "non-overlapping" files. 
2) Inform the algorithms (#433, etc.) of how the user decided in previous (similar) cases of similar transactions

This would mean that there is a "cache-file" stored somewhere next to the beancount-file, in which the texts/rows/data from the source (XML, CSV, etc.) in connection with the resulting transactions would be stored, in order for the "matcher" to have past data to rely on when deciding how a transaction in the source should be interpreted.

**Comment by xentac** [comment]
#1 is harder than you'd think. Blais has a heuristic that comments out
transactions that it thinks are duplicates. I recommend your form just lets
you comment out and include/exclude lines as you see fit.

I collect my transactions for a single account in a single place, mostly
separated by markdown section comments. Could it also insert the file
contents where I see fit? The only thing that gets appended in my file is
prices.

**Comment by aumayr** [comment]
> 1 is harder than you'd think. Blais has a heuristic that comments out
transactions that it thinks are duplicates. I recommend your form just lets
you comment out and include/exclude lines as you see fit.

It does track lines that have been imported in a separate file, and if previously imported, comments them out. 

> Could it also insert the file contents where I see fit? The only thing that gets appended in my file is prices.

This is not planned at the moment, as it is hard to implement (except the `FAVA-INSERT-MARKER`, which is what it will use.

**Comment by ngoonee** [comment]
> This is not planned at the moment, as it is hard to implement (except the `FAVA-INSERT-MARKER`, which is what it will use.

While I understand that 'location in file' would be hard and require a marker of some sort, surely a dropdown selection of the actual file used would be simple (for those who do multi-file split for accounts).

Also a possible hack is to use `FAVA-INSERT-MARKER-<name>` markers in the input file(s) to generate a list of locations to select from, allowing the user to custom-name them.

**Comment by xentac** [comment]
I like that idea. Having multiple input locations selectable with a drop
down would be fine to put in my file.

**Comment by johannesjh** [comment]
This feature would be awesome, especially in combination with the smart suggestions!! Are you aware of existing implementations? There even exists one tool written in Python.

- [quentinsf/icsv2ledger (written in Python)](https://github.com/quentinsf/icsv2ledger)
- [cantino/reckon (written in Ruby)](https://github.com/cantino/reckon)
- [tomszilagyi/banks2ledger (written in Clojure)](https://github.com/tomszilagyi/banks2ledger)

Maybe some of the code and/or ideas can be reused.

**Comment by yagebu** [comment]
Implemented in #503.
