### ISSUE TITLE
Dependencies in setup.py need updating?

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#437]
Was writing an Arch Linux PKGBUILD for fava and realized the following dependencies (at least) aren't listed in setup.py

google-api-python-client
beautifulsoup4
magic

With those dependencies fava seems to run fine (no complex testing yet as I'm yet to get used to beancount itself). Not sure if there's more required. In any case, setup.py probably needs an update.

**Comment by yagebu** [comment]
These are not dependencies of Fava but only of Beancount (and Beancount does list them).

**Comment by ngoonee** [comment]
beancount seemed to work fine before I installed those though. Now that I check it it's setup.py does mention them, I just hadn't used those imports yet in my cursory testing.

Thanks, sorry for the noise. Will go fix the user-submitted PKGBUILD I was using.
