### ISSUE TITLE
Web input form - Narrow aspect ratio 'creates' trailing posting line

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#438]
When I change the aspect ratio of my browser a spurious posting line appears. Please see image. Note that there should only be 2 posting lines at this point (I didn't click 'add posting').
[Link to image showing the issue, narrower aspect ratio is on the right](https://www.dropbox.com/s/5pqhnxlmsd76z1w/FavaInputDialog.png?dl=0)

**Comment by aumayr** [comment]
This should be fixed in master... can you confirm that this is still an issue after you git pull?

**Comment by ngoonee** [comment]
No longer an issue, thanks.
