### ISSUE TITLE
My fava instance isn't viewable from another device on the same wifi net

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#439]
I can view the instance from my laptop via localhost:5000 but not from another device on the same wifi network.

In case it was my router, I tried doing a hotspot from the phone and then using the phone's browser, no-go.

Pretty sure it's PEBKAC here, but I can't imagine what mistake I might have made. I'm just running "fava ledger.beancount", and I don't see anywhere to configure permissions etc.

**Comment by adamgibbins** [comment]
fava is bound to localhost by default. You need to start it like so if you want it listening to everything: `fava -H 0.0.0.0`

**Comment by ngoonee** [comment]
Thanks, once pointed out it's quite obvious. I tried '-h' but not '--help'....
