### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#440]
Hooks on specific events may be useful. One use-case I can think off is to auto-commit changes to the ledger (with a comment generated from some combination of payee/narration etc.) to <insert vcs of your choice here>.

As with hooks in package managers etc. the simplest form would be an option (maybe 'post-add-transaction-hook') which is normally not set and can be set to the name of an executable script.

Slightly higher level than that would be that the option could be set to the name of a python script. This script would be able to process the transaction and take action based on it.

I would just hack this in to check for the option's existence and call the relevant script (or import/run) if it did. Pretty sure some basic validation would be better. If that's not necessary, however, this would be a really simple add. I'd probably add it at the end of api_add_transaction and api_add_document, since if I'm not mistaken api.file.insert_metadata_in_file and api.file.insert_transaction have no access to the options.

**Comment by ngoonee** [comment]
@yagebu sorry for tagging, but where does 'unplanned' sit on the scale between 'nope', 'maybe next time' or 'PR welcome'?

**Comment by yagebu** [comment]
Good idea! Something like an auto-commit hook after adding a transaction or saving a file would be a neat feature.

It will be quite hard to do it right though, I think. It should work using python imports and there should just be one option for all hooks, which can be given multiple times if needed. Maybe actually having "plugins", which can register multiple hooks, is preferable to having single hooks (a "auto-commit" plugin could have a "add-transaction" and a "file-saved" hook for example).

@ngoonee: I guess the milestones could be more descriptive - "unplanned" is just "won't promise to finish it by the next release". A PR is always welcome :)

**Comment by ngoonee** [comment]
Thanks, that's clear. I don't think fava has plugins (yet) though? I don't have any experience with developing plugins (all that additional overhead code-wise), while a PR for the behavior I described for a quick-and-dirty hook is something I could whip up in a jiffy. If I could just get confirmation that that's okay (i.e. you don't already have half a plugin architecture sitting on a branch somewhere that I should base on) for now?

**Comment by aumayr** [comment]
I quite like the idea of this!

Over at #436 a plugin architecture of some sort is needed as well: One should be able to register a function that determines if it can parse a passed input file (CSV, XML, PDF, etc.), and if it can, will parse the transactions found in the file.

**Comment by yagebu** [comment]
> I don't think fava has plugins (yet) though? I don't have any experience with developing plugins (all that additional overhead code-wise), while a PR for the behavior I described for a quick-and-dirty hook is something I could whip up in a jiffy. If I could just get confirmation that that's okay

Fava doesn't have a plugin architecture yet. I'm against merging a quick-and-dirty solution for hooks - I'm willing to help with the work though. If you provide a PR that does this somehow and some sample hooks ("autocommit" would be nice to ship with Fava), I'll try to put some plugin architecture into place.

**Comment by ngoonee** [comment]
https://github.com/beancount/fava/pull/443

Works for me.

**Comment by yagebu** [comment]
Implemented in #477
