### ISSUE TITLE
New transaction direct link?

### ISSUE THREAD

**Issue by adamgibbins** [beancount/fava#442]
There's no way to link directly to the new transaction screen (nice addition btw, thanks!) without JS shenanigans, so I can't bookmark it on my phone easily. Can we add one?

**Comment by lipidity** [comment]
I believe having a dedicated page for transaction entry would not only solve the above issue, but would also be much simpler to implement without requiring the extensive javascript that the overlay demands. (Progressive enhancement and all that)

**Comment by yagebu** [comment]
Good suggestion, that's definitely something worth adding! I'm thinking of having a `#add-transaction` hash at the end of the URL open it directly.

>I believe having a dedicated page for transaction entry would not only solve the above issue, but would also be much simpler to implement without requiring the extensive javascript that the overlay demands. (Progressive enhancement and all that)

The Javascript that's needed for the overlay per se is negligible, so I don't think it'd make much of a difference.

**Comment by ngoonee** [comment]
Just to note that from a mobile-centric point of view a page is normally preferable to an overlay. Less screen real-estate coupled with not having to load/render the backing page first. The current implementation works just fine though, am already using it!

**Comment by yagebu** [comment]
This is now implemented, adding `#add-transaction` to any URL should open the form.
