### ISSUE TITLE
Language-option does not have any effect

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#444]
I created a new beancount-file:

```
option "title" "Test"
option "operating_currency" "EUR"

2017-01-01 custom "fava-option" "language" "de"
```

I expected the UI to change to German, as the option was picked up by Fava:

![screenshot](https://cloud.githubusercontent.com/assets/5135450/21522256/3bd5201a-cd04-11e6-8ac8-a60173d67b3b.png)

But as can be seen in the screenshot, the language does in fact not get picked up.

**Comment by yagebu** [comment]
Odd, I can't reproduce this.

**Comment by aumayr** [comment]
I made a fresh pythonanywhere.com-account and installed fava 1.2 there. Browser was safari and crome on a Mac.

**Comment by yagebu** [comment]
I guess the problem is that the translations are not listed in the manifest
