### ISSUE TITLE
Filtering Balance Sheet by 2017 (or any year entirely in the future) produces a very weird graph

### ISSUE THREAD

**Issue by xentac** [beancount/fava#445]
No particular input causes the problem, an example file is all that's necessary to reproduce.

It seems like every month loses 5k-ish in value.

No idea what's going on there.

**Comment by yagebu** [comment]
I can't reproduce this at all - the graph just shows the (constant) current net worth.

Is this maybe due to some plugin that you are using?

**Comment by xentac** [comment]
I see the same thing with an entirely stock example file (bean-example), so no plugins there.

The part that makes me think it's a problem with fava is that all the month values are the same no matter which year (in the future) I choose.  2017 looks exactly the same as 2018.  If I span multiple years (2017 - 2018), I see the same slope graphed over a longer line.

I'm trying to create a minimal example, but I can say that a file with a single transaction is not enough to recreate it.  I'll post when I have an update.

**Comment by adamgibbins** [comment]
I'm seeing this too, removing all my plugins doesn't correct. Changing from yearly->quartely->monthly->weekly->daily views all gives different amounts. Daily being the worse, yearly having no change.

**Comment by xentac** [comment]
option "operating_currency" "USD"                                                                                                                    

1980-05-12 open Liabilities:US:Chase:Slate                      USD

2014-01-03 * "Cafe Modagor" "Eating out after work"
  Liabilities:US:Chase:Slate                       -16.77 USD
  Expenses:Food:Restaurant                          16.77 USD

1980-05-12 open Expenses:Food:Restaurant

**Comment by xentac** [comment]
It looks like it doesn't actually have anything to do with the future and instead has to do with the total transaction time.  I didn't see it in my initial test, because it was an opening balance test.  Looks like it has to be a liability that's graphed over time.

I guess we're reapplying the negative accounts every month when calculating the graph, especially if there's no transaction data?

**Comment by yagebu** [comment]
Thank you for the example file, I've found the bug. When running out of transactions, the last one was added again for every interval.
