### ISSUE TITLE
Would there be an incognito mode?

### ISSUE THREAD

**Issue by wzyboy** [beancount/fava#446]
Hi,

Fava is a beautiful web interface to Beancount that I would like to show to more people. However I do not want to censor the actual numbers every time I make a screenshot. `bean-web` has an `--incognito` option which replaces all digits with `X`s. For example, `-123.45 USD` would be shown as `-XXX.XX USD` in incognito mode.

It would be nice that Fava implements a similar feature as well.

**Comment by yagebu** [comment]
Isn't this use-case something that would be better served by running Fava from an example file (which can be auto-generated)?

**Comment by wzyboy** [comment]
Auto-generated example file is somewhat too "fake". The account names, commodity names are "exotic" to my friends. If there is an incognito mode, I could show my friends with localized information (local banks, local companies, local currencies) when demonstrating the features of Fava. :-)

**Comment by blais** [comment]
You're welcome to parameterize the generator script with localized names :-)

**Comment by aumayr** [comment]
I think this should be supported in two ways:

1. A flag when starting Fava, eg. `--incognito`, like beancount already does it.
2. An option in the beancount file itself, as I do want to use this feature, but not restart Fava everytime I want to invoke this.

**Comment by wzyboy** [comment]
> An option in the beancount file itself, as I do want to use this feature, but not restart Fava everytime I want to invoke this.

Nice point. Does Beancount file already support custom option field now? Or this could be done via something like vim modeline (`# fava: incognito:`). Implementing something like a modeline seems like an overkill...

**Comment by aumayr** [comment]
> Does Beancount file already support custom option field now?

Kind-of... They are custom fields, like `2017-01-03 custom "fava-option" "incognito" True`

**Comment by aumayr** [comment]
I have used this feature (with the custom option) frequently, but it is always a pain, because:

1. You want to show Fava to someone, but do not want to show actual numbers
2. You ask him/her to look away, in order for you to edit the beancount file to include the incognito option
3. You show Fava
4. You have to remove the option from your file

What I rather would want to do is start Fava with an ``--incognito`` CLI-flag.

**Comment by wzyboy** [comment]
> What I rather would want to do is start Fava with an --incognito CLI-flag.

The scenario above may be the reason why Martin implement `--incognito` as a CLI flag in bean-web in the first place ;-)
