### ISSUE TITLE
Prices in Holdings View

### ISSUE THREAD

**Issue by johannesjh** [beancount/fava#447]
Given an example beancount file such as this:

```
;; -*- mode: org; mode: beancount; -*-

option "title" "Fava Prices"
option "operating_currency" "EUR"

plugin "beancount.plugins.auto_accounts"

2015-12-01 * "Buy house"
  Assets:Real-Estate  1 HOUSE {350000 EUR}
  Expenses:Real-Estate:Transaction-Costs  10000 EUR ; etwa 10% des Einkaufspreises
  Assets:Cash

2025-01-31 price HOUSE  400000 EUR

2025-01-31 * "Dummy Transaction" ; to make sure the latest price is evaluated
    Assets:Cash  0 EUR
    Income:Real-Estate
```

When I remove the dummy transaction in the above input file, the "Holdings" view in Fava forgets about the new price of 400,000.00 EUR. In other words, the dummy transaction is required in order for Fava to parse the price statement.

Where does this behavior come from? I am not sure if this is rather due to Fava or Beancount. Does this involve some hidden logic which makes the behavior a Feature rather than a bug?

**Comment by blais** [comment]
What period are you selecting?

**Comment by johannesjh** [comment]
Hi Martin,
thank you for your response!

I am not sure about your question. What do you mean by selecting periods? 
Where and how would I do that? E.g., in Fava's web UI? In the beancount file?
Are you referring to the filters above Fava's holdings page? I left those untouched.

I'll attach two screenshots to clarify what I am referring to: 

**A) Holdings view for a beancount file with the dummy transaction:**

<img width="1280" alt="with-dummy-transaction" src="https://cloud.githubusercontent.com/assets/581188/21582376/2ba6316c-d055-11e6-80c9-b9159d8a4f49.png">

---

**B) Holdings view without the dummy transaction:**

<img width="1280" alt="without-dummy-transaction" src="https://cloud.githubusercontent.com/assets/581188/21582389/ae70303e-d055-11e6-9d35-470307fa2a2a.png">

**Comment by blais** [comment]
I'm not so familiar with Fava, but it's possible that the Price directive
gets filtered away if you're looking at a period that doesn't include its
date.
Though in this case if the only difference is the transaction, I'm not sure
why it doesn't get applied.

**Comment by johannesjh** [comment]
I continued to play around with the filters and I found that I have to select the year 2025 in order to see the final price, compare this screenshot:

<img width="1392" alt="screen shot 2017-01-03 at 22 40 19" src="https://cloud.githubusercontent.com/assets/581188/21624132/0f4dadf8-d206-11e6-9f0f-ac58f9836b5d.png">

Is this inconsistent with the other views in fava?, e.g. with the balances view that by default shows the end result of all transactions, not just one year.

**Comment by xentac** [comment]
I think I know why this is.  I was looking at the code around this last night.

https://github.com/beancount/fava/blob/master/fava/api/helpers.py#L26 is used to fill out the holdings tables, called through https://github.com/beancount/fava/blob/master/fava/api/__init__.py#L276.  If you notice, it uses self.date_last to calculate holdings at the last date...

self.date_last is calculated in _apply_filters (https://github.com/beancount/fava/blob/master/fava/api/__init__.py#L183).  It finds the max Transaction, which explains why you need to create a dummy transaction.

Why use the last date and not just get the most recent price always?  My guess is because of the filtering.

I'm not familiar enough with the code to fix this myself, but I hope someone like yagebu or aumayr could fix it from my references.

**Comment by blais** [comment]
It's a choice. You could totally consider other directives in your min/max
date calculations.

**Comment by yagebu** [comment]
Thanks for the report. This should now work correctly (by using the latest price unless a time filter is active). If the time filter is active, I think it's the correct behaviour to also fix the date at which the price is determined to the end of filtered period.

Thanks @xentac for the investigation! The other places where `date_{first,last}` are used are for transactions, so only considering transactions should (now) be the right thing.
