### ISSUE TITLE
Balance sheet display signs

### ISSUE THREAD

**Issue by knoxx093** [beancount/fava#448]
Propose to add options that will flip the signs in the balance sheet display.
Option to show liabilities as positive.
Option to show Equity with same sign as net-worth.
Perhaps Similar options for Income Statement display.

Reason:
It's driving me nuts that my negative net worth is showing up as a positive number.

**Comment by blais** [comment]
On Mon, Jan 2, 2017 at 4:22 PM, knoxx093 <notifications@github.com> wrote:

> Propose to add options that will flip the signs in the balance sheet
> display.
>
That's a very good idea! I've had this on my todo list for bean-web for a
while.
In addition, when this is turned on, I'd recommend indicating to the user
that this feature is turned on by using a slightly different background
color or font for those numbers which have been "adjusted" to be normally
positive, so that one doesn't have to wonder whether it's on or not.


> Option to show liabilities as positive.
> Option to show Equity with same sign as net-worth.
> Perhaps Similar options for Income Statement display.
>
IMHO a single option for all numbers is sufficient.
The implementation is simple: all numbers are associated with an account
anyway: when a number is rendered, flip the sign if the account is either
of Liabilities, Equity or Income.



> Reason:
> It's driving me nuts that my negative net worth is showing up as a
> positive number.
>

**Comment by knoxx093** [comment]
I think a single option would be equally helpful at least for my case. My initial reasoning for providing them separately is that it's apparently not uncommon to show liabilities as negatives. 
The suggestion to provide a visual indicator that this feature is turned on is a great idea as well.

If I had more time I'd attempt a PR for this but I unfortunately don't have much to spare now.

**Comment by aumayr** [comment]
Good idea (initial idea and font-color)!

Maybe, when enabled, show the sign anyway but in a light-gray color so it is visually easier to distinguish (instead of hiding/flipping it completely)?

**Comment by blais** [comment]
The problem with too many options is that it would quickly get confusing.
Don't forget contra accounts, which might make this even more confusing,
that is, accounts whose signs are opposite of the expected ones. A single
option means that there's only two possibilities: either the signs are
flipped, either they're not. If you flip only the Liabilities that would
make Income incoherent.

I'd advise against supporting the full flexibility of enabling arbitrary
flips, even if there's some usage for it somewhere (AFAIK you don't need
it, you mention that "it's not uncommon"; I'd ignore that). Keep it simple.
Start with a single option. See if that fulfills your immediate needs.

**Comment by knoxx093** [comment]
You make a strong case against individuals options. I hadn't considered
contra accounts when making my proposal. I think that on its own is a good
enough reason to avoid separating the options.

On Jan 2, 2017 4:42 PM, "Martin Blais" <notifications@github.com> wrote:

The problem with too many options is that it would quickly get confusing.
Don't forget contra accounts, which might make this even more confusing,
that is, accounts whose signs are opposite of the expected ones. A single
option means that there's only two possibilities: either the signs are
flipped, either they're not. If you flip only the Liabilities that would
make Income incoherent.

I'd advise against supporting the full flexibility of enabling arbitrary
flips, even if there's some usage for it somewhere (AFAIK you don't need
it, you mention that "it's not uncommon"; I'd ignore that). Keep it simple.
Start with a single option. See if that fulfills your immediate needs.






On Mon, Jan 2, 2017 at 4:54 PM, knoxx093 <notifications@github.com> wrote:

> I think a single option would be equally helpful at least for my case. My
> initial reasoning for providing them separately is that it's apparently
not
> uncommon to show liabilities as negatives.
> The suggestion to provide a visual indicator that this feature is turned
> on is a great idea as well.
>
> If I had more time I'd attempt a PR for this but I unfortunately don't
> have much to spare now.
>
> —
> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub
> <https://github.com/beancount/fava/issues/448#issuecomment-270024286>, or
mute
> the thread
> <https://github.com/notifications/unsubscribe-
auth/AAUgk1_nQKsyKHMwnt5nE14-XUvCIz45ks5rOXIjgaJpZM4LZN0k>
> .

>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/beancount/fava/issues/448#issuecomment-270028000>, or mute
the thread

**Comment by duarteocarmo** [comment]
Hey @yagebu! Is this in the roadmap at all? Very interested in this feature 😄

**Comment by yagebu** [comment]
@duarteocarmo: I'm not planning to implement this.

**Comment by AlphaJack** [comment]
@andreasgerstmayr @aumayr many thanks!
