### ISSUE TITLE
Individual account view (journal) - default sort latest on top?

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#449]
Under income statement/balance sheet the current balance/total of each account is shown. Clicking on an account brings up a journal view of all transactions.

Could the sorting default to latest transaction on top? I find myself just always clicking on the sort button as soon as I'm in any journal page.

**Comment by aumayr** [comment]
If we do this, the default sort-order of the main Journal page should be changed as well (so all journal pages are the same). 

What is better:
- Sensible default or
- option?

**Comment by aumayr** [comment]
(For me, I also always have to scroll to the bottom. And the reports my bank sends/displays are ordered newest-first as well.)

**Comment by ngoonee** [comment]
If there's a sensible way to do it which doesn't add another option I think that'd be preferable. That being said I know most accounting software follows strict chronological order, latest at the bottom. Which is not as much of a problem when the page opens up at the bottom, but is for a webpage like this.

A compromise between 'sensible default' or 'option' is for a cookie/session/thingamijig to be set everytime the user selects a sort which remembers the order the user last used, as I don't think that'd change very often.

**Comment by aumayr** [comment]
Scrolling to the bottom via JavaScript initially sounds like a good idea!

We don't use cookies yet, and I don't think that we should start because of this. Many other views allow customization via GET-params, like which filters are activated/deactivated on the Journal page. Maybe we can add the sort-order to the GET-params as well.

**Comment by ngoonee** [comment]
It only sounds like a good idea if you have sensible filters already in
place. Scrolling to the bottom of a 9 year long journal with
multiple-times-a-day transactions is painful on phones =)

**Comment by xentac** [comment]
What about the graph though? That will still be at the top.

**Comment by aumayr** [comment]
Maybe no auto-scrolling, but a keyboard shortcut and button? (Like the "🔝"-button on many websites, but "bottom" instead.)

**Comment by yagebu** [comment]
Seems like most people here would like to see the sort order reversed, which I also wouldn't mind, so that seems like the simplest solution to the problem.

Does anyone prefer the current (default) sort order?

**Comment by aumayr** [comment]
No, I'm also for just reversing it by default.
