### ISSUE TITLE
Add contributions to Beancount to Fava help pages

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#451]
In light of new tools in the Beancount ecosystem like gnucash-to-beancount, add a dedicated section to the help pages that mirrors http://furius.ca/beancount/doc/contrib.

Fava should also contain a better guide on how to use Beancount.

**Comment by blais** [comment]
After I'm done with the intro doc I'll work on automatically replicating
all the GDocs into your beautiful static HTML thingamajig.
Then I'll fix #149.
Then I'll do some cleanups.
Then I'll start a normal release process and christen 2.0.

**Comment by aumayr** [comment]
All the Beancount documentation (what is now in GDocs) naturally lends itself to be integrated into Fava, so all the necessary documentation comes (at least linked-to) with the UI. 

> After I'm done with the intro doc I'll work on automatically replicating
all the GDocs into your beautiful static HTML thingamajig.

I recently came across another documentation based on Sphinx, which had a pretty neat front page. We could use this for the beancount documentation as well: 

![bildschirmfoto_2016-12-12_um_10 19 071](https://cloud.githubusercontent.com/assets/5135450/21671289/ac541e7e-d31a-11e6-870b-bc433b5b33b7.png)

**Comment by aumayr** [comment]
@blais Any updates the 2017-new-year's-resolutions from above? 😇 

> Then I'll fix #149.
> Then I'll do some cleanups.
> Then I'll start a normal release process and christen 2.0.

If this is not relevant anymore I think we should close this issue.

**Comment by yagebu** [comment]
@aumayr: Still interested in adding this help page?

**Comment by aumayr** [comment]
Question is if it should me a mere mirror of the beancount contrib page or out own, maintained version. What do you think?

**Comment by yagebu** [comment]
I think we can start with a short and opinionated list with just plugins that are pip-installable and seem to have some working tests (and then have a link to Martin's document).

**Comment by yagebu** [comment]
This has gotten quite stale. I don't see much benefit in this, probably contributions are better centrally listed in Beancount's document.
