### ISSUE TITLE
Export to Google Spreadsheets for nearly every screen

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#452]
Nearly every screen should have an "Export to Google Spreadsheets"-button. 

When invoked, an overlay asks for the link, name and sheet-name, and then exports the data to Google Spreadsheets. Martin already wrote a lot of code for beancount showing how to export to Google Spreadsheets.

In addition, let the user specify target-Google Spreadsheets-documents via custom fava options, so the mentioned overlay shows them as targets.

What do you think about this feature?

---

Also: Make the print stylesheets better and incorporate the "`label:`"-metadata-field, that replaces the account name with the value of this metadata-field, in order to produce beautiful PDFs of balance sheets or income statements.

**Comment by blais** [comment]
On Tue, Jan 3, 2017 at 2:52 AM, Dominik Aumayr <notifications@github.com>
wrote:

> Nearly every screen should have an "Export to Google Spreadsheets"-button.
>
> When invoked, an overlay asks for the link, name and sheet-name, and then
> exports the data to Google Spreadsheets. Martin already wrote a lot of code
> for beancount showing how to export to Google Spreadsheets.
>
I totally agree.
I could move some of it to a library if it helps.


> In addition, let the user specify target-Google Spreadsheets-documents via
> custom fava options, so the mentioned overlay shows them as targets.
>
> What do you think about this feature?
>
Exporting to Sheets I've completely replace my usage of Google Finance.
It's very powerful and allows me to get rid of a lot of custom reporting
jobs--I just export all the positions to a sheet and do the work in the
spreadsheet. I couldn't recommend it more.

Another kind of integration I'd like to do eventually is IPython notebook,
another very powerful idea.

**Comment by aumayr** [comment]
> Another kind of integration I'd like to do eventually is IPython notebook,
another very powerful idea.

I didn't think of this, but as I use IPython (now Jupyter) notebooks a lot, this totally makes sense! (One step further: Not only getting the data into a notebook with a Python-kernel, but writing our own kernel for BSQL, like the new Query editor in Fava.)

> I could move some of it to a library if it helps.

Yes, it would help a lot. This library could also be home to the IPython notebook support down the road.

**Comment by johannesjh** [comment]
Why not regular Excel or OpenOffice? I am sceptical of tight interweaving with cloud based solutions, especially from companies like Google that make their revenue from the data we give them.

**Comment by adamgibbins** [comment]
Excel + OpenOffice don't have the great Google Finance lookup functions: https://support.google.com/docs/answer/3093281?hl=en

**Comment by johannesjh** [comment]
Alright, agreed. Google does have unique selling points.

Nonetheless, as a word of caution: One motivation for using and improving open source, text-based accounting software is to avoid the big commercial players that want to make profit of  personal payment data, such as Quicken or Mint. I bet many users are motivated by similar thoughts.

I suggest that users should be able to configure (and optionally disable!) integrations with third party players. Are you planning on making the feature opt-in or opt-out? 

Enabling the feature by default has many advantages, e.g. this would greatly increase the feature's discoverability. But in this case, Google should not be made aware of the installation or user prior to first use.

**Comment by blais** [comment]
On Mon, Jan 16, 2017 at 3:52 AM, johannesjh <notifications@github.com>
wrote:

> Why not regular Excel or OpenOffice?
>
Those work too, but if you have CSV you're pretty much already there.
The reason I've used Sheets is that there are then no manual steps to
publishing, and you can build interactive dashboards that feed live stock
market quotes. Very convenient.

**Comment by alexjj** [comment]
Exporting the current view to CSV would be a nice feature. Straight to Google sheets is nice but not everyone uses it and perhaps CSV is a nice intermediate.

**Comment by pfrancois** [comment]
why not putting this export as a plugin that could be enabled ?

**Comment by aumayr** [comment]
Ref #630

**Comment by redstreet** [comment]
Echoing johannesjh's comment above. Tight integration of an open source software with a commercial cloud vendor raises serious privacy concerns.

Making such a feature strictly opt-in would decrease these concerns. Ensuring there's no way to unintentionally click a button and have a Google sheets open up would be good, particularly given many users typically stay logged in to a Google service in their browser.

If feature discoverability is a concern, an opt-in/out button could be made visible by default until the user has chosen.

**Comment by yagebu** [comment]
I'll close this issue since there's not been any activity on it for a couple of years. For me, just copy-pasting query result tables works well enough, via the csv we have another option to export query results. If someone wants to work on more elaborate export options, feel free to restart the discussion :)
