### ISSUE TITLE
Filtering by time displays different net worth lines than unfiltered views

### ISSUE THREAD

**Issue by xentac** [beancount/fava#453]
I have two operating currencies (USD and CAD), this may be contributing.

Looking at an unfiltered net worth graph vs. a filtered one for the same time period gives similarly shaped graphs with different total amounts.

I will try to create a minimal example, but I think I need a few months worth of data... we'll see.

**Comment by xentac** [comment]
I have narrowed this down to the way we calculate net worth at particular dates: https://github.com/beancount/fava/blob/master/fava/core/holdings.py#L184

Turns out that the summarizing code does take into account unrealized transactions, but this net worth code doesn't.  That's why filtering changes the apparent values.  I'm pretty sure the correct way to do this is to drop the FLAG_UNREALIZED check in this case.  The original code was probably copied from the holdings function which correctly ignores unrealized transactions (because the unrealized values are displayed as market value).

Given that this method looks to exist only for displaying the balance chart, I'm going to write a patch to remove the filter.

**Comment by blais** [comment]
So this problem highlights a flaw in Beancount: The idea of materializing
unrealized gains into transactions was probably a mistake.  It fails when
materializing gains at different points in time and it causes the need to
filter those here and there. TBH, it was a bit of an experiment; I wanted
to see if I couldn't keep the reporting code as simple as possible by
converting the flow of transactions in this way, but I think it causes too
many problems.

It seems it would be easier to always do the conversion to market value at
reporting time. Reports that care about market value would explicitly have
to make the conversion when necessary, at the desired date, and I should
add functions to make that super easy (underway in branch "conversions").

Perhaps in the interest of avoiding confusion I should remove the
unrealized_gains plugin?
Any thoughts?

**Comment by xentac** [comment]
Like I had mentioned in the other thread, I agree with the eventual goal
and I still plan on working on it. Until that point I'm going to keep using
my unrealized gains plugin ;). To fix the immediate problem I'll write the
patch, but I do agree more and more that the unrealized plugin probably
isn't best.

**Comment by yagebu** [comment]
Ref. the discussion in #467 - It seems to me that adding unrealized gains at the end of the reporting period is still fine and that the issue here was monthly unrealized gains which `summarize` mangled (as it didn't expect to have to deal with unrealized entries).

@xentac: Without your monthly unrealized plugin, do the net worth charts still look different?

**Comment by xentac** [comment]
Without the monthly unrealized plugin the net worth charts are identical.  This issue is explained.  The solution is to stop using the periodic unrealized plugin ;)
