### ISSUE TITLE
PyPI: "fava" vs "beancount-fava"

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#454]
A few months back, before the first version of Fava was released on PyPI as `beancount-fava`, I contacted the owner of the PyPI-package `fava`, as the name was already taken but showed up as not-actively-used. 

He did not respond, until now.

He transfered the ownership of `fava` on PyPI to me, and now it is possible to publish the package as `fava` instead of `beancount-fava`.

Do we want to rename the package to `fava`?

**Comment by blais** [comment]
On Tue, Jan 3, 2017 at 2:46 PM, Dominik Aumayr <notifications@github.com>
wrote:

> A few months back, before the first version of Fava was released on PyPI
> as beancount-fava, I contacted the owner of the PyPI-package fava, as the
> name was already taken but showed up as not-actively-used.
>
> He did not respond, until now.
>
> He transfered the ownership of fava on PyPI to me, and now it is possible
> to publish the package as fava instead of beancount-fava.
>
> Do we want to rename the package to fava?
>
Your call of course, but I think it makes sense.

**Comment by yagebu** [comment]
I'm all for it 👍

**Comment by aumayr** [comment]
I'm for renaming as well. 

So what is the game plan when renaming a PyPI package? Uploading a last version to the original package name, in it adding a big red banner to Fava that announces the rename, and then release every subsequent version under the new name?

**Comment by yagebu** [comment]
Doesn't seem like PyPI does renaming. What I would do:

- Rename the project and upload 1.3 as `fava`.
- Add a dummy release to `beancount-fava` (maybe as 1.2.1). I don't think we need to announce the rename at PyPI in a previous release and I think making the switch directly is fine. This dummy package could just contain a small script that prints out a notice about the rename.
