### ISSUE TITLE
Stored query fails with caps or spaces in title

### ISSUE THREAD

**Issue by jdrueke** [beancount/fava#459]
Fava queries defined in beancount file fail if the title contains upper case letters or spaces.

For example, this query fails
2016-05-03 query "Chase Cleared" "
SELECT sum(position) WHERE account ~ 'Liabilities:Credit:Chase' AND flag = '*'
"

But this query succeeds
2016-05-03 query "chase_cleared" "
SELECT sum(position) WHERE account ~ 'Liabilities:Credit:Chase' AND flag = '*'
"
Thanks for your help.

**Comment by xentac** [comment]
This used to work.  I think the bug was introduced when query history was added.

**Comment by yagebu** [comment]
This works for me in the shell (when quoting the query name, which is also required in `bean-query`), however the download fails.

**Comment by yagebu** [comment]
Thank you for the report! The queries in the sidebar links are now quoted and the query download should properly deal with it too. Can you confirm that it works now?

**Comment by jdrueke** [comment]
Works great!  Thanks for the quick response.

BTW, I've been using beancount/fava for our household accounting since 
April 2016 and have all of 2016 transactions entered.  It is excellent!
