### ISSUE TITLE
Deploy the master-version to pythonanywhere

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#461]
With recent changes it is possible to install from `master` to pythonanywhere.com (aka `favadev.pythonanywhere.com`). 

Helpers:
https://help.pythonanywhere.com/pages/Node/ => "Using NVM to get the most updated version of node".

**Comment by ngoonee** [comment]
I'm doing this myself on a live fava instance of my own accounts, so yes it works =)

**Comment by aumayr** [comment]
@ngoonee I used the hints you gave in another issue (or was it on the mailinglist?) to do this myself yesterday as well - thanks for that!

**Comment by aumayr** [comment]
What would be awesome if the different branches/PRs could be deployed automatically as well, so people can test what ideas we prototype at the moment without requiring them to install everything themselves.

**Comment by ngoonee** [comment]
Mailing list. Pretty sure for long-lived branches that'd be easy, but for temporary branches it probably would need a paid account (I don't have that), since at th e minimum we'd need multiple hosts.

**Comment by aumayr** [comment]
You could be fancy and start each branch in it's own virtualenv and on a different port, and then have an index page with links to the different branches (ports).

**Comment by yagebu** [comment]
Are you still planning to work on this @aumayr?

**Comment by aumayr** [comment]
Lost the thread on this - will pick it up this week, thanks for the reminder!

**Comment by aumayr** [comment]
Done - see #570.
