### ISSUE TITLE
Add thousands to numbers in chart tooltips

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#463]
Is it possible to add thousands separators to numbers shown on the chart tooltips? Example from fava.pythonanywhere.com:

![image](https://cloud.githubusercontent.com/assets/691755/21753120/a78387b8-d59a-11e6-894c-2a3bbcbb1edb.png)

**Comment by xentac** [comment]
Originally there was a render_commas beancount option that controlled this.

**Comment by yagebu** [comment]
Thanks @xentac, good point! Will adjust the Javascript to respect the option.

**Comment by xentac** [comment]
Ok, I'm a bit confused.  What I was saying is that my charts had commas in them already, I thought because I enabled the render_commas option in my beancount file.

Now with your changes, my charts no longer have commas...

**Comment by yagebu** [comment]
> What I was saying is that my charts had commas in them already, I thought because I enabled the render_commas option in my beancount file.

No that can't really be, the `render_commas` option was ignored in JS, so before 245a7d5 thousand separators were never shown.

> Now with your changes, my charts no longer have commas...

Yes, it was missing the change in the template.

**Comment by xentac** [comment]
I promise that something was adding commas to my charts.  I verified it (on my phone anyway) right before I made my initial replies.  I could convert back to my older image and give you a link to my site if you like.

I don't know how it was happening, but I know that it was.

I just noticed that it still shows with commas on my phone, but no commas on my desktop (with 07191c8).  Weird...

**Comment by yagebu** [comment]
That's quite odd, maybe a browser bug (or one in d3-format).

Should work consistently now.
