### ISSUE TITLE
Better Assets / "Net worth" reporting

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#464]
In #129, it was stated that balance summaries should be based on book value, not market value. This covers the account standpoint. However, in addition, a net worth reporting standpoint is useful to answer such question as:

- What is the current state (market value) of each of my accounts? (#129 also asks this)
- How are my assets spread across {accounts, currencies, lots} based on market value?

The holdings page shows the basic data on this. Minor extensions (#462) would make it better, but what would be really useful is to have a version of the treemap and sunburst charts for better net worth reporting. Perhaps as a start, the "Holdings by Account" and  "Holdings by Currency" would benefit from these two charts.

Anyone else have thoughts on this?

**Comment by xentac** [comment]
My plan was to add a market/cost toggle to the balance sheet, so that
balances could be calculated and displayed with the graph there. I just
haven't had time to write any of it.

**Comment by redstreet** [comment]
@xentac that sounds like a good idea, and covers all the basic net worth info.

**Comment by xentac** [comment]
Given the discussion in https://github.com/beancount/fava/pull/467, my current plan forward is to create new pages that display market value.  One "Market Balances" page similar to the "Balance Sheet" but only displaying market values and two new links in the account journal that calculates market value for Changes and Balances.

**Comment by xentac** [comment]
Consider https://github.com/beancount/fava/pull/468 my first attempt.  I picked some random variable names (like conversion being either 'cost' or 'market').  It should cover my use cases though.

**Comment by yagebu** [comment]
The 'cost/value' select is now implemented (#504)
