### ISSUE TITLE
Password to access (as an additional option in the beancount file probably)

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#465]
As someone running fava off pythonanywhere I'd like a built-in password solution in fava, as the popup password box pythonanywhere does can't be auto-filled, so it annoys my wife =)

**Comment by aumayr** [comment]
At least for me (on a Mac/Safari) the pythonanywhere-password-prompts (as it is simple Basic Auth I guess) are auto-filled.

**Comment by ngoonee** [comment]
Oh on real computers that's not too hard, but smartphone browsers (at least Chrome on Android) aren't as capable of that I think. At least in my experience.

**Comment by yagebu** [comment]
As Fava supports multiple files at the same time, having it as an option in the file is not the way to go IMO. Really as this depends on the deployment of Fava as well, the easiest way to do it should be to use (in your WSGI script that start Fava) some WSGI middleware that allows for whatever sort of authentication that you want.
