### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#469]
@mkaito in #411:

> Beancount and Fava look like something I'd love to try at home. But for my wife to use the web interface, it needs to be in Spanish. There seems to be some work done regarding i18n in Fava, which is great. I'd be happy to contribute a Spanish translation of the interface, given some time. Did you guys ever set up that poeditor.com thing, or should I go to town on the mo/po files?

I did set up poeditor.com just now. I can add you as a contributor - what is your poeditor.com username/email?

**Comment by aumayr** [comment]
@corani Would you/your wife provide a Chinese translation (via poeditor.com) as well?

**Comment by aumayr** [comment]
@fokusov Do you want to have access to poeditor.com as well?

**Comment by fokusov** [comment]
> @fokusov Do you want to have access to poeditor.com as well?
@aumayr  Yes, of course

**Comment by corani** [comment]
> @corani Would you/your wife provide a Chinese translation (via poeditor.com) as well?
I can certainly check 😄 At the least I can provide a Dutch translation.

My username is the same as here.

**Comment by aumayr** [comment]
@fokusov @corani @mkaito You can contribute with this link: https://poeditor.com/join/project/TlraSxOCxt

> At the least I can provide a Dutch translation.

If you are serious and think this is a good idea you can request the new language at the link above.

**Comment by mkaito** [comment]
@aumayr I'm trying to sign up for poeditor, but they seem to have an issue with their mail delivery. Will post here once I'm able to sign up.

**Comment by mkaito** [comment]
The confirmation mail eventually arrived. I've joined the Fava project on poeditor.com, but can't seem to do anything. I'll check back tomorrow and get translating as my time allows.

**Comment by mkaito** [comment]
Seeing that poeditor.com doesn't want to let me work, I've started working directly on the .po file in the repository. Chances are, emacs' po-mode is more convenient than some online editor anyway. I'll file my work in a pull-request.

**Comment by yagebu** [comment]
@mkaito: It needed approval of your request to be a contributor at poeditor.com (which I've just done). Can you try now?

**Comment by mkaito** [comment]
That appears to have done the trick. Would poeditor.com then be the preferred way to contribute a translation or part thereof?

**Comment by yagebu** [comment]
> Would poeditor.com then be the preferred way to contribute a translation or part thereof?

Yes.

**Comment by mkaito** [comment]
I'm done. Someone with more knowledge of accounting jargon in Spanish might find a few mistakes, but it'll do. There's two fuzzy entries that I'm not sure about. Maybe when I see them in context.

**Comment by aumayr** [comment]
Perfect, thanks!

**Comment by mkaito** [comment]
I feel like there are things in the interface that were not in the translated strings. Let me know if you do another pass at the source and mark up additional msgids.
