### ISSUE TITLE
Horizontal scrollbar is always present now

### ISSUE THREAD

**Issue by xentac** [beancount/fava#473]
It looks like some padding or something got messed up and now the aside area always scrolls left to right regardless of the size of the window.

**Comment by aumayr** [comment]
I cannot confirm this on current `master` - on which page are you seeing the scrollbar?

**Comment by yagebu** [comment]
I can reproduce this, it seems to be due to `width: 100vw` being set on `body`. @aumayr seems like you changed it to that value, can you remember why?

**Comment by aumayr** [comment]
I added this in https://github.com/beancount/fava/commit/8d097c0377c35d350ec8c7dae62ddffcb6f8917e when I styled the transaction form. As far as I remember this was because the overlay needs to be full-width on mobile.

**Comment by yagebu** [comment]
The overlay sets a width of (100vw - 20px), I don't think setting a width on the body is necessary. Will be removed in #475.

**Comment by yagebu** [comment]
(removed the offending scss, if this creates a problem on some mobiles, I guess it could be added back scoped in a media query)
