### ISSUE TITLE
FAVA-INSERT-MARKER vs default-file for multiple instances on single set of files

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#480]
I'm trying to get something slightly convulated going on...

My objective is to have a single set of accounts (distributed over various files) accessed by two fava instances. Both fava instances should have the same total accounts, but default to entering (via editor and the new transaction entry method) info to different files.

So I'd have:-

EntryForA.beancount  # Fava Instance A should edit/insert transactions here
EntryForB.beancount  # Fava instance B should edit/insert transactions here

And both fava instances should show all transactions in both beancount files (as well as some others, but that's just a matter of importing the right files somewhere).

What I've tried:-
EntryForA.beancount
    2000-01-01 custom "fava-option" "default-file"
EntryForB.beancount
    2000-01-01 custom "fava-option" "default-file"
BaseA.beancount
    include "EntryForB.beancount"
    include "EntryForA.beancount"
BaseB.beancount
    include "EntryForA.beancount"
    include "EntryForB.beancount"

This works fairly nicely for the editor, it will open to the last included beancount file (which by messing around with include orders, is exactly what I want).

Unfortunately putting FAVA-INSERT-MARKER in both EntryFor{A.B}.beancount files doesn't work as the search process just finds the first one it can (and hence always returns EntryForA.beancount which is alphabetically ahead).

What DOES work (but gives a duplicate import error) is the following:-
EntryForA.beancount
    include "EntryForB.beancount"
EntryForB.beancount
    include "EntryForA.beancount"

fava instaces run against EntryFor{A,B}.beancount do input their transactions in the right file, both for editor and the new transaction entry method. However that error leads me to believe this hack is not likely to work eventually.

Any ideas?

**Comment by yagebu** [comment]
Would this be addressed by #481? If not, can you give some motivation for your setup?

**Comment by ngoonee** [comment]
Yes I think that would do, in a more fine-grained and possibly less convenient way.

My primary motivation in running two Fava instances is to be able to differentiate between transactions entered by my wife and by myself. The roughest solution which I was looking at above is for our transactions to be recorded into different files (I'd later organize things appropriately, or not, depending on how anal I feel at the time). As we share joint accounts and credit cards, this would allow me to quite precisely estimate spending patterns on a per-person basis without the hassle (and error prone-ness) of having something like extra sub-accounts like Assets:OurBank:CreditCard:PersonASpending

Also she tends to make mistakes in entering data (leaving out the currency, debit instead of credit, etc. so this eases my job of fixing that.

That being said the linked proposal would be workable as well, more generalized.

**Comment by blais** [comment]
On Tue, Jan 17, 2017 at 1:44 PM, Ng Oon-Ee <notifications@github.com> wrote:

> Yes I think that would do, in a more fine-grained and possibly less
> convenient way.
>
> My primary motivation in running two Fava instances is to be able to
> differentiate between transactions entered by my wife and by myself. The
> roughest solution which I was looking at above is for our transactions to
> be recorded into different files (I'd later organize things appropriately,
> or not, depending on how anal I feel at the time). As we share joint
> accounts and credit cards, this would allow me to quite precisely estimate
> spending patterns on a per-person basis without the hassle (and error
> prone-ness) of having something like extra sub-accounts like
> Assets:OurBank:CreditCard:PersonASpending
>
> Also she tends to make mistakes in entering data (leaving out the
> currency, debit instead of credit, etc. so this eases my job of fixing that.
>
In my experience this kind of setup is best served by sharing a template
Google Sheets doc with your partner and having her add rows in there.
That's worked best for me in the past, especially if your partner isn't
detail-oriented. You can then save and convert to Beancount format at your
convenience, and remove the imported rows.

Just my 2c,

**Comment by ngoonee** [comment]
I hear that, but it's advantageous for me to have her see the system as the graphs are helpful to indicate to her how things are going. Also a google sheet doc means she won't be able to check if her own accounts are accurately updated (current balance).

**Comment by yagebu** [comment]
Running several instances of Fava on the same files and have them behave differently is not something I ever want to support. Should be possible to do this via an extension.

**Comment by ngoonee** [comment]
Thanks, that's fine.
