### ISSUE TITLE
Better transaction-insertion

### ISSUE THREAD

**Issue by yagebu** [beancount/fava#481]
Currently, Fava determines where to insert a transaction in a less-than-ideal way. It abuses the insert marker, which is really only intended for the editor as it's a per-file setting whereas transactions are always inserted globally. Also, it doesn't allow one to insert transactions for different accounts in different places.

One way I've thought we could solve this would be to provide a new option, say `insert`, which can be a regular expression for an account name. When inserting a transaction, Fava would then go through the postings in reverse order<sup>[1](#footnote-1)</sup>, and try to match the `insert` regular expressions.

For example if I had two insert fava-options, one with `Assets:Cash`, the other with `Liabilities:CreditCard`, transactions for those two accounts would be inserted above the respective options.

I don't know how others order transactions in their files, would this approach be flexible enough? Alternatively we could try to determine the file positions completely algorithmically, but I don't see an easy way that's flexible enough to do it.

1<a name="footnote-1"></a>: I don't know if this is a convention for Beancount too, but in ledger the "source" account is contained in the last posting, which for me at least is the most relevant account for determining the position.

**Comment by aumayr** [comment]
> I don't know how others order transactions in their files, would this approach be flexible enough? 

I also sort the postings this way. What I don't quite get is how this option would look like - could you provide a short example? Is this a comment like the current insert marker?

If this is a `custom` directive, then it would have a date, which is not really relevant (and quite confusing), as the _position_ in the file would be relevant, where otherwise only the _date_ of the entry is relevant (one of the positive aspects of Beancount, IMHO, is that the ordering in the file does not matter).

**Comment by adamgibbins** [comment]
I place all my transactions in one file, until I get around to automating the import of that account at which point I move it out into its own (as it's easier to compare then with new imports etc). I'm unlikely to ever use the add transaction feature to add transactions in their final resting place - it's likely to be "quick, get it recorded" type entries which I'll then follow up on and move before committing. So I'm perfectly happy with having the ability to write to a scrap/scratch file or similar.

**Comment by yagebu** [comment]
@aumayr: I'd imagine this as a `fava-option`. Since the date is irrelevant for *all* our options and we're already using the position in the file for the `default-file` option, I don't see why this would be an issue here in particular. The following example would lead to all transactions to subaccounts of `Assets:Cash` being inserted above the option (if that's the first regex they match).

    2000-01-01 custom "fava-option" "insert" "Assets:Cash:.*"

**Comment by ngoonee** [comment]
I think such options would normally go to the top of the file (I think of them as headers), where they're less confusing. That would not be the case here though. A comment like the insert-marker would be preferable for me (I understand there's a higher chance for mistakes here though). Something like

`; ACCOUNT-INSERT Assets:Cash:.*`

**Comment by yagebu** [comment]
I went with the custom option in #530. Beancount already has a well-defined grammar so using comments instead would be quite a hack IMHO. Also, the dates are actually useful as they allow prioritising if multiple options match (and entries can be split by date).

**Comment by ngoonee** [comment]
Thanks, gave a comment on the PR.
