### ISSUE TITLE
Make Query page more attractive

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#483]
Although I quite like the new look of the Query page, some parts are missing:

- There are no examples
- When viewed the first time, it is not really obvious what to do (at least a `placeholder="..."` on the input would help)

![screenshot2](https://cloud.githubusercontent.com/assets/5135450/22163976/7decfbe0-df55-11e6-9ee5-cb1ca4f87cb3.png)

A screenshots from the old version for comparison:

![screenshot3](https://cloud.githubusercontent.com/assets/5135450/22163996/8de5bee2-df55-11e6-8294-c73076a33348.png)
 

- When viewing the results, the download-button (CSV, etc.) is on a easily-overlooked position IMHO
- The styling of the query-history is broken when multi-line queries are displayed

![screenshot1](https://cloud.githubusercontent.com/assets/5135450/22163989/842277c4-df55-11e6-9fa6-b632f217d2da.png)

**Comment by yagebu** [comment]
I've fixed the bugs and added a placeholder pointing out the 'help' command.

I disliked the examples on the query page, weren't that helpful really and added visual bloat to the page. Putting all focus on the interactive query input and the help command should actually help user write useful queries quicker.

> the download-button (CSV, etc.) is on a easily-overlooked position IMHO

That's exactly how it should be IMHO - it's easily spottable but once you know it's there it doesn't get in your way and doesn't distract you from the actually useful data - the query and the result table.
