### ISSUE TITLE
Key/value pairs as labels

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#486]
This is a very low priority feature request. I see my key/value pairs showing up as labels:

![image](https://cloud.githubusercontent.com/assets/691755/22277911/4d6ad8c6-e274-11e6-97d8-cc433a14ce8b.png)

This is great. Could the hover text on these labels be made to show the key/value pair? Thanks!

**Comment by aumayr** [comment]
This should already be implemented here: https://github.com/beancount/fava/blob/master/fava/templates/_journal_table.html#L220

Are you running on `master`?

**Comment by yagebu** [comment]
Duplicate of #455. And already implemented.

**Comment by redstreet** [comment]
Thanks @aumayr. I'm behind master, which explains.
