### ISSUE TITLE
Show budget amounts in graphs

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#489]
Right now budget information is shown under the "Changes" or "Balances" tabs/tables, which shows how much over/under budget a category was.

Also, the budgeted amount is plotted in the 'Changes' graph.

There's no (AFAICS) current way to show the total budgeted amount of each time period. To avoid further cluttering the "Changes" and "Balances" tables, I propose that the mouseover/tooltip of the graph which currently shows

XXXX USD
Jan 2017

be expanded to show

XXXX USD
(YYY USD budgeted)
Jan 2017

or

XXXX USD / YYY USD
Jan 2017

**Comment by aumayr** [comment]
I don't know if this information is available in the charts - if yes, this change is easy to make!
