### ISSUE TITLE
custom/budget entries do not show

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#491]
Whether the 'custom' and/or 'budget' selectors are active or not does not change anything in journal view. Budget entries still do not show in the journal. The correct budget amounts do show under 'Changes', both the graph and the tables.

**Comment by yagebu** [comment]
I can't reproduce this, can you provide an example file?

**Comment by ngoonee** [comment]
Even the most basic one shows the same behaviour. Clicking 'custom' or 'budget' doesn't do anything, while clicking 'open' does show the account open entry on 1st January.

;; -*- mode: org; mode: beancount; -*-
* Options
option "title" "My Accounts"
option "operating_currency" "MYR"

2017-01-01 open Expenses:Expenses MYR
2017-01-01 open Income:Income MYR
2017-01-02 custom "budget" Expenses:Expenses "yearly" 1000 MYR

2017-01-03 * "" "Test"
    Expenses:Expenses 100 MYR
    Income:Income

**Comment by yagebu** [comment]
The Journal shows the budget entry for me. There was a problem with the toggle that I just fixed but even before the entry would show...

**Comment by ngoonee** [comment]
Sorry, what I meant is the individual journal for the Expenses account.

So under the Income Statement page, click on the lower 'Expenses' (the sub-account). There is an 'Account Journal' (default view) which does not show the custom/budget entries.

**Comment by yagebu** [comment]
Ah I see. `custom` entries don't have an account, so they can't be shown on the account Journal.

**Comment by aumayr** [comment]
Maybe we should show the `custom "budget"`-entries in the account Journal, as this is the expected behaviour.

**Comment by ngoonee** [comment]
Yeah, since from a usability point of view the user does specify one (and only one) account for the budget to apply to.

Ideally it would show at the beginning of each period mention, so a weekly budget would show everytime a monday comes around.

**Comment by yagebu** [comment]
Custom entries are now (be8b25d2bee21313f8d8a0d4726f96317aaee122) also filtered by any accounts their values might contain.
