### ISSUE TITLE
Limit transaction input form to only open accounts

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#492]
Filtering out closed accounts makes sense, especially for those with many legacy accounts (old promotional savings accounts or expenses accounts for a previous place of work) in their ledger.

**Comment by yagebu** [comment]
This would require us to ship two completion lists, so I'm not sure it's worth the effort as #505 should actually address this mostly - old and inactive accounts will be pushed to the bottom of the suggestion list so they shouldn't distract much.

**Comment by ngoonee** [comment]
Agree that that's a superset solution to the issue raised here.
