### ISSUE TITLE
wrong balance

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#493]
i found a problem.
if i have the attached file,
the last balance seem wrong. it should be 0 and not 154.08

[test.zip](https://github.com/beancount/fava/files/746511/test.zip)

**Comment by blais** [comment]
The balance of what?
Your question is not specific enough.

**Comment by pfrancois** [comment]
as i said, with the file attached above, I found a problem.
if i take the account journal in fava of this and sort it from old to new,, we have a problem that show on the last column that is called balance, the wrong order.
even if beancount show that the balance is ~0 eur, fava show +154 eur, it is because the two last lines are permuted and they should not.

**Comment by pfrancois** [comment]
I try to minimise the file.

> option "operating_currency" "EUR"
option "booking_method" "FIFO"
option "booking_algorithm" "FULL"
2001-01-01 open Assets:Titre:PEE:Cash
2001-01-01 open Assets:Titre:PEE
2001-01-01 open Assets:Banque:BANK
2001-01-01 commodity PEEA
2002-05-28 * "tr1"
    Assets:Titre:PEE:Cash    70 EUR
    Assets:Banque:BANK  -70 EUR
2002-05-28 ! "tr2" 
    Assets:Titre:PEE                      1 PEEA {70 EUR}
    Assets:Titre:PEE:Cash                -70 EUR
2004-01-01 balance Assets:Titre:PEE:Cash          0 EUR`

i found the problem.
it is not a problem about the balance. it is a problem about the sorting.
by defaut, the account journal show in the reverse chronological order (from the new to the oldest). 
so
1) the balance operation
2) tr2
3) tr1

but if i click to have the chronological order, i don't have it.
if have 
1) tr2
2)tr1
3) balance

and the problem is in balance column, we have wrong column.
![capture](https://cloud.githubusercontent.com/assets/421310/22629825/fc272edc-ebed-11e6-8715-c1f7f13d9c06.PNG)

the line of tr2 (in the case of the picture) should have balance of -70
the line of tr1 should have 0
the problem is fava don't recalculate the balance when we two transaction a the date.

**Comment by yagebu** [comment]
All the balances that are displayed are correct - the problem is just that only sorting by date doesn't necessarily result in the same order that we rendered them in.
