### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by johannesjh** [beancount/fava#495]
Thanks for improving the Makefile, but I am having a few issues:

- `rollup -C` now throws an error when building the static ressources, 
see this log output: [log.txt](https://github.com/beancount/fava/files/749158/log.txt)

- Also, I think the following command should be added to the Makefile's `clean` target:
`rm -rf fava/static/gen`
Otherwise `make clean all` does not execute `npm run build`.

- And, more on a sidenote, `binaries` should be a PHONY target, right?

**Comment by yagebu** [comment]
> rollup -C now throws an error when building the static ressources

Can't reproduce this. How did you run it?

> Otherwise make clean all does not execute npm run build

Why should it? If the generated code is uptodate why rebuild it?

> binaries should be a PHONY target, right?

Sure, doesn't really matter though since no file of that name exists.

**Comment by yagebu** [comment]
> Also, I think the following command should be added to the Makefile's clean target:
rm -rf fava/static/gen

The current clean is more of a "save space" not completely in line with a standard `clean` maybe. I guess both kinds of targets are useful.

**Comment by johannesjh** [comment]
Regarding rollup -C:
The error with rollup -C happened twice yesterday. But I can't reproduce it anymore. All the better ;-)

Regarding `make clean`:
I expected that clean would allow me to do a fresh build, e.g. to reproduce an issue or to test if changes build correctly.

**Comment by yagebu** [comment]
> I expected that clean would allow me to do a fresh build, e.g. to reproduce an issue or to test if changes build correctly.

`make clean` shouldn't be necessary in that case, if the files change, `make` will re-generate them.

Will change the make targets to be a bit more in line with GNU standards anyhow.
