### ISSUE TITLE
Would love to import Gnucash file

### ISSUE THREAD

**Issue by christopherlam** [beancount/fava#496]
Reviewing the data structures between beancount and gnucash, I think there is a fair bit of overlap. There is a nice gnucash XML import library which can directly read Gnucash XML files and expose accounts, transactions, splits and slots:
https://github.com/jorgenschaefer/gnucashxml

Could the developer point me towards the correct file to hack at it? It would be mainly for my personal use to start with.

**Comment by aumayr** [comment]
There are already some tools for, and threads about, translating gnucash to beancount, see the mailinglist for example: https://groups.google.com/forum/#!searchin/beancount/gnucash%7Csort:relevance

Are the tools mentioned there what you wanted to implement?

**Comment by christopherlam** [comment]
Agree I've used these translation tools successfully, however, with this
library I think we can directly access a Gnucash .XML file without using
command-line -- If this is difficult I wouldn't expect developers to add to
main; but I'd be keen to hack it in my own repo. I'd do it via an in-memory
.beancount representation (string?).

There's nothing more satisfying to a Gnucash user than to click File>Save,
and immediately flick to fava in Firefox and run a custom report. Some of
us are tired of using arcane tools after every save to access a custom
report.

So... in this repo where does fava actually load the .beancount journal?

**Comment by aumayr** [comment]
Ah now I understand it - this sounds like a good idea!

The way to go I think is adding this feature as a command line flag, specifying the gnucash-file to use. The script would then convert it to a temporary beancount file and feed that to Fava. 

What do you think @yagebu ?

**Comment by yagebu** [comment]
What you are proposing sounds quite like what https://github.com/henriquebastos/gnucash-to-beancount/ does already. I'd be against having something like this in Fava. Parsing a gnucash file, printing it to a Beancount file and then parsing that seems like quite a hack.

Another (and better IMHO) possibility would be to generate a (Python) list of Beancount entries directly. Those could actually be inserted into the Beancount entry list using a (Beancount) plugin. If you want to implement this, have a look at the [Beancount Plugin Documentation](https://docs.google.com/document/d/1QftxNvQPdH-MikMBHupftU6F4IsNZP5FlFh1LCbVgk8/edit). Generating a list of transactions (`beancount.core.data.Transaction`) from the data that `gnucashxml` gives you shouldn't be too hard.

**Comment by christopherlam** [comment]
Thank you.

FWIW Gnucash stores either as XML or SQL (SQL as SQLite3, Postgresql, or mySQL). https://github.com/henriquebastos/gnucash-to-beancount/ is one of many modules which can load from sqlite3. XML datafiles are more well-tested within gnucash, but have fewer out-converters. 

If fava wishes to open up their fileinput api one day, gnucashxml is already available for xml extraction.  I just love the bloated Gnucash GUI and fava reporting! The following snippet will generate a .ledger file which I believe is highly compatible with beancount:

`from gnucashxml import from_filename`
`book = from_filename('test.gnucash')`
`return book.ledger()`
