### ISSUE TITLE
Mac: Leak in Python/Fava?

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#497]
For some weeks now my Mac shows strange behaviour when running `fava` in `--debug`-mode or running the tests with `tox`: It eats up all the free hard drive space. 

Has anyone else experienced such weird behaviour?
Any hints how to debug this?

Versions:

Mac: 10.12.3 (16D32)
Python: 3.6.0 (Installed via `brew install python3` and running in a `virtualenv`; de- and reinstalled both)
Fava: `HEAD` of `master`

**Comment by yagebu** [comment]
Which files take up the space?

**Comment by aumayr** [comment]
How do I find that out? 🙄

**Comment by yagebu** [comment]
`du` could help

**Comment by aumayr** [comment]
I found the culprit:

- `~\.bean-shell-history` had 1.6 GB
- It was filled with the same BQL commands over and over: https://github.com/beancount/fava/blob/master/tests/test_application.py#L30-L43
- I tranced it back to the invocation of the initializer of `beancount.query.shell.BQLShell` and `DispatchingShell`
- I deleted `~\.bean-shell-history`, and everything is well now

@blais Does this (the growth of the `~\.bean-shell-history`-file, the use by Fava of `BQLShell` (here: https://github.com/beancount/fava/blob/03e018665635c6f27c843087e2dc94894765c6dc/fava/core/query_shell.py#L25)  and that it was filling up my hard drive) sound like a bug?

**Comment by yagebu** [comment]
(Fava limits the size of the shell history, so this shouldn't happen anymore)
