### ISSUE TITLE
fava-collapse-account does not seem to be working

### ISSUE THREAD

**Issue by scanta2** [beancount/fava#498]
I have the following open statement with a metadata tag for fava-collapse-account. I tried collapse-account, "True" and "true", but nothing changes in the balance sheet. Am I doing something wrong?

1994-05-25 open Assets:Non-Retirement:Ciara:USD:Investments:WiseBanyan USD
  fava-collapse-account: "true"
  collapse-account: "true"

**Comment by yagebu** [comment]
Fixed. (needs to be `fava-collapse-account: "True"` like documented)
