### ISSUE TITLE
problem if error of currency

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#499]
with this file:
```
2002-03-30 * "firm" ""
    Income:Category    -40.02 E
    Assets:Account   40.02 EUR
```
if by mistake , I put a E instead of a EUR, i got a error 500.

bean-check say 
`/mnt/d/ledger/data/test.ledger:2:       Invalid token: 'E'`

in theory, fava should say the same thing.

**Comment by yagebu** [comment]
Can't reproduce this. Fava shows the error as it should for me. Which version are you using?

**Comment by pfrancois** [comment]
ok after having updated to the last master in from github, it seem to be ok
