### ISSUE TITLE
y axis ticks rounding in LineChart

### ISSUE THREAD

**Issue by scanta2** [beancount/fava#501]
I don't know JavaScript, but I played a little bit with the LineChart class in chart.js and I have modified the bounds of the y axis domain to be between the minimum and maximum value in the chosen time series (i.e. LineCharts do not start at 0). Let's now say my current y axis domain is from $430k to $460k. There are about 12 grid lines in the y-axis, but they are just rounded to the first two significant digits, i.e. I see 430k, 430k, 430k, 440k, 440k, 440k, 440k, etc... instead of 432, 433, 434, 435, 436, 437, etc

Where do I change the rounding in the y-tick labels?

**Comment by yagebu** [comment]
There's a `formatCurrencyShort` function that handles these values.
