### ISSUE TITLE
Compatibility with PyInstaller and Flask

### ISSUE THREAD

**Issue by qingweiqm** [beancount/fava#506]
hi, guys 

I have a Flask applications, I want to use pyinstaller to turn it  into a executable file on centos.

I have installed the pyinstaller 3.2.1 and  other needed things.

The pyinstaller can run and build an binary file, but when I try to run the binary file,

[root@centos-c10 dist]# ./manage runserver
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
usage: manage [-?] {test,shell,db,runserver} ...
manage: error: invalid choice: './manage' (choose from 'test', 'shell', 'db', 'runserver')

but I can start the server by using python command,

[root@centos-c10 flasky]# python manage.py runserver -h 0.0.0.0
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger pin code: 257-310-652

any ideas or suggestions are appreciated.
I'm a freshman to Pyinstaller and python, I searched google, but no clear answers.And if I missing something, just let me know.

thanks!

**Comment by qingweiqm** [comment]
wrong place,sorry.

**Comment by hustxiaofeng** [comment]
@qingweiqm , i have encounted the same problem, have you resolved?
