### ISSUE TITLE
module readline missing

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#508]
i install fava with pip.
and when i launched fava, i have a error:
`ImportError: No module named 'readline'`

moreover it don't work in windows.

**Comment by pfrancois** [comment]
for windows, we need to install pyreadline; and it is a drop in replacement

**Comment by yagebu** [comment]
Thanks for the report! Added the dependency for `pyreadline` on Windows.

@blais: I believe this affects Beancount too.
