### ISSUE TITLE
Not all payees appear in the filter

### ISSUE THREAD

**Issue by alexjj** [beancount/fava#511]
I was trying to see how much we spend at Costco to see if the higher memberships are worthwhile and found I couldn't get Fava/beancount to filter on Costco for the payee. It gave blank results.

I then tried random things to see what was happening. I'm not 100% sure but it seems like if a transaction looks like this:

YYYY-MM-DD * "Payee A"
...

Payee A doesn't appear in the filter list. However, if it's like this:

YYYY-MM-DD * "Payee B" "Description about it"
...

Payee B does appear.

Is this the way it's meant to work? Is this beancount rather than fava? I tried a Query and that yeilded no results:
`balances where payee ~ "Costco"`

**Comment by aumayr** [comment]
Example entry:

```ruby
2017-03-11 * "Text"
  Expenses:Other    1.00 USD
  Assets:Cash
```

When specifying only one "String" in quotes next to the date in an entry like in the example above, "Text" is interpreted by Beancount as the description, not the payee. You can see this in the Journal view in Fava. 

You have to specify it like the following example to leave the description empty:

```ruby
2017-03-11 * "Text" ""
  Expenses:Other    1.00 USD
  Assets:Cash
```

In this example, the description is empty, and the payee is "Text".

**Comment by alexjj** [comment]
Ah okay. Thanks for the explanation. I missed that info when I first read the documentation. 

Now to go back and edit the past 2 years..!

**Comment by blais** [comment]
I'll admit that it is a bit confusing.
I've considered making a single string represent a payee, but this seemed
less adequate, b/c I think there are more often descriptions than payees.
Another option would have been to put the payee in the second string, but
that would be at odds with the Ledger convention from which it sprouted.
