### ISSUE TITLE
Monthly balances don't include padding transactions

### ISSUE THREAD

**Issue by xentac** [beancount/fava#515]
If I look at a regular asset account but filter per year, I would expect the monthly balances shown to be the real balances for that period, not the sum of all transactions in that time.  I think we just need to include the synthetic padding transaction when calculating monthly balances.

Is my expectation off?

**Comment by yagebu** [comment]
Thanks for the report, that's indeed a bug. The monthly balances should be independent of any time filter (at least for intervals completely included in the filtered time period).
