### ISSUE TITLE
Saved queries don't play well with filters

### ISSUE THREAD

**Issue by xentac** [beancount/fava#517]
I think that the change to support applying filters to queries doesn't work when using saved queries.

I don't know which way I would want it to go, but the easiest thing would be to ignore filters when running saved queries.

**Comment by yagebu** [comment]
That queries can't be found if the time filter doesn't include them is the problem you are referring to, I guess?

Will fix that, so that the query shell always has access to all queries in the file. But for consistency, the currently active filters should still be applied to the saved query.
