### ISSUE TITLE
Add Collapse all on the tree tables

### ISSUE THREAD

**Issue by alexjj** [beancount/fava#524]
Would be convenient to have a Collapse all on the tree tables. Often I just want to look at handful of items and it would be quicker to collapse all then expand the ones I want.

**Comment by xentac** [comment]
The tooltip tells you to shift+click to collapse/expand all and ctrl+click to expand one level.

**Comment by alexjj** [comment]
That it does. Guess I've never hovered long enough over the arrows to see that.
