### ISSUE TITLE
'Pad' directives don't seem to update balance on target (2nd) account

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#527]
I have a Pad and a Balance Assert as below:-

2017-04-11 pad Assets:Cash:Wife Expenses:UnaccountedExpenses

2017-04-12 balance Assets:Cash:Wife                                          237.9 MYR

The balance updates correctly in the Assets:Cash:Wife account (Narration says 'Balance ...') but the Expenses:UnaccountedExpenses account shows a transaction with Narration of 'Pad ...' and the actual balance is not updated.

Screenshot available below, the expected amount (shown on bean-web) is 20 MYR.
![2017-04-14-063653_3520x1080_scrot](https://cloud.githubusercontent.com/assets/135656/25027145/3bd97d0e-20dd-11e7-8fb6-e0ccb58b7ac4.png)

**Comment by xentac** [comment]
I've noticed there are actually two associated transaction lines with Paddings...  Click the X transaction type, that should show transactions of type 'P' which should have transaction legs and update the balances correctly.

**Comment by ngoonee** [comment]
Oh, that works. What in the world is 'X'? In any case, this isn't a bug then, thanks.

**Comment by xentac** [comment]
X is "all other transaction types other than * and !"
