### ISSUE TITLE
Suggestions for Editor view

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#534]
A few suggestions for the Editor:-

1. Start (maybe optionally) with all folds folded.

2. Close folds with any click on the number line rather than only on the head/title of fold.

3. When clicking save, check whether beancount file has changed in the meantime.

Number 1 should be self explanatory, much more convenient for dealing with large files.

Number 2 eases navigation in large files.

Number 3 is an attempt to deal with the asynchronous access issue. As it is if youre in the Editor page and use the transaction entry popup to enter a transaction, the editor page still contains the old version of the file. Can also be triggered if using the editor in one tab while entering transactions in another. This can result in data loss without warning. Perhaps a md5sum of the file can be saved on opening, and on saving check the md5sum of the file currently on disc against that saved md5sum. If not matching, provide option to override, to not save, or to save as another file name.

**Comment by aumayr** [comment]
Number 3 is definitely something we should add - this happens sometimes, and is frustrating each time.

**Comment by yagebu** [comment]
All good suggestions! Any work on this would be welcome :)

**Comment by yagebu** [comment]
I'm working on this.

**Comment by yagebu** [comment]
1. and 3. are addressed IMHO:

1.  "fold all" and "unfold all" are available from the menu. However they are quite slow for large files so I'm against starting with all folds closed as that makes the page lock up for a few seconds (on my file).

3. Saving will now fail if the source file was changed externally.

I had a look at 2. but didn't find a good way to do it. I'll not spend more time on it myself so I'm closing this issue, but if anyone wants to work on it, feel free!
