### ISSUE TITLE
Point to hosted Beancount file

### ISSUE THREAD

**Issue by jmgilman** [beancount/fava#536]
This is starting both a discussion and adding a feature request. The discussion is around pointing to a hosted beancount file, the feature request would be officially supporting it.

I would imagine this must not be very uncommon, but I host my beancount file in a git repository on a self-hosted platform (Gogs). Fava is sitting on a separate container with a local copy of said git repository. Here is how they sync:

- I push a local change to the git repository
- A webhook in Gogs see's the push and triggers an HTTP GET request to a home made Node app on the Fava container
- The homemade Node app responds to the GET request and executes a git pull command on the local repository that Fava is pointed to
- The end result is that the Fava web interface updates within a few seconds of pushing a git change

I created this implementation about a year ago, but I haven't seen anything in Fava change logs that would point to a more simplified approach. I would be curious to see if anyone else has attempted something similar.

As for the feature request: It would be incredibly useful to add another flag for referencing a remote file, specifically one from a repository. It would most likely have to be read-only, but that's a consequence worth having.

**Comment by jmgilman** [comment]
After some development, I was able to remove the middleman web app that was doing the pull request. I've now consolidated the update logic into the post_receive git hook using Python. After committing to the git server, this hook will grab the content of the updated beancount file from the repository and then submits the content to the Fava instance using the included API. So git is essentially talking directly to Fava now. You can find the code below:

`#!/usr/bin/env python2

import subprocess
import json
import urllib2
import sys

FAVA_URL = 'http://FAVA-IP/LEDGER-NAME/api/source/' # The correct API URL for Fava
FAVA_PATH = '/path/to/ledger.beancount' # Beancount file path relative to Fava
GIT_PATH = 'ledger.beancount' # Beancount file path relative to the git repository

# Grab the reference for the latest commit
ref = sys.stdin.read().split()[1][0:6]
print('Updating Fava for ref ' + ref)

# Build JSON API string that Fava is expecting
data = {}
data['file_path'] = FAVA_PATH
data['source'] = subprocess.check_output(["git", "show", ref + ":" + GIT_PATH]) # Returns file content of beancount file for latest commit

# PUT the request to the Fava instance
opener = urllib2.build_opener(urllib2.HTTPHandler)
request = urllib2.Request(FAVA_URL, data=json.dumps(data))
request.add_header('Content-Type', 'application/json')
request.get_method = lambda: 'PUT'
url = opener.open(request)`

This could be optimized to use something like _requests_, but I think it's better to rely on the standard library in situations like this. 

Regardless of this improved solution, I would still love to see better support for this type of implementation inside Fava (not having to use git hooks).

**Comment by yagebu** [comment]
In a lot of places Fava currently assumes that the Beancount file is a local file (and part of the local filesystem). The autoreload functionality checks the file on every page load for updates. Documents, extensions, imported files and import config can all be relative to the Beancount file. So to offer a similar functionality "remote files" would have to support the same operations like a local filesystem.

I don't quite see the benefit of having this sort of functionality as part of Fava. There's also too many types of "remote files" so that picking one or few to support seems hard (for example git, hg, any other VCS, HTTP, WebDAV, SSH, FTP, etc...). I think using a dedicated tool is better suited for this purpose.

Your current solution looks simple enough and I don't see how the instant update could be achieved without some sort of push/hook. If you want this to happen on the Fava side, a hook could be added to Fava's extensions that can be triggered via some URL endpoint (in your case, this hook could then run `git pull`).

**Comment by jmgilman** [comment]
Thanks for the feedback, and I concur with the difficulty of integrating it into Fava. Given the existing architecture being built around local files, I think beefing up the extension support is the key to solving this issue on a per-user basis.

Has there been thought to allowing extensions to add on to the UI of Fava? I would love to develop a simple link/button that does a `git pull`.

**Comment by yagebu** [comment]
> Has there been thought to allowing extensions to add on to the UI of Fava? I would love to develop a simple link/button that does a git pull.

Allowing extensions to register their own reports or pages would be nice I think and should cover your usecase.

**Comment by alexjj** [comment]
This is very simple: I host my fava on pythonanywhere and use a nightly git pull scheduled job to get the latest copy from my git repo.

**Comment by jmgilman** [comment]
Scheduled nightly isn't the same as auto updating. After I finish writing
my finances, I want Fava to already be updated. Having link to update is
better than waiting till the next day in my opinion.

**Comment by alexjj** [comment]
I agree. I was just describing a simple solution that may work for some. Personally, I run fava on my local machine if I want to look at anything once I've updated it, but then have the pythonanywhere hosted version available any time/anywhere if I need it.

**Comment by jmgilman** [comment]
Ah, yes I agree that a local instance is always the best solution for immediate updates. Unfortunately my spouse is technically challenged and would be lost trying to run her own Fava instance :)

**Comment by alexjj** [comment]
Heh, if one hosted fava on something other than pythonanywhere it would probably be easy. Things like unison, and numerous other file syncing tools can be used to make it always updated.

**Comment by yagebu** [comment]
I'm closing this issue to keep the issue tracker clean. If there's any concrete request for what kind of hook/functionality extensions should support or any more need for discussion, feel free to continue here of course.
