### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#542]
@yagebu Do you think it's time to release 1.4?

**Comment by yagebu** [comment]
There were some minor problems with the conversion to a single currency (https://github.com/beancount/fava/pull/531#issuecomment-295313998) that we should maybe address before, otherwise it's definitely time to do the next release.

**Comment by aumayr** [comment]
👍

> There were some minor problems with the conversion to a single currency (#531 (comment)) that we should maybe address before

Are you working on this?

**Comment by xentac** [comment]
I finally replied to that comment.  I think we're in agreement on my two open points, but I'm not sure that it's worth blocking the release for.  The conversion that happens works for many cases.

Another way to look at it would be, if you release 1.4 as is, what would the version number be that fixed #531?  It feels like slightly more than 1.4.1 but definitely less than 1.5.

**Comment by yagebu** [comment]
> Are you working on this?

I'll probably have time to work on it tomorrow.

**Comment by yagebu** [comment]
v1.4 is basically ready. I've updated the strings on POEditor and notified the translators (I guess this part we could do earlier before the next release). Let's give it one or two days and release it then.

**Comment by yagebu** [comment]
@aumayr: Can you push the new translations, then I'll make the release? (it's annoying that I can't do that, even though I'm an admin for project on poeditor.com...)

**Comment by aumayr** [comment]
@yagebu Done.

It's also annoying that it generates so many commits…

**Comment by yagebu** [comment]
> It's also annoying that it generates so many commits…

Oh wow, yes that's quite ugly...

I think we shouldn't use the integration and just do this by hand. And maybe if you remove the Github integration I'll also be able to export the files...

**Comment by yagebu** [comment]
@aumayr: can you upload the release to PyPI?

**Comment by aumayr** [comment]
Done! 

@yagebu Thanks for the good work and the helpful comments on the PRs!

**Comment by yagebu** [comment]
@aumayr: Can you remove the Github integration on POEditor?

**Comment by aumayr** [comment]
Completely remove it? Or just the push-to-github-part?

**Comment by yagebu** [comment]
> Completely remove it? Or just the push-to-github-part?

What else does it do?

**Comment by aumayr** [comment]
<img width="274" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5135450/26104631/05d34d9a-3a3f-11e7-9537-25550918c0a3.png">

**Comment by yagebu** [comment]
I could still import a .pot file so the import-from-github part doesn't seem to do any harm (but I can't use it). So just removing the export part should be enough.

**Comment by aumayr** [comment]
I think importing and exporting functionality cannot be removed separately. As the exporting-to-Github has to be started manually anyway it could just stay as it is, without starting the export in the future.

**Comment by yagebu** [comment]
> I think importing and exporting functionality cannot be removed separately

Then please remove both.

**Comment by yagebu** [comment]
> Then please remove both.

Nevermind. I only now figured out that one has to go to the language page to do the export and it has nothing to do with the Github integration (which is still quite useless)...

**Comment by yagebu** [comment]
@aumayr: I'll add a script that uses POEditors API to push/fetch translations. So I think it's better if the Github integration is removed completely. The import can't really work anyway since the template file is not kept in git...

**Comment by yagebu** [comment]
@aumayr: It seems like POEditor is automatically fetching the outdated translation terms so the Github integration really needs to be disabled.

**Comment by aumayr** [comment]
I disabeled it. Do I have to do anything else?

**Comment by yagebu** [comment]
No. Now to update the translations there's `make translations-push` and `make translations-fetch`.
