### ISSUE TITLE
not possible to add a transaction

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#544]
in the last version deployed in pythonanywhere; i can't add a transaction.
when i click on the "+" near editor, nothing happen. in fact, i can there are an error:
 TypeError: newPosting.querySelectorAll(...).forEach is not a function

**Comment by yagebu** [comment]
This seems to be a problem with an outdated browser that we don't support. What browser are you using?

**Comment by pfrancois** [comment]
ok it seem that after upgrading my Firefox. it works with ff53 but it don't work with edge.
it say with osoft Edge 40.15063.0.0
 "Object doesn't support property or method 'forEach'"

**Comment by yagebu** [comment]
Thanks for the update. The `forEach` for `NodeList`s (which is what `querySelectorAll` returns) is more recent than I remembered and we actually have a helper function to deal with this. Can you check if it works now?
