### ISSUE TITLE
/jump URL always 404s

### ISSUE THREAD

**Issue by alexjj** [beancount/fava#545]
I was trying to use /jump to make a sidebar link to have a last month's income statement link, but found that whatever /jump? option I use it always gives 404.

I was trying `http://localhost:5000/finances/income_statement/jump?time=last+month`

However, I tried multiple other options but nothing worked, and just gave 404. 

I build from the git repo and updated eariler today.

**Comment by yagebu** [comment]
The jump URL is at the root: `http://localhost:5000/jump?....`.

Also if you want a link to the income statement with some fixed filters, the jump handler doesn't do what you want, just set a link to the income statement with the filters.

**Comment by alexjj** [comment]
Thanks for the reply. I'm still a little confused...

The help says:

> There's a special URL handler /jump which can be used to jump to current page with given params. This is useful to limit the scope of current viewing page. E.g.  /jump?time=last+month+-+next+month will show current page but limit to the last month, this month and the next month.

Let's use the fava pythonanywhere to simplify things.

If I type http://fava.pythonanywhere.com/example-3/jump?time=2017 it puts in a slash after jump to render http://fava.pythonanywhere.com/example-3/jump/?time=2017 which 404s.

Similarly http://fava.pythonanywhere.com/example-3/income_statement/jump?time=2017 still 404s.

Could you provide a link to demonstrate the correct usage of /jump on the pythonanywhere site please.

**Comment by adamgibbins** [comment]
It only works in the sidebar links, you can't navigate to it directly. So you literally want `/jump?time=2017` in a sidebar link. Nothing else, just `/jump?time=2017`, not example-3  Then you click the link and it'll append `?time=2017` to the params.

**Comment by alexjj** [comment]
Ah okay. Thanks! 

Although the filters it shows in the help (last+month+-+next+month) don't seem to work, which is a shame as I'd like a "last month".

**Comment by yagebu** [comment]
> I'd like a "last month".

`month-1` does the trick (see the help pages for details).
