### ISSUE TITLE
Fava's editor sometimes won't display beancount file

### ISSUE THREAD

**Issue by victoraraujo01** [beancount/fava#547]
Ever since I've started to store a couple of custom queries in my beancount file using the query directive (as suggested in #96 ) the fava's editor can't display my file.

Here's a sample file I've created to show the problem. From what I could tell based on my tests, this bug is somehow related to having the date comparison (`date > 2014-07-02`) before the `GROUP BY`. If I remove the date condition and keep the `GROUP BY` or if I remove the `GROUP BY` and keep the date, the editor displays the file just fine. 

```;; My legder file

option "operating_currency" "BRL"

** Queries

2017-03-06 query "my_query" "
SELECT month(date) as month, year(date) as year, cost(sum(position))
WHERE
  account ~ 'Assets' and
  date > 2014-07-02
GROUP BY month, year"

** Accounts

1988-03-29 open Assets:Cash
1988-03-29 open Assets:Bank-Account
2011-07-19 open Expenses:Restaurants

2014-10-28 * "Test" "Test"
    Assets:Cash                               -20.00 BRL
    Expenses:Restaurants```

**Comment by yagebu** [comment]
Thank you for the report and the sample file. This seems to be a problem with the editor mode for the Beancount query language. Maybe some malformed regular expression. Will investigate.
