### ISSUE TITLE
Document how to configure fava options

### ISSUE THREAD

**Issue by yegle** [beancount/fava#550]
I had to read the source code to understand how to set those options.

**Comment by yagebu** [comment]
The "Options" help page has some example custom entries at the start that show how to set the options. Is that not sufficient?

**Comment by yegle** [comment]
Ah, I missed that page. Maybe a link from Options page to the help page then?

**Comment by yagebu** [comment]
Sure, feel free to add one 👍

**Comment by yagebu** [comment]
(or better, I'll just add one now, now need for the hassle of opening a PR)
