### ISSUE TITLE
Fava shows different Net Worth than Beancount

### ISSUE THREAD

**Issue by b4ndit** [beancount/fava#557]
I hope this isn't a stupid mistake on my part, but I can't seem to figure out what's going on.

Let's say I have a Scottrade account holding $228.93 in cash and 15 shares of SPY purchased at $223.99 USD each. Beancount will report a Net Worth of $3,880.68 using bean-report. However, Fava shows a Net Worth of $228.93 in the graph on the Balance Sheet page. For whatever reason, Fava is not seeing the 15 shares of SPY in the Net Worth calculation.

Here is a minimal beancount file to reproduce (has the issue as of today 6/7/2017, on the newest version of Fava available on pip3).

```
* Options

option "title" "Scottrade issue test"
option "operating_currency" "USD"
option "account_rounding" "Rounding-Errors"


* Commodities

1792-01-01 commodity USD
  export: "CASH"
  name: "US Dollar"

2017-01-01 commodity SPY
  export: "NYSEARCA:SPY"
  name: "SPDR S&P 500 ETF"
  price: "USD:google/NYSEARCA:SPY"



* Equity Accounts

1992-05-11 open Equity:Opening-Balances
1992-05-11 open Equity:Rounding-Errors


* Scottrade Investments

2017-01-01 open Assets:US:Scottrade
  institution: "Scottrade"

2017-01-01 open Assets:US:Scottrade:SPY                 SPY
2017-01-01 open Assets:US:Scottrade:Cash                USD

2017-01-01 * "Opening Balance for Scottrade"
  Assets:US:Scottrade:SPY                         15.00 SPY {223.99 USD}
  Assets:US:Scottrade:Cash                       228.93 USD
  Equity:Opening-Balances

2017-06-06 balance Assets:US:Scottrade:Cash      228.93 USD
2017-06-06 balance Assets:US:Scottrade:SPY        15.00 SPY


2017-06-07 price SPY                                243.45 USD
```

**Edit June 8:** I just tested bean-web on the example provided and it also shows the wrong Net Worth, so the issue is not limited to Fava.

**Comment by yagebu** [comment]
Fava will only show the charts for months between the first and last transaction basically. So in your example the net worths on 2017-01-01 (0 USD) and 2017-02-01 (just 228.93 USD as there is no price for SPY) are shown. If you set the time filter to `2017`, you can see that the net worth is calculated as 3880.68 starting from 2017-07-01.
