### ISSUE TITLE
Editor page doesn't show save/format buttons

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#559]
Based on git bisect, this started happening at commit d4948cf5b8c78f4053bbbab68292075c7f61f818

**Comment by yagebu** [comment]
This can only really happen if the frontend end stuff hasn't been recompiled (which would then also be the cause for the other issue you openened).

**Comment by ngoonee** [comment]
Makes sense. Is anything other than pip install required?

**Comment by yagebu** [comment]
You need to run `make`. See https://beancount.github.io/fava/development.html

**Comment by ngoonee** [comment]
Okay that fixes it, closing. Sorry for PEBKAC.
