### ISSUE TITLE
Inline-text-editor for the Add Transaction-overlay

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#565]
Currently the Add Transaction overlay (and the Import view) uses a form for input.

Add a button/link and keyboard shortcut (and maybe option) to switch the form to a small editor (like the context overlay has).

**Comment by aumayr** [comment]
@yagebu Do you think this can be implemented without much effort?

**Comment by yagebu** [comment]
> without much effort

No, that I can see. Right now the all of the "adding entries" code assumes it's dealing with entries and not slices of text, so we'd basically need separate functions supporting text slices for all of this.

Maybe extending the transaction form to support more is an easier route to take. What limitations of the form are you mainly running into? I guess one way of extending the transaction form to support more valid kinds of transactions would be to replace the number+currency input with just one input, which allow one to input price/cost and use calculations for the numbers.

**Comment by aumayr** [comment]
> replace the number+currency input with just one input

I like this idea, but I'm not quite sure if it makes it harder to use for some very novice users, like family-members that are not computer-savvy. Adding an option to do this would be a possibility.

> What limitations of the form are you mainly running into?

Two ideas why I would like this:

- Input is faster when you are in an editor, compared to the form. So when quickly adding 3 transactions and a `note` this would be very handy, without leaving the current page. (Weak argument, I know.)
- This could also be used to preview what the transaction will look like in the beancount file, like here on Github where you have a "Write" and "Preview"-tab for comments.

(This is not high priority for me. Just wanted to restart the discussion, so we can find out if it should have a higher priority or should be closed.)

**Comment by yagebu** [comment]
I don't think it's worth the effort, so I'll close the issue. Feel free to re-open if you ever feel like working on it.
