### ISSUE TITLE
Collapsing/expanding accounts in tree view also clicks on the account on mobile

### ISSUE THREAD

**Issue by xentac** [beancount/fava#567]
Possibly events are still being propagated when they're not supposed to be?  Reproducible in chrome inspector's mobile mode.

**Comment by yagebu** [comment]
I can't reproduce this in Chrome - only when I actually hit the link the link gets clicked.

**Comment by xentac** [comment]
If I click towards the left side of the arrow (the mobile circle is 1/3 over the arrow and 2/3 off), then the collapsing happens.  If I put the arrow in the middle of the circle it clicks the link too.

**Comment by yagebu** [comment]
I don't quite see the problem then - if you click the link, the link should be clicked, right?

**Comment by xentac** [comment]
If the majority if my finger touches the arrow but only a tiny part touches the link, I expect the collapse to be toggled.  If I touch to the left of the arrow with only a very small part of my finger touching the arrow, I would expect that to do nothing.

Instead tapping squarely on the arrow clicks the link and purposefully missing the arrow toggles the collapse.

I agree that clicking the link should click the link, but I don't think that having regular sized fingers means I need to dodge links aggressively in case I might click them ;P

**Comment by xentac** [comment]
I also expect that Chrome would handle the "finger tap near two links" problem, but because the arrow isn't actually a link, it dutifully clicks on the nearest link when I hit the arrow.

**Comment by yagebu** [comment]
Not hitting the link should be a bit easier to the right of the account name.

**Comment by xentac** [comment]
Fine.  Somehow I forgot that I could do that...
