### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#571]
@yagebu Ready for releasing 1.5?

**Comment by yagebu** [comment]
Yes! Can you make the release? I'll be on vacation for two weeks starting this weekend and I don't know if I'll have time until then to do it.

**Comment by aumayr** [comment]
Two thinks that would be awesome if you could provide:

- The changelog
- The "standalone"-executables

Everything else I can do 👍

Have a good vacation! 🏝

**Comment by yagebu** [comment]
> The changelog

Done.

> The "standalone"-executables

These we don't do anymore (1.2 was the last release to have them)

**Comment by yagebu** [comment]
@aumayr: I just noticed that the v1.5 release doesn't have the AppImage of the GUI. Did you delete this file or was it missing? `.AppImage` is like `.app` but for Linux, so the AppImage and the DMG are the two files that should be kept.

**Comment by aumayr** [comment]
Honestly I don't know if I simply forgot to add the file or if it was missing, but will keep it in mind  the next time around!

**Comment by aumayr** [comment]
Thanks for noticing and adding!
