### ISSUE TITLE
Charts not showing in Safari in fava version 1.5

### ISSUE THREAD

**Issue by jokorn** [beancount/fava#572]
After upgrading to version 1.5 the charts are no longer showing in Safari. Fava only shows "Loading charts..." where the charts should be. I tried downgrading to fava version 1.4 and the charts are working fine in this version. It is only an issue in Safari and works as usual in both Chrome and Firefox. I am not really sure how to troubleshoot this further.

**Comment by aumayr** [comment]
Hi @jokorn, thanks for the bug report!

For me the charts in Safari (current `master`) are working. So to track this down a few questions:

- Did you install via `pip` or from source?
- Which version of Safari are you using?

**Comment by jokorn** [comment]
Hi aumayr. I'm using Safari version 10.1.1 on Mac Os X Sierra. Fava installed with pip3. However, I can't reproduce this issue today after upgrading to fava version 1.5 again. So I'm closing this issue. Sorry for the inconvenience and thank you for an amazing piece of software.

**Comment by aumayr** [comment]
Glad that it works!
