### ISSUE TITLE
Error edit last entry in Journal

### ISSUE THREAD

**Issue by uzkikh** [beancount/fava#576]
Clicking on the entry date (that have last note in my .beancount file) in the Journal will open an overlay that shows the error: 
_The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application._

**Comment by yagebu** [comment]
Hey, thanks for the report. Can you try running Fava in debug mode (by starting it with the `--debug` command line flag) to see if it produces a more detailed error message? Also, can you provide a minimal beancount file with which you can reproduce this?

**Comment by yagebu** [comment]
Closing, as I can't reproduce it without anything to go on...
