### ISSUE TITLE
Copy/Paste functionality in the Electron app

### ISSUE THREAD

**Issue by johannesjh** [beancount/fava#577]
Bring able to copy/paste in the Electron app would be nice. Implementation hints see e.g.:
https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by aumayr** [comment]
In the same spirit: There is no "Back-Button" in the Electron-app (like in a Browser), so using Fava is a bit more cumbersome.

**Comment by yagebu** [comment]
Good suggestion (and thanks for the link)!

**Comment by yagebu** [comment]
Adding an actual back-button to Fava's interface would require some more elaborate changes. For me the back entry in the menu and the keyboard shortcut are enough, so I'll close this issue (but if anyone wants to add a button, a PR is welcome).

**Comment by aumayr** [comment]
> Adding an actual back-button to Fava's interface would require some more elaborate changes.

Does it? Wouldn't a button with `history.back()` be sufficient?

**Comment by yagebu** [comment]
> Does it? Wouldn't a button with history.back() be sufficient?

I guess "elaborate" was a bit strong, just adding a button is not quite enough though: We would have to add a `--gui` flag or something to Fava to tell it to show the button only when run by the GUI. If you've got time to add a button, that'd be welcome of course!

**Comment by johannesjh** [comment]
JavaScript can detect if it is running inside electron by checking `process.versions.electron`, compare https://github.com/electron/electron/issues/4248.
