### ISSUE TITLE
problem with chart

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#578]
i have a problem , with the chart done by fava.
the chart of account balance is wrong.
to expose it: i will make a easy example:

date | balance | transaction
----- | ------- | -------
01/01/2015 | 0 | 0
01/01/2016 | 100 | 100
01/06/2017 | 90 | -10
01/07/2017 | 80 | -10
01/08/2017 | 70 | -10
01/09/2017 | 60 | -10
01/10/2017 | 50 | -10
01/11/2017 | 40 | -10
01/12/2017 | 30 | -10
01/01/2018 | 20 | -10
01/02/2018 | 10 | -10
01/03/2018 | 0 | -10

the chart is 
![image](https://user-images.githubusercontent.com/421310/29753960-5072ae0c-8b7c-11e7-910c-d0d4c9ce9168.png)

but in fact the reality is more:
![image](https://user-images.githubusercontent.com/421310/29753988-f31d7b32-8b7c-11e7-91f8-993e26895eb5.png)

if on the second part ( the descending) , agree that the line is better), the first part is much more understandable. it show that there are no transaction in this account in 2015. and only one in 2016.

coudl it be possible to have something more readible ?

**Comment by yagebu** [comment]
Compared to your first picture, the charts in Fava have clearly visible data points, so a long gap can easily be seen. I think this is more a matter of taste than a question of right or wrong, the charts should try their best to make the important parts of the data easily visible and can sacrifice some exactness (in some cases, that exactness might not be correct actually). I don't have a very strong opinion on it, but I guess I slightly prefer the (current) interpolated chart. What do others think?

**Comment by aumayr** [comment]
To be honest, I also agree with @yagebu that the interpolated charts do look and "feel" better, as in the second version the points would be sufficient.
