### ISSUE TITLE
Improve example files

### ISSUE THREAD

**Issue by yagebu** [beancount/fava#581]
The example files on [fava.pythonanywhere.com](https://fava.pythonanywhere.com/) are a nice way to get an idea of what Fava looks like. They could be improved though and show of some Fava-specific features. That way they could also serve as a reference of what this would look like - for example with budgets, it's maybe not obvious from the documentation where they should show up. If there was an example file with budgets on Pythonanywhere, this could simply be linked to if someone has an issue.

I'll take one of the auto-generated example files as a base and add some budgets. Anything else that should be added to show of one of Fava's features?

@aumayr: I discovered that the example files are not read-only, so anyone can edit them currently. I've updated the scripts to mark them read-only. Can you run them to see if they work? (I fixed some things that spellcheck complained about - I hope I didn't break them)

**Comment by aumayr** [comment]
Pythonanywhere currently does not work (after I upgraded to the new `update.sh` because the 500MB disk quota is full. Culprint: `/usr/share/pip-wheels`, but I can't delete anything in this directory ("Permission denied").

**Comment by aumayr** [comment]
Any ideas how to fix this?

**Comment by aumayr** [comment]
@yagebu I was able to fix the error mentioned above, and the read-only-ness does work. When saving a file, it is not saved, and the following is displayed:

<img width="456" alt="bildschirmfoto 2017-09-11 um 20 48 02" src="https://user-images.githubusercontent.com/5135450/30291294-b2808cb0-9732-11e7-9857-8206cc5a9491.png">

**Comment by yagebu** [comment]
> When saving a file, it is not saved, and the following is displayed:

👍 

On favadev.pythonanywhere.com, I can still edit the file, did you also update the script there?

**Comment by yagebu** [comment]
Closed in 332de2333f0e6a735e637346f100d8ec3f270e26
