### ISSUE TITLE
Polling /changed is uncool, let's use websockets!

### ISSUE THREAD

**Issue by xentac** [beancount/fava#586]
A websocket solution seems much better than constantly polling the server for updates. If no one is opposed to this, I plan on adding something like socket.io to fava for pushing change notifications instead of polling them.

I'm excited to remove the constant /changed log lines being spewed out. Especially when I leave multiple browser windows open on different machines.

**Comment by aumayr** [comment]
If this does not add too much overhead (JS-deps), then this is a very welcome change! Thanks for the help & contribution!

**Comment by yagebu** [comment]
> A websocket solution seems much better than constantly polling the server for updates.

Definitely - I've thought about implementing this a couple of times and actually went about half-way of implementing it once. It's nontrivial to do this right. This would introduce a lot of dependencies and would turn Fava from a simple WSGI-app into something that's maybe harder to run in some setups.

Regarding the possible implementation: To watch files and directories in Python watchdog seems to be the only real cross-platform solution. It doesn't seem to be well-maintained and is kind of crappy to work with. The main problem in our use case is that it's (unnecessarily I think) blocking (on macOS at least) so we can't simply use flask-socketio with eventlet. It could be run in a separate process or thread, but then we need some form of interprocess communication. This is at least how I saw the situation maybe half a year ago. It could be that now there's some better solution using the shiny new async stuff in 3.6.

It would still be very nice to have this - maybe there's even some easier way to do it than I thought. Work on this would be quite welcome!

> I'm excited to remove the constant /changed log lines being spewed out.

Removing them in any case would be nice, I imagine changing the logging to ignore them shouldn't be too hard and would be a welcome change somewhat independent of the question of switching to websockets.

**Comment by yagebu** [comment]
@xentac: Are you still planning to work on this?

**Comment by xentac** [comment]
I investigated it. My original plan was to set up a thread to poll for
changes then publish the change status over websockets.

I looked into your other references and they all look good but I wasn't
able to figure out a testing strategy without just saying "works for me".

I don't have a lot of time to dedicate to this right now, so if you want to
take it up I'd be happy.

**Comment by yagebu** [comment]
I won't be taking this up anytime soon and I guess this is quite low-priority. I'm closing the issue, feel free to reopen if you want to take this up again.
