### ISSUE TITLE
Convert to currency does not work if multiple conversions are needed

### ISSUE THREAD

**Issue by tarioch** [beancount/fava#587]
I tried the convert to currency option on the reports pages and was baffled why it did convert some currencies and not some others. After some experimentation I figured out that it seems to only work if there is a direct currency conversion available. e.g.

Balances as follows
10 CHF
10 EUR
10 USD

Prices as Follows
1 USD = 1.1 CHF
1 EUR = 1.2 USD

If convert to CHF is selected, it will convert the USD but not the EUR (as to convert EUR it would need to do EUR -> USD -> CHF)

**Comment by yagebu** [comment]
Hey, thanks for the report! I agree that indirect conversions would be nice in some cases. There's an (seemingly inactive) pull request for Beancount ([#16](https://bitbucket.org/blais/beancount/pull-requests/16/treat-prices-as-a-graph/diff)) trying to address this. See the response by Martin Blais for some the problems involved. Another issue not mentioned there is the following: If your prices are on different dates, doing the indirect conversion through might give you something that could be quite far off the real rate.

So I'm not sure that doing an indirect conversion by default is a good idea - and if it did, it would have to happen in Beancount. Fava can't differ in something as essential as prices. So for now you'll have to add price entries for the EUR-CHF conversion or, probably simpler, use a small plugin that inserts them automatically.

**Comment by JamesTheAwesomeDude** [comment]
Bitbucket link's dead; latest discussion seems to be around https://github.com/beancount/beancount/issues/255#issuecomment-632818355
