### ISSUE TITLE
Inconsistent display of commodity balances

### ISSUE THREAD

**Issue by cceckman** [beancount/fava#588]
Hi - 

I was starting to import some of my investment transactions into Beancount, but noticed something odd about how Fava displays them. I put together a minimal example of the issue in [this gist](https://gist.github.com/d892b8c4eeb6f2dc3877ac88beee5313).

It seems that `bean-report` gets the correct commodity for the HAL account, and the journal likewise shows a balance in commodity HAL:

<img width="926" alt="journal" src="https://user-images.githubusercontent.com/861696/30525687-28d8fbc2-9bc0-11e7-8455-aa3a55172341.PNG">

But the balance sheet and trial balance views show HAL's balance in USD:

<img width="935" alt="balance sheet" src="https://user-images.githubusercontent.com/861696/30525690-4083c888-9bc0-11e7-99b4-fe1ccf7d7f4d.PNG">

Fava does display the correct commodity for other accounts.

Did I mess up the transactions here, or is this a bug, or something else?

**Comment by yagebu** [comment]
> Did I mess up the transactions here, or is this a bug, or something else?

This behaviour is intended: The balance sheet shows the account balances at their book value, i.e., "at cost". The account journal shows the units currently in the account balance. It's not ideal I guess that the "At Cost" dropdown is shown as it doesn't apply to the two shown charts and the journal (it only changes the display of balances normally displayed at cost, i.e., the account trees and corresponding charts.

What's shown in the journal could be up for debate, but the balance sheets should really show the book value.

Let's take the following example: 

    2017-02-01 * "Invest in HAL"
      Assets:Investment:USD
      Assets:Investment:HAL 10 HAL {5 USD}

    2017-03-01 price HAL 6 USD

Then the book value of the balance of the `Assets:Investment:HAL` account is 50 USD and its market value is 60 USD (which would be shown in the net worth chart).

**Comment by blais** [comment]
On Mon, Sep 18, 2017 at 10:40 AM, Jakob Schnitzer <notifications@github.com>
wrote:

> Did I mess up the transactions here, or is this a bug, or something else?
>
> This behaviour is intended: The balance sheet shows the account balances
> at their book value, i.e., "at cost". The account journal shows the units
> currently in the account balance. It's not ideal I guess that the "At Cost"
> dropdown is shown as it doesn't apply to the two shown charts and the
> journal (it only changes the display of balances normally displayed at
> cost, i.e., the account trees and corresponding charts.
>
> What's shown in the journal could be up for debate, but the balance sheets
> should really show the book value.
>
That's debatable. I would argue for displaying them at market by default,
and to add an option (a toggle?) to display at book value.

**Comment by yagebu** [comment]
> That's debatable. I would argue for displaying them at market by default,
and to add an option (a toggle?) to display at book value.

I guess "should really show the book value." should have been "should really show the book value by default.". As far as I understand, a "balance sheet" in standard accounting lists the book value, so if we call it the same, I think it should do the same. Displaying them at market value or converting them is possible via the dropdown already.

**Comment by blais** [comment]
On Mon, Sep 18, 2017 at 10:51 AM, Jakob Schnitzer <notifications@github.com>
wrote:

> That's debatable. I would argue for displaying them at market by default,
> and to add an option (a toggle?) to display at book value.
>
> I guess "should really show the book value." should have been "should
> really show the book value by default.". As far as I understand, a "balance
> sheet" in standard accounting lists the book value,
>
I never heard of this. Do you have any reference on this?
Not knowing any better, I'd have reported at market value and added a tax
liability to account for taxes on the unrealized profit, so that the
balance reflect the value on liquidation.
