### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by JaneSmith** [beancount/fava#591]
Is there a reason why there are no Windows builds on the Releases page?

**Comment by alexjj** [comment]
Windows sucks :grin:

If you use Windows Subsystem for Linux, then it's a simple `sudo pip3 install fava`

**Comment by JaneSmith** [comment]
Well, it's generally a desired quality of software for it to be available on multiple platforms, right? I would prefer not to have to use the Windows Subsystem for Linux, but if that's the only way, then okay.

Will installing it in this way include the GUI version (Electron wrapper)? That's what I'm looking for.

**Comment by yagebu** [comment]
If someone provides a PR with a working Appveyor config that builds the GUI, we can add releases for Windows. This shouldn't be too hard, as Beancount apparently supports being built on Windows better than the last time I tried (see [#17](nhttps://bitbucket.org/blais/beancount/pull-requests/17/add-appveyor-support-for-building-windows/diff) for the commands that should work to build it on Windows).  See `.travis.yml` for what commands need to be run to build Fava's Pyinstaller binary and the GUI and what dependencies are needed on the other platforms.

**Comment by yagebu** [comment]
We now run the tests on AppVeyor and build the GUI for Windows. I can't test this myself, so this would need some help - the generated installer (which can be download from the artifacts of the latest build at https://ci.appveyor.com/project/yagebu/fava) seems suspiciously small.

Is anyone willing to debug/test the Windows build?

**Comment by aumayr** [comment]
> Is anyone willing to debug/test the Windows build?

Thanks for working on this! I do not run Windows, but have some VMs laying around, in case I need to test something. For testing it right now I can provide some time, but for testing on Windows on a permanent basis my VMs are not the right solution.

**Comment by yagebu** [comment]
@aumayr: Cool! I think that'd be enough to get started. Can you test the installer? If it doesn't work, there's mainly two things I'd expect to go wrong: The Pyinstaller producing something that doesn't work or the GUI not finding (and maybe packaging) the right executable. So it would be good to run the appveyor build steps locally and see what they produce.

**Comment by aumayr** [comment]
I just tried with b811370:

- The installer finishes successfully.
- On first launch, it crashed:

<img width="558" alt="screenshot" src="https://user-images.githubusercontent.com/5135450/37571046-f360829a-2af7-11e8-8da0-d13696f51b18.png">

- On subsequent launches, it gets stuck on the "Starting Fava..." screen (as it does on my Mac as well!)

**Comment by yagebu** [comment]
I guess with the removal of the gui, the main point of this issue has become kind of moot, so I'll close the issue
