### ISSUE TITLE
Allow Budgets on Income accounts

### ISSUE THREAD

**Issue by tarioch** [beancount/fava#592]
It would be great if it would also be possible to specify (negative) budgets on income accounts. It looks to me like this is not working right now.

**Comment by yagebu** [comment]
Just tried this and the negative budgets seem to show up in all the places that the positive ones would. Can you give some details on what you mean by "this is not working"?

**Comment by tarioch** [comment]
I looked at it on the chart in the income report.

**Comment by yagebu** [comment]
It works for me in the charts.

**Comment by tarioch** [comment]
Updated to Dev Version, there it seems to work fine.

**Comment by yagebu** [comment]
Ah yes this got accidentally fixed in b4186c800ccd41dfb3242e5604aaf5d0e37cbaba, since before the `Counter`s were added with `+`, which only adds positive values.
