### ISSUE TITLE
Errors: Parse and link Account names

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#593]
Quick idea: Parse the Error messages (emitted by beancount) with a RegEx to find Account names, and link those to the accounts.

**Comment by blais** [comment]
There's already a filename/lineno to take you to the offending transaction.

**Comment by aumayr** [comment]
> There's already a filename/lineno to take you to the offending transaction.

Fava uses this info already, and links to the editor to the corresponding line. What I want is a link _in the description of the error message_ being linked to the corresponding Account view.
