### ISSUE TITLE
Why is Babel<2.5.0 required?

### ISSUE THREAD

**Issue by TomJohnZ** [beancount/fava#598]
Recently, my copy of python-babel updated to 2.5.1, so fava throws an error since babel<2.5.0 is required in setup.py.

Of course, I could downgrade babel to make fava work, but I was wondering why newer version of the package aren't allowed?

**Comment by yagebu** [comment]
It broke PyInstaller support, which we use for the GUI.

https://github.com/python-babel/babel/issues/529

**Comment by TomJohnZ** [comment]
That makes sense; thanks a lot!
