### ISSUE TITLE
Underscores replaced by spaces in drag-and-drop file upload

### ISSUE THREAD

**Issue by HappyAtDomain** [beancount/fava#602]
I'm using fava==1.5 from pypi.

If I drag a PDF file from my file manager (nautilus) on to a journal entry and its filename contains underscores, they are replaced with spaces when they are uploaded

The filename as shown in the pop-up dialog is correct, but when I submit it the colourful toast in the top right has the wrong filename. The `statement` metadata on the tx is wrong as is the filename on disk.

I've tried this in both Firefox and Chrome with the same outcome.

**Comment by yagebu** [comment]
Hey thanks for the report. Don't really know why we replace underscores with spaces in the uploaded filenames - will change that.
