### ISSUE TITLE
filter on metadata values

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#603]
As far as I can tall there is no UI element in Fava that allows to query based on metadata values.
Similarly to the "Tag" text entry, one could imagine a "Metadata" text entry that takes a comma-separated list of "key: value" pairs, filtering on the corresponding metadata values.
Bonus point: supporting regular expressions (on both sides?).

Thanks for Fava!

**Comment by yagebu** [comment]
Have you tried writing a `FROM` expression for this? The query language has a `ENTRY_META()` function, so for a fixed key this should be possible.

I'm not really keen on adding any more text entries to the filters form, it already gets quite clunky on smaller screens. I'd rather be up for grouping some of them together - however it seems to me that would duplicate what the query language can already do.

**Comment by zacchiro** [comment]
I confess I'm having hard time understanding which part of the Beancount query language can be written in the FROM input field, the doc says "as supported by BQL" but that doesn't seem to be the case. So I'm guessing you support a subset of the query language (which makes sense), but I can't figure out which subset exactly. Can you clarify?

**Comment by yagebu** [comment]
Any entry filter expression suppported by the BQL can be used (this is referred to as `<entry-filter-expression>` in the [Google Doc](https://docs.google.com/document/d/1s0GOZMcrKKCLlP29MD7kHO4L88evrwWdIO0p4EwRBE0) and `<from_expr>` in the integrated help). You can run `help from` in the query shell to get a list of supported columns and functions.

**Comment by zacchiro** [comment]
On Tue, Nov 07, 2017 at 12:56:32PM +0000, Jakob Schnitzer wrote:
> Any entry filter expression suppported by the BQL can be used (this is
> referred to as `<entry-filter-expression>` in the [Google
> Doc](https://docs.google.com/document/d/1s0GOZMcrKKCLlP29MD7kHO4L88evrwWdIO0p4EwRBE0)
> and `<from_expr>` in the integrated help). You can run `help from` in
> the query shell to get a list of supported columns and functions.

Thanks for this explanation. Do you confirm that you cannot use WHERE
expressions? Because that is my feeling and also the cause of trouble
here.

For instance, a query like:

  select * where any_meta('trip') ~ 'berlin'

does work in native bean-query (and its web based equivalent), but
AFAICT cannot be entered (not even clipped at the start of the
any_meta() call) in the FROM box.

The reason seems to be that the following query does *not* work:

  select * from any_meta('trip') ~ 'berlin'

because FROM applies filtering to any kind of transaction and metadata
lookup fails on any non-transaction entry due to stuff like this:

  AttributeError: 'Commodity' object has no attribute 'posting'

So unless I'm missing something I don't think the current FORM input
field can be used to do metadata filtering, which is unfortunate.


I'd also like to mention that a dedicated metadata filter widget would
allow to do automatic completion on the (right hand) values of the (left
hand) metadata name that has already been inserted, which would be a
pretty killer feature :-)


That said, I'm very sensible of the "screen estate" argument --- in
fact, I plan to use this on a phone myself. Maybe a different
arrangement of the filtering widgets, possibly triggered only on
med/small screens, would be a better fix for that problem?


Thanks a lot for Fava, it's amazing!
Cheers

**Comment by yagebu** [comment]
> Do you confirm that you cannot use WHERE expressions?

Yes only FROM expressions can be used, since only complete entries can be filtered.

> So unless I'm missing something I don't think the current FORM input field can be used to do metadata filtering, which is unfortunate.

With the `entry_meta` function I mentioned above it does work though, right?

**Comment by yagebu** [comment]
> With the entry_meta function I mentioned above it does work though, right?

Mhh it seems that all these metadata functions only work on postings - that looks like a limitation of the BQL that could be fixed though.

@blais: Are we missing something here or is accessing any entry metadata in a FROM expression currently not possible? Could the `META()` function be changed so that it works for entries too?

**Comment by zacchiro** [comment]
> With the entry_meta function I mentioned above it does work though, right?

Nope: neither of `meta`, `entry_meta`, `any_meta` works:
- `meta` and `any_meta` fail not finding a `posting` attribute on non-transaction entries
- `entry_meta` fails not finding a `entry` attribute on non-transaction entries

**Comment by yagebu** [comment]
All the attributes to access metadata in the BQL are indeed unsuitable for FROM expressions. In the query shell this is not really a problem as one usually filters for postings and can use a WHERE expression. In Fava however, a filter that should work on all reports can only filter for complete entries.

This could be solved by using a more flexible filter language (and have it replace some of the single filters). I'm thinking of something along the lines of the filter language of Github or Google Search. Say a filter `payee:test, key:test-.*` would filter for all entries with either a payee "test" or a metadata value starting with "test-" for the metadata key "key". Tags and links could also be supported by this. The account and time filter are imported enough to have their own inputs IMHO but all the others could then be subsumed by this single filter input.

**Comment by aumayr** [comment]
> The account and time filter are imported enough to have their own inputs IMHO but all the others could then be subsumed by this single filter input.

Some novice users might find this a bit harder to use, so if there is a way to preserve the dropdowns we have right now would be very helpful (option? Keep both the dropdowns and the new language? Hide the old filters behind a button?).

**Comment by yagebu** [comment]
I'd be against keeping them since the filter form is already too convoluted IMHO. Tags and links would work as is, so there's really no need to keep that input and the FROM filter is not for novice users anyway. Regarding the payee filter, I don't think that the syntax `payee:Name` is too hard to understand.

**Comment by aumayr** [comment]
> I'd be against keeping them

I see your point, it would not really make it harder for novice users 👍

**Comment by yagebu** [comment]
[I'm intending to update the autocompletion too so that one would still get completions for payees of course, otherwise it would indeed be a step back for some use cases]

**Comment by zacchiro** [comment]
Nothing more to add, just wanted to thank you for your discussion about this issue. FWIW, I also like the idea of a minimal UI with a flexible "search engine style" query language.

**Comment by yagebu** [comment]
Superseded by #632.
