### ISSUE TITLE
Exclude all postings to a set of accounts

### ISSUE THREAD

**Issue by SirVer** [beancount/fava#604]
This might be possible with the current implementation and I just do not know how, so this might be more of a question than a feature request.  Is it possible with a filter to exclude all expenses that go to accounts matching a regular expression?

My use case: I have "real" (food, rent, electricity) expenses and "virtual" (tax) expenses. I'd like to compare "real" expenses over time to see how much more expensive my lifestyle got - for this I'd like to exclude "virtual" expenses from all reporting on all pages. Right now I approximate this by having `Expenses:R:Food` and `Expenses:V:Tax2017` accounts - but that is quite clunky. Is there a better way?

**Comment by yagebu** [comment]
>  Is it possible with a filter to exclude all expenses that go to accounts matching a regular expression?

The filters only apply to complete transactions and not single postings (to keep the accounting equation satisfied). Are there transactions that have postings to both "real" and "virtual" expense accounts? If not, you can write a regular expression to filter the virtual ones out I guess.

**Comment by SirVer** [comment]
> Are there transactions that have postings to both "real" and "virtual" expense accounts?

Yes, that is the case. For example my paycheck, some goes to taxes (virtual), some to insurance (real). I'll keep using the workaround for now then. Thanks!

**Comment by yagebu** [comment]
This is actually something that I've been wanting to do too. I've written a small plugin (https://github.com/beancount/fava-plugins/pull/4/files, nearly done) that splits these transactions into one containing all income and taxes, transferring the difference to a "net income" account, and one containing the net income and the asset accounts involved. The former transaction is tagged, so by filtering out this tag, you're just left with your net income and the "real" expenses.

**Comment by yagebu** [comment]
I've merged the PR, and the plugin can be installed with `pip3 install fava-plugins`, so I'm closing this issue.
