### ISSUE TITLE
Confirmaton to save changes in editor and autosave editor option

### ISSUE THREAD

**Issue by Vanav** [beancount/fava#605]
Currently if I make some changes to editor and then switch to other tab or close browser, unsaved changes are lost without confirmation. This often leads to data loss and is not an expected behavior.

I suggest:
1) on switch to other tab or closing browser ask for confirmation: "Save? Yes/No".
2) add an option to autosave any changes on tab switch or browser close.

Other requests for this fix: #191.

**Comment by yagebu** [comment]
Closed in bb5ade85c40cf2f7fcdc29b5f92d01aa9d8fdda1
