### ISSUE TITLE
Navigation in editor by arrow keys is interrupted by autocomplete popup (focus is lost)

### ISSUE THREAD

**Issue by Vanav** [beancount/fava#606]
If I move cursor in editor window with keys Up, Down, Home, End, PgUp, PgDown, and cursor happens to stop on word with autocomplete popup, then popup appears and navigation with keys can't be continued: focus is stolen by popup.

Is there any workaround to show popup only by hotkey?

**Comment by aumayr** [comment]
I also experience some weird behavior with the autocomplete popup, like as @Vanav describes.

**Comment by yagebu** [comment]
What we currently do (https://github.com/beancount/fava/blob/master/fava/static/javascript/editor.js#L147) is basically the same as this SE answer: https://stackoverflow.com/a/33021864. There are some other answers that suggest excluding more keys. Any help on fixing this would be very welcome and should be easy! (If you've got any questions on how to get started, just ask)

**Comment by aumayr** [comment]
@Vanav I implemented a fix in PR #639 - Can you test this code and report back if it works as you expect/fixes this behavior?

**Comment by Vanav** [comment]
@aumayr, ah, I've did similar fix a day ago, just was testing internally: PR #641. Now you can choose one or both.
