### ISSUE TITLE
Render commas according to Indian system

### ISSUE THREAD

**Issue by balaramadurai** [beancount/fava#614]
Hello,
  I love fava and beancount. This is a fantastic and powerful personal finance system.

I live in India and we follow a different numbering system (the placement of the commas in currency) as compared to the rest of the world. Reference - [Indian numbering system](http://en.wikipedia.org/wiki/Indian_numbering_system)

Would it be possible to include an option in render_commas to include the locale like in here - https://stackoverflow.com/a/40952632?

Thanks and have a great day!
Bala

**Comment by blais** [comment]
https://bitbucket.org/blais/beancount/issues/204/add-international-support-for-rendering
