### ISSUE TITLE
metadata is discarded from imported transactions

### ISSUE THREAD

**Issue by johannesjh** [beancount/fava#615]
I have an importer that adds metadata to the transactions to be imported. Specifically, it adds a `__source__` field with the original line from the CSV file. Example output from the importer:

    2017-07-03 * "Bezahlung Karte Hornbach Baumarkt"
      __source__: "AT123400000012345678;Bezahlung Karte Hornbach Baumarkt;03.07.2017;30.06.2017;-42,75;EUR"
      Assets:Current:Joh:PSK  -42.75 EUR
      Expenses:Household                

When I use the fava import GUI with this importer, then unfortunately the metadata `__source__` field is discarded. i.e., it does not show up in the GUI and it is not saved as result of the import.

**Comment by yagebu** [comment]
I think the Beancount code we use to render transactions simply doesn't render out metadata. Also if it, it shouldn't render out `__source__` which is something used internally in Fava's import system - it would be good to render other metadata (and you could add it as `source:`) though.

**Comment by yagebu** [comment]
Actually, it does render out metadata - but the `__source__` one is stripped since it's internally used by the importer. It shouldn't show up in the source just like the `__duplicate__` metadata IMHO. As noted above, just set a `source` metadata key or so.
