### ISSUE TITLE
Links do not open

### ISSUE THREAD

**Issue by pmatos** [beancount/fava#616]
While trying to click on the link to open the help on the import system, I get a failed to open url.

Screenshot attached. Python 3.6.2, running on localhost, Fedora 27,  firefox 58.

![2017-12-07-131533_1654x403_scrot](https://user-images.githubusercontent.com/7911/33714876-e7a69f58-db50-11e7-99a0-fc6ef1ff2d6e.png)

**Comment by aumayr** [comment]
Thanks for reporting! I can reproduce this.
