### ISSUE TITLE
Truncated or oversized response headers

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#624]
I'm trying to deploy Fava behind Apache with mod_wsgi but I'm hitting an "Truncated or oversized response headers received from daemon process" that I'm unable to further debug. This is most definitely a deployment problem, but as I'm in fact trying to produce ready-to-use deployment examples to contribute to the fava doc, I'm reporting it here. Feel free to close if you think it's inappropriate.

Details follow.

Apache configuration:
```
WSGIScriptAlias /beancount /srv/www/servername.example.com/beancount/fava.wsgi
WSGIDaemonProcess servername.example.com processes=1 threads=2 display-name=%{GROUP}
WSGIProcessGroup servername.example.com
WSGIApplicationGroup %{GLOBAL}
```
fava.wsgi script:
```
from fava.application import app as application
from fava.application import load_file
appplication.config['BEANCOUNT_FILES'] = ['/srv/www/servername.example.com/ledger/current.beancount']
load_file()
```
The WSGI script (+ application.run() at the end) works fine by hand (with no errors/warnings on stdout/stderr):
```
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fava.application import app as application
>>> from fava.application import load_file
>>> application.config['BEANCOUNT_FILES'] = ['/srv/www/servername.example.com/ledger/current.beancount']
>>> load_file()
>>> application.run()
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
^C>>> 
```
But fails with a 500 HTTP error when run by apache/mod_wsgi. Even with loglevel set to debug, all I get from Apache logs is:
```
[Sat Dec 30 09:45:49.289932 2017] [wsgi:info] [pid 3706] [remote 87.7.49.170:18568] mod_wsgi (pid=3706, process='servername.example.com', application=''): Loading WSGI script '/srv/www/servername.example.com/beancount/fava.wsgi'.
[Sat Dec 30 09:45:49.708503 2017] [wsgi:error] [pid 3711] [client 87.7.49.170:18568] Truncated or oversized response headers received from daemon process 'servername.example.com': /srv/www/servername.example.com/beancount/fava.wsgi, referer: https://servername.example.com/
[Sat Dec 30 09:45:49.708810 2017] [ssl:debug] [pid 3711] ssl_engine_io.c(1044): [client 87.7.49.170:18568] AH02001: Connection closed to child 4 with standard shutdown (server servername.example.com:443)
[Sat Dec 30 09:45:50.428928 2017] [wsgi:info] [pid 3794] mod_wsgi (pid=3794): Attach interpreter ''.
[Sat Dec 30 09:45:50.432952 2017] [wsgi:debug] [pid 3794] src/server/mod_wsgi.c(8815): mod_wsgi (pid=3794): Started thread 0 in daemon process 'servername.example.com'.
[Sat Dec 30 09:45:50.433037 2017] [wsgi:debug] [pid 3794] src/server/mod_wsgi.c(8815): mod_wsgi (pid=3794): Started thread 1 in daemon process 'servername.example.com'.
```
I welcome suggestions on how to further debug this.

Thanks a lot for fava!

**Comment by yagebu** [comment]
The `threads=2` might be problematic, have you tried without it?

**Comment by zacchiro** [comment]
@yagebu just tried that, but it didn't help ­— same symptoms.
Thanks for the idea though!

**Comment by yagebu** [comment]
There are some troubleshooting tips in Flask's docs (the web framework that Fava uses): http://flask.pocoo.org/docs/0.12/deploying/mod_wsgi/#troubleshooting. If none of those help, you should try to get some more verbose logging somehow, otherwise I don't think I'll be able to help with this.

**Comment by yagebu** [comment]
@zacchiro: did you have any more luck troubleshooting this? It's odd that this error happens right when the WSGI starts and not when a request is made. Maybe `load_file()` is taking too long and this somehow confuses `mod_wsgi`...

**Comment by zacchiro** [comment]
Not really, and as it works with --prefix/ReverseProxy I'm not terribly motivated in debugging this issue further. What I'd love to see is complete details of a *functioning* setup with mod_wsgi, so that I can exclude configuration errors on my part and drill down on what doesn't work.

What you suggest is plausible, I've a non-trivial beancount file (40k lines, 1.4 MB), but in the ReverseProxy setup performances are really good, and a slow down of a few seconds is noticeable only when asking to render the full ledger. So I'm skeptical that is the cause.

**Comment by yagebu** [comment]
I'll close this issue then. As Fava is mostly designed to be used by a single user (and it's not very IO heavy), there's not much to be gained from running in a very different way. And if we put some effort into supporting some different deployment options I'd prefer something that has cross-server support. Also the fact that `mod_wsgi` only gives some crappy unhelpful logs and errors in case of failure doesn't really suggest it as a sensible deployment option.

> What you suggest is plausible, I've a non-trivial beancount file (40k lines, 1.4 MB), but in the ReverseProxy setup performances are really good, and a slow down of a few seconds is noticeable only when asking to render the full ledger. So I'm skeptical that is the cause.

Yes after the file is loaded the pages render quite quickly, but the initial load will take a few second and if mod_wsgi expects it to be ready soon that could be a problem.

**Comment by yagebu** [comment]
@zacchiro: I've removed load_file, so the code in the WSGI should now run instantaneously. Does that help with this?

**Comment by bilalbaqar** [comment]
It used to be a [bug]( https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=758035) in mod-wsgi 4.2.
