### ISSUE TITLE
allow to customize /static dir URL

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#625]
The `static/` dir of Fava isn't shipped by setup.py.
So, as I understand it, it is up to the people willing to deploy a stable Fava server to deploy it by hand out of the Fava Git repository. Can you confirm this is the case?

If so, it would be nice if the path of the static folder used by the the Fava Web UI could be customized, because on servers that also host other applications the `/static` URL is very likely to be crowded.

Something like `app.config['STATIC_FOLDER']`, as suggested in [this Flask snippet](http://flask.pocoo.org/snippets/102/), would be perfect.

**Comment by yagebu** [comment]
> The static/ dir of Fava isn't shipped by setup.py.

It is. See MANIFEST.in.

For deploying Fava side-by-side with other applications, I'd recommend using a prefix (there's a CLI option for it and if you want to use it in a WSGI app, see fava/cli.py on how this is set up). As Fava will use the Beancount file names for the URLs, you might run into other collisions too otherwise.

**Comment by zacchiro** [comment]
> It is. See MANIFEST.in.

Well, the whole `static/javascript/` dir is (implicitly) pruned, and the same goes for `static/css/`.
Is that the intended behavior then?

I'll give a try to the CLI option, thanks!

**Comment by zacchiro** [comment]
So, I've now tried with ReverseProxy, but I'm getting no love from fava either.
Fava is running like this:
```
$ fava --prefix /beancount
* Running on http://localhost:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Dec/2017 12:05:12] "GET // HTTP/1.1" 200 -
```
And Apache is configured like this:
```
ProxyPass "/beancount" "http://localhost:5000/"
```
When I access servername.example.com/beancount all I get is an empty page (it's an actual empty HTTP response body, no markup no anything). Even if fava itself is receiving and answering it, as shown in the log message above.

I've tried a variation of prefix with and without leading/trailing slashes, with no luck either. `fava --debug` didn't say anything more either.

(Again, I'm very willing to contribute doc on how to deploy fava in a non-local setting, but first I need to make it work :-))

**Comment by xentac** [comment]
Doesn't the ProxyPass line need to include the prefix because Apache strips
it off?

ProxyPass "/beancount" "http://localhost:5000/beancount"

If I understand correctly, you have told fava to only service requests
under /beancount. So when it gets s request for / it responds with nothing.
Test it out with curl (curl http://localhost:5000 and
http://localhost:5000/beancount)

**Comment by yagebu** [comment]
> Well, the whole static/javascript/ dir is (implicitly) pruned, and the same goes for static/css/.
Is that the intended behavior then?

The Javascript and CSS are compiled to static/gen, so the files in static/{javascript,css} are not needed for running Fava.

**Comment by zacchiro** [comment]
> ProxyPass "/beancount" "http://localhost:5000/beancount"

Thanks @xentac , that did the trick! I wasn't sure of the actual semantics of --prefix, but you're right that that makes fava mounting the main flask app at that URL.

For the records, only `--prefix /beancount` works properly here; removing the heading slash doesn't work (resulting in empty HTTP 200 answers again).

**Comment by zacchiro** [comment]
OK, found the root of the issue: the static bundles under gen/ weren't built when i did my original setup.py install. Now that I've built them and reinstalled all works fine (with --prefix) without any need of serving static files separately.

As it was arguably my fault, this issue can definitely be closed.

While we are at it, I think it'd be nice if setup.py would complain/fail if the gen/ bundles aren't available at install time. Feel free to rename this issue accordingly if you think that's desirable.

**Comment by yagebu** [comment]
> While we are at it, I think it'd be nice if setup.py would complain/fail if the gen/ bundles aren't available at install time. Feel free to rename this issue accordingly if you think that's desirable.

Just checking if the bundles are there wouldn't really be sufficient though, as they could be outdated. For a development install (pip install -e) one has to run `make` independently anyway so I don't think there'd be much use to integrate it into setup.py.
