### ISSUE TITLE
UnboundLocalError: local variable 'l__' referenced before assignment

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#626]
I'm getting the following traceback when accessing any functionality that relates to journal entries (the journal as a whole in the example below, but clicking on any kind of account name to get a partial journal fails in the same way).

I can reproduce this on a python 3.5 machine (Debian Stretch), when running under --prefix, but not on a python 3.6 one (Debian testing), with or without --prefix.
Backward compatibility issue with jinjia maybe?

```
fava[24064]: [2017-12-30 22:57:57,688] ERROR in app: Exception on /beancount/journal/ [GET]
fava[24064]: Traceback (most recent call last):
fava[24064]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
fava[24064]:     response = self.full_dispatch_request()
fava[24064]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
fava[24064]:     rv = self.handle_user_exception(e)
fava[24064]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
fava[24064]:     reraise(exc_type, exc_value, tb)
fava[24064]:   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
fava[24064]:     raise value
fava[24064]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
fava[24064]:     rv = self.dispatch_request()
fava[24064]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
fava[24064]:     return self.view_functions[rule.endpoint](**req.view_args)
fava[24064]:   File "/usr/local/lib/python3.5/dist-packages/fava-1.7.dev0-py3.5.egg/fava/application.py", line 280, in report
fava[24064]:     return render_template('{}.html'.format(report_name))
fava[24064]:   File "/usr/lib/python3/dist-packages/flask/templating.py", line 134, in render_template
fava[24064]:     context, ctx.app)
fava[24064]:   File "/usr/lib/python3/dist-packages/flask/templating.py", line 116, in _render
fava[24064]:     rv = template.render(context)
fava[24064]:   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 989, in render
fava[24064]:     return self.environment.handle_exception(exc_info, True)
fava[24064]:   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
fava[24064]:     reraise(exc_type, exc_value, tb)
fava[24064]:   File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
fava[24064]:     raise value.with_traceback(tb)
fava[24064]:   File "/usr/local/lib/python3.5/dist-packages/fava-1.7.dev0-py3.5.egg/fava/templates/journal.html", line 3, in top-level template code
fava[24064]:     {% import '_journal_table.html' as journal_table with context %}
fava[24064]:   File "/usr/local/lib/python3.5/dist-packages/fava-1.7.dev0-py3.5.egg/fava/templates/_layout.html", line 43, in top-level template code
fava[24064]:     {% block content %}{% endblock %}
fava[24064]:   File "/usr/local/lib/python3.5/dist-packages/fava-1.7.dev0-py3.5.egg/fava/templates/journal.html", line 6, in block "content"
fava[24064]:     {{ journal_table.journal_table(ledger.entries) }}
fava[24064]:   File "/usr/local/lib/python3.5/dist-packages/fava-1.7.dev0-py3.5.egg/fava/templates/_journal_table.html", line 67, in template
fava[24064]:     <a href="{{ url_for('download_journal', account=account_name) if account_name else url_for('download_journal') }}" class="button" title="{{ _('Export Journal as a Beancount file') }}" data-remote>{{ _('Export') }}</a>
fava[24064]: UnboundLocalError: local variable 'l__' referenced before assignment
fava[24064]: 127.0.0.1 - - [30/Dec/2017 22:57:57] "GET /beancount/beancount/journal/?partial=true HTTP/1.1" 500 -
```

**Comment by zacchiro** [comment]
FWIW, I've tried deploying on a dedicated hostname, removing the need of --prefix, but this issue is still present.

**Comment by yagebu** [comment]
> Backward compatibility issue with jinjia maybe?

Does installing a newer version of jinja fix it?

Could you also try to see if replacing the '.. if .. else ..' with just the else part fix it?

**Comment by zacchiro** [comment]
On Wed, Jan 03, 2018 at 06:54:14AM -0800, Jakob Schnitzer wrote:
> Does installing a newer version of jinja fix it?

Yes, upgrading jinja2 from 2.8 to 2.10 made the issue go away; reverting
back makes it reappear, so it looks like we have a culprit.

> Could you also try to see if replacing the '.. if .. else ..' with
> just the else part fix it?

I've tried applying this diff:
https://upsilon.cc/~zack/stuff/_journal_table.html.diff but it didn't
fix the issue. I get the same traceback, on the same line.

**Comment by yagebu** [comment]
> Yes, upgrading jinja2 from 2.8 to 2.10 made the issue go away

Could you also try 2.9, so that we don't bump the requirement unnecessarily?

**Comment by zacchiro** [comment]
> Could you also try 2.9, so that we don't bump the requirement unnecessarily?

Not easily unfortunately, as I don't have a Debian package handy of that
version.

**Comment by yagebu** [comment]
This code was moved and changed in #630, does this error still occur with jinja2 2.8?

**Comment by zacchiro** [comment]
On Sun, Jan 07, 2018 at 09:58:10PM +0000, Jakob Schnitzer wrote:
> This code was moved and changed in #630, does this error still occur with jinja2 2.8?

After the most recent Fava upgrade the Web UI is completely broken for
me, every UI interaction I try fail with the following traceback in the
browser console:

app.js:25607 Uncaught (in promise) TypeError: Cannot read property 'value' of null
    at updateInput (app.js:25607)
    at app.js:25621
    at Array.forEach (<anonymous>)
    at app.js:25615
    at app.js:2388
    at Array.forEach (<anonymous>)
    at Events.trigger (app.js:2387)
    at app.js:26071
    at <anonymous>

(yes, I've done make to regenerate gen/ stuff and reinstalled locally)

So I'm unfortunately currently unable to answer your question.

Cheers.

**Comment by zacchiro** [comment]
[ disregard my previous message, I didn't restart the Fava service ]

On Sun, Jan 07, 2018 at 09:58:10PM +0000, Jakob Schnitzer wrote:
> This code was moved and changed in #630, does this error still occur with jinja2 2.8?

I've now retried with the current HEAD (commit
470735d5dc162ccd8fff71de3e6d089d8af00cb2 ) and jinja2, the bug is still
there. If I upgrade jinja2 to 2.10, it goes away again.

HTH,

**Comment by yagebu** [comment]
I'll bump the jinja2 dependency then.

Thank you very much for the help debugging this and the other issues you discovered!
