### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#627]
In a Fava instance running behind HTTP auth and ReverseProxy with --prefix, I'm hitting repeatedly the following Javascript exception, logged in my browser (Chromium) console:
```
app.js:25545 Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at app.js:25545
    at app.js:2361
    at Array.forEach (<anonymous>)
    at Events.trigger (app.js:2360)
    at app.js:16720
    at <anonymous>
```
This seems to be the cause of a bunch of misbehaving UI elements, such as:
- the income statement > net profit chart, usually shown as homepage, does not load and "loading charts ..." remains. If i click on another menu item and then come back to income statement, it does appear
- the current page is often not highlighted in the sidebar and the previous visited page remains highlighted
- when the screen is narrow and the sidebar is hidden (due to responsiveness adjustment), clicking on the 3 vertical dots does not open the sidebar making impossible to navigate

Here is my built [app.js](https://upsilon.cc/~zack/stuff/app.js), for cross referencing line numbers in the traceback above.

**Comment by zacchiro** [comment]
FWIW, I've tried deploying on a dedicated hostname, removing the need of --prefix, but this issue is still present.

**Comment by yagebu** [comment]
The js is outdated. Run `make`

**Comment by zacchiro** [comment]
Thanks! That was it.
Closing.
