### ISSUE TITLE
Let me choose my language please

### ISSUE THREAD

**Issue by MarkusTeufelberger** [beancount/fava#629]
While my browser or OS might be set to German, I don't want to use Fava exclusively in German. Please make the language configurable.

**Comment by aumayr** [comment]
You can set the language by adding this to your beancount file:

```
2018-01-02 custom "fava-option" "language" "en"
```

See https://github.com/beancount/fava/blob/master/fava/help/options.md for more options.

**Comment by aumayr** [comment]
(Feel free to reopen if this does not work.)

**Comment by MarkusTeufelberger** [comment]
https://github.com/beancount/fava/blob/master/fava/help/features.md#language is a bit less specific about this.

**Comment by MarkusTeufelberger** [comment]
Oh and thanks a lot for the extremely fast reaction. It works as documented! :+1:
