### ISSUE TITLE
link metadata to filter expressions in journal views

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#633]
Now that we have filtering on metadata values (YAY #603 !), it seems sensible to link metadata values rendered in individual journal transactions to filter updates.

For instance, if I've a transaction like this:
```
2018-01-01 * coffee
    trip: "2017-12-20-beijing-holiday"
    Expenses:Dining:Bar  2.00 EUR
    Expenses:Cash
```
Clicking on the trip line should update the current filter and add `trip: "2017-12-20-beijing-holiday"` as a condition. This would be consistent with what happens when clicking on account names.

The current behavior is to simply fold/unfold the transaction details.

**Comment by yagebu** [comment]
Sounds good. It should be implemented in Javascript to not increase the size of the page markup (and template generation performance).

**Comment by zacchiro** [comment]
wow, that was quick :-)
thanks a lot!

**Comment by zacchiro** [comment]
has there been a regression in this?

what I'm seeing in a Fava deployment from Git dated 2018-08-04 is this:

- open journal view, find transactions with links, tags, and/or metadata values
- tags and links are shown immediately on the right of narrations/payees and are indeed hyperlinks that update the current search filters
- metadata values are shown on the far right of the journal line (below the "Cost" column, not sure why) and abbreviated to two-letter prefixes, e.g., "au" for "author", "tr" for "trip", etc. But they are not hyperlinks that updated the selection filters, rather, clicking on them just fold/unfold the transaction

am I missing something?

**Comment by zacchiro** [comment]
On Tue, Aug 21, 2018 at 05:57:38AM -0700, Jakob Schnitzer wrote:
> You need to click the "Metadata" button to show metadata below the
> entry line - those are clickable, the little round ones are just there
> to show on a quick glance which entries have metadata. This part of
> the journal hasn't changed since this issue was closed though if I
> recall correctly ;)

Weird, I'm pretty sure I did try this when you fixed this issue, but I
couldn't find this time before your tip. Oh well, it was PEBKAC anyway.
Thanks for your quick feedback and my apologies for the noise! :-)
