### ISSUE TITLE
How to use a given date for a price within a report?

### ISSUE THREAD

**Issue by ludenticus** [beancount/fava#635]
In a similar fashion of issue #242, I'm trying to see some transactions in one single currency. However, I haven't been able to figure out if Fava can «convert» from the price of a given date. For instance:

```
2018-01-05 price USD 19.423805485 MXN
2018-01-10 price USD 19.55 MXN

2018-01-05 * "Online purchase"
	Assets:Bank:Savings		35.37 USD @@ 687.02 MXN
	Assets:Bank:Savings		-687.02 MXN
	Assets:Bank:Savings		-35.37 USD
	Expenses:Clothing		35.37 USD
```

Instead of `682.02 MXN` (which was the actual cost), fava reports `691 MXN`, based on the latest price. It doesn't change if I use `{{ 687.02 MXN }}` instead. I'm tempted to put the transaction in MXN and write the original amount in a comment, but I'd prefer to see as well the original price.

As a consequence, I'd like to ask:

1. Is there a better way to report online transactions involving different currencies?
2. Can I somehow always keep the actual cost across reports?

**Comment by yagebu** [comment]
To change the date the prices are fetched, you can set a time filter (then the latest price before the end of the filter will be used).

Generally Beancount assumes that the cost of currencies is irrelevant so the cost won't be stored (if only a price and no cost is given). To have them reported like commodities, giving a cost should work. If you select 'Converted to ...', the conversion will always use the price. If you select 'at cost', the cost will be displayed if there's one.

Note that two simpler posting lines should actually suffice:

      Assets:Bank:Savings    687.02 MXN
      Expenses:Clothing       35.37 USD @

or, to have them reported at cost

      Assets:Bank:Savings    687.02 MXN
      Expenses:Clothing       35.37 USD {}

**Comment by ludenticus** [comment]
Thanks for the answer.

This is what I was looking for to report at cost:

```
2018-01-05 * "Online purchase"
  Assets:Bank:Savings    687.02 MXN
  Expenses:Clothing       35.37 USD {}
```
