### ISSUE TITLE
Add support for code folding in editor

### ISSUE THREAD

**Issue by jmgilman** [beancount/fava#636]
For unruly beancount files, code folding in the web editor would be a useful feature. As it stands, I think just being able to fold on transactions as well as comments would be an improvement. My typical file will look like:

    ; Some fancy title
        2018-01-11 * "Foo" "Bar"
            Assets:One:Two -15.00 USD
            Expense:One:Two

    ; Another title
        <another transaction>

This way I can group transactions together under each title and quickly hide/show these groups with folding.

**Comment by yagebu** [comment]
Code folding is already implemented :) Markdown (`#`) and org-mode headings (`*`) are supported

**Comment by jmgilman** [comment]
Can you show a screenshot of how that works? Since ```#``` and ```*``` are not valid syntax for Beancount, how are we intended to use them for folding?

**Comment by jmgilman** [comment]
Never mind, didn't realize the example site was using org mode. Makes sense now, thanks!

**Comment by yagebu** [comment]
> Since # and * are not valid syntax for Beancount, how are we intended to use them for folding?

In Beancount, any invalid character at the start of a line will lead to the line being ignored, so in some sense, invalid characters are valid at the beginning of a line.
