### ISSUE TITLE
Make it possible to query for an intersection of tags

### ISSUE THREAD

**Issue by kamalmarhubi** [beancount/fava#638]
The tags query box is really useful, but it'd be great to be able to specify an intersection of tags to query on.

Strawman syntax: `+#tag` to specify required tags.

**Comment by yagebu** [comment]
Just give a list of tags separated by spaces. The syntax is specified on the 'Filtering entries' help page.

**Comment by yagebu** [comment]
Ignore my previous comment if you're running the stable version of Fava: The filters have been changed (#632) and this will be possible in the next release.

**Comment by kamalmarhubi** [comment]
Ah, thanks for the info. I was running stable but just upgraded to current master. Good to know this stuff is changing, as I only just started using fava & beancount. Saves me learning the obsolete way. :-)
