### ISSUE TITLE
Transaction form: Auto-fill postings depending on payee

### ISSUE THREAD

**Issue by yagebu** [beancount/fava#643]
Even though the autocomplete makes the entry form quite easy to use, for my daily transactions, I tend to use my editor, as copy-pasting and then changing one number feels quicker than tabbing through all the input fields.

This could be changed by the following change/improvement: When entering a payee (in an otherwise empty form), all the other fields could be filled with the data from the last transaction with that payee.

**Comment by aumayr** [comment]
Sounds very reasonable and quite helpful to me.

For my habits: I often try to match the way a narration is written for the same payee, eg. "Telecom bill #recurring-monthly" for the Telecom-payee. This change would speed up this task immensely, as now I either have to recall it from memory or look up how I wrote it last time.

**Comment by yagebu** [comment]
Closed in #668
