### ISSUE TITLE
Wrong number of decimals displayed when using `include`

### ISSUE THREAD

**Issue by potz** [beancount/fava#644]
I came accross an interesting bug, it seems that when using the include directive the DisplayContext gets a bit confused.

Here is a sample file:

```
option "title" "Portfolio"
option "operating_currency" "USD"
option "render_commas" "true"

2015-01-01 open Assets:Cash
2015-01-01 open Assets:Wallet
2015-01-01 open Equity:Capital

2015-01-02 * "Bitcon Purchase"
  Assets:Wallet                                 1.06146971 BTC {942.09 USD}
  Assets:Cash                              -1,000.00 USD
```

Fava renders this file's balance sheet as expected (extra decimal places on Conversions account are not displayed):

<img width="992" alt="screen shot 2018-01-19 at 18 02 12" src="https://user-images.githubusercontent.com/5178184/35169230-f30180b6-fd42-11e7-8021-a99557541629.png">

Now if I just remove the same transaction from the main file and put it in a separate file:

```
; Contents of main.bean
option "title" "Portfolio"
option "operating_currency" "USD"
option "render_commas" "true"

2015-01-01 open Assets:Cash
2015-01-01 open Assets:Wallet
2015-01-01 open Equity:Capital

include "bitcoin.bean"
```

```
; Contents of bitcoin.bean
2015-01-02 * "Bitcon Purchase"
  Assets:Wallet                                 1.06146971 BTC {942.09 USD}
  Assets:Cash                              -1,000.00 USD
```

Then fava renders a lot of decimals that I don't want to see:

<img width="999" alt="screen shot 2018-01-19 at 17 59 00" src="https://user-images.githubusercontent.com/5178184/35169293-2a19a678-fd43-11e7-83b4-b3edea48401a.png">

I wonder if this is somehow related to  #9 (which was the only thing that seemed related when I searched)

**Comment by potz** [comment]
Just found a workaround, if anyone's interested:

I added a zero balance with my desired number of decimal places to all accounts on the main file:

```
; Contents of main.bean
option "title" "Portfolio"
option "operating_currency" "USD"
option "render_commas" "true"

2015-01-01 open Assets:Cash
2015-01-01 open Assets:Wallet
2015-01-01 open Equity:Capital

2015-01-01 * "Initial Balances"
  Assets:Wallet                                 0.00000000 BTC
  Assets:Cash                                   0.00 USD
  Equity:Capital                                0.00 USD

include "bitcoin.bean"
```

This seems to make it use the correct formatting info for some reason.

**Comment by Argentumbolo** [comment]
I saw the same issue with currency which I registered as currency, have prices for it, but don't have any accounts with it yet.
And then if I use *Convert to GBP*: **2.014471980739032382543143484 GBP**

**Comment by aumayr** [comment]
Thanks for the bug report, @potz and @Argentumbolo!

What does beancount itself output (on the command line)?

**Comment by Argentumbolo** [comment]
Just usual log:
`127.0.0.1 - - [21/Jan/2018 14:56:56] "GET /beancount/balance_sheet/?interval=day&conversion=GBP&partial=true HTTP/1.1" 200 -
`

I reproduce it on this simple file: [beancount.txt](https://github.com/beancount/fava/files/1649760/beancount.txt)
With each currency except the *UAH*:

**Comment by yagebu** [comment]
This is a limitation on Beancount's part. The options from included files (of which the so called "display context" for currencies is part of) are only aggregated in a somewhat limited way.

Ref https://bitbucket.org/blais/beancount/issues/166/inconsistent-rendering-of-decimal-numbers, https://bitbucket.org/blais/beancount/issues/150/review-behaviour-of-options-and-plugins

**Comment by Argentumbolo** [comment]
> The options from included files (of which the so called "display context" for currencies is part of) are only aggregated in a somewhat limited way.

Not exactly the same, because in file [beancount.txt](https://github.com/beancount/fava/files/1649760/beancount.txt) I don't use any includes.

**Comment by yagebu** [comment]
@Argentumbolo: The issue you described is different from the initial issue: In your file, the currency GBP is never used in an amount, so there's no way to deduce the most common number of decimal digits.
