### ISSUE TITLE
Holdings average_cost does is not weighted

### ISSUE THREAD

**Issue by tarioch** [beancount/fava#645]
As far as I'm able to tell, the average_cost from the holding queries is not weighted.

I.e. if I have the following holdings

5000 @ 1 X
1 @ 2 X

then the average should be ~1 but it's 1.5

**Comment by tarioch** [comment]
I think it should be something like book_value / units but I wasn't able to do this with a query

**Comment by yagebu** [comment]
Hey, thanks for the report. I've just removed the average_cost column from the 'by account' and 'by cost currency' tables - there it doesn't make much sense to have the column as it might aggregate over several different currencies.

You're quite right, the current `average_cost` is broken. In addition to the problem you mention it also factors in the cost of positions that have been sold already. The following query calculates book_value/units:

    number(only(first(cost_currency), cost(sum(position))))/number(only(first(currency), units(sum(position)))) as average_cost

However: if units is zero, we divide by zero (once Beancount implements `HAVING` this shouldn't be a problem anymore). I don't see any other way to implement this using the current BQL, so I've removed it from the report for now.

**Comment by yagebu** [comment]
Mhh, maybe this wouldn't even work if `HAVING` was implemented - these invalid decimal divisions would still occur somewhere I guess.

@blais: Would it be possible to ignore invalid decimal operations in the BQL to allow for this kind of query?

**Comment by blais** [comment]
File a ticket with a specific query which you think shouldn't fail and I
can look at it.
It could spit a warning and ignore that row? Is that reasonable?
