### ISSUE TITLE
--cumulative switch for budget feature

### ISSUE THREAD

**Issue by gour** [beancount/fava#650]
Hello,

recently I switched from Gnucash to hledger and, for me, the killer feature is 'envelope budgeting' as described [here](http://hledger.org/budgeting-and-forecasting.html), so I wonder if Fava'a budget feature could get something like  `--cumulative` switch in order that unused amounts for e.g.g monthly budgets do move to the next month and therefore enabling one to have better picture for the whole (yearly) budget?

No need to say, that Fava's reporting features are great, so we would like to have best of the both worlds...

**Comment by yagebu** [comment]
See also https://github.com/beancount/fava/issues/375#issuecomment-313710002. I don't know if Fava's budget capabilities are not a bit too lightweight for envelope budgeting. With envelope budgeting, I guess at some point maybe at the end of the year, you'd want to reset the budgets, right? If we have to add more budget directives and start doing account balance calculations, the plugin approach might be better suited to do envelope budgeting in Fava.

**Comment by gour** [comment]
>  I don't know if Fava's budget capabilities are not a bit too lightweight for envelope budgeting...

You're right - I'll stay with hledger...

**Comment by yagebu** [comment]
Keeping #909 open in favour of this one.
