### ISSUE TITLE
Past queries get HTMLified, leading to LexToken error

### ISSUE THREAD

**Issue by tbm** [beancount/fava#654]
I go to the query tab and enter:

> SELECT account WHERE date < 2016-01-01;

It runs correctly.

I then click on the query tab again and now the query shows up as:

> SELECT account WHERE date &lt; 2016-01-01;

and running it gives:

> Unknown token: LexToken(error,'&lt; 2016-01-01;',1,26)

**Comment by sarg** [comment]
Seems that github replaces html entities in comments.
It should be read as:
> I then click on the query tab again and now the query shows up as:
> `SELECT account WHERE date &lt; 2016-01-01;`
> and running it gives:
> `Unknown token: LexToken(error,'&lt; 2016-01-01;',1,26)`

**Comment by tbm** [comment]
Thanks!
