### ISSUE TITLE
Clear "Permission denied" error when navigating to another tab

### ISSUE THREAD

**Issue by tbm** [beancount/fava#658]
On the favadev demo, I try to edit and save a transaction and a red "Permission denied" error pops up on the top right.

I then navigate to another tab and the red error is still there.

Maybe it should be cleared when you navigate away?

(Feel free to close if you disagree. I'm just sharing some random ideas...)

**Comment by tbm** [comment]
Same with "Stored 1 entries." (in green) after I add a new transaction.

**Comment by yagebu** [comment]
I don't think it should be closed by navigating away from the page as it's not necessarily related to the current report. Adding a timeout to remove them automatically after a few seconds would be good though (as is currently done for the reload notifications).

**Comment by tbm** [comment]
That sounds good to me!
