### ISSUE TITLE
Conversion (at cost, at market value, etc) not intuitive

### ISSUE THREAD

**Issue by tbm** [beancount/fava#659]
The account page which offers conversion (at cost, at market value, conversion to XXX) is not very intuitive.

1) In the default view (Account journal), none of the options have ANY effect. So why offer the conversion option there?

2) Ok, I figure out to click on "Balances (monthly)".  Now the table below changes.  But the chart doesn't change.  Even though it says "Account balance", it doesn't show the account balance at market value or whatever.  It always shows the number of units I own.

I don't know how to address this best but as a start I would:

1) Add a column to the "Account journal" view. Currently it shows the "Balance" (units commodity). It should also show the balance in USD (or whatever currency) according to the conversion option chosen.

2) The chart should be updated accordingly.

**Comment by tbm** [comment]
I think it might be best to reopen #662 again.  That described a very specific bug (what I have as bullet point 2) above whereas this issues describes a number of potential and I think I need to sit down and describe them again in a more coherent way.

**Comment by yagebu** [comment]
#742 should address this. With it, the selected conversion will apply consistently and everywhere
