### ISSUE TITLE
Should Commodities tab be renamed to Prices?

### ISSUE THREAD

**Issue by tbm** [beancount/fava#660]
The "Holdings" tab displays the information I would expect to see when I see a tab called "Commodities".

What "Commodities" shows is really historical prices.  Why is it not called "Prices"?

**Comment by yagebu** [comment]
Don't have a strong opinion on "Commodities" vs "Prices". I think both terms are appropriate, the report is telling you something about your held commodities, namely the prices. For symmetry with bean-web, I have a slight preference for "Commodities".

**Comment by tbm** [comment]
> the report is telling you something about your held commodities, namely the prices

I guess that's a good point.  And symmetry with bean-web makes sense too.

If you don't mind, can you leave this ticket open for a while?  I'd like to see if there's
input from other people as well as how I feel about it in a few weeks.

**Comment by tbm** [comment]
@dholl I was going to say that this is really more of a beancount question rather than fava. But I see you commented on the beancount bug in the meantime.  Maybe it's also worthwhile to send your idea to the beancount mailing list.

**Comment by yagebu** [comment]
@tbm: Feel free to open a PR changing the name if you still feel like it
