### ISSUE TITLE
Why does "Commodities" tab offer conversion option?

### ISSUE THREAD

**Issue by tbm** [beancount/fava#661]
It's my understanding that the "commodities" tab shows historical prices.

Yet the upper right corner has a conversion box, which (afaict) doesn't change anything (neither in the chart now the tables).

Why is it there?

(Sorry, I'm probably missing something...)

**Comment by yagebu** [comment]
It's always shown when there is a chart (not that that's a good reason). I guess it should actually be available on each page, since it's part of the "app state".

**Comment by tbm** [comment]
But does it actually change the chart on the commodities tab? If it doesn't change anything (and I don't see what it would change since we're talking about historical prices here) I don't think it should be there.

**Comment by yagebu** [comment]
I think #659 should cover this, so I'll close this issue
