### ISSUE TITLE
Unable to set the "alternative" theme

### ISSUE THREAD

**Issue by murtaza52** [beancount/fava#670]
Hi,

I would like to switch to the alternative theme. 

I tried the following entry in the .beancount file -

> 2018-01-01 custom "fava-option" "themes" "alternative"

However the above gives me the following error in beancount - 

> Failed to parse fava-option entry

Can someone please help ?

**Comment by aumayr** [comment]
Hi @murtaza52,

the support for the alternative theme was removed some months ago, so it is not available anymore (and the option is gone as well).
