### ISSUE TITLE
Unrealized gains calculation leads to too much precision

### ISSUE THREAD

**Issue by tbm** [beancount/fava#682]
I use 2 digits of precision for EUR and GBP (i.e. 12.45).  However, the balance sheet and trial balance show 3 digits after the . for EUR and 4 digits for GBP.  This is because the unrealized gains are calculated as  -3059.255 EUR and -624.4931 GBP.

Please use the level of precision appropriate for each commodity (i.e. whatever the user used).

**Comment by yagebu** [comment]
>Please use the level of precision appropriate for each commodity (i.e. whatever the user used).

Fava does, we use the so-called "display context" from Beancount to render out most numbers. Can you check what it is in your case for these two currencies (on the options page)?

**Comment by tbm** [comment]
Thanks for pointing out the options page. I was wondering if this came from Beancount.

> EUR             : sign=1   integer_max=5   fractional_common=3   fractional_max=5   "-00000.000" "-00000.00000"
> GBP             : sign=1   integer_max=6   fractional_common=4   fractional_max=6   "-000000.0000" "-000000.000000"

I wonder if this is related to the bug I filed yesterday: https://bitbucket.org/blais/beancount/issues/234/cost-leads-to-too-much-precision-being

I will try to add a test case there. Thanks.

**Comment by tbm** [comment]
I filed: https://bitbucket.org/blais/beancount/issues/235/unrealized-gain-calculated-with-too-much

**Comment by yagebu** [comment]
In the example you give there, you use GBP twice in an amount, once with 2 digits of precision, once with 4 digits - so it seems correct to use 4 digits, no?

**Comment by tbm** [comment]
I cannot remember where I read it but I'm pretty sure I read that the precision of a COST would not have an impact.

**Comment by yagebu** [comment]
I meant the price directive, not the cost

**Comment by tbm** [comment]
Oh, interesting.  In ledger a price db entry also has no effect on the precision.  Maybe this is different in beancount.  If so, I think that's wrong.  Anyway, I think we should have that conversion in the beancount ticket. :)

**Comment by yagebu** [comment]
> If so, I think that's wrong

I agree. I'll close this issue - as long as we're using DisplayContexts, this is something for Beancount to handle.

**Comment by tbm** [comment]
Agreed.

Thanks for your comments.

I'm still new to beancount and fava so sometimes it's not obvious where the bug really is.

**Comment by yagebu** [comment]
> I'm still new to beancount and fava so sometimes it's not obvious where the bug really is.

It is often not clear indeed - this might be indeed be handled better by Fava too, there's definitely some more improvements to be made to the number rendering, e.g. #614.
