### ISSUE TITLE
payee autocompletion requires memo fields

### ISSUE THREAD

**Issue by bdowling** [beancount/fava#683]
@yagebu Re: #634  It looks like the autocompletion list does not populate unless you have the memo field on transactions.  I started with a ledger-to-beancount converter that doesn't add these memo fields, and also noted that the importers don't always create them either.

I started to look around for where this lies in the code to offer a PR, but TBH I haven't had the time to grok the code base yet to locate the right area

**Comment by yagebu** [comment]
> unless you have the memo field on transactions

Sorry, I don't understand this - what is the "memo field"?

**Comment by bdowling** [comment]
I thought I may have had a terminology issue after posting this.  I'm referring to the 2nd quoted field.  Examples from help.  Only the first with `"one"  "two"` quoted elements will trigger the completions.   
```2015-05-30 * "Some narration about this transaction"
  Liabilities:CreditCard   -101.23 USD
  Expenses:Restaurant       101.23 USD

2015-05-30 ! "Cable Co" "Phone Bill"
  id: "TW378743437"               ; Meta-data
  Expenses:Home:Phone  87.45 USD
  Assets:Checking    

```

**Comment by bdowling** [comment]
So I found this in the beancount docs to clarify.. So if I'm reading this correct -- without two fields a payee is not assigned?and its called the narration,  but if there are two fields the second is called the narration.  Seems a bit counter intuitive there, but does explain the autocomplete behavior I am seeing. 

> If you place a single string on a transaction line, it becomes its narration:
```2014-05-05 * "Lamb tagine with wine"
   … ```
> If you want to set just a payee, put an empty narration string:
```2014-05-05 * "Cafe Mogador" ""
   … ```

**Comment by aumayr** [comment]
Correct: 

- The fields are `payee` and `narration`
- When only one is given, it will become the `narration`, with an empty `payee`
- When you only want a `payee`, use the second example you have given (`"2015-05-06 "Cafe Mogador" ""`

**Comment by bdowling** [comment]
Sounds good. Also, currently the narration field is not used for filtering either,  correct? 

If you like we can leave this open and I will write a help docs PR when I can to help clarify this for the other new users out there. ;)

**Comment by aumayr** [comment]
You _can_ filter the narration-field, eg. with `narration:"Cappuccino"` (strings or RegExes)

> If you like we can leave this open and I will write a help docs PR when I can to help clarify this for the other new users out there. ;)

Thanks for the help!

**Comment by tbm** [comment]
@bdowling just a gentle reminder that you promised to contribute doc improvements :)

**Comment by bdowling** [comment]
Chop Chop!

Hold my feet to the fire are you? :P

Haven't forgotten,  thanks...

**Comment by yagebu** [comment]
I'll close this issue, don't really see this as high-priority thing (or rather it's something that's probably well-explained in Beancount's docs). Any docs improvements are welcome though ;)
