### ISSUE TITLE
Yellow reload warning hard to read when it overlays text

### ISSUE THREAD

**Issue by tbm** [beancount/fava#695]
Sometimes the yellow reload warning is displayed on top of some text and then it's hard to read.

![reload](https://user-images.githubusercontent.com/1556037/37878919-61fba20c-3070-11e8-8292-f313203393a8.png)

**Comment by yagebu** [comment]
I think even without any text underneath it's hard to read :D - white on yellow doesn't have the best contrast...

**Comment by tbm** [comment]
> white on yellow doesn't have the best contrast...

Agreed.

But even the white on red isn't ideal with text underneath:
![filter](https://user-images.githubusercontent.com/1556037/37900132-950a455e-30ed-11e8-963a-0d89ebd6905d.png)
