### ISSUE TITLE
Improve handling of errors on async page load

### ISSUE THREAD

**Issue by tbm** [beancount/fava#697]
When I type something invalid into the filter box (like "martin" or "test"), it takes a long time (maybe 5 seconds?) to get the error message "invalid filter".

It wasn't clear to me why this would take so long when all filters had a specific pattern (`payee`:, etc).  As it turns out, an account name is valid.  But looking up the transactions for an account shouldn't take 5 seconds.  Hmm, no, an account name is not valid. (In the filter box, not the account box)  So what is it doing for 5 seconds?

I'm not sure what's going exactly but maybe you can try if you see what I mean.

FWIW, `Ready with 13791 directives (9645 postings in 3995 transactions).`

**Comment by tbm** [comment]
BTW, it only takes 5 seconds the first time.  The second time (with the same word) it's faster.  If I pick another word it takes ~5 seconds again.

**Comment by yagebu** [comment]
Can't reproduce this at all - also grepping fava source returns no match for 'invalid filter' - are you runnning an outdated version?

**Comment by tbm** [comment]
Sorry, the error is "Failed to parse filter:".

**Comment by tbm** [comment]
I was using the last release of fava (pip3 install fava).  I had some problems installing directly from GitHub but I've finally resolved them.

The overall behaviour seems different now.  Previously, I'd see a loading icon where the fava logo is.  Now it seems the loading icon is the favicon.  (I prefer the previous behaviour to be honest).  It overall feels more sluggish to me but the invalid filter search seems a bit faster (but not very fast).

Let me play around some more later and update.

**Comment by yagebu** [comment]
> The overall behaviour seems different now. Previously, I'd see a loading icon where the fava logo is. Now it seems the loading icon is the favicon.

No - this is a build error or some javascript error - what's the js console output?

**Comment by tbm** [comment]
> No - this is a build error or some javascript error - what's the js console output?

Yeah, I think there's an installation error or something.  I opened #704 before I saw your reply.  Let's discuss that there.

**Comment by tbm** [comment]
Takes about 3 seconds with latest fava from GitHub.  I'll try to find out more details and add them here.

**Comment by tbm** [comment]
Just noticed not all of my beancount had been loaded.  Now it's slower.  So it definitely depends on how much data you have.  I'll investigate later.

**Comment by yagebu** [comment]
I assume this has nothing to do with the filter (which get's parsed quickly) but by your file being reloaded because Fava has noticed some change

**Comment by tbm** [comment]
Yeah, it seems some reload is going on.  But not because I changed my file.  It definitely didn't change.

**Comment by tbm** [comment]
btw, I understand the tokenizing stuff in `fava/core/filters.py` but what calls functions like `p_simple_expr_key`.  I don't see how you get from KEY being recognized to calling that function.

The reason I ask is because I'm trying to figure out what happens when STRING is found (not KEY STRING, but only STRING).

**Comment by yagebu** [comment]
> Yeah, it seems some reload is going on. But not because I changed my file. It definitely didn't change.

Note that changes in any of the document folders will also trigger reloads

> btw, I understand the tokenizing stuff in fava/core/filters.py but what calls functions like p_simple_expr_key. I don't see how you get from KEY being recognized to calling that function.

We use http://www.dabeaz.com/ply/index.html for the parsing, so ply calls `p_simple_expr_key` when the `simple_expr: KEY STRING` production is reduced by the parser.

Currently just `STRING` is not a valid expression of the grammar and hence the parser will throw an error.

**Comment by tbm** [comment]
@yagebu can you try fava on the attached example.  You'll see opening the journal takes about 15 seconds or so.  And when you type "foo" or "test" into the filter box it takes about the same time.

So, as you say, something is reloading the filter.  But there's no change in the file so why would the filter cause a reload?

Ah, I can't attach a compressed file. You can get it here: http://www.cyrius.com/tmp/bug697.beancount.bz2

**Comment by yagebu** [comment]
> You'll see opening the journal takes about 15 seconds or so. And when you type "foo" or "test" into the filter box it takes about the same time.

That's expected, the journal on such a big file simply takes a while to render (in both Fava and the browser). There's no reload going on.

**Comment by tbm** [comment]
Sure, I understand that opening the journal takes time. But why is there *another* delay after I type "foo" and press enter?

**Comment by yagebu** [comment]
> Sure, I understand that opening the journal takes time. But why is there another delay after I type "foo" and press enter?

Setting a filter means loading a page with the filter set, right?

**Comment by tbm** [comment]
Doh!

So to avoid the problem the filter would have to be parsed in JavaScript and I suppose that would be tricky.

**Comment by yagebu** [comment]
Mhh actually maybe not. We would have to change some internal logic though. So currently, basically all links are loaded asynchronously (with `partial=true` in the URL string) so Fava just renders the page minus header and sidebar and that is inserted into the page. In case of an invalid filter (which is quickly checked before any part of the page is rendered), we could also just throw a HTTP error (when `partial=true`) instead of rendering the page and showing the error message.

**Comment by tbm** [comment]
Yeah that sounds great.

I wonder how much work it would be actually do the filtering in JavaScript so it would never need a page reload, e.g. using [PEG.js](https://pegjs.org/) or something similar.  But your solution solves the immediate problem.  Thanks.

**Comment by yagebu** [comment]
> I wonder how much work it would be actually do the filtering in JavaScript so it would never need a page reload, e.g. using PEG.js or something similar.

Doing the filtering in JS is impossible - the reports are outputs of non-trivial "functions" on the list of entries
