### ISSUE TITLE
Filters should be case insensitive

### ISSUE THREAD

**Issue by tbm** [beancount/fava#698]
The filters are currently case sensitive. I might be wrong because I don't know how other users work, but I think case insensitive matches would make more sense.

**Comment by yagebu** [comment]
Sounds good. PR?

**Comment by tbm** [comment]
I'll look into it.

**Comment by yagebu** [comment]
`Match` in fava.core.filters does the matching - I think there's a case insensitive flag for regular expressions in python

**Comment by tbm** [comment]
beancount allows #test and #TEST as separate tags but I think if people use case sensitive tags or links they are inviting pain.  But this would be an argument not to change this.

**Comment by yagebu** [comment]
I think the tag matching should remain case sensitive - it's an exact match and the tags are suggested by the autocompletion anyway.

**Comment by tbm** [comment]
I have some uppercase, short #tags and always type it lowercase and it's shorter to type then to click on the autocompletion.  But you're probably right.  I modified the PR accordingly.
