### ISSUE TITLE
Goes back to first chart when I change "converted to"

### ISSUE THREAD

**Issue by tbm** [beancount/fava#700]
When you change "converted to", it goes to the first chart instead of showing the chart you were previously on.

Steps to reproduce:

1. I'm looking at a specific account page
2. The chart shows "Account Balance"
3. I choose "Changes"
4. I choose "converted to ..." from the box
5. The chart updates but it shows "Account Balance" instead of "Changes"

It should remember which chart I'm looking at.

**Comment by yagebu** [comment]
Changing the selected conversion option basically means reloading the page, so that kind of state is currently lost
