### ISSUE TITLE
Should invalid filter be cleared when you go to another page

### ISSUE THREAD

**Issue by tbm** [beancount/fava#706]
I enter an invalid filter and get the `Failed to parse filter` message.  It clears after a few seconds thanks to the recent fix.

But when I navigate to another page, I get another "Failed to parse filter" error.

If there's an invalid filter and you open another page, could the filter be cleared (removed)?  Obviously only if it's invalid.

**Comment by yagebu** [comment]
I don't think it should be cleared - that way you can fix it

**Comment by yagebu** [comment]
With #718, you'll be forced to fix the filter before you can change the page.

**Comment by yagebu** [comment]
You entered the filter in the first place to do some filtering, right? So if, for some reason, the filter you wrote has some invalid syntax, it should remain there for you to fix it.

**Comment by tbm** [comment]
Ok.
