### ISSUE TITLE
Date sometimes takes two lines

### ISSUE THREAD

**Issue by tbm** [beancount/fava#708]
Sometimes (not often) the date is split across two lines.  Maybe you can increase the size of the date box a bit?

![date1](https://user-images.githubusercontent.com/1556037/37964690-ac8c8400-31c2-11e8-98a0-94ca468b57c0.png)
![date2](https://user-images.githubusercontent.com/1556037/37964692-accd5f70-31c2-11e8-878b-0288a6844fea.png)

**Comment by tbm** [comment]
FWIW, this is in Chromium.  I don't see it in Firefox.

**Comment by yagebu** [comment]
#705

**Comment by tbm** [comment]
For the record, this was fixed in 95cd532

**Comment by xentac** [comment]
Just wanted to point out my comment on https://github.com/beancount/fava/commit/95cd532e2a3f619c952543e733751a75b7847a86. It looks like we added nowrap to tree-table, which breaks "at Market Value" rendering.

**Comment by tbm** [comment]
@xentac probably best to open a new issue for this.
