### ISSUE TITLE
Sunburst: don't show empty charts

### ISSUE THREAD

**Issue by tbm** [beancount/fava#720]
I have 3 operating currencies so I usually get 3 sunburst charts.  But I chose "converted to EUR" so I only get one.

However, I also see 2 "chart is empty".  This shouldn't be there since I chose to see everything in one chart.

**Comment by yagebu** [comment]
> However, I also see 2 "chart is empty". This shouldn't be there since I chose to see everything in one chart.

"converted to ..." doesn't need to imply that there'll only be one chart. Still, more generally, this could be improved so that empty charts aren't shown.

**Comment by tbm** [comment]
> "converted to ..." doesn't need to imply that there'll only be one chart

Good point!
