### ISSUE TITLE
tree-table numbers no longer wrap when viewing "at Market Value"

### ISSUE THREAD

**Issue by xentac** [beancount/fava#721]
When viewing at Market Value on the balance sheet, black text is pushed into the next column.

In the fix for https://github.com/beancount/fava/issues/708, https://github.com/beancount/fava/commit/95cd532e2a3f619c952543e733751a75b7847a86 probably shouldn't have been applied to ".tree-table .num" and maybe even ".journal .num".

**Comment by aumayr** [comment]
@xentac Can you post a screenshot?

**Comment by xentac** [comment]
![screenshot 2018-04-01 at 10 20 08 am](https://user-images.githubusercontent.com/1805/38175755-593774fe-3596-11e8-9644-ecf414d0d885.png)

Interestingly, another bug is that incognito mode doesn't work with at Market Value... I'll file a bug for that one too.
