### ISSUE TITLE
Incognito mode doesn't elide "At Market Value" gains

### ISSUE THREAD

**Issue by xentac** [beancount/fava#725]
![screenshot 2018-04-01 at 10 20 08 am](https://user-images.githubusercontent.com/1805/38175763-794fcc1e-3596-11e8-9cc4-d08a62edc085.png)

I expect it to be shown as (XXX,XXX.XX) instead of seeing numbers

**Comment by yagebu** [comment]
A PR with a fix would be welcome!

**Comment by yagebu** [comment]
Don't care enough about incognito mode to do anything about it, so I'll close this as a wontfix
