### ISSUE TITLE
Prices on balance sheet for market value still use current date not filter date

### ISSUE THREAD

**Issue by xentac** [beancount/fava#726]
It looks like https://github.com/beancount/fava/issues/613 didn't quite address the prices at filter date problem. I wrote a PR that may address the issue, but I'm not sure it's the right way to do it, especially because it uses the date of the most recent transaction in the Tree. This isn't 100% analogous to the latest filter date, but I didn't want to depend on the g.ledger object everywhere.

**Comment by yagebu** [comment]
Fixed in ef40734ef41f37d8b4f102cd1ba59aa71a4a18e5
