### ISSUE TITLE
sunburst chart has gap

### ISSUE THREAD

**Issue by tbm** [beancount/fava#730]
The sunburst chart has a gap at the top where it doesn't tell you where it is. But if you look at the one in the middle (in particular), it seems the gap is big enough that it doesn't have to be a gap.

![gap](https://user-images.githubusercontent.com/1556037/38269703-87512c12-3781-11e8-94bb-fd309fd7fcb8.png)

**Comment by tbm** [comment]
Actually, now that I look at my data, I see the one in the middle, the gap is actually 5 different 2nd level accounts.  I guess there isn't enough to put 5 different colours there.

How about creating an "other" so there's no gap?

**Comment by yagebu** [comment]
The gaps are there because tiny slices visually broke the chart as far as I recall.

**Comment by yagebu** [comment]
Could you try the charts with the tiny slices? Removing the `(d.x1 - d.x0) > 0.005` filter in charts.py (currently line 257) should do that.

**Comment by tbm** [comment]
Hmm, I'm having a hard time with this.  If I remove the filter line on 257 in `fava/static/javascript/charts.js` as far as I can tell nothing changes. At least the difference is not obvious to me. The gap is still there.

If I remove the filter line (the same one) from the update() function further down, the the gap goes away (and looks ok) but then all labels disappear and the circle is filled.
