### ISSUE TITLE
Account view with filter kills browser (memory)

### ISSUE THREAD

**Issue by tbm** [beancount/fava#731]
When I open a certain account which has 10 transactions, it works fine.  When I then click on the link of one of the transactions, it tries to filter on that and suddenly my browser takes up huge amounts of memory and gets killed.

Any suggestions how to debug this?

**Comment by yagebu** [comment]
Can't reproduce this and also don't have any good suggestions on how to debug this, except for using the browser dev tools. What does the JS console show?

**Comment by tbm** [comment]
With the developer tool open in Chromium the page loads fine. When I close it and reload, it crashes. Typical. :)

I'll see if I can find a reduced test case but it may take a few days.

**Comment by tbm** [comment]
Ok I managed to create a reduced test case. I don't see what's so special about this but it reliably kills Chromium and Firefox.

Sometimes it loads fine when I load it the first time but reloading the page kills the browser due to memory.

Firefox told me:

> A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the scriptcontinue.
>Script: http://localhost:5000/static/gen/app.js:20301

Go to http://localhost:5000/beancount/account/Expenses:Test

with this file:

```
option "operating_currency" "EUR"

1970-01-01 open Assets:Cash
1970-01-01 open Expenses:Test

2018-01-09 * "Test"
  Expenses:Test           50.00 EUR
  Assets:Cash            -50.00 EUR

2018-01-10 * "Test"
  Expenses:Test           50.00 EUR
  Assets:Cash            -50.00 EUR

2018-01-11 * "Test"
  Expenses:Test           50.00 EUR
  Assets:Cash            -50.00 EUR

2018-01-12 * "Test"
  Expenses:Test           50.00 EUR
  Assets:Cash            -50.00 EUR

```

**Comment by tbm** [comment]
The problem seems to be (re)loading the chart.

**Comment by yagebu** [comment]
Interesting, thanks for providing a file that reliably reproduces this!

The second `voronoi.polygons` call seems to be the problem and it seems to be a bug with d3-voronoi: https://runkit.com/yagebu/5ac88e13ef4e310012a3c15f

**Comment by tbm** [comment]
Thanks for tracking this down!

**Comment by yagebu** [comment]
It seems that d3-delaunay uses a better algorithm which might avoid this (and that d3-voronoi is somewhat obsolete, not maintained anymore)
