### ISSUE TITLE
treemap shows wrong label for currency

### ISSUE THREAD

**Issue by tbm** [beancount/fava#734]
Income statement, I open the treemap.  The drop down offers me EUR, GBP, USD.  I choose GBP and the chart updates to show GBP.  But the label still says EUR.

**Comment by yagebu** [comment]
@tbm: can you confirm if this is fixed? I only have one operating currency and didn't really test it...

**Comment by tbm** [comment]
Yes, works as expected now. Thanks @yagebu!
