### ISSUE TITLE
Translate Fava error messages

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#738]
As discussed in https://github.com/beancount/fava/pull/737#discussion_r179400190

**Comment by aumayr** [comment]
@yagebu Why do you think this is a bad idea? (I do not have strong feelings about that, just want to discuss and have the discussion and decision on the record.)

**Comment by yagebu** [comment]
Currently, most translations of Fava seem to be at about 2/3 translated strings, which is quite far from "completely translated" - so for one thing, translating error messages would be another burden for the translators. Another reason would be consistency - the error messages to me are somewhat more a "Beancount language"-related thing and this "language" is simply English-based. Also, none of the documentation for the budgeting feature is translated and before that happens, I think it would be odd to translate the error messages for it. In an utopian world where Fava and all its and Beancount's help docs have complete translations in multiple languages, I'd be happy to add the error messages to the translateable strings, but before we reach that utopia, I think it just creates too much churn.

**Comment by aumayr** [comment]
That sounds reasonable, and I agree that translating everything 100% is a far fetched utopia.

I would be interested in the opinion of people who have worked on the translation, what they think is worth translating and not. So if anybody comes across this issue, please do comment your opinion. I'll close this (as it is decided/documented), but feel free to comment!
