### ISSUE TITLE
support for generic documents (not only statements) associated to transactions

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#740]
I'm looking into how Fava support documents referenced from the journal, and it is not clear to me if there is a desire to support generic documents, as opposed to only bank-style statements.

In particular, I'm interested in the ability to accept "receipts", "invoices", etc., that will generally be associated to Expenses transactions, or Assets:Receivable, etc. Is that something that Fava wants to support?

If so, I think it would be nice to rename the link_statement plugin into something more generic, and not use `#statement` as a tag, but maybe something like `#document`. I suspect that the name comes from the `document` directive of Beancount itself which, on the other hand, really seems to be statement-specific, as documents are conceptually inserted by Beancount *in between* transactions, rather than *on* them.

**Comment by yagebu** [comment]
There's nothing special about "statements", so other documents should be linked too. But I think supporting a long list of metadata keys to link documents and transactions is not desireable. Currently all keys starting with 'statement' are searched for document paths - maybe this could be replaced with something more generic?

**Comment by zacchiro** [comment]
yep, that was the crux of my idea/proposal: use something more generic, like "document"

**Comment by yagebu** [comment]
I'd be happy with that (actually happier than with 'statement', which seems overly specific)

**Comment by tbm** [comment]
I looked at this plugin recently too and while I haven't started using it (although I want to) I also though it should be more generic. Ideally, you should specify multiple metadata tags in a variable because in addition to `statement` and `document` something like `invoice` might be good.

Also, it wasn't obvious to me why this plugin is in fava and not beancount itself.

**Comment by zacchiro** [comment]
It looks like we all agree something more generic would be welcome. I agree with @yagebu that making this configurable via a list of tags would be overkill. Can we settle with just using `document` instead of `statement`? That is also the most coherent and obvious naming to match the fact that beancount uses `document` transactions. If that's fine, I'll be happy to submit a PR addressing this.

**Comment by tbm** [comment]
* Stefano Zacchiroli <notifications@github.com> [2018-05-19 04:53]:
> It looks like we all agree something more generic would be welcome. I agree with @yagebu that making this configurable via a list of tags would be overkill. Can we settle with just using `document` instead of `statement`?

What if one posting or transaction has several documents?  e.g.
invoice, receipt, etc

-- 
Martin Michlmayr
https://www.cyrius.com/

**Comment by yagebu** [comment]
> If that's fine, I'll be happy to submit a PR addressing this.

:+1: 

> What if one posting or transaction has several documents? e.g. invoice, receipt, etc

Then you can use several metadata entries, just like now (document, document-1...)

**Comment by tbm** [comment]
> Then you can use several metadata entries, just like now (document, document-1...)

What's the actual downside of making it a config variable?  It can be optional.  If you don't specify, it's "document".

One reason I don't like document, document-1, is that a) using different tags is more description (invoice, receipt, etc) and b) that using tags allows you to add better checks, e.g. that every payment has an invoice attached. How do you check that if the invoice could be document or document-1.

**Comment by zacchiro** [comment]
yeah, but it was (and still is) not clear to me if we've consensus on the desired behavior

**Comment by yagebu** [comment]
> What's the actual downside of making it a config variable? It can be optional. If you don't specify, it's "document".

Performance, convention over configuration, code complexity mainly, like with all config variables. You're also still free to use `document-invoice` as a meta key, or more appropriately put it in the document name.

I don't really see the point in discussing this minimal UI feature of Fava at this length. Let's just do `s/statement/document/` and be done with it.
