### ISSUE TITLE
Document caching issues in developer docs

### ISSUE THREAD

**Issue by tbm** [beancount/fava#741]
As seen e.g. in issue #729 some people run into issue because the JavaScript code is cached in the browser. Mention this is in the developer docs.

@yagebu I intend to contribute a patch but it might be a few days.

**Comment by yagebu** [comment]
Shouldn't be necessary since #747

**Comment by tbm** [comment]
Excellent!  I'm sorry I never submitted a patch but I'm happy to hear it's obsolete now anyway ;)
