### ISSUE TITLE
Order of charts on income statement

### ISSUE THREAD

**Issue by tbm** [beancount/fava#744]
Is it intention that the order in the income statement is: Income, Expenses, Expenses, Income instead of I, E, I, E.

Actually, I always found it confusing Income and Expense are listed twice without it being obvious what the difference is.

Why not only: Net worth, Income, Expenses.  And then provide a toggle at the top between: 1) bar chart 2) treemap 3) sunburst.

**Comment by tbm** [comment]
Having treemap and sunburst for net worth would be an additional bonus from this change.

**Comment by yagebu** [comment]
Nope, no special intention behind that weird order. Maybe I'll rename the first two to "Monthly Income/Expenses".

I think keeping them as separate charts is better, as that way it's faster two switch between them.

**Comment by yagebu** [comment]
> Maybe I'll rename the first two to "Monthly Income/Expenses".

Nevermind - that seems to unnecessarily duplicate information. So I'm not sure how to best solve this - is there another naming we could choose that would distinguish them?

**Comment by tbm** [comment]
I'm not sure but maybe: `Net profit | Income (monthly, total) | Income (monthly, total)` with `monthly` and `total` being links.

**Comment by yagebu** [comment]
> Net profit | Income (monthly, total) | Income (monthly, total)

I like it. Wouldn't be a trivial change though (right now the chart labels are simply a one-dimensional list)

**Comment by yagebu** [comment]
Feel free to address this, I probably won't, so I'll close this as wontfix
