### ISSUE TITLE
Add nicer net worth chart, showing assets, liabilities and net worth in one chart

### ISSUE THREAD

**Issue by tbm** [beancount/fava#745]
A net worth chart like this would be great, i.e. showing assets, liabilities and net worth in one chart:

![gl4n3vi 1](https://user-images.githubusercontent.com/1556037/38586728-3dcd3ff6-3d1f-11e8-94b0-59fd34eb9f0a.png)

Source: http://imgur.com/gL4N3vI (which was posted somewhere on reddit).

@yagebu do you have time for this?  If not, maybe time for me to learn d3 (might take a while though).

**Comment by yagebu** [comment]
@tbm: probably won't have time for this soon

**Comment by mariosangiorgio** [comment]
@tbm from your message it seems you could have attempted to implement this.

Have you had a chance to give it a try?

**Comment by tbm** [comment]
Not yet, no.

**Comment by yagebu** [comment]
I'm closing this, since it's become unfeasible with the net worth chart possibly displaying multiple lines.
