### ISSUE TITLE
Custom sidebar links always open in a new tab

### ISSUE THREAD

**Issue by andyjefferies** [beancount/fava#749]
I recently updated my fava install and now my custom sidebar links always open in a new tab.

It was introduced here d3a2ac34d256ea72e80a2053a83602d47d087e82 but doesn't make sense for any of my sidebar links (which are shortcuts to accounts and date-ranges).

**Comment by yagebu** [comment]
I don't have a strong opinion on this - does anyone mind reverting this?

**Comment by andyjefferies** [comment]
I've raised a PR for this if you decided to go ahead; for my usage it's annoying enough for me to patch when I run locally.
