### ISSUE TITLE
fava-option default-file fails to parse

### ISSUE THREAD

**Issue by ndecker** [beancount/fava#750]
The default-file option fails to parse:
> 2018-01-01` custom "fava-option" "default-file"

The reason is the an if instead of an elif in https://github.com/beancount/fava/blob/ccc89fa69999a2b3fddf9fe89e9000a81392ae97/fava/core/fava_options.py#L100
This causes an IndexError in https://github.com/beancount/fava/blob/ccc89fa69999a2b3fddf9fe89e9000a81392ae97/fava/core/fava_options.py#L108

The workaround is to add an empty extra argument:
> 2018-01-01` custom "fava-option" "default-file" ""

**Comment by yagebu** [comment]
Thanks for reporting this!
