### ISSUE TITLE
Tag order changes in journal

### ISSUE THREAD

**Issue by tbm** [beancount/fava#752]
I was testing something with a file like this:

```
2014-04-23 * "Flight to Berlin" #foo #berlin-trip-2014 ^bar
  Expenses:Flights                                                    -1230.27 USD
  Liabilities:CreditCard   ; comment 2
```

and I noticed that the order of the tags changed sometimes when I started fava again and loaded the journal.

Tags have the same order in beancount (alphabetical, it seems, although I wonder if it should preserve the original order from the file).

First I thought it might be https://stackoverflow.com/questions/280713/elements-order-in-a-for-in-loop but I see the same in Firefox.

**Comment by yagebu** [comment]
Tags and links are sets and unsorted as such. I guess we could render them in a sorted order though.

**Comment by aumayr** [comment]
I also think that consistency should have priority here, so sorting (alphabetically?) makes sense.
