### ISSUE TITLE
Offer treemap/sunburst breakdowns by tag or payee

### ISSUE THREAD

**Issue by glasserc** [beancount/fava#756]
I find Fava very useful for exploring my expenses, but I find that it is the most helpful when I organize my expenses by account (e.g. `Expenses:Travel:France`, `Expenses:Travel:Australia`). When I have this layout, I can select the account `Expenses:Travel` using the account selection box on the top of the page, and then I can show a treemap or sunburst of the expenses (showing by comparison how much went to `Expenses:Travel:France`, `Expenses:Travel:Australia`, and how much remained in `Expenses:Travel`). However, for some expenses, I prefer to use tags or payee name to organize them. In this organizational scheme, I can no longer generate treemaps/sunbursts of the expenses. It would be nice to use the same visualizations, but with the expenses split up according to payees or tags instead of account hierarchy.

Tags present some difficulties because a transaction can have multiple tags (whereas a transaction can only have one payee), so perhaps each treemap/sunburst "category" should be a possible combination of tags.

My specific use cases:

- I would like to break down my `Expenses:Groceries` spending according to merchant, to determine which merchant's branded credit card would be the most valuable to me (if any).
- I apply a `deductible` tag to many different transactions in many different categories. I would like to look at my `Expenses:Charity` spending and determine how much is deductible for tax purposes.

**Comment by aumayr** [comment]
@yagebu Would implementing showing a treemap/sunburst based on Payee or Tag (when viewed on a specific Account page) be feasible?

**Comment by yagebu** [comment]
Should be doable - but for added flexibility I think it would be best to have this render a treemap for any query (having some required structure) instead of some more hardcoded charts

**Comment by slifty** [comment]
As a beancount newbie I wasn't sure what kind of queries I could run to result in these visualizations; I wanted to post an example here in case someone else finds the issue and would benefit:

```
SELECT
  payee,
  SUM(COST(position)) AS balance
WHERE
   account ~ 'Expenses'
GROUP BY payee, account;
```

**Comment by yagebu** [comment]
Thanks @slifty, I've added your example to the help pages :)
