### ISSUE TITLE
Import page fails to load due to file_account() method

### ISSUE THREAD

**Issue by mondjef** [beancount/fava#758]
I have created a custom beancount importer that inherits from the built in csv.Importer.  In this custom importer I am over riding the file_account() method with the following to get the account based on the file name:
```

    def file_account(self, file):
        if file:
            m = re.match(r'.+SIMPLII_(\d{4})_.*', file.name)[1]
            if m:
                sub_account = self.account_map.get(m)
                if sub_account:
                   self.account = self.account + ':' + sub_account
        return self.account
```
My importer works with both bean-identify and bean-extract without issues, however Fava does not like something and it seems to be something with the passed in 'file' parameter for this method as from what I can read in the on-screen error message it says that str object has no attribute 'name'.  To explain the above file_account() method...it takes the filename and matches against a regex to get the part that identifies the account then it looks up in a dictionary (account_map) to get the full beancount account name.  I can provide more if I knew where to get logs/errors from fava other than the on-screen error that is display for 5 seconds.

**Comment by mondjef** [comment]
ok I have found work around for the issue of cumulatively expanding Importer and Account variables with the following version of file_account() method.

```
    def file_account(self, file):
        __account = self.account
        if file:
            # if a string is passed its coming from Fava
            if isinstance(file, str):
                __filename = file
            # otherwise its assumed to be a FileWrapper from beancount
            else:
                __filename = file.name
            m = re.match(r'.+SIMPLII_(\d{4})_.*', __filename)[1]
            if m:
                sub_account = self.account_map.get(m)
                if sub_account:
                   __account = __account + ':' + sub_account
        return __account

```
However, I am not really sure this is the proper way this should be handled as it seems very hacky to me and maybe there needs to be some changes made to either beancount or fava but I am not familiar enough with the code base yet.

**Comment by yagebu** [comment]
Hey, thanks for the report! Fava was making one call to `importer.file_account()` in the template, passing the filename and not the FileMemo object from Beancount's cache.
