### ISSUE TITLE
extensions: support user reports

### ISSUE THREAD

**Issue by seltzered** [beancount/fava#759]
I'm trying to see if there's a need among others for an option for fava to look for additional templates in a separate directory (outside the fava codebase) - the idea is that this would facilitate 'custom reports'.

I'm pretty new to the fava code but from looking at it so far, implementing this would entail:
- A 'custom' directive so that one's beancount file points to the directory of templates
   - e.g. `2010-01-01 custom "fava-option" "custom-templates-dir" "$LEDGERDIR/fava_user_templates/"`
- app.routes dynamically created for the detected user templates. 
- Modifying things so 'navigation_bar' has an insert for 'User' templates.

Is there interest in such a thing? Am I missing something fundamental in fava/beancount that would already do this? 
 
Motivation: I'm finding areas where I want to have mini reports that are specific to my own needs (e.g. watching balance among work expenses vs. reimbursement income over time, wanting to see both a 'raw' and a 'filtered' version of my income statement, showing percent profit/loss on non-commodity investments, etc.). I could write/execute my own separate python scripts to do this, but ideally I want the presentation of these things to be within fava. 

I've considered using beancount 'plugins' to do filtering but there's times where I still want to see the unfiltered reports.

I'm also trying to understand fava's 'extensions' ([issue](https://github.com/beancount/fava/pull/477), [commit](https://github.com/beancount/fava/pull/477)) - one thought is that custom reports could instead be implemented via extensions if some extra hooks are added within application.py.

**Comment by aumayr** [comment]
Have you seen the [Custom links in the sidebar](https://fava.pythonanywhere.com/example-with-budgets/help/features/)-feature in the help pages? They are pretty powerful, as you can add a link to a  BQL-query to the sidebar as well. 

If this does not go far enough for you, I think we could extend the Extension mechanism to allow for custom views to be added to the sidebar. (I would rather go the Extension way than the autodetect-templates-way, as this is already a "known" mechanism to extend the functionality of Fava and does not add yet another way to do that.)

**Comment by seltzered** [comment]
Thanks, I hadn't seen that feature - custom sidebar links to filtered statements will cover some of my needs. Will look into the adding to the extension mechanism if that doesn't go far enough.

**Comment by yagebu** [comment]
This sort of thing was always something that I thought the extension system should support at some point, so a PR adding this to extensions would be very welcome! :)

**Comment by seltzered** [comment]
I'm currently playing around with this idea. Code is too ugly to share at the moment, the approach I've been trying to take is:
- Add a subclass of `FavaExtensionBase` called `FavaExtensionReport`
- `FavaExtensionReports` get loaded within Fava core, but then a `load_extension_reports` method gets called to register report names in application.py's `_load_file`
- Add an 'extensions-dir' fava option to let the user set the folder where extensions are loaded. 
   - This also helps in testing, such that we can have an extension-example.beancount in `tests/data` that references the `fava/ext` folder  

The issue I'm running into is when it comes writing tests. Particularly, I'm torn between:
  - Modifying the `long-example.beancount` file to include entries the ExtensionReports, which seems like a bad idea and breaks other tests.
  - Having a separate `example-extension-report.beancount` file, which seems to lead me towards refactoring application.py a bit to support multiple app instances (i.e. have a `create_app` application factory method)

Any advice? Should I go ahead and refactor application.py or is there other path I'm not thinking of?

**Comment by yagebu** [comment]
> Add a subclass of FavaExtensionBase called FavaExtensionReport

Not needed IMHO, there can just be an attribute on `FavaExtensionBase` like `.reports`.

> FavaExtensionReports get loaded within Fava core, but then a load_extension_reports method gets called to register report names in application.py's _load_file

I don't think there's any need to register them, when the user tries to access a report we can just check if it exists.

> Add an 'extensions-dir' fava option to let the user set the folder where extensions are loaded. 

I think this is not needed, we can stick to loading them from Python modules (so `fava.ext.[...]` can already be accessed from the tests) since we also search the folder of the Beancount file.

**Comment by yagebu** [comment]
Cool! I opened a PR for that branch, I've seen WIP pull requests in a worse state ;)

**Comment by seltzered** [comment]
@yagebu Just noticed your review comments, thanks for the pointers! Limited on time this week but should continue work soon. One thing on my mind has been wondering what's the appropriate way to provide data from an extension's .py model to the extensions's template - initial thought has been to have an instance getter method within `ExtensionModule`.
