### ISSUE TITLE
Make dependency on Babel optional

### ISSUE THREAD

**Issue by yegle** [beancount/fava#761]
It looks like `babel` alone takes 21.5 MB and doesn't provide much value if you prefer using English in fava. Is it possible to make Babel optional?

```
# du -sh babel
21.5M   babel
```

**Comment by aumayr** [comment]
Fava is currently translated into 9 different languages. I don't think `babel` should be optional in a default install (via pip), but we can discuss if there are ways to make it optional if you remove it after you install via pip.

**Comment by yagebu** [comment]
I'm strongly opposed to making it optional. L10n is a core feature, I dont' want to support some shims to disable it.

**Comment by yegle** [comment]
I wonder if babel can be made a built time dependency and fava can run w/o the library.

I.e. one can choose to install fava in a particular language (something like `FAVA_LANGUAGE=en pip install fava`), and then a pre-processed copy of source code can be installed with strings substituted.

**Comment by yagebu** [comment]
I don't really see the point of spending tons of time on this to save a few MBs in 2018. If you want to save the disk-space, just delete Babel's data files.
