### ISSUE TITLE
Importing balance Error: Saving failed: KeyError: 'account'

### ISSUE THREAD

**Issue by csarn** [beancount/fava#762]
I just tried to make an Importer that generates balance assertions. Those are supposed to be supported by fava. In the import review view it is listed correctly, but upon pressing "Import entries" I get the error 

>  Saving failed: KeyError: 'account'

It seems that the js frontend does not send the account information to the backend. Chrome developer tools shows this json is sent to the backend:

> {type: "Balance", meta: {some: "meta"}, date: "2018-05-14", number: "14", currency: "EUR"}

Indeed, the 'account' key is missing.

I am not competent enough in javascript to fix this myself, even if it seems like a low-effort fix.

**Comment by aumayr** [comment]
Does your Importer just generate Balance entries?

**Comment by csarn** [comment]
For testing purposes, I generated one Transaction entry and one Balance entry. Hardcoded, no real import yet.
Basically this:

    def extract(self, file, existing_entries=None):
        return [Transaction(...), Balance(...)]

**Comment by aumayr** [comment]
Seems like the `account` key was missing after all 👼 
Should be fixed in 534f444.

Can you test if this is the case, @csarn?
