### ISSUE TITLE
Update Editor Syntax for changes in Beancount 2.1.0

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#763]
@blais released Beancount 2.1.0, which triggers some changes in Fava:

> - Support for transaction tags and links in indented postings block in grammar
> - Globbing patterns in include statements

Does the Syntax definition for the editor support both?

**Comment by tbm** [comment]
Also, full-line comments in transactions are allowed now. The editor doesn't handle that 100% too. When I normally write a comment (after a posting or on a line starting with ; it doesn't offer account completion) but if I type

```
  ; foo
```
I get account completion on foo, so I think the editor doesn't realise this is a comment.

**Comment by yagebu** [comment]
The changes don't change anything about the tokens, so no changes to the editor are necessary.

I don't really care about unnecessary completions in comments, the completions are suggested since the line is indented in your example.
