### ISSUE TITLE
Problem with filtering with FROM after updating beancount

### ISSUE THREAD

**Issue by renatocan** [beancount/fava#767]
After updating to beancount 2.1.2, fava started to crash when filtering with FROM.

For example, when using from:'year = 2012', as in the help exemple, it shows:

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I'm not sure if this is a fava problem or a beancount problem. I've tested filtering using bean-query and it worked.

Thanks,

[]s,

Renato.

**Comment by yagebu** [comment]
Beancount changed something internal some time ago, which broke this filter. The 'from' filter has been removed in Fava, so this will be fixed in the next release.
