### ISSUE TITLE
Filters: Allow "where" filtering

### ISSUE THREAD

**Issue by tribut** [beancount/fava#771]
Would be great if there was some way to filter on the actual contents of the postings (for example "all transactions > 500 EUR"). As far as I understand that is not possible in FROM but only in WHERE filters.

I'd love to be able to do that from fava.

Example: "where number(value(position)) > 500" (not sure if it is possible to state this query in a less complicated way)

**Comment by yagebu** [comment]
Fava doesn't support FROM filters any more. Have you made yourself familiar with the new filter syntax? The `any()` filter does allow filtering entries based on specific postings

**Comment by tribut** [comment]
Thanks for your response. I've seen the new syntax but wasn't aware of `any()` because it is not yet available in a release. Great to see it has been added, though!
