### ISSUE TITLE
Assign colours once

### ISSUE THREAD

**Issue by tbm** [beancount/fava#774]
When I move between different pages/charts, different colours get assigned. So EUR might be blue in one chart but red in another one.

Would it be possible to assign colours once and then use them for all charts?

(Maybe there should even be a way for users to assign colours, so they are consistent between different runs of fava.)

**Comment by tbm** [comment]
Are you sure this is working correctly?

> operating_currency | ['EUR', 'GBP', 'USD']

![a1](https://user-images.githubusercontent.com/1556037/42112287-99c700f6-7be7-11e8-9eae-6cd70b64732d.png)
vs
![b2](https://user-images.githubusercontent.com/1556037/42112292-9e6f7624-7be7-11e8-907d-6eb1100f4118.png)

**Comment by yagebu** [comment]
Is this after 21e796003b9d275817df7b20a16d72d3b8a2a0e8?

**Comment by tbm** [comment]
Yes

**Comment by tbm** [comment]
> Can you try debugging it?

I don't know how.  Any suggestions?

However, you can reproduce it with the simple test case below.  Click on "Income Statement" and then click on "Balance Sheet".  Sometimes the order is the same.  Re-start fava and try again and EUR and USD will change position (GBP stays in the middle).

Test case:

```
option "operating_currency" "EUR"
option "operating_currency" "GBP"
option "operating_currency" "USD"

2000-01-01 open Assets:Test

2018-01-02 * "Test"
    Assets:Test                  10.00 EUR
    Assets:Test                 -10.00 EUR

2018-01-02 * "Test"
    Assets:Test                  10.00 GBP
    Assets:Test                 -10.00 GBP

2018-01-02 * "Test"
    Assets:Test                  10.00 USD
    Assets:Test                 -10.00 USD
```

**Comment by yagebu** [comment]
Lol, I only now realized that it is working as expected in the picture you posted, it's just that the order is different, which is quite unrelated

**Comment by tbm** [comment]
> Lol, I only now realized that it is working as expected in the picture you posted, it's just that the order is different, which is quite unrelated

Doh!  You're right.  I didn't notice that either.
