### ISSUE TITLE
New transaction: doesn't show error for invalid accounts

### ISSUE THREAD

**Issue by tbm** [beancount/fava#781]
When you enter an invalid account name (e.g. assets:Foo), nothing happens when you press "Save".  
  
Shouldn't there be an error so people know why pressing the button doesn't do anything?

**Comment by yagebu** [comment]
Since the forms use HTML5 form validation, this might be browser dependent. When I implemented it, it worked quite sensibly and highlighted the input in red, but in a current Firefox it seems to have changed.
