### ISSUE TITLE
Uptodate indication shows date since last transaction instead of last balance

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#784]
As mentioned in title. I was under the impression from https://github.com/beancount/fava/issues/35 that only balance transactions would affect the indicator (hence a very active account which I haven't balanced in 60 days would show grey). Unfortunately current 1.7 seems to show grey only for my inactive accounts.

Also as a slightly colour-blind user could we get a much lighter shade of green (the current one is quite dark). Something like the colour of the 'comment' button on this page.

**Comment by yagebu** [comment]
>  In addition, a grey dot will be shown if the account has not been updated in a                                                                                                                                                           while, as configured by the `uptodate-indicator-grey-lookback-days` option.

Is what the current help says, which seems to match the behaviour, no?

>Also as a slightly colour-blind user could we get a much lighter shade of green

Choose your favourite green and submit a PR ;)

**Comment by ngoonee** [comment]
I believe the original intention was for an indicator of last time the account was balanced (especially useful for high traffic accounts where one missed transaction could throw things off, and then you'd have to check everything since last balance).

And I will on the colour, any pointers where this is defined?

**Comment by yagebu** [comment]
> And I will on the colour, any pointers where this is defined?

`style.css`

**Comment by ngoonee** [comment]
pip-installed fava doesn't have style.css, and changing the matching parts of static/gen/app.css doesn't seem to do anything. Will have to take a deeper look if I can find the time. I was changing color-status-green as that seems closest to what I'm looking for.

**Comment by yagebu** [comment]
You'll need to install from git to work on Fava.

**Comment by yagebu** [comment]
So as far as I can tell from the original discussion, the current behaviour seems to be in line with both how it was suggested and how it's currently described in the help, so I'll close this issue.
