### ISSUE TITLE
Increase the width of the `num` style class

### ISSUE THREAD

**Issue by matze** [beancount/fava#785]
Although I am not super rich, I get a garbled asset table at market value because of the varying unrealized earnings and total value. Increasing the width of the `num` class to `12em` alleviates that.

**Comment by matze** [comment]
I don't know if I can find the time to learn the frontend framework and get it running but one idea that should work for both desktop and mobile use is inserting another column for the market value difference and not adding that to the existing cell.

**Comment by yagebu** [comment]
Help with this is still welcome, but I'm closing the issue since I won't address this myself
