### ISSUE TITLE
Doesn't stop reloading with Firefox

### ISSUE THREAD

**Issue by tbm** [beancount/fava#790]
Use the attached simple test case and go to http://localhost:5000/beancount/account/Assets:Test1/ in Firefox. Everything is fine.  Now expand one of the transactions and click on `Assets:Test2`.  The new chart will load correctly.

However, the loading indicator in the upper left corner doesn't stop.

This is only in Firefox (52.9.0 ESR), not in Chromium.

Test case:

```
option "operating_currency" "EUR"
option "operating_currency" "GBP"
option "operating_currency" "USD"

2000-01-01 open Assets:Test1
2000-01-01 open Assets:Test2

2018-01-02 * "Test"
    Assets:Test1                 10.00 EUR
    Assets:Test2                -10.00 EUR

2018-01-02 * "Test"
    Assets:Test1                 10.00 GBP
    Assets:Test2                -10.00 GBP

2018-01-02 * "Test"
    Assets:Test1                 10.00 USD
    Assets:Test2                -10.00 USD
```

**Comment by yagebu** [comment]
Can't reproduce this in stable Firefox - what does the console show?

**Comment by tbm** [comment]
> Can't reproduce this in stable Firefox - what does the console show?

My Firefox is fairly old (it's what it's Debian stable), so maybe it has ben fixed.

Which console?  On the command line, where I run `fava test.beancount`, nothing is written. Is there an option to enable more debugging?

**Comment by yagebu** [comment]
I mean the browser console

**Comment by tbm** [comment]
It says:
```
TypeError: $.fetch(...).then(...).finally is not a function[Learn More]  app.js:14152:4
	loadURL http://localhost:5000/static/gen/app.js:14152:4
	navigate http://localhost:5000/static/gen/app.js:14129:6
	takeOverLinks/< http://localhost:5000/static/gen/app.js:14213:10
	delegate/< http://localhost:5000/static/gen/app.js:314:8
```

**Comment by yagebu** [comment]
Mhh it seems that `finally` is not very well-supported yet
