### ISSUE TITLE
Unaligned Sunburst rings

### ISSUE THREAD

**Issue by zacharylawrence** [beancount/fava#795]
The sunburst chart consistently shows outside rings overlapping the wrong inner elements. For example, here you can see the large outside blue ring overlapping multiple different categories. Highlighting the outside blue ring brightens inner elements starting from 0 deg (ie due North).

![example](https://user-images.githubusercontent.com/4469505/43051043-99d9944a-8de0-11e8-8afa-dea3f29a4763.png)

Fava Version: Fava 2.7
Browser Version: Chrome 67 on macOS (High Sierra)

**Comment by yagebu** [comment]
I assume this is due to having both accounts of positive and of negative balance. So I think there's not much we can do about that.
