### ISSUE TITLE
Populate lists of suggested accounts and payees with metadata from the importer

### ISSUE THREAD

**Issue by johannesjh** [beancount/fava#801]
Follow-up from https://github.com/beancount/fava/issues/579#issuecomment-414147625: I would like to see a feature where fava populates the list of suggested account names and payees in the import-GUI based on suggestions found within the importer's output.

**Comment by yagebu** [comment]
@johannesjh: Are you willing to implement this and provide a PR?

**Comment by johannesjh** [comment]
In my experience, the suggestions provided by fava work reasonably well. 
-> I think we can close this issue.  

On a more detailed note, in my personal experience: Either smart_importer's prediction was correct, then I don't need suggestions. Or smart_importer's prediction was false, then I type a few keystrokes and correct the falsely-predicted attribute... and as I said, fava's existing suggestions work sufficiently well for this purpose.
