### ISSUE TITLE
Commodities page doesn't work properly with specific data

### ISSUE THREAD

**Issue by Argentumbolo** [beancount/fava#802]
Steps to reproduce:
 - Open project from [archive](https://github.com/beancount/fava/files/2301800/beancount-bug.zip) as "fava ledger.beancount"
 - Go to "Commodities"

Expected:
 - Commodities page show.

Actual behaviour:
 - Script newer ended.

Environment:
 - KUbuntu 18.04 x64, Firefox 61.0.1
 - KUbuntu 18.04 x64, Chromium 68.0.3440.106

**Comment by yagebu** [comment]
Thanks for the report - this seems to have been a bug in one of our dependencies (d3-delaunay) for the charts
