### ISSUE TITLE
Keyboard entry filtering doesn't work on safari.

### ISSUE THREAD

**Issue by seltzered** [beancount/fava#809]
Creating issue based on @victoraraujo01 's comment in https://github.com/beancount/fava/issues/768#issuecomment-403682834

When entering in a filter in safari (e.g. year), the entry doesn't seem to work when entered via keyboard. 
![beancount_fava_safari_filter_bug](https://user-images.githubusercontent.com/297435/44820004-e41e2580-aba3-11e8-9153-8fe757693d42.gif)

**Comment by yagebu** [comment]
Does the browser console show any errors?

**Comment by seltzered** [comment]
Browser console doesn't appear to have any errors. 
Is there anywhere else I could set a breakpoint for besides `e.on('form-submit-filters' ...` in app.js ?

**Comment by seltzered** [comment]
Humm, okay it looks like even the general event listener (line 314 of app.js, or line 13 of helpers.js https://github.com/beancount/fava/blob/b6f65541b2538414d761b5a49002da3da6d0f349/fava/static/javascript/helpers.js#L13 ) will trigger on clicking of the element, but not on hitting enter.

**Comment by yagebu** [comment]
Since this works in Firefox and Chrome, I assume this a browser bug in Safari. I can't really investigate this any further, if you can and find some workaround, I'd be happy to merge that. Otherwise this would be a wontfix to me.

**Comment by seltzered** [comment]
Yep, fine with it being a wontfix. Spent a little bit of time trying to figure out how to solve this but it's not a priority at the moment - just been using another browser instead to workaround it.
