### ISSUE TITLE
How to approach filtering on transactions with multiple postings (i.e. 3 or more) 

### ISSUE THREAD

**Issue by seltzered** [beancount/fava#812]
One thing I've been trying to wrap my head around in both beancount & fava is how to handle multi-posting transactions, particularly when it comes to filtering and writing reports.

For example, let's imagine the [#trip-boston-2017](https://github.com/beancount/fava/blame/e2cc2214ba07c5428635ec122f533fdcac84d687/contrib/examples/example.beancount#L2785) is done instead as a trip where a large bill is later split among friends with similar end amounts for restaurants/coffee paid. Modified example is [here](https://gist.github.com/seltzered/b35fa370e90d8d5c41996313049947e1).

```
2017-06-03 * "Boston Trip Billsplit" #trip-boston-2017
  Liabilities:US:Chase:Slate      -539.25 USD
  Expenses:Food:Restaurant        514.16 USD
  Expenses:Food:Coffee             25.09 USD
```

The user then wants to see how much they're spending on coffee. Comparing the normal example (left) with the modified billsplit example (right) shows the difference, where filtering on an account captures whole transaction amounts rather than the posting amounts. The same will happen also on advanced filters going by posting attributes e.g. using `all(account:"Expenses:Food:Coffee)` 

<img width="1677" alt="screen_shot_2018-09-02_at_2_27_42_pm" src="https://user-images.githubusercontent.com/297435/44960937-3ec5c300-aebd-11e8-8f08-4d531f7a441f.png">

Is there something fundamental I'm missing about multi-posting transactions? My concern is that this quickly impacts the more typical usecase of payroll transactions that have multiple postings (e.g. if you're trying have a view that filters out regular 401k contributions)

One could argue that this isn't the responsiblity of fava, and that this should be solved by a beancount plugin that will split out multi-posting transactions into multiple transactions instead. And yet there's something that just feels odd from a user-experience standpoint of approaching things that way. Writing such a plugin seems like there may be some edgecases, particularly with the payroll transactions where there's mutilple postings of incomes, transfers, and expenses (e.g. the example payroll [shows such transactions](https://github.com/beancount/fava/blame/e2cc2214ba07c5428635ec122f533fdcac84d687/contrib/examples/example.beancount#L4190))

**Comment by yagebu** [comment]
> The user then wants to see how much they're spending on coffee.

But that is something they can see from the account tree, no?

Generally, filters that work in all reports can only filter out whole entries as otherwise the accounting equalities could be violated (I don't want Fava to show a balance sheet that doesn't balance)

**Comment by yagebu** [comment]
Implementing a stacked bar chart is tracked by #716 - a PR for that would be welcome of course ;)

Otherwise, to split transactions, you might want to have a look at the [split_income](https://github.com/beancount/fava-plugins/blob/master/fava_plugins/split_income.py) plugin.
