### ISSUE TITLE
Import error: AttributeError: 'NoneType' object has no attribute 'extract'

### ISSUE THREAD

**Issue by mondjef** [beancount/fava#813]
I have a strange issue that recently started happening with my fava imports that I think is related to fava's caching but not certain or know how to confirm.

When I go to the import page my import file is correctly identified, however the first time I click on extract it works great and I am displayed with the list of extracted transactions and at this point if I navigate to another page without actually importing the transactions then go back to import page and click on extract a second time it fails with the following error....how can I fix this and what is causing it, is it the caching?  If I restart my docker image that I run fava in the extract will work again (on the first try only)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 826, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/fava/application.py", line 280, in report
    return render_template('{}.html'.format(report_name))
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/fava/templates/extract.html", line 3, in top-level template code
    {% import '_entry_forms.html' as entry_forms %}
  File "/usr/local/lib/python3.6/site-packages/fava/templates/_layout.html", line 42, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python3.6/site-packages/fava/templates/extract.html", line 19, in block "content"
    {% for entry in g.ledger.ingest.extract(request.args.get('filename'), request.args.get('importer')) %}
  File "/usr/local/lib/python3.6/site-packages/fava/core/ingest.py", line 86, in extract
    existing_entries=self.ledger.all_entries)
  File "/usr/local/lib/python3.6/site-packages/beancount/ingest/extract.py", line 68, in extract_from_file
    if 'existing_entries' in inspect.signature(importer.extract).parameters:
AttributeError: 'NoneType' object has no attribute 'extract'
```
Here is my current import script, note there is some additional logic in file_account function that is not needed any more related to #758 :

```
#!/usr/bin/env python3

from beancount.ingest import extract
from beancount.ingest.importers import csv
from beancount.ingest import cache
from beancount.ingest import regression
import re
from os import path

from smart_importer.predict_postings import PredictPostings

class SimpliiImporter(csv.Importer):
    '''
    Importer for the Simplii bank.
    Note: This undecorated class can be regression-tested with
    beancount.ingest.regression.compare_sample_files
    '''

    config = {csv.Col.DATE: 'Date',
            csv.Col.PAYEE: 'Transaction Details',
            csv.Col.AMOUNT_DEBIT: 'Funds Out',
            csv.Col.AMOUNT_CREDIT: 'Funds In'}

    account_map = {'7655':'Chequing-7655'}

    def __init__(self, *, account, account_map=account_map):
      self.account_map = account_map

      super().__init__(
        self.config,
        account,
        'CAD',
        ['Filename: .*SIMPLII_\d{4}_.*\.csv',
         'Contents:\n.*Date, Transaction Details, Funds Out, Funds In'],
        institution='Simplii'
        )

    def file_account(self, file):
        __account = self.account
        if file:
            # if a string is passed its coming from Fava
            if isinstance(file, str):
                __filename = file
            # otherwise its assumed to be a FileWrapper from beancount
            else:
                __filename = file.name
            m = re.match(r'.+SIMPLII_(\d{4})_.*', __filename)[1]
            if m:
                sub_account = self.account_map.get(m)
                if sub_account:
                   __account = __account + ':' + sub_account
        return __account

    def extract(self, file):
        self.account = self.file_account(file)
        return super().extract(file)

@PredictPostings(training_data='/beancount/personal.beancount')
class SmartSimpliiImporter(SimpliiImporter):
    '''
    A smart version of the Simplii importer.
    '''
    pass

```
I am guessing that something is not working right with the extract function either on my side or with fava...I am a green python programmer so likely my side.  The idea with my work flow is to create a general purpose csv importer that can be used for all my accounts at one institution and just derives the source account from the file name.  I am extending the beancount csv importer and decorating with smart_importer.

Here is my import config:
```
#!/usr/bin/env python3
"""Example import configuration."""

# Insert our custom importers path here.
# (In practice you might just change your PYTHONPATH environment.)
import sys
from os import path

from beancount.ingest import extract

sys.path.insert(0, path.join(path.dirname(__file__)))
from importers import simplii

CONFIG = [
    simplii.SmartSimpliiImporter(account='Assets:Simplii')
]

# Override the header on extracted text (if desired).
extract.HEADER = ';; -*- mode: org; mode: beancount; coding: utf-8; -*-\n'
```

**Comment by yagebu** [comment]
Thanks for the report. Could you try to reformat the traceback as a code block? It's a bit hard to read as it currently is. Also, could you post your importer config?

Fava doesn't do a whole lot of caching, it only keeps the importer config around between runs of extract - could it be that your importer modifies itself when extract is run and somehow removes its extract method?

**Comment by mondjef** [comment]
did a bit more poking around think I have found a clue to what is going on but still don't know the root cause of it or how to fix it.

This is a screen shot of how the import page looks the first time when things seem to work:
![first_time](https://user-images.githubusercontent.com/22079851/44999741-8025a380-af8d-11e8-9bec-75d598f2b747.png)

This is a screen shot of how the import page looks on the second try when things don't work, something is happening with the account name and appending:
![second_time](https://user-images.githubusercontent.com/22079851/44999740-8025a380-af8d-11e8-9f41-59335f01d375.png)

**Comment by yagebu** [comment]
Well the problem here is that the name of the importer changes between runs and it's used to identify the importer. `importer.name()` should uniquely identify the importer.

**Comment by mondjef** [comment]
I have partially fixed this....

I have re-implemented the importer.name() function as such in my importer:
  ```
  def name(self):
        cls = self.__class__
        return '{}.{}'.format(cls.__module__, cls.__name__)
```
but I still have the issue with the account repeatedly appending and can't seem to fix as I can't seem to locate how or why it happens.
I think this can be closed as its really an issue with how I am implementing my importer I believe and not an issue with fava or beancount itself.  Any help is appreciated...I am learning python and trying to get my beancount/fava all setup to get going with it.

**Comment by xentac** [comment]
Probably if you share your importer and config we could help you.

**Comment by xentac** [comment]
Ah, I didn't realize. I was just keeping track of the issue through my
email.

It's pretty clear that the second time around account is actually
"Assets:Simplii:Chequing-7655". Have you tried using the
non-PredictPostings version as your importer?

Your code also has a common problem where every instances shares the same
account_map instance. If that's your intention, that's fine, but any
modifications to account_map will be reflected in all instances.

Actually if you look at the extract and file_account code you can see how
account gets modified. The second time extract is called it already has the
Chequing-7655 appended. Then file_account adds it again.

**Comment by mondjef** [comment]
The account_map is just to translate a 4 digit identifier into something more into the full beancount associated account.  It is fine that all instances share this account mapping, there is only one mapping right now but the plan is to extend this to all my accounts at this institution so that I can use the one importer for all accounts.

I think the issue is with the extract function, I am trying to extend the extract function that is supplied in the generic csv importer provided by beancount by supplying it the dynamically derived account name by setting it before calling the extract function of the csv importer.

**Comment by mondjef** [comment]
not really sure how, but if I change my extract function to it works...but I don't understand how my extract function is aware of the dynamically set value for account:

```
    def extract(self, file):
#        self.account = self.file_account(file)
        return super().extract(file)
```

**Comment by mondjef** [comment]
I guess there is something I am not quite grasping along the way here....

My logic or way of thinking was this, in extract() of the beancount csv importer there is a reference to self.account when constructing the transactions during extraction and because I am wishing to dynamically derive the account based on filename and a lookup I need to somehow make extract() aware of this value instead of the account value that is originally passed in when the importer is called.  This is where the logic came in to set self.account to this derived account prior to calling super().extract() (beancount csv import extract()).  I thought this would be fine as each instance of the importer is called with account value set to root account 'Assets:Simplii' but it seems that each instance shares values and somewhere file_account() is being called but I am not aware where hence why I am explicitly making the call.

**Comment by mondjef** [comment]
so I have managed to get this working however I don't think its the proper way to do it...

I changed the extract function like this

```
def extract(self, file):
    self.account = self.file_account(file)
    postings = super().extract(file)
    self.account = 'Assets:Simplii'
    return postings
```

basically I set the self.account to the value I need to, call the parent class extract function saving results to variable, reset the self.account variable and return results. Seems more of a work around than the proper way but at least its here in case it helps someone else out.
