### ISSUE TITLE
`input in flex scanner failed`

### ISSUE THREAD

**Issue by bspeice** [beancount/fava#814]
Not 100% sure of what exactly is going on in the application, but things appear to start, and then die whenever I try to view the page in my web browser:

```
[bspeice@bspeice-MS-7971: finance]$ fava .
Running Fava on http://localhost:5000
input in flex scanner failed
```

Noting that it doesn't fail until I actually try to view the web page, there's no indication of an error on startup. This was done using the most recent `pip3 install fava --user`, please let me know if there's something different I should be doing.

**Comment by yagebu** [comment]
Thanks for the report. The Beancount parser uses flex and I don't know if this is related to Fava. Does running bean-check and others work on the file?

**Comment by bspeice** [comment]
`bean-check` has no issues, I'm about to validate everything just fine. I'm going to try later today and see if the user mode installation is an issue.

**Comment by xentac** [comment]
Are there other files in that directory that aren't beancount files? I list
my beancount files explicitly on the command line.

**Comment by bspeice** [comment]
Ah, found the issue, thanks for that comment. I shouldn't have been running `fava .`, it should've been `fava main.bean`. Thanks for the assistance!

**Comment by yagebu** [comment]
Damn, should have noticed that...

This is still a bug though, Fava should fail with a more understandable error message.
