### ISSUE TITLE
Filter by "Events"

### ISSUE THREAD

**Issue by christopherjenness** [beancount/fava#820]
beancount and fava can keep track of events, but doesn't make any use of them.   It would be nice to at least be able to filter by event.

**Comment by yagebu** [comment]
There's the "Events" page... What do you mean by "filter by event"?

**Comment by christopherjenness** [comment]
> There's the "Events" page

My understanding is the events page is just for looking at your events. 

> What do you mean by "filter by event"?

What if you want to know how much you spent on groceries while you lived in a certain city? For example

**Comment by yagebu** [comment]
What meanings the events have are really up to the user, I don't really see how we could use them to filter in a generic way - how would you suggest we do it?
