### ISSUE TITLE
Add option 'import-destination'.

### ISSUE THREAD

**Issue by sarg** [beancount/fava#822]
My ledger is split between few beancount files. My current setup presumes that main file is used only to declare options, open/close accounts and include other files. It would be nice to have `import-destination` option which points to beancount file where new entries should be written.

**Comment by yagebu** [comment]
There's the `insert-entry` option which handles this.

**Comment by sarg** [comment]
Consider referencing this option in `fava/fava/help/import.md`

**Comment by yagebu** [comment]
> Consider referencing this option in fava/fava/help/import.md

Sounds good (that help page is a bit short anyway) - willing to do that in a PR?
