### ISSUE TITLE
custom query list only shows the first 5 queries

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#828]
I've 10 user-defined queries, but the query list on the Fava UI only shows the first 5, ignoring the others.

Looking at the template code I'm not entirely sure how, as it seems to iterate over all queries.

I'm sure all queries are well-defined and accessible by bean-query, as I use them regularly using the CLI tools.

(Related to this: there might indeed be a problem with too many user-defined queries which will overflow the left panel. The right solution to this seems to be allowing folding/unfolding the Query menu item in the panel.)

**Comment by zacchiro** [comment]
ah, no, silly me, just found `sidebar-show-queries`, sorry for the noise :)

**Comment by lucasew** [comment]
> ah, no, silly me, just found `sidebar-show-queries`, sorry for the noise :)

thank you for the SEO
