### ISSUE TITLE
make custom query list foldable

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#829]
When there are many custom queries the vertical screen estate occupied by the Query menu entry might become significant. The current solution of only showing up to `sidebar-show-queries` queries does not fix this, as it just makes impossible to one-click execute the queries that are not shown. A better solution would be to make the Query menu entry foldable/unfoldable upon click.

**Comment by yagebu** [comment]
Foldable and scrollable with some maximum height would be ideal IMHO

**Comment by yagebu** [comment]
@zacchiro: PR?

**Comment by zacchiro** [comment]
I can propose something, but I haven't yet had time to lookup the right CSS incantations. If you know them off the top of your head and can mention it here (even if they've to be double-checked, I don't mind), it will increase the chances that I can PR something :) TIA

**Comment by zacchiro** [comment]
OK, I've found all the ingredients now, but I'm overwhelmed by the event propagation mechanism in the JS part of Fava. Can you point me to what would be the most Fava-style way of adding a simple onclick handler that will fire when clicking on the "Query" menu item in the sidebar? (I've already added IDs to each menu entry, so it's easily selectable using CSS selectors.) Alternatively I can simply put the handler in the HTML template, but I guess you wouldn't like it :)

**Comment by yagebu** [comment]
The events that are in use are documented in `main.js`. Since the element that triggers the toggle should probably be a button you can use the `button-click-*` event. Simply put a handler for that in `sidebar.js`.

**Comment by yagebu** [comment]
@zacchiro: Are you still planning to work on this?

**Comment by yagebu** [comment]
ups

**Comment by zacchiro** [comment]
On Sat, Dec 08, 2018 at 02:08:20PM -0800, Jakob Schnitzer wrote:
> @zacchiro: Are you still planning to work on this?

I'm, but I'm struggling to find time to implement/test it.

If it's annoying to let this linger in the open issue list, feel free to
close, I'll just submit a PR when I have one.
