### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by HKTKzyx** [beancount/fava#832]
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 3601: illegal multibyte sequence

When I try to create a transaction through the web, the previous error will occur.

**Comment by yagebu** [comment]
Could you provide more details?

**Comment by HKTKzyx** [comment]
When I use fava's editor to take a transaction, it will fail and indicate that "internal error". The error code is mentioned in my last comment.

**Comment by yagebu** [comment]
I assume that this is due to your system locale being something other than utf-8. Without any traceback or log this will be impossible to track down. Can you run fava in debug mode and post the output?

**Comment by yagebu** [comment]
Without any further feedback, this is impossible to track down...
