### ISSUE TITLE
set chart y axis range

### ISSUE THREAD

**Issue by alexmat** [beancount/fava#840]
Is there a way to set the net-worth chart y axis range? It's very hard to see changes in net worth with the y axis starting at zero. Would be great if it was +/- 10% or so of the lowest and highest net-worth for the chart period.

**Comment by yagebu** [comment]
Sounds good! Keen to implement this?

**Comment by alexmat** [comment]
Looks like the change would have to happen in charts.js and I'll need to look into D3. Does that sound like I'm on the right track? I can give it a shot but might need some hand holding :)

**Comment by yagebu** [comment]
Thanks for giving it a shot! :)

That sounds like you're already on the right track. I guess the relevant part will be related to the scale (or maybe the axis) of the chart, so part of d3-scale and d3-axis, both of which are well-documented on their respective Github pages. I guess increasing the domain of the scale should do it. If you need any further help, just ask :)

**Comment by alexmat** [comment]
Took me a bit to get up to speed, but I think I have a first draft. Look forward to hearing your feedback.
