### ISSUE TITLE
Net worth line chart should match "At cost", "At market value"

### ISSUE THREAD

**Issue by scanta2** [beancount/fava#841]
In my opinion, the net worth line chart should match the selection of "At cost", "At market value", etc, so that it matches what the tables shows right below.

What do you think?

**Comment by yagebu** [comment]
I think "net worth" offers the most value as a simple gauge of ones financial situation, which it does when behaving like the current chart: Showing (assets + liabilities) converted to all operating currencies separately.

It is however somewhat inconsistent - so I'm not opposed to changing it to also respect the conversion setting. What do others think?

**Comment by scanta2** [comment]
My reasoning for having more consistent charts is that the "At cost" net worth can be subtracted from the "At market value" net worth to show unrealized gains/losses over a period of time.

**Comment by scanta2** [comment]
This commit sort of works, but it shows nice results only if you book all commodities at cost. Sometimes I don't want to do that, because if I do, fava will show the cost/price amount instead of the unit amount. This also does not work well with multiple currencies (ie commodities bought in Euro, but Euro is not an operating currency)

For example

```
2010-01-01 * "Buy House"
 Assets:Fixed:House -515000 USD
 Assets:Fixed:House 1 HOUSE @ 515000 USD
```

vs 

```
2010-01-01 * "Buy House"
 Assets:Fixed:House -515000 USD
 Assets:Fixed:House 1 HOUSE {515000 USD} @ 515000 USD
```

**Comment by scanta2** [comment]
Also, other commodities such as vacation hours, mileage points, etc, which do not convert to an operating currency because they have no price/cost, show up in the balance sheet graphs.

**Comment by yagebu** [comment]
> but it shows nice results only if you book all commodities at cost.

That's what you get for consistency ;)

**Comment by scanta2** [comment]
:) I really appreciate the work on this!
Would it be possible to only render those commodities that convert to
operating currencies instead?

**Comment by yagebu** [comment]
No, I'd be opposed to that - I think we shouldn't hide any amounts

**Comment by scanta2** [comment]
OK I get your point. It is much more consistent now, thanks for fixing! But what about Income Statements and Trial Balances?
Trial Balances have a nifty drop-down menu that lets you choose an operating currency. Maybe we can add that to the Balance Sheet, with an "All" option to show all commodities?
