### ISSUE TITLE
Improve chart colour palettes

### ISSUE THREAD

**Issue by mschwld** [beancount/fava#843]
Hello,

im running fava version 1.9. The color of the bar chart used to blue (which was fine), the way they're in the demo. My beancount file now creates red bars. I tried it with the huge example file from [1] and got purple bars:
![purple](https://user-images.githubusercontent.com/19236996/47984243-51839080-e0d6-11e8-820c-003fb7589c43.png)

How does the color come about and how do I get back to the blue variant?
Thank you in advance for your help.

[1] https://fava.pythonanywhere.com/huge-example-file/income_statement/

**Comment by yagebu** [comment]
The chart colours are chosen from a fixed colour scale (https://github.com/d3/d3-scale-chromatic#schemeCategory10), which is initialised with the list of currencies - so if that changes, the colours for a given currency might change. I don't really want to make this configurable - is purple so bad? ;)

**Comment by mschwld** [comment]
Purple would be fine, but my file produces red graphics where the contrast to the otherwise blue surface is too big for me. So I thought there might be something wrong with my currency configuration. 

I have found out that i can cycle through the color scale by adding some "fake" opening-statements only for this purpose:

; Only to switch colors
2017-07-01 * "Opening"
  Assets:SomeAccount     1 ABC {0.00 EUR}
  Assets:SomeAccount     1 DEF {0.00 EUR}
  Equity:Opening-Balances

Maybe this will help those who also want to force a color change. Otherwise, I now know that Favas' behaviour in my case is intended, so that clarifies my question. Thanks for your help!

**Comment by yagebu** [comment]
> red graphics where the contrast to the otherwise blue surface is too big for me. 

We're not fixed on the current selection of colours. If anyone comes up with a range of 10 or so colours that are more pleasant on the eyes, I'd be happy to change them.

**Comment by yagebu** [comment]
I've changed the generation of the colours, they are hopefully lighter on the eyes now.

**Comment by geekplux** [comment]
I guess we also need a color blind mode 😅 because d3's default color schema is not clear enough for color blind people, just like me 😅

**Comment by James-E-A** [comment]
Is there an API for plugins to manipulate these colors?

**Comment by James-E-A** [comment]
> What kind of manipulation do you want to do?

Same sort of thing as everyone else, just generally manipulate them, particularly on the pie chart view — show the Rent & Taxes category as red, Communications as green, Energy as yellow, Household Maintenance as grey, etc.

**Comment by createyourpersonalaccount** [comment]
In Trial Balance > Icicle with gray font and pastel colors I can barely read the text! Treemap only slightly better. Why are you using gray as opposed to black if you're going for pastel colors? I'm using Fava's dark theme.

<img width="178" height="202" alt="Fava Treemap image showing bad colors" src="https://github.com/user-attachments/assets/bcef629b-6676-4945-aaa3-0319d6d84dc4" />

Can you even see the word "Assets" above?

**Comment by seowalex** [comment]
I'm assuming that it's because in light mode, it looks ok. But yes, could the colour be changed for the icicle layout?
