### ISSUE TITLE
Functionality similar to bean-bake for fava?

### ISSUE THREAD

**Issue by gety9** [beancount/fava#846]
Guys hi,

It will be great to have possibility to generate static files. This way beautiful fava reports can be shared with people who don't have beancount installed. (CPAs, tax advisors, partners, etc)

**Comment by yagebu** [comment]
Because Fava is not as static as bean-web, a functionality similar to bean-bake is not really possible afaict. You can print report as PDFs and there's an issue tracking exporting to Google Sheets (#452). How would you envision this feature?

**Comment by yagebu** [comment]
It would also be simple to export single reports to HTML, if someone wants to implement that.
