### ISSUE TITLE
Different lots clutter up "last update" view

### ISSUE THREAD

**Issue by tbm** [beancount/fava#847]
The statistics pages show the "last update" for each account - it also shows that the account contains, but different lots clutter up the view.  i.e. if you bought 1 AAA one one day and 3 AAA on another, it won't show just 4 AAA but 1 AAA and 4 AAA separately.  I don't think this adds any value on this page since the always have the "holdings" page.

![fava-last-update](https://user-images.githubusercontent.com/1556037/49392944-9aac1c00-f738-11e8-95ce-00fc3007737d.png)

**Comment by yagebu** [comment]
Yep, you're quite right. I never really use that page...

**Comment by tbm** [comment]
> Yep, you're quite right. I never really use that page...

Yeah, I think it's the first time I looked at the page properly.

Thanks for the fix!
