### ISSUE TITLE
Update fava dockerfile

### ISSUE THREAD

**Issue by manojkarthick** [beancount/fava#848]
First of all, fava is awesome. Thank you!

I noticed that @yegle seems to have updated the Dockerfile on his repo to use multi-stage builds now. This approach is cleaner and also produces much smaller image.

```
$ docker image ls
manojkarthick            fava                fb0f642cb0db        44 seconds ago      152MB
yegle/fava               latest              68ceba8d0e0f        7 months ago        129MB
```

It would be great if the official fava repository on Docker Hub is updated to use the newer image, or maybe add a mention in the docs to use `yegle/fava` for those who want to use fava through docker.

**Comment by adamgibbins** [comment]
Have you tested this? It doesn't actually work for me, nothing in the logs and HTTP just returns nothing.
```
% curl -vvv http://localhost:5000
* Rebuilt URL to: http://localhost:5000/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5000 (#0)
> GET / HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.54.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Comment by adamgibbins** [comment]
Also, curiously - my fava image is much smaller than yours? Are you certain you're running HEAD?
`fava                                       latest              0002695e7054        2 weeks ago         124MB`

**Comment by manojkarthick** [comment]
I did not test it until now. It doesn't work for me as well. Also strangely I notice that my image file seems to have different sizes on my linux box vs macOS.

**Comment by adamgibbins** [comment]
Sorry ignore me, I'm a muppet -- I think I was running a version with a newer alpine and forgot I'd done so, just rebuilt and its the same as yours. Ignore me, sorry for the confusion.

**Comment by adamgibbins** [comment]
@yegle yeah that doesn't work for me, I get the failure mentioned above. Unclear why, I tried the image on the hub and building it myself, same result.

**Comment by yegle** [comment]
Hmm weird, I'm trying my latest docker images `yegle/fava:latest`, and I can use it without issue.

**Comment by adamgibbins** [comment]
😕 how odd, I've even tried with an empty file same result.
`% touch test.beancount; docker run --rm -ti -p 5000:5000 -v $(pwd):/beancount -e BEANCOUNT_INPUT_FILE=/beancount/test.beancount yegle/fava:latest`

`curl http://localhost:5000
curl: (52) Empty reply from server`

**Comment by adamgibbins** [comment]
Ha, good catch, that was the problem indeed.
Not sure what wants doing with this issue, do we merge the @yegle into this repo and maintain it forever more. Or do we just point the README at @yegle's repo.

**Comment by yegle** [comment]
Note my repo was previously imported to fava repo already: https://github.com/beancount/fava/commits/master/contrib/docker
