### ISSUE TITLE
Barchart auto-filter to quarterly view fails to parse

### ISSUE THREAD

**Issue by moraxy** [beancount/fava#850]
Go to `Income Statement` and select the `Quaterly` time interval (e.g. [in the live demo](https://fava.pythonanywhere.com/example-with-budgets/income_statement/?interval=quarter))  
Clicking on any of the quaterly ticks on the x-axis autofills the time filter box at the top with, for example, `2016Q2` instead of `2016-Q2`, causing a parsing error.

Should be as simple as fixing the format string in `timeFilterDateFormat`:
https://github.com/beancount/fava/blob/aaa95eb85489229405d0c1e8cc7fc66c82b5c1f9/fava/static/javascript/format.js#L44-L52

After some digging in the git history, it seems like a simple typo that was introduced in c66dcb154fc1afa024f9c8643a9d4d18abf60456 way back in August 2016.

Chrome 71.0.3578.80 and Fava current.

**Comment by yagebu** [comment]
Thanks!
