### ISSUE TITLE
ImportError: cannot import name '_parser'

### ISSUE THREAD

**Issue by saqib-nadeem** [beancount/fava#851]
While deploying app to AWS Lambda getting error below:
![screen shot 2018-12-18 at 4 33 03 pm](https://user-images.githubusercontent.com/3468379/50227051-99305400-03c6-11e9-8d54-d7a32151d75f.png)

**Comment by saqib-nadeem** [comment]
@adamgibbins @xentac @mhansen @yegle Can you please guide on above issue.

Thanks in advance!

**Comment by yagebu** [comment]
This has little to do with Fava actually and rather with Beancount - Beancount uses C code for its parser which needs to be compiled (and apparently didn't get compiled in your case).

Never used AWS Lambda, what's the installation procedure for Python packages like there?

**Comment by yegle** [comment]
It looks like when you do deployment, the `_parser.so` file was omitted, or you built beancount C extensions on a system that's not compatible with AWS Lambda's Linux environment.

Alternatively, if you just need a free hosting of fava, I would highly recommend you to try App Engine's new Python 3.7 runtime, which was announced GA yesterday. (disclaimer: I work for the company on this product).
