### ISSUE TITLE
Configurable and more relevant unit display options

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#854]
Some suggestions about the unit display list (at cost, at market value, units, etc.):

- There is a long list of "Converted to XXX" for each ticker I have in my portfolio. This can make a for a long list of irrelevant options. It would be great if this could only display currencies and not ticker symbols, as I don't see a use case for displaying journal entries in arbitrary ticker symbol units

- "Units" could perhaps be renamed to something more meaningful. Examples: "Native units" or "Unchanged"

- Can the default journal units display be configured to something other than "At cost?" If not, is it possible to make this configurable? I like that the "?conversion=units" is sticky, but if I keep having to remember to do that each time I start up. No biggie, and not worth it if this is more a few minutes of work

- Speaking about which, "At cost" is probably not the best default: I'd guest the more common use case would be current market value, but I might be mistaken

**Comment by yagebu** [comment]
> There is a long list of "Converted to XXX" for each ticker I have in my portfolio. This can make a for a long list of irrelevant options. It would be great if this could only display currencies and not ticker symbols, as I don't see a use case for displaying journal entries in arbitrary ticker symbol units

Sounds good .

> "Units" could perhaps be renamed to something more meaningful. Examples: "Native units" or "Unchanged"

I find "units" good enough ;)

> Can the default journal units display be configured to something other than "At cost?" If not, is it possible to make this configurable? I like that the "?conversion=units" is sticky, but if I keep having to remember to do that each time I start up. No biggie, and not worth it if this is more a few minutes of work

I'd rather strive for consistency here and keep the current behaviour.

> Speaking about which, "At cost" is probably not the best default: I'd guest the more common use case would be current market value, but I might be mistaken

I find it a good default. It matches Beancount's default also.
