### ISSUE TITLE
installation fails: ImportError: No module named 'setuptools_scm'

### ISSUE THREAD

**Issue by tbm** [beancount/fava#856]
On Debian stable with Python 3.5 I get:

```
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'setuptools_scm'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/tbm/scratch/cvs/fava/
```

**Comment by tbm** [comment]
Actually, this is not a 3.5 issue.  It works fine after I install `python3-setuptools-scm`.

Maybe a documentation issue.

**Comment by yagebu** [comment]
It's listed in `setup_requires`, so setuptools should download it...

**Comment by tbm** [comment]
I saw that but it didn't do that. I don't know...
