### ISSUE TITLE
"Cost" column does not show error if off by one cent

### ISSUE THREAD

**Issue by senorsmile** [beancount/fava#857]
I insert "balance" transactions regularly to verify that the balance is accurate in beancount.  

I just came accross an issue where my balance was off by 1 cent for 5 months!  I finally found the transaction and fixed it. 

If this would have made the balance under the "Cost" column go from green to red, like it should, I wouldn't have had to track down this error.  

Is there an adjustable configuration value somewhere I can set to zero?  Or is this simply a bug?

**Comment by adamgibbins** [comment]
This is a beancount "issue" rather than a fava one, as thats what does balance enforcement. You'll probably want to read https://docs.google.com/document/d/1lgHxUUEY-UVEgoF6cupz2f_7v7vEF7fiJyiSlYYlhOo/edit if you haven't already.

**Comment by adamgibbins** [comment]
Have you read https://docs.google.com/document/d/1lgHxUUEY-UVEgoF6cupz2f_7v7vEF7fiJyiSlYYlhOo/edit this is a beancount rather than fava thing.

**Comment by senorsmile** [comment]
ah, you are right! I had not read through that doc before.  

putting the balance with the extra ~ x.xx as in
`100.00 ~ 0.00 USD`
definitely makes it do what I expect. 

I glanced through most of it, and didn't see any option that I could make that permanent (i.e. for all balances).  Either way, at least I know it's beancount (not fava) and how to make my balances err on 0.01 variance.

**Comment by adamgibbins** [comment]
You can set the default tolerance with inferred_tolerance_default. But AIUI if you're consistent with your decimal points, i.e. always use 0.00 USD, not sometimes 0 USD and other times 0.000 USD etc - it should do the right thing.
