### ISSUE TITLE
Remnants of statement metadata

### ISSUE THREAD

**Issue by vianney** [beancount/fava#860]
With #740, the `statement:` metadata key was renamed to the more generic `document:` key, but there are some remnants of the old key in the code (tested on 1.9):

* When uploading a document through drag-and-dropping on a transaction, fava adds a `statement` metadata instead of `document`.
* The "Fava's features" help page describes the old metadata and inexistent `fava.plugin.link_statements` plugin.

**Comment by yagebu** [comment]
The second point was addressed by #858, a PR for the first would be welcome.
