### ISSUE TITLE
autocommit plugin doesn't work

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#862]
I've tried using the [autocommit plugin](https://github.com/beancount/fava/blob/master/fava/ext/auto_commit.py) (or adaptations of it made by myself using the same hooks) but it doesn't seem to do anything at all. Here is a minimal example that reproduce the issue with Fava 1.9:
```
$ git init fava
$ cd fava
$ cat >> fava.beancount
option "operating_currency" "EUR"

plugin "fava.ext.auto_commit"

1970-01-01 open Equity:Opening-balances
1970-01-01 open Assets:Bank:Checking
1970-01-01 open Expenses:Dining

1970-01-01 commodity EUR

2019-01-01 * "opening balances"
    Assets:Bank:Checking       42.00 EUR
    Equity:Opening-balances

2019-01-01 * "Luigi's" "pizza"
    Expenses:Dining             7.00 EUR
    Assets:Bank:Checking
CTRL-D
$ bean-check fava.beancount
$ git add fava.beancount
$ git commit -m 'initial ledger checkin'
[master (root-commit) 311d51a] initial ledger checkin
 1 file changed, 17 insertions(+)
 create mode 100644 fava.beancount
$ fava fava.beancount
Running Fava on http://localhost:5000
```

In the resulting Fava web UI I can edit the journal and add transactions using the submission form. The corresponding edits / added transactions are properly saved to fava.beancount, but not committed in Git.

Is the plugin not working, or am I missing something here?

**Comment by yagebu** [comment]
> Is the plugin not working, or am I missing something here?

No clue. Have you tried debugging this?

**Comment by zacchiro** [comment]
Debugged it, found the issue, and it's PEBCAK: s/plugin "fava.ext.auto_commit"/1970-01-01 custom "fava-option" "extensions" "fava.ext.auto_commit"/ in my example.
