### ISSUE TITLE
This is beautiful! Thank you!

### ISSUE THREAD

**Issue by davidrusu** [beancount/fava#863]
Just wanted to say that this tool is just a joy to use, thanks for your work on this! :)

**Comment by zahanm** [comment]
❤️ me too!

**Comment by majkinetor** [comment]
Amazing. I never wanted to have anything with accounting but this started it...

Totally intuitive, great minimal and cleand design yet functional.

**Comment by yagebu** [comment]
Thanks for the praise! :)
