### ISSUE TITLE
ModuleNotFoundError: No module named 'readline'

### ISSUE THREAD

**Issue by saqib-nadeem** [beancount/fava#864]
@adamgibbins @mhansen @yegle @mariosangiorgio 

Getting this error below:

  File "/var/task/two_app.py", line 4, in <module>
  from myfava import app as favaapp
  File "/var/task/myfava.py", line 3, in <module>
  from fava.application import app
  File "/var/task/fava/application.py", line 34, in <module>
  from fava.core import FavaLedger
  File "/var/task/fava/core/__init__.py", line 31, in <module>
  from fava.core.query_shell import QueryShell
  File "/var/task/fava/core/query_shell.py", line 5, in <module>
  import readline

**ModuleNotFoundError: No module named 'readline'**

Any help is appreciated!

**Comment by yegle** [comment]
Your Python interpreter did not compile with `readline` library.

**Comment by saqib-nadeem** [comment]
@yegle, I'm using python 3.6 and issue came while deploying to AWS lambda.

**Comment by yegle** [comment]
It's irrelevant whether you are using some fancy tech, your interpreter was not compiled with `readline` library.

As for AWS, you should contact their tech support.

**Comment by saqib-nadeem** [comment]
ok, thanks
