### ISSUE TITLE
Show net profit on income statement

### ISSUE THREAD

**Issue by zacchiro** [beancount/fava#867]
In the Net Profit view currently there is the timeline plus two columns, for Income and Expenses. It would be nice to show somewhere the cumulative total of Expenses - Income (i.e., the cumulative net profit) matching the current view and filters.

Right now one can easily obtain the net profit only for each bar in the chart (by hovering with the mouse cursor) or by mentally doing the difference between the topmost entries in the Expenses and Income chart, which is kind of annoying.

**Comment by yagebu** [comment]
I don't understand what you mean by "Net Profit view". If you're referring to the net profit chart, that one already does exactly what you seem to request: show the sum of income and expenses (per interval).

**Comment by zacchiro** [comment]
I'm talking about the Net Profit "tab" of the Income Statement view. It shows the profit chart and the sum of income and expenses *per interval* indeed. But it does not show the sum of income and expenses over the entire time period being observed. Or, alternatively, the grand total of all the bars you're seeing in the chart.

So, say, if you've filtered on a specific time period, e.g., 2015-2019, and you've selected yearly charting, *for each year* you can easily find your net profit, but you don't have an easy way to find out your net profit over the overall period. To do so you've to either add up the values of each bar, or make the sum of the top cells in the Expenses and Income tables.

Hope this clarifies,

**Comment by zacchiro** [comment]
So, if you're against this, what is then the recommended Beancount way to see "how well" something that you've tracked with accounting went in terms of expenses+income?

What I currently do is:
- set up my filters using the top bar (time period, tags, metadata, etc.)
- go to the net profit view
- add up (in my head or with an external calculator) the totals of the Income and Expenses tables just below the net profit chart

Of course I can do a BQL query in the Query view, but that feels weird, given I'm using a UI. If the proper way is to use BQL, then I could as well just run bean-query on the command line.

Am I missing something here?

**Comment by zacchiro** [comment]
Income statement in the "net profit" tab, as per initial suggestion, or as you saying to put it in a different tab of that view?

**Comment by yagebu** [comment]
There aren't any "tabs" on the income statement - it's just one page, you can only switch between the charts.

**Comment by zacchiro** [comment]
OK, so you want it below the charts, in the common part. I'll give it a try.

**Comment by yagebu** [comment]
> OK, so you want it below the charts, in the common part. I'll give it a try.

Yes, it would be unnecessarily complicated to implement otherwise.

I don't where net profit will usually be positioned on an income statement, but if there's some sensible convention, we should follow it.
