### ISSUE TITLE
Fava insert-entry options

### ISSUE THREAD

**Issue by huydbui** [beancount/fava#875]
**_Please excuse me if I'm posting this wrong. This is new, I don't know how to ask for help. This is NOT AN ISSUE. I just need some help. I've been doing research without any luck._**

-----
**What I want (short version):**
To be able to insert new transactions (via GUI) into the same transaction group of the same credit card (or any account/payment method/...), not at the end of the file.

**What I want (long version):**
Hypothetically, let say I have these transactions already:

> 2017-09-01 * "Corner Deli" "Buying groceries"
>  Liabilities:US:Chase:Slate                        -112.86 USD
>  Expenses:Food:Groceries                          112.86 USD
>
> 2017-09-02 * "Corner Deli" "Buying groceries again. Ate them all already."
>  Liabilities:US:CapitalOne:Spark               -32.15 USD
>  Expenses:Food:Groceries                          32.15 USD

On the 3rd, when I add one more transaction for Slate, it will be under the 2017-09-02 transaction by default. I want it to be under 2017-09-01 because it is Slate. If it was Spark, then under 2017-09-02 is correct.

**What I had found (could be the solution):**
Visit: [https://fava.pythonanywhere.com/example-with-budgets/help/options/](https://fava.pythonanywhere.com/example-with-budgets/help/options/)
Read: _insert-entry_

**What I am asking:**
How to set this option, what value to set? If it's possible, please give me an exact value for insert-entry base on this example so I can figure it out.

**Comment by yagebu** [comment]
> How to set this option, what value to set?

    2018-01-01 custom "fava-option" "insert-entry" "Liabilities:US:Chase:Slate"

after the transaction on that account. As written in the documentation, the position of the insert-entry option in the file will be used to insert the transaction before it.

**Comment by huydbui** [comment]
If you have many cards, Slate1, Slate2, Slate3, Slate4. Doing that will only insert into Slate correct? How does it know when to insert into Slate1/Slate2/Slate3... group?

**Comment by yagebu** [comment]
The value that this option takes is a regular expression matching the account name - so you can add `.*` at the end to match all accounts starting with that string.
