### ISSUE TITLE
Tree-View toggled by default

### ISSUE THREAD

**Issue by llpamies** [beancount/fava#876]
Is there any way to get tree-views to be all toggled by default?

It would be even better if there was an option/config to set the tree depth starting from where you want everything to be toggled by default :)

**Comment by xentac** [comment]
https://github.com/beancount/fava/blob/5c8a2bb8817a0ddfd851e51a86e19c00ae2c3b6e/fava/help/features.md#displaying-only-relevant-accounts

The option you want is "fava-collapse-account" as metadata on the account.

**Comment by vloris** [comment]
> The option you want is "fava-collapse-account" as metadata on the account.

That's a nice option! But it only works if the parent account you want to collapse is a 'real' account. In my case usually it doesn't, so I can't attach metadata.
I don't want to have to create a 'real' parent account, to enforce amounts can only be posted to sub-accounts, not to the parent account itself.

**Comment by xentac** [comment]
You could open the account far in the future or only allow a fictitious currency in the account or set a balance directive for far in the future as well.

I feel like there should be a way to open an account for the purposes of metadata but not allow any postings to it.

**Comment by mbudde** [comment]
> You could open the account far in the future or only allow a fictitious currency in the account or set a balance directive for far in the future as well.

This is the workaround I currently use (using a fictive `DONTUSE` currency) but it feels like a hack. Ideally I would like to be able to do something like:
```
2000-01-01 custom "fava-option" "collapse-below-level" "3"
```
meaning that all accounts below level 3 would be collapsed by default. `fava-collapse-account` metadata on an account should still override this option such that it would be possible to collapse most subaccounts but keep a few open. If you would accept a pull-request for that feature I would like to give it a shot.

**Comment by yagebu** [comment]
Sounds good @mbudde!
