### ISSUE TITLE
Opening balances valuation in Balance Sheet

### ISSUE THREAD

**Issue by nick-buhro** [beancount/fava#877]
Hello, I am very impressed by the Fava/Beancount and thankful for it. I'am in a stage of migration from GnuCash and it seems that I found a bug. Please correct me if I misunderstand something or it exists a better way for transaction recording.

As my local currency isn't very stable, I use USD as reporting currency. The issue is related to the Balance Sheet report in "Converted to USD" view. For better understanding let's see small example with 3 transactions:

``` Beancount
option "operating_currency" "USD"

2018-01-01 open Equity:Opening-Balances USD
2018-01-01 open Assets:USD              USD
2018-01-01 open Assets:BYN              BYN

; YEAR 2018

2018-01-10 * "Opening balance"
    Assets:USD         1000 USD
    Equity:Opening-Balances

2018-01-21 * "USD => BYN"
    Assets:BYN         2000 BYN @ 0.50 USD
    Assets:USD        -1000 USD

2018-12-30 price BYN   0.40 USD ; Set end of the year price for valuating unrealized loss in USD

; YEAR 2019

2019-01-05 * "BYN => USD"
    Assets:BYN        -2000 BYN @ 0.25 USD
    Assets:USD          500 USD

2019-02-05 price BYN   0.20 USD  ; Try to comment this
```
In this example we buy currency BYN in 2018 and sell it all in 2019 with loss (not recorded directly).

At the end of 2018 we have 2000 BYN and we expect that it would be converted using price from 2018 (0.4). So the expected equity is -800.

Also it's expected that 2019 opening balance should be uqual to the 2018 equity (2000 BYN with valuation of 800 USD). __It means that 2019 opening balance should be valuated by the 2018 prices.__

But it seems that Fava uses current prices for valuation of opening balances. It is disappointing because changing current prices affects historical data (previous period equity and current period opening balance).

P.S.: for listed example it's converted to USD Balance Sheet:

|  | 2018 (expected) | 2019 (expected) | 2019 (actual) |
| --- | ---: | ---: | ---: |
| **ASSETS**  | **800** | **500** | **500** |
|   Assets:BYN         |  800 |      |  |
|   Assets:USD         |      | 500 | 500 |
| **EQUITY** | **> -800** | **-500** | **-500** | 
|   Equity:Conversions |  200 |  300 | -100 |
|   Equity:Opening-Balances     |-1000 | **>** -800 | **>** -400 |

P.S.: Fava 1.10 with Goggle Chrome.

**Comment by yagebu** [comment]
When using the `@ number` price syntax, Beancount doesn't store the price (which is usually sensible for currencies, where the price that, say, one USD was bought for doesn't really matter).

If you want to track the cost of assets, you'll need to use the `{}` cost notation.
