### ISSUE TITLE
extensions: support an options map?

### ISSUE THREAD

**Issue by seltzered** [beancount/fava#878]
While thinking of an example for extension reports https://github.com/beancount/fava/issues/759 , I'm starting to wonder if extensions themselves should allow for an options_map similar to how beancount's own `plugin` statements allow. Doing this likely means changing the `extensions` fava-option from being in `LIST_OPS` to a non-listed `extension` perhaps marked under a new list called `MAP_OPTS` or `OPT_OPTS`.

**Comment by yagebu** [comment]
Sounds like a good idea.

**Comment by seltzered** [comment]
Cool, I'll likely roll this into https://github.com/beancount/fava/pull/872
