### ISSUE TITLE
Interpretation of "Net Worth": total net worth in each currency?

### ISSUE THREAD

**Issue by wzyboy** [beancount/fava#881]
As discussed [here](https://bitbucket.org/blais/beancount/issues/190/use-of-implicit_prices-and#comment-50870360):

(quote @blais )

> The correct interpretation of this is the total networth expressed in each currency. It possible (likely?) that the Fava implementors decided to reproduce this.

Should Fava somehow let user decide if they wants to display "total net worth in each currency" or "total net worth of all currencies"?

**Comment by yagebu** [comment]
Duplicate of #841
