### ISSUE TITLE
default-file could also set the insertion file

### ISSUE THREAD

**Issue by ljani** [beancount/fava#882]
I expected [`default-file`](https://github.com/beancount/fava/blob/77b5436c842f9be27a5dc368a4b058b17d13919e/fava/help/options.md#default-file) option to also set the append file for the "add transaction" dialog of the UI, instead of only changing the behavior which file is opened when editor is opened. Currently the new entries are inserted in the main file regardless of `default-file` setting.

The buttons for the editor and add transaction are next to each others in the UI, thus I found this very confusing.

According the docs, the [`insert-entry`](https://github.com/beancount/fava/blob/77b5436c842f9be27a5dc368a4b058b17d13919e/fava/help/options.md#insert-entry) option seems to be the way to control this, but I think that `insert-entry` should fallback to looking for `default-file` before "the entry will be inserted at the end of the main file."

Any thoughts?

**Comment by yagebu** [comment]
Sure. I don't care much for `default-file` are you willing to provide a PR?

**Comment by ljani** [comment]
I could take a look when I have some spare time, but do not expect it soon.

**Comment by yagebu** [comment]
Closing this stale issue, a PR is still welcome :)

**Comment by abourget** [comment]
Would love this.. how do we change the behavior of the New entry UI?!
