### ISSUE TITLE
How to select custom date range?

### ISSUE THREAD

**Issue by gety9** [beancount/fava#886]
Guys hi,

In [time field](https://puu.sh/CYAmh/bfac711b1a.png) i can input specific year (2017, 2018, etc),
but if i need to have custom date range (example from Mar 1 2018 to Feb 28 2019), how to that?

**Comment by yagebu** [comment]
https://fava.pythonanywhere.com/example-with-budgets/help/filters/

**Comment by tvytlx** [comment]
FYI: The newest URL is https://fava.pythonanywhere.com/example-beancount-file/help/filters

**Comment by yagebu** [comment]
The demo is not really the canonical location for the help pages.
The newest URL really just is the URL for the help pages of your Fava instance ;)
