### ISSUE TITLE
Implement bean-file functionality

### ISSUE THREAD

**Issue by a-bali** [beancount/fava#890]
Please implement filing functionality as originally initiated in PR #837. My workflow (which I believe might be quite typical) consists of downloading the statements to the import directory, importing it via fava and the only thing that still requires beancount CLI is the filing. Adding this functionality would eliminate the requirement for CLI access.

Ideally the filing should be done after a successful import, or alternatively (as implemented in the referenced PR) as a separate action.

**Comment by yagebu** [comment]
A PR continuing #837 would be welcome @a-bali :)

**Comment by yagebu** [comment]
I'll implement this in #915
