### ISSUE TITLE
Balance sheet graph ignores operating_currency

### ISSUE THREAD

**Issue by tbm** [beancount/fava#897]
In the past, the graph on the "balance sheet" tab only showed the commodities defined in `operating_currency`.  It seems that is no longer the case and now all commodities are shown there.  This makes the graph unusable for me since I have over 20 commodities.

**Comment by tbm** [comment]
![bal](https://user-images.githubusercontent.com/1556037/55479398-3480c880-5648-11e9-940c-3e199328cadc.jpg)

**Comment by yagebu** [comment]
Select "Convert to x" then. The old behaviour was rather inconsistent, see #841

**Comment by tbm** [comment]
Sorry, I should have asked this before you closed the bug, but I see an inconsistency.

The `Income Statement` graph still shows only my 3 operating currencies while the `Balance Sheet` graph shows all commodities.  Where is there an inconsistency?

**Comment by yagebu** [comment]
The chart didn't follow the selected conversion - it does now.
