### ISSUE TITLE
Version number in web interface

### ISSUE THREAD

**Issue by tbm** [beancount/fava#898]
When installing I get:
```
Successfully installed fava-1.11.dev35+g32ad62b.d20190403
```

But is there a way to see the fava version number in the web interface?  I can't find it anywhere. (Maybe it would be worth to show the beancount version too)

Then the docs can be updated to tell people to mention the version number when reporting bugs.

**Comment by yagebu** [comment]
`fava --version` shows the version number.

**Comment by tbm** [comment]
Yeah, but I was wondering within the UI. Maybe it's not needed but it might be useful. Not everyone has access to the server.

**Comment by yagebu** [comment]
I'll close this, feel free to open a PR, for me it doesn't seem worth the (small) effort.
