### ISSUE TITLE
Same colours used for multiple commodities

### ISSUE THREAD

**Issue by tbm** [beancount/fava#899]
I have 3 operating currencies.  Two have the same colour.  I thought this got fixed, but i'm using the latest version from Git.

![colour](https://user-images.githubusercontent.com/1556037/55479221-ce944100-5647-11e9-9a93-8ca556ab8680.jpg)

**Comment by yagebu** [comment]
We use a colour scale with a bounded number of colours, so inevitably some will overlap. Seems like a wontfix to me

**Comment by tbm** [comment]
But these are my operating currencies and not just some random currencies. While I agree there might be overlap with many currencies, I think that operating currencies should be given preference and overlap should be avoided for those.

**Comment by yagebu** [comment]
PR?

**Comment by tbm** [comment]
> PR?

I'll try

**Comment by tbm** [comment]
Thanks for fixing this!

I know I said I'd look into creating a PR but haven't had the time yet. (But looking at your fix, I wouldn't have been able to do it anyway!)
