### ISSUE TITLE
fava doesn't get language preference from Accept-Language right

### ISSUE THREAD

**Issue by tbm** [beancount/fava#900]
Fava shows me some German messages, and some messages in English.  I don't know how to check what info my browser is sending, but I always use English everywhere.

This is with latest fava from Git.

I see this in Chromium 72.0.3626.109-1.  I do not see this issue in Firefox 60.5.1esr-1 (all messages are English).

![lang1](https://user-images.githubusercontent.com/1556037/55480140-cb01b980-5649-11e9-82eb-f3e94539637e.jpg)

![lang2](https://user-images.githubusercontent.com/1556037/55480147-cf2dd700-5649-11e9-8104-0e18bc6eaff6.jpg)

**Comment by yagebu** [comment]
Can't reproduce this, without any more info this is non-debuggable...

**Comment by tbm** [comment]
So this is what my browser sends:

> Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,de-DE;q=0.7,de;q=0.6

So `de` is in there but as a lower preference than `en`.

**Comment by tbm** [comment]
And Firefox sends:

> Accept-Language: en-US,en;q=0.5

So it seems that the language preference isn't selected correctly when your `Accept-Language` contains different languages with different priorities.

**Comment by tbm** [comment]
Yep, I changed Firefox to:

> Accept-Language: en-US,en;q=0.7,de;q=0.3

and now I get German there too.

You can reproduce by changing the language choice in your browser. Set English is default, German as second language and fava will be in German.

**Comment by yagebu** [comment]
Fixed. I still don't fully trust the function that chooses the languages to work for all locale+territory combinations, but meh...
