### ISSUE TITLE
Budgets do not display

### ISSUE THREAD

**Issue by Rudd-O** [beancount/fava#903]
I'm running a fairly recent stable release of Fava.  When I follow the instructions outlined [here](https://github.com/beancount/fava/blob/master/fava/help/budgets.md) I do not get any budget information in the table below (but the graphs show the budgets).  As a consequence, I cannot track down which account I've misbudgeted.

Why aren't the numbers showing up in the table below the chart on the report `income_statement`?

**Comment by yagebu** [comment]
The budgets don't show up on the income statement (as they really only make sense on a month-by-month (or other interval) basis). You can find them on the "Monthly Changes" page for an account, e.g., Income.
