### ISSUE TITLE
Upload statements to import directory for ingest

### ISSUE THREAD

**Issue by mondjef** [beancount/fava#904]
Apologies if this exist already but I have not found how to do it if does.  I do not always have physical access to my box that runs the instance of fava for example when I'm at work.  However I would like to download my bank statements and then import them in fava when I have spare time but I can't as I can't get these statements uploaded so that fava can then import.

Can this feature be added or does it already exist?  My thinking is it should allow one to drag a file over the import menu item and the file will be uploaded to the configured import directory.

**Comment by yagebu** [comment]
This could be added, a PR would be welcome :)

As a workaround you could add a dummy account and upload your documents to the account folder for now and then add this folder as one of the import directories.

**Comment by mondjef** [comment]
I would really love to do a PR but my experience in programming/hacking are limited.  I have looked at the mechanics of the drag and drop functionality of uploading documents on accounts as I think it should work sort of similar to that but I cannot quite follow everything on the code side...too many moving parts.  If anyone can point me a bit better maybe I can piece something worthy together but I think I am out of my league.

**Comment by mondjef** [comment]
yes the account upload feature can serve as a work around but it is kind of hacky and it would be better to have a cleaner more intuitive out of the box method I think long term for users.  In the meantime I have a fix though, thanks

**Comment by yagebu** [comment]
This was implemented in #1551
