### ISSUE TITLE
Show FY in time dropdown menu when fiscal-year-end is set

### ISSUE THREAD

**Issue by tbm** [beancount/fava#906]
Fava shows all years that are mentioned in the beancount file in the `time` box.

Some organizations and countries don't follow the calendar year. For example, Software Freedom Conservancy's financial year starts on March 1.  In the UK, the tax year runs from April 6 to April 5.

It would be nice if fava allowed users to configure some time periods.

(I'm not sure if this should be done in fava or beancount. But afaik beancount doesn't have any mechanism for predefined time periods. Any opinion?)

**Comment by adamgibbins** [comment]
Are you familiar with the `fiscal-year-end` option? It won't modify what appears in the time box but it does allow use e.g. `FY2018` within filters. I am British so follow the UK tax year as you point out - so I have `custom "fava-option" "fiscal-year-end" "04-05"` set.

**Comment by tbm** [comment]
Sorry, I missed that option. Sounds exactly like what I want.

"The last day of the fiscal (financial or tax) period for accounting purposes in
`%m-%d` format. Allows for the use of `FY2018`, `FY2018-Q3`, `fiscal_year` and
`fiscal_quarter` in the time filter."

**Comment by tbm** [comment]
Ok, I admit I didn't read the docs before I filed this issue. Fava does what I want.

However, let's make this issue into something useful: even if a FYE is specified in the fava
config, the `time` dropdown menu will show calendar years.  It would be nice to show FYs
in that dropdown.

I will submit a WIP patch but it needs some help from @yagebu.
