### ISSUE TITLE
Unable to set import-config

### ISSUE THREAD

**Issue by floli** [beancount/fava#910]
Hello,

first steps with fava and beancount, so just in case, please forgive ;-)

I wrote a simple importer and try to use with fava. It works with `bean-extract` and `bean-identify`. To use with fava I set the options:

```
option "title" "Example Beancount file"
option "operating_currency" "USD"
2016-06-14 custom "import-config" "bc.import"
2016-06-14 custom "import-dirs" "."
```
However, even after a restart, fava should the two option as unset (`None` resp. `[]`)

Thanks!

**Comment by yagebu** [comment]
Hey, the syntax to specify options for fava is a little different - you need to add `"fava-option"` to the custom entries (see https://fava.pythonanywhere.com/example-beancount-file/help/options/):

```
2016-06-14 custom "fava-option" "import-config" "bc.import"
2016-06-14 custom "fava-option" "import-dirs" "."
```

**Comment by floli** [comment]
Ah, I see. I read the page you linked to, but only the first line
```
2016-06-14 custom "fava-option" "default-file"
```
as I expected a key-value syntax, I parsed it as `fava-option = "default-file`, i.e., took `fava-option` as a placeholder for the key. The next lines, having three entries, make it more clear, that this a multi-level key-value, like `fava-option.interval = "week"`.

I am at the wrong machine right now, will try it out and then close this issue. Thanks!
