### ISSUE TITLE
Fava doesn't show transactions with "txn" with latest beancount

### ISSUE THREAD

**Issue by tbm** [beancount/fava#916]
I submitted a patch to beancount to bring the behaviour of transaction flags in line with the documentation. In the past, both `txn` and `*` led to the `*` flag, but now `txn` leads to `entry.flag` being `None`.

The problem is that Fava's journal view only shows transactions with `*` and `!` flags by default, so the `txn` transactions are not shown.

What's the best way to solve that?  Add a new `txn` button that's on by default?  What should the description of these transaction be? "Transactions without flag"? "Unknown transactions" / "Transactions with unknown status"?

**Comment by yagebu** [comment]
> I submitted a patch to beancount to bring the behaviour of transaction flags in line with the documentation.

As far as I can tell, *one* line of documentation was wrong, the syntax documentation correctly specified the old behaviour and all code occurences did so too.

I think the patch should just be reverted (and the one incorrect line of documentation updated instead).

**Comment by tbm** [comment]
well, treating `txn` and `*` as the same doesn't make a lot of sense. It's useful to have an unknown default (txn), cleared (*) and pending (!).  If you disagree feel free to re-open my beancount issue and comment there.

**Comment by yagebu** [comment]
> well, treating txn and * as the same doesn't make a lot of sense

I disagree - `*` is simply a shorthand for `txn` as explained in the documentation. (I personally dislike that `txn` is allowed at all).

> It's useful to have an unknown default (txn), cleared (*) and pending (!).

There is a default already: `*` - the patch was a breaking change hidden as a "fix". I don't really see any need for the added complexity, if you want to mark some transactions as different, simply mark them with any one of the allowed characters as a flag.

**Comment by tbm** [comment]
Closing since patch got reverted upstream
