### ISSUE TITLE
Align amounts: support for calculated values

### ISSUE THREAD

**Issue by benedekl** [beancount/fava#917]
Align amounts function in editor currently handles only simple numeric values. It would be nice to be able to align even when the value is a result of some calculation:
```
  Expenses:Acc1           47/2 USD
  Expenses:Acc2           47/2 USD
```

Please consider replacing the current regex with this one or something similar:
```
r'([^";]*?)\s+((?:(?:[-+]?\s*[\d,]+(?:\.\d*)?)\s?)*(?:[-+/*]?\s*[-+]?\s*[\d,]+(?:\.\d*)?))\s+([A-Z]+\b.*)'
```

**Comment by yagebu** [comment]
PR?

**Comment by yagebu** [comment]
Closing this stale issue. A PR is still welcome
