### ISSUE TITLE
fava-collapse-account and "unreal" accounts

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#918]
I'd love being able to use the collapse option on "unreal" parent accounts as my account hierarchy is quite deep. It would have to be a fava specific option since the idea is to not have to open an account in beancount. As an example:

```
1901-01-01 custom "fava-option" "collapse-account-below-level" "Assets:Banks" "2"
```

This would also take care of being able to collapse selected root accounts (for instance, I want "Equity" collapsed fully always, but not Assets or Liabilities).

Also see:
> The option you want is "fava-collapse-account" as metadata on the account.

That's a nice option! But it only works if the parent account you want to collapse is a 'real' account. In my case usually it doesn't, so I can't attach metadata.
I don't want to have to create a 'real' parent account, to enforce amounts can only be posted to sub-accounts, not to the parent account itself.

_Originally posted by @vloris in https://github.com/beancount/fava/issues/876#issuecomment-466007149_

**Comment by yagebu** [comment]
I don't want to add ten different options and ways to collapse accounts. If you need customisability beyond what is currently offered, I guess you could add an option taking a regular expression so that accounts matching that regex would be collapsed.

**Comment by redstreet** [comment]
Good idea, regex based collapse would cover all cases without blowing up the options space. I see this would also take care of #919.

It might be a while before I can submit it PR, so I hope it's okay to leave this ticket open so someone can beat me to it.

**Comment by redstreet** [comment]
@yagebu are you thinking the regex option would tried the existing fava-collapse-account and collapse-below-level ?

**Comment by redstreet** [comment]
@yagebu do you see a way the regex option could replace the existing fava-collapse-account and collapse-below-level, so we have a single option to cover all cases?

It can certainly replace fava-collapse-account, but probably not the functionality of collapse-below-level. Thoughts?

**Comment by yagebu** [comment]
> It can certainly replace fava-collapse-account, but probably not the functionality of collapse-below-level. Thoughts?

It can't replace the current collapse-below-level which doesn't use the account level but rather the level in the (displayed) tree. That behaviour is a bit odd anyway though, and if we wanted it to just take the account name into account that could be done with a regex (`[^:]+:[^:]+:.+` to match all accounts with at least 3 components for example)

**Comment by redstreet** [comment]
Agreed that in theory it could replace collapse-below-level, but collapse-below-level is much more intuitive, and is cheaper than a regex as well, so I'd vote for keeping it.

I'll put a PR out soon.
