### ISSUE TITLE
Add level option to fava-collapse-account

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#919]
For fava-collapse-account, instead of taking just a True/False as its argument, it would be great if a number can be specified with the same semantics as the argument for collapse-below-level (see #876). This and #918 together should offer completely customizability of collapse options, from what I can tell.

**Comment by yagebu** [comment]
Oh, please no.

**Comment by redstreet** [comment]
Why?

**Comment by redstreet** [comment]
This functionality is available via #918 now.
