### ISSUE TITLE
A UI option for traditional double-entry accounting users

### ISSUE THREAD

**Issue by wzyboy** [beancount/fava#920]
Source or the idea: https://groups.google.com/forum/#!topic/beancount/wmORvjyVCR8

As we all know, Beancount uses a modified version of the accounting equation, so "Income" and "Liabilities" accounts are usually negative while "Expenses" accounts are usually positive. This leads to confusion if a new user of Beancount / Fava already has experience with traditional double-entry accounting systems (the "debit" and "credit" terminology), as shown in the discussion above.

Could it be possible, that Fava provides an option, to flip the signs and enable a traditional Income Statement and Balance Sheet?

**Comment by vloris** [comment]
It looks like #448 is already a request with ongoing discussion for pretty much the same right?

**Comment by wzyboy** [comment]
Right... I should have searched the issue list. Closing.
