### ISSUE TITLE
Mouse hovering on linechart shows wrong labels

### ISSUE THREAD

**Issue by scanta2** [beancount/fava#923]
In the Balance Sheet view, for "At Market Value" and "At Cost", if you over the mouse over several traces, the algorithm picks the closest point but the y coordinate is flipped, i.e. if you are closest to the top of the chart you'll get a label for the bottom trace, and viceversa.

The issue does not happen when you choose "Converted To xxx" even if you have traces that do not convert.

**Comment by yagebu** [comment]
Can't reproduce this

**Comment by scanta2** [comment]
Here's a screenshot of the issue. I am using Chrome on Ubuntu, but I have seen it for several weeks now, on Fedora, too.
![screenshot](https://user-images.githubusercontent.com/12899673/57583305-de980f80-7494-11e9-8338-2e6f8bf7bdf0.png)

**Comment by xentac** [comment]
If you scroll partway down the screen, the popup is in the wrong spot, which may be what this is.

**Comment by scanta2** [comment]
The pop-up is on the correct trace for the value. The pop-ups just come in in opposite order compared to the pointer location. This does not happen for "converted to usd". I'm wondering if it's due to the number of traces shown.

**Comment by yagebu** [comment]
@xentac: also noticed that when testing for this issue - I've got a fix for that.

**Comment by yagebu** [comment]
I think any errors of tooltip placements were due to some limitations of the voronoi diagrams drawn to determine them. Using a direct search using d3-quadtree (#940) should fix this.
