### ISSUE TITLE
Question: Unreleased v1.11 New Import Design

### ISSUE THREAD

**Issue by MickMorley** [beancount/fava#931]
Currently I import my OFX files weekly.  In doing so there are hundreds of transactions that I ignore. 

My use case is, toggling "Ignore" at the top and scrolling down to the bottom. I work backwards to import a handful of transactions out of the hundreds.

I stumbled across the new DEV version while troubleshooting a DOCKER fava issue.  In this new version, you re-designed the import tool to go one by one through each transaction.  This new design wouldn't work for myself. I would have to manually select Toggle Duplicate and hit Next 800 times before I get to the last transactions to actually import.  

Do you have any info on this?  Am I going about this wrong? But my first impression is to stay on the previous versions when this new version gets released.

**Comment by yagebu** [comment]
I'd modify the importer to filter for the transactions that you might actually want to import and also mark any potential duplicates there already.

**Comment by MickMorley** [comment]
Its not so much filtering the transactions that I want to import.  My bank downloads the last 90 days into 1 OFX files.  So if I import them each week, I only want to import the most recent 7 days.  But the importer starts at the beginning of the OFX.

With the new importer, it makes it more tedious to import not that there is a Previous/Next button for 90 days worth of transactions. 

I don't want to sidetrack the thread with another issue, but I havent gotten the OFX importer to exclude any duplicates automatically.  I always hit Toggle Ignore for all of them and scroll down to the most recent.

**Comment by redstreet** [comment]
You seem to be using the GUI to solve a data clean up issue, which may not be efficient. Have you tried smart importer and its duplicate detector?

https://github.com/beancount/smart_importer/blob/master/README.rst

smart_importer is wonderful for its core purpose of categorizing too, not to mention how well it's designed overall.

**Comment by yagebu** [comment]
I've added buttons to jump to the very end of the transactions. Marking all of them as duplicates is easily done in the importer, so I don't think a button for that is necessary.

**Comment by MickMorley** [comment]
> I've added buttons to jump to the very end of the transactions. Marking all of them as duplicates is easily done in the importer, so I don't think a button for that is necessary.

Do you have an example of how to mark them as duplicates in the importer? I found the docker grostim/fava-docker which has smart-importer built in. However, when there are many split transactions, it doesn't know any better if its a duplicate.

**Comment by yagebu** [comment]
In your importer code, when generating the entry, you can set the corresponding metadata:
```
entry.meta['__duplicate__'] = True
