### ISSUE TITLE
Github release is useless due to the use of setuptools-scm

### ISSUE THREAD

**Issue by yegle** [beancount/fava#942]
Anyway to force a version here?

```
$ wget https://github.com/beancount/fava/archive/v1.10.tar.gz
$ tar xvf v1.10.tar.gz                                       
$ cd fava-1.10
$ pip3 wheel .
...
    LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-xe9vp__c'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by yegle** [comment]
OK learned this trick from `setuptools-scm`'s test:

https://github.com/pypa/setuptools_scm/blob/fcf7c5e8705285ed8653cae878fc8881ad2c04ab/testing/test_regressions.py#L26

**Comment by yegle** [comment]
I'm reopening this issue because the workaround https://github.com/beancount/fava/issues/942#issuecomment-501583847 don't actually work: the templates directory will somehow missing from the installed files.

**Comment by yagebu** [comment]
Github creates just a tarball of the git tree at that commit, they're not releases.

**Comment by AluisioASG** [comment]
Is there a release tarball that includes the tests? Currently I package Fava for Void Linux using the PyPI archive, but we can't run the tests with it.

**Comment by yagebu** [comment]
@AluisioASG: The source dist on PyPI includes the tests

**Comment by AluisioASG** [comment]
Ah, you're correct. Sorry, I've seen so many packages where that's the case that I didn't stop to double-check why they weren't running.
