### ISSUE TITLE
Unable to get sample extension report (portfolio list) to work

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#948]
Ran (HEAD):
```
fava fava/tests/data/extension-report-example.beancount
```

When clicking on the PortfolioList link in the sidebar, I get a red box that says:
```
Loading http://localhost:8000/main-accounts/extension/PortfolioList/ failed
```

1) Am I missing something or is this a bug?
2) How do I debug this? How do I see the traceback?

**Comment by yagebu** [comment]
Can't reproduce this. Did you run make? Run in debug mode and post the traceback

**Comment by redstreet** [comment]
Rebuilt and re-ran, and unable to reproduce it. I'll chalk this one to user error for now. Sorry to make you look!
