### ISSUE TITLE
unrealized in the market value with a year selector

### ISSUE THREAD

**Issue by pfrancois** [beancount/fava#954]
when i select the market value view in , everything is shown but i see also the unrealized gain between the market value and the cost value.

but if i select a time, i still see all the unrealized gain. i think it could be better if we split between the unrealized gain from this period of time and the unrealized gain from before.

like this, we can have easily the unrealized gain during a period.

**Comment by yagebu** [comment]
I disagree - the unrealized gain is just that - unrealized. So we shouldn't "realize" it at the end of the previous period.

**Comment by yagebu** [comment]
Closing due to lack of other input. As always, feel free to reopen :)
