### ISSUE TITLE
Automatically trigger git push after each update ?

### ISSUE THREAD

**Issue by grostim** [beancount/fava#957]
Hi,

This may be already anticipated and I may have missed the information, otherwise, this could be a new feature request:

Is it possible to trigger a "git commit & git push" after each update of the beancount file from within fava (either by manual editing, or by importing a statement from the bank) ?

I am currently doing it manually, but opening a command line after each update is not great .

**Comment by yagebu** [comment]
Hey, this is possibly with Fava's extension system (see the 'Extensions' help page for some details). The example extension (https://github.com/beancount/fava/blob/master/fava/ext/auto_commit.py) actually does this apart from the push part.

**Comment by grostim** [comment]
Amazing.
I will create an extension covering my needs.

**Comment by onnyyonn** [comment]
@grostim would it be possible for you to share the extension if you have created it?

**Comment by grostim** [comment]
I have this in my beancount  file:
```
1981-02-07 custom "fava-extension" "myAutoCommit"
```

And this in myAutoCommit.py :
```
"""Auto-commit hook for Fava.

This mainly serves as an example how Fava's extension systems, which only
really does hooks at the moment, works.
"""
# pylint: disable=missing-docstring

import os
import subprocess

from fava.ext import FavaExtensionBase


class AutoCommit(FavaExtensionBase): # pragma: no cover
    def _run(self, args):
        cwd = os.path.dirname(self.ledger.beancount_file_path)
        subprocess.call(args, cwd=cwd, stdout=subprocess.DEVNULL)

    def after_write_source(self, path, _):
        message = "autocommit by fava: file saved"
        self._run(["git", "add", "--all"])
        self._run(["git", "commit", "-am", message])
# self._run(["git", "push"])

    def after_insert_metadata(self, *_):
        message = "autocommit by fava: metadata added"
# self._run(["git", "commit", "-am", message])
# self._run(["git", "push"])

    def after_insert_entry(self, entry):
        message = "autocommit by fava: entry on {}".format(entry.date)
# self._run(["git", "commit", "-am", message])
# self._run(["git", "push"])
```

Le sam. 3 mai 2025, 08:21, Anamitra Saha ***@***.***> a
écrit :
