### ISSUE TITLE
Preset query links: query_string parameter of url is removed on click

### ISSUE THREAD

**Issue by ericgla** [beancount/fava#958]
There seems to be an issue specific to v1.11 regarding the preset query links in the sidebar.  The link is rendered correctly when the site is loaded:

`<a href="http://localhost:5000/ledger/query/?query_string=run+my-report"`

However, once the link is clicked the `takeOverLinks` function is called and the link is rewritten as:

`<a href="http://localhost:5000/ledger/query"`

The issue seems to be with this line in `takeOverLinks`:

`newURL.search = window.location.search`

I'm assuming this is here to retain any selected filters but ends up removing any query string parameters if no filters are set.

**Comment by yagebu** [comment]
Thanks for the bug report :)
