### ISSUE TITLE
How fava solve ambigous "insert-entry" ?

### ISSUE THREAD

**Issue by grostim** [beancount/fava#959]
Hi!

I have several "insert-entry" lines in my beancount file. one per bank account that i may import.
for example, i have:
1981-02-07 custom "fava-option" "insert-entry" "Actif:Boursorama:CCJoint"
and
1981-02-07 custom "fava-option" "insert-entry" "Actif:Boursorama:CCAnna"

From time to time i have a wire transfer from Actif:Boursorama:CCAnna to Actif:Boursorama:CCJoint .
How fava decides where the entry should be inserted ?
- First posting of the transaction ?
- First insert-entry line met in the beancount file ? 
- Something else ?

**Comment by yagebu** [comment]
The behaviour is documented on the options help page

**Comment by grostim** [comment]
Yes, sorry i missed it.

`When adding an entry, the account of the entry (for a transaction, the account of the last posting is used) is matched against all  insert-entry options and the entry will be inserted before the datewise latest of the matching options. If the entry is a Transaction and no insert-entry option matches the account of the last posting the account of the second to last posting and so on will be tried. If no insert-entry option matches or none is given, the entry will be inserted at the end of the main file.`

It is clear enough for me.
