### ISSUE TITLE
My importer behave differently in fava and in Command Line

### ISSUE THREAD

**Issue by grostim** [beancount/fava#960]
Hi,

I have a basic importer to file my pdf . It is based on the acme.pdf exemple from beancount, the main difference being that the account is determined based on the pdf content and not given as an argument.
I am just parsing the text content to find the account number and determine the relevant beancount account.

My importer work properly in command line:
```
root@e706d20f98f5:/myData# bean-identify Famille.import A_Importer/2018-12-27\ Releve.pdf
**** /myData/A_Importer/2018-12-27 Releve.pdf
Importer:    importers.pdfbourso.pdfbourso.pdfbourso
Account:     Passif:Boursorama:CBJoint
```
The statement is properly connected to the rightful account.

Now, If i try to move the files from within fava, the account is not the correct one. See below:
<img width="926" alt="Capture d’écran 2019-08-24 à 16 23 53" src="https://user-images.githubusercontent.com/3714755/63638678-d783be80-c68b-11e9-92a7-5938996746ae.png">

The mistake is probably on me, but do you have an idea of what could lead to a different behavior ?

**Comment by yagebu** [comment]
We call the `importer.file_account` method just like Beancount does AFAICT, so I'm surprised there's a difference

**Comment by grostim** [comment]
However, i have been able to reproduce the issue.
It happens when i have several documents in the "to_be_imported" folder that use the same importer but are related to different account.
Fava shows all the document linked to the same account, while bean identify link each document to the correct account.
If necessary i can share a few samples files and my importer.

**Comment by yagebu** [comment]
Can you check by adding some logging statements to see if your file_account method is called with the correct arguments?

**Comment by yagebu** [comment]
It could be that you have some sort of state in your importer so that it will always return the same account name. If using `bean-identify` with one file, that's not a problem, but in Fava, the same importer instance will be used for all files.

**Comment by yagebu** [comment]
This is almost certainly an issue with your importer as described above, so I'll close this issue.
