### ISSUE TITLE
Fava does not allow negative balance directive ?

### ISSUE THREAD

**Issue by grostim** [beancount/fava#962]
Hi.

I just completed my first impoter that also manadge balance directive.
This is an american express pdf statement parser.
It works pretty well (in command line at least) but Fava reject the balance statement because of the "minus" sign. 
Being a credit card, my balance is always negative....
![image](https://user-images.githubusercontent.com/3714755/63708573-19039d80-c835-11e9-8209-d2c184e3ea3c.png)

Currently, the only option i have is to remove the negative sign in the form and then to correct it in the editor...

Is this normal ?

**Comment by yagebu** [comment]
Thanks for the bug report :)
