### ISSUE TITLE
Chart difference between 2 accounts

### ISSUE THREAD

**Issue by gety9** [beancount/fava#963]
Guys hi,

I didn't find anything similar in docs, so opening an issue.

Is it possible to chart difference between 2 accounts ?

Let say i have 2 accounts
Income:Business:Company1
Expenses:Business:Company1

Right now i see charts for them individually at
localhost:5000/myledger/account/Income:Business:Company1 and
localhost:5000/myledger/account/Expenses:Business:Company1

Can i see chart for "Income:Business:Company1" + "Expenses:Business:Company1" ?

**Comment by yagebu** [comment]
This is currently not possible. A UI for allowing for a bigger variety of charts such as this one would be nice.

**Comment by gety9** [comment]
@yagebu 

1
> This is currently not possible. A UI for allowing for a bigger variety of charts such as this one would be nice.

How difficult it will be to add one ? I don't think i will be able to do UI, but maybe in query format smng similar to this:
`localhost:5000/myledger/?Income:Business:Company1+Expenses:Business:Company1`

2
In beancount google group i was suggested to use advanced filter
`"any(account:"Expenses:Business:Company1"), any(account:"Income:Business:Company1")"`
But this does not work if there are transactions with multiple postings one of each is inside Company1 and another outside.

**Comment by gety9** [comment]
@yagebu 

i see that issue is fixed by Charts for appropriately structured queries PR,
but can't understand how to use it. Could you please explain ?

Tried:
-`localhost:5000/myledger/?Income:Business:Company1+Expenses:Business:Company1` as url
-`any(account:"Expenses:Business:Company1"), any(account:"Income:Business:Company1")` as advanced filter
-`any(account:"Expenses:Business:Company1"), any(account:"Income:Business:Company1")` as query

fava version 1.12

**Comment by yagebu** [comment]
You need to use the "Query" page and run a BQL query that has a result with two columns: the date and the balance. So something like `select date, units(sum(position)) where account ~ ".*:Business:Company1" group by date`

**Comment by gety9** [comment]
@yagebu 

than you, i got two column table with date and units_sum_position
https://puu.sh/EWZx0/a6f6bb3699.png

how do i get chart from this ?

**Comment by yagebu** [comment]
I see from your message above that you're running the latest released version, this is currently just in the master branch and will be contained in the next release. The chart is just above the query result

**Comment by gety9** [comment]
@yagebu 

can i install the master branch now ? or is it troublesome and it's better to wait for next release ?
(when are you planning to release by the way ?)

**Comment by yagebu** [comment]
If you're asking that, it's probably best to wait for the next release ;) I don't have a date for the next release. Sometime this month I guess.

**Comment by gety9** [comment]
Thank you for the feature! It works and very useful! Fava team is amazing!

**Comment by yagebu** [comment]
That's good to hear :)
