### ISSUE TITLE
Make Fava a Progressive Web App (PWA)

### ISSUE THREAD

**Issue by debanjum** [beancount/fava#965]
This will allow a "native" app experience of Fava on the desktop and phone.

I currently have Fava running on Android via Termux. 
While this works for viewing purposes, making Fava a PWA would:
1. Speed up page loads
2. Make Fava installable as an app and allow putting it on the phone home screen

This would make adding transactions on the go practical.
Basically we'd get a Fava Android/iOS app for what seems like minimal effort. 
 
From my understanding, to make Fava a progressive web apps would entail:
1. Add a manifest file to fava 
2. Make manifest reference the static assets that can be cached/pre-loaded.
3. Add some minor metadata tags to the base/index.html in fava 
   (e.g to point to manifest)

Does this seems doable ?

Reference: [Building Your First Progressive Web App {Google}](https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/)

**Comment by yagebu** [comment]
Sadly, it's not quite that simple. Adding just a manifest isn't enough to speed anything up, we'd have to write a service worker which handles the caching of resources. Also Fava is quite unusable when offline so we'd be violating the basic promises of a PWA:

> Users who install a PWA expect that their apps work, no matter what kind of network connection they're on. It's a baseline expectation that must be met by every installed app.

Since I'd never put my whole Beancount file on my phone, but would still like to have a convenient way to input transactions on the go, I've been considering building a separate completely offline-capable frontend (and PWA) to do just that. I won't have time soon to implement that but I would personally first spend time on that than on turning Fava into a PWA.

**Comment by debanjum** [comment]
I've reached a satisfactory solution for myself without requiring anything too complicated. I've been using this to input transactions since the last 2 months.

**Summary:** Just add a link to `{Your_Fava_URL}/income_statement/?interval=day&time=week#add transactions` to your phone's Home Screen via the `Add to Home Screen` option on your phone web browser. Works/looks like an app, does decently fast Add Transaction operations.

**Details**:
1. To decrease page load time when trying to add a transaction, just switch to a lighter fava page to `#add-transaction`. I use `/income-statement` page instead of the earlier  `/journal` with no time interval specified. The `journal` page takes fairly long to load for a multi-year/10K+ line ledger (at least on my phone).
     Specifically (for me), the new link I use is `http://localhost:4242/beancount/income_statement/?interval=day&time=week#add-transaction`
2. The `Add to Home Screen` button in Chrome/Firefox on Android allows saving a page as a home screen shortcut. This handles the requirement of making fava more app like. See [Add Website to Home Screen on Android/iOS etc](https://www.howtogeek.com/196087/how-to-add-websites-to-the-home-screen-on-any-smartphone-or-tablet/).

**Background**: I have `Fava` running locally on my phone via `Termux`. My beancount file is synced between my devices via `Syncthing`
