### ISSUE TITLE
Display Commodity meta-name

### ISSUE THREAD

**Issue by grostim** [beancount/fava#975]
Hi,

I think, it could be useful to find a way to display the meta-name of a commodity .

When you monitor a portfolio with many ETF or Funds, the tickers are not always explicit... (and when you decide like i do to use the ISIN code as commodity name, it is not explicit at all).

I would like to discuss a way to display the complete name of the commodity (from the metatag "name").
I suggest displaying an info-bubble when a commodity is hovered by the pointer, but i will be happy to discuss any alternative solution.

**Comment by yagebu** [comment]
I like it :)

> I suggest displaying an info-bubble when a commodity is hovered by the pointer

Sounds good.
