### ISSUE TITLE
Budgets not showing

### ISSUE THREAD

**Issue by lsdza** [beancount/fava#984]
Hi,

I am unsure what im doing wrong, but cant see any budget information.  I also notice in 1.11 there is no monthly changes (which was suggested to see budget info). 

I am using yearly budget and attaching my simple journal file.  I have also tried the example file and cant seem to see it either. Maybe i'm not actually sure what I should be seeing?

[journal.beancount.txt](https://github.com/beancount/fava/files/3723282/journal.beancount.txt)

**Comment by yagebu** [comment]
>  I also notice in 1.11 there is no monthly changes (which was suggested to see budget info).

There is - see for example https://fava.pythonanywhere.com/example-with-budgets/account/Expenses/changes/

> Maybe i'm not actually sure what I should be seeing?

The budgets are shown in the monthly changes and balances for the relevant accounts and as a grey backdrop in the various monthly charts (for example on the account page and the income statement)
