### ISSUE TITLE
How to export to excel ?

### ISSUE THREAD

**Issue by gety9** [beancount/fava#986]
Guys hi,

Could you help me understand how to export to excel ?
Here is what i did:

1 installed fava with excel dependency
`pip3 install fava[excel]`

2 click "arrow button" next to import.

But the only option i am getting is:

> Download currently filtered entries as a Beancount file

**Comment by yagebu** [comment]
You can only report query results to excel, so try running some BQL query, the export links to the various formats should be at the top of the result table.
