### ISSUE TITLE
Demo Site is down

### ISSUE THREAD

**Issue by worldworm** [beancount/fava#987]
your page is not available.
https://fava.pythonanywhere.com/example-with-budgets/income_statement/

If the URL has changed, please open a pull request at
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

Kickball/awesome-selfhosted#1767

**Comment by yagebu** [comment]
Thanks for reporting that - the free sites at pythonanywhere expire every 3 months, I've just renewed it.

**Comment by jpluscplusm** [comment]
This seems to have happened again :-)

**Comment by yagebu** [comment]
Thanks :)
