### ISSUE TITLE
Option "fava.plugins.link_documents" Causes Errors When Not Found - Need a Way To Ignore

### ISSUE THREAD

**Issue by OptikSage** [beancount/fava#989]
I archive my Documents folder each year, but I leave the transactions in the journal file. I am only interested in linking documents for the current year. But the link option will throw errors because the prior year's documents are missing. I would love for this to be a warning instead or preferably something I can set via options such as: 2000-01-01 custom "fava-option" "link-documents-year" "2019" or similar.

**Comment by yagebu** [comment]
Why not just remove or rename the metadata for the transactions when removing the documents?

**Comment by OptikSage** [comment]
The metadata still has value in of itself. It tells me that this transaction has a document and that that document has a name. Combined with the date I can then go look for it in the appropriate archived location. I suppose I might be able to rename the the metadata name/type to something that keeps the value, but is no longer considered a document. I'll give that a go and see of it works.
