### ISSUE TITLE
First Impression Feedback

### ISSUE THREAD

**Issue by nomorethirst** [beancount/fava#99]
Sorry about my original post.  When I first logged into Github to view this issue tracker, I saw a message that Github thought I was a  robot and to contact support to make my profile public again, and then the textbox for posting, which I quickly posted that I was a human.  Then I saw it was your issue tracker -how embarassing!  So, I decided to overwrite it and give you my feedback for beancount-web here.

First of all let me say I LOVE what you've done with beancount-web!  I've had it on my list to dig into some javascript frameworks/libraries and hack something together myself, in particular to give some data visualation in the form of charts graphs.  You have done that and so much more - not being much more than a novice myself, I never could have done so much, so well, so fast.  So great job, and thanks for your work.  I've been using beancount for a little over a year, and really like it.  I found myself using bean-web more and more viewing reports, eventually using it exclusively for viewing data, and the text file for editing/data entry.  You've made a lot of improvements, and gave it a clean, pro-looking interface.  The charts/graphs are great, filters handy, and bean-query custom functionality the icing on the cake.  I'll be using beancount, giving feedback and perhaps contributions where I can.

I also have a few initial questions/suggestions. 
1.  I really like how the balance sheet has a "net work in (op curr)" graph.  It seems to be totalling and then converting all currencies to that one op curr?  My question is, where does it get the exchange rate?  It doesn't seem to be using the price directives that I've provided in my data file.
2. I think someone mentioned in the beancount mailing list about negative values in the charts.  For example, when viewing monthly income graph in the income statement view, the bars are "upside down."  I realize this is because income entries are negative because of the accounting equation, but somehow my brain still wants to view them in the graph as "rightside-up."  Is this a more pro/accounting way of looking at it?  In my experience with personal finance software (Quicken, Gnucash, iBank, etc.), I've always seen income presented as positive values in charts/graphs.
3. For tables, I find myself wanting to see the default view as collapsed, giving a bird's eye view first, and then drilling down to the details by expanding.  I realize others may not like this, but I suggest putting some discrete "collapse all"/"expand all" buttons (esp. for balance sheet and trial balance views).
4.  Perhaps this goes against the whole premise behind the ledger/CLI accounting movement (where recording transactions and other info is strictly done in the text files), but does anyone ever think about using the web interface to write/edit data (transactions, notes, etc.).  Like I said, I may be missing the point altogether, but I find myself missing this feature of mainstream personal finance software.

Anyway, again great job.  If there's a particular area where you would like some help/ contributions, let me know, and if it's within my abilities, I'll do my best to help.

~Danny

**Comment by yagebu** [comment]
It's odd - I can't remember seeing this issue before even though the list of open issues has always been quite small. So I apologize for only replying now.

Thanks for the feedback! Now some of the points you mention have already been addressed:

1. Fava only uses the prices in your file to do the conversions.
2. is tracked in #448.
3. This can be done per-account by setting the `fava-collapse-account` metadata entry to "True".
4. Fava has gained some features that can simplify adding/editing transactions recently.

I'll close this now very old issue as I feel like the important points have been addressed (or are tracked elsewhere), but feel free to open new issues or continue the discussion here if you have other suggestions.

**Comment by nomorethirst** [comment]
@yagebu Thanks for the response, even though it is so old.  I figured the issues got addressed by now.  I think what happened was my account went inactive ("flagged", don't ask me why).  Anyway, I just reactivated it, so this issue must have reappeared.  Keep up the great work on this favulous :) gui for beancount!
