### ISSUE TITLE
Contributing translations

### ISSUE THREAD

**Issue by xuhcc** [beancount/fava#990]
How can I contribute a translation? The link to Fava project on POEditor (https://poeditor.com/projects/view?id=90283) in [CONTRIBUTING.md](https://github.com/beancount/fava/blob/master/CONTRIBUTING.md) is broken, it leads to 404 error page.

**Comment by yagebu** [comment]
> it leads to 404 error page.

That's some odd behaviour on their side - it works for me, but apparently it doesn't work for new contributors, that link...

https://poeditor.com/join/project/TlraSxOCxt should work

**Comment by xuhcc** [comment]
Thanks, it's working.

**Comment by xuhcc** [comment]
@yagebu I selected language and joined project. I guess now you need to approve me as a contributor?

Here's how Fava project appears on dashboard:

![Screenshot from 2019-10-27 21-46-59](https://user-images.githubusercontent.com/1660460/67639673-a16cf000-f903-11e9-8abd-f362940cc75d.png)

The "Russian" button is not active and there is a tooltip that says "pending".
