### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by xuhcc** [beancount/fava#993]
When I add new transaction in Fava, its postings and metadata are indented with 2 spaces. Is it possible to change default indent to 4 spaces?

If not, I suggest adding a new option:

```
1970-01-01 custom "fava-option" "indent" "<value>"
```

Where `value` can be a number (e.g. `4`) or `tab`.

**Comment by xuhcc** [comment]
It appears that some changes are needed on beancount side: https://bitbucket.org/blais/beancount/issues/407/indentation-of-postings-and-metadata-in

**Comment by yagebu** [comment]
I also use 4 spaces for indentation and I simply run `bean-format` on my ledger to unify the indentation - I think that's a slightly superior solution, since that will also nicely align the numbers in the transactions.

**Comment by xuhcc** [comment]
I use `bean-format` too, but for some reason it leaves tx metadata with 2-space indent.

Even if this problem did not exist, I would prefer to have a custom option, since it does not require additional actions from the user.

**Comment by yagebu** [comment]
If you are willing to contribute a PR, I'd be happy to accept it.

**Comment by xuhcc** [comment]
Yes I am, but this requires changes to beancount itself, and my [patch](https://bitbucket.org/blais/beancount/issues/407/indentation-of-postings-and-metadata-in) has not yet been accepted.

**Comment by yagebu** [comment]
Require is a strong word ;) We (need to) do some beautifications to the output of the Beancount printer  [anyway](https://github.com/beancount/fava/blob/4d4b340ae8d8de8b71f013e25bac15e496c9d3bd/fava/core/file.py#L374), so we could also change the indentation there.

**Comment by xuhcc** [comment]
OK, I'll look into it. By the way, are you considering maintaining a fork of beancount? I think the community would welcome such initiative :)
