### ISSUE TITLE
An apostrophe (character \u2019) in an account means that files are not linked in the search path.

### ISSUE THREAD

**Issue by drummonds** [beancount/fava#995]
Note this is not the simple apostrophe but slightly different:  '’
I am running on Windows.  I was using a file with french customers who had an apostrophe.  This meant the documents didn't get up loaded, the web display of the account name was fine.

Workaround: remove the apostrophe D’ALB  →  DALB

**Comment by yagebu** [comment]
> This meant the documents didn't get up loaded, the web display of the account name was fine.

In the issue title you state that linking the documents failed and here you state that uploading fails - which is it, could you please elaborate?

**Comment by drummonds** [comment]
Sorry not clear.  It is simply that a document file does not appear on the web page.
Removing the character from the account name and the directory and refreshing and the documents will appear.

I have never had a failure where the link appears and is broken.

I really like fava / beancount.  Problems that I found conceptually hard have become easy.

**Comment by yagebu** [comment]
The generation of document entries for the files is done by Beancount and not by Fava.

The reason that the document entry is not generated in this case is that the validation of account names is done in a slightly stricter way on the Python side (allowing only letters), whereas the parser allows all unicode. So the account name with the apostrophe is not really valid (but currently allowed by the parser).

**Comment by drummonds** [comment]
Hi Yagebu, thanks for the update.  Yuck - if you enforced the stricter definition the parser you would break a whole  lot of instances.  I am not sure if this should be a goal or it should just be left as an idiosyncrasy.

**Comment by yagebu** [comment]
> if you enforced the stricter definition the parser you would break a whole lot of instances

To clarify - it's strict on ASCII, and non-strict on non-ASCII unicode. So I'm not sure it would break many instances. Also the syntax definition is quite clear.

Anyway, none of this has much to do with Fava, so I'll close this issue.
