### ISSUE TITLE
Cash flow statements?

### ISSUE THREAD

**Issue by joliver** [beancount/fava#998]
Is there some kind of report in Fava that generates a statement for cash flow? I see income statements and a balance sheet.

**Comment by yagebu** [comment]
No, there is currently not. What would you expect that report to look like?

**Comment by joliver** [comment]
As I look at the Wikipedia article on [cash flow statements](https://en.wikipedia.org/wiki/Cash_flow_statement), I suppose it would be hard for Fava (and Beancount for that matter) to show proper cash flow because a typical statement makes distinctions from operating activities vs investing and other financing activities which context is not available to either program.

The example statement at the bottom of the article under the section "**Example: cash flow of XYZ**" is kind of what I was hoping for.

**Comment by ngoonee** [comment]
Just was browsing and came across this. As context is required, you can provide that in a saved query. Here's mine:-

    2018-09-21 query "cashflow" "SELECT
        QUARTER(date) as quarter, root(account, 0) as Account, sum(number) as Total
    WHERE
        account ~ 'Assets:Banking|Assets:Cash|Liabilities:CreditCards|Liabilities:BalanceTransfer'
        AND NOT account ~ 'Assets:Banking:Mybank:Account '
    GROUP BY quarter, Account
    ORDER BY quarter, Account DESC
    FLATTEN"
